<?php
$options = (array) $block['options'];
$items   = (array) $block['items'];
$target  = empty($options['target']) ? '_blank' : $options['target'];
?>
<div class="widget-list">
    <ul>
        <?php foreach($items as $item) { ?>
        <li>
            <a href="<?php echo _escape($item['link']); ?>" 
                title="<?php echo _escape($item['caption']); ?>" 
                class="pi-ellipsis pi-ellipsis-1" 
                target="<?php echo _escape($target); ?>">
                <?php echo _escape($item['caption']); ?>
            </a>
        </li>
        <?php } ?>
    </ul>
</div>
