<?php
$options    = (array) $block['options'];
$items      = (array) $block['items'];
$activeItem = array_shift($items);
$width      = empty($options['width']) ? 120 : $options['width'];
$height     = empty($options['height']) ? 90 : $options['height'];
$target     = empty($options['target']) ? '_blank' : $options['target'];
?>
<div class="widget-list">
    <div class="media" style="margin-bottom: 10px">
        <?php
            echo sprintf(
                '<a href="%s" title="%s" class="pull-left" target="%s">
                    <img src="%s" class="img-responsive" alt="%s" style="width:%spx; height:%spx">
                </a>',
                $activeItem['link'],
                $activeItem['caption'],
                $target,
                $activeItem['image'],
                $activeItem['caption'],
                $width,
                $height
            );
        ?>
        <div class="media-body">
            <h4 class="media-heading">
                <a href="<?php echo _escape($activeItem['link']); ?>" 
                    title="<?php echo _escape($activeItem['caption']); ?>"
                    class="pi-ellipsis pi-ellipsis-1"
                    target="<?php echo _escape($target); ?>">
                    <?php echo _escape($activeItem['caption']); ?>
                </a>
            </h4>
            <?php
                $htmlDetail = '';
                if (!empty($activeItem['detail'])) {
                    $htmlDetail = sprintf(
                        '<span class="pull-right"><a href="%s" target="%s">%s</a></span>',
                        $activeItem['detail'],
                        $target,
                        __('Detail')
                    );
                }
                echo sprintf(
                    '<div class="pi-ellipsis">%s%s</div>',
                    $activeItem['desc'],
                    $htmlDetail
                );
            ?>
        </div>
    </div>
    <ul>
    <?php foreach($items as $item) { ?>
        <li>
            <a href="<?php echo _escape($item['link']); ?>" 
                title="<?php echo _escape($item['caption']); ?>"
                class="pi-ellipsis pi-ellipsis-1"
                target="<?php echo _escape($target); ?>">
                <?php echo _escape($item['caption']); ?>
            </a>
        </li>
    <?php } ?>
    </ul>
</div>
