<?php
// Options: interval, pause, height
$options = (array) $block['options'];
$items   = $block['items'];
$activeItem = array_shift($items);
$count = count($items);
$width = empty($options['width']) ? 120 : $options['width'];
$height = empty($options['height']) ? 90 : $options['height'];
$target = empty($options['target']) ? '_blank' : $options['target'];
$rows   = empty($options['max_summary_row']) ? 2 : $options['max_summary_row'];
?>

<div class="media">
    <?php
        echo sprintf(
            '<a href="%s" class="pull-left" style="width: %spx; height: %spx">
                <img src="%s" class="img-responsive">
            </a>',
            $activeItem['link'],
            $width,
            $height,
            $activeItem['image']
        );
    ?>
    <div class="media-body">
        <h4 class="media-heading">
            <a href="<?php echo _escape($activeItem['link']); ?>" 
               title="<?php echo _escape($activeItem['caption']); ?>"
               class="pi-ellipsis pi-ellipsis-1"
               target="<?php echo _escape($target); ?>">
                <?php echo _escape($activeItem['caption']); ?>
            </a>
        </h4>
        <?php
            echo sprintf(
                '<div class="pi-ellipsis pi-ellipsis-%s">%s</div>',
                $rows,
                $activeItem['desc']
            );
            if (!empty($activeItem['detail'])) {
                echo sprintf(
                    '<span class="pull-right"><a href="%s">%s</a></span>',
                    $activeItem['detail'],
                    __('Detail')
                );
            }
        ?>
    </div>
</div>
<ul>
<?php foreach($items as $item) { ?>
    <li class="">
        <a href="<?php echo _escape($item['link']); ?>" 
           title="<?php echo _escape($item['caption']); ?>"
           class="pi-ellipsis pi-ellipsis-1"
           target="<?php echo _escape($target); ?>">
            <?php echo _escape($item['caption']); ?>
        </a>
    </li>
<?php } ?>
</ul>