<?php
$options = (array) $block['options'];
$items   = $block['items'];
$width   = empty($options['width']) ? 100 : $options['width'];
$height  = empty($options['height']) ? 100 : $options['height'];
$target  = empty($options['target']) ? '_blank' : $options['target'];
?>
<div class="widget-list">
    <?php foreach($items as $item) { ?>
    <div class="media">
        <?php
            echo sprintf(
                '<a href="%s" title="%s" class="pull-left" width="%s" height="%s">
                    <img src="%s" class="img-responsive" alt="%s">
                </a>',
                $activeItem['link'],
                $activeItem['caption'],
                $width,
                $height,
                $activeItem['image'],
                $activeItem['caption'],
            );
        ?>
        <div class="media-body">
            <h4 class="media-heading">
                <a href="<?php echo _escape($item['link']); ?>" 
                   title="<?php echo _escape($item['caption']); ?>"
                   class="pi-ellipsis pi-ellipsis-1"
                   target="<?php echo _escape($target); ?>">
                    <?php echo _escape($item['caption']); ?>
                </a>
            </h4>
            <?php
                echo sprintf(
                    '<div class="pi-ellipsis pi-ellipsis-%s">%s</div>',
                    $rows,
                    $item['desc']
                );
                if (!empty($item['detail'])) {
                    echo sprintf(
                        '<span class="pull-right"><a href="%s">%s</a></span>',
                        $item['detail'],
                    __('Detail')
                    );    
                }
            ?>
        </div>
    </div>
    <?php } ?>
</div>
