<?php
$options = (array) $block['options'];
$items   = $block['items'];
$width   = empty($options['width']) ? 100 : $options['width'];
$height  = empty($options['height']) ? 100 : $options['height'];
$target  = empty($options['target']) ? '_blank' : $options['target'];
?>

<?php foreach($items as $item) { ?>
<div class="media">
    <?php
        echo sprintf(
            '<a href="%s" class="pull-left" style="width: %spx; height: %spx" target="%s">
                <img src="%s" class="img-responsive">
            </a>',
            $item['link'],
            $width,
            $height,
            $target,
            $item['image']
        );
    ?>
    <div class="media-body">
        <h4 class="media-heading">
            <a href="<?php echo _escape($item['link']); ?>" 
               title="<?php echo _escape($item['caption']); ?>"
               class="pi-ellipsis pi-ellipsis-1"
               target="<?php echo _escape($target); ?>">
                <?php echo _escape($item['caption']); ?>
            </a>
        </h4>
        <?php
            $htmlDetail = '';
            if (!empty($item['detail'])) {
                $htmlDetail = sprintf(
                    '<span class="pull-right"><a href="%s" target="%s">%s</a></span>',
                    $item['detail'],
                    $target,
                    __('Detail')
                );
            }
            echo sprintf(
                '<div class="pi-ellipsis text-muted">%s%s</div>',
                $item['desc'],
                $htmlDetail
            );
        ?>
    </div>
</div>
<?php } ?>
