<?php
$options = (array)$block['options'];
$items   = (array)$block['items'];
$target  = $options['target_new'] ? '_self' : '_blank';
?>
<div class="widget-list widget-list-social-network">
    <ul class="list-inline">
        <?php foreach ($items as $item) { ?>
            <li class="list-inline-item">
                <a href="<?php echo $item['link']; ?>" title="<?php echo _escape($item['caption']); ?>"
                   target="<?php echo $target; ?>">
                    <?php if (!empty($item['icon'])) { ?>
                        <i class="<?php echo _escape($item['icon']); ?>"></i>
                    <?php } else { ?>
                        <?php echo _escape($item['caption']); ?>
                    <?php } ?>
                </a>
            </li>
        <?php } ?>
    </ul>
</div>
