<?php
$options = (array) $block['options'];
$items   = (array) $block['items'];
$target  = empty($options['target']) ? '_blank' : $options['target'];
?>
<div class="widget-list">
    <?php foreach($items as $item) { ?>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <a href="<?php echo _escape($item['link']); ?>" 
                   title="<?php echo _escape($item['caption']); ?>"
                   class="pi-ellipsis pi-ellipsis-1"
                   target="<?php echo _escape($target); ?>">
                    <?php echo _escape($item['caption']); ?>
                </a>
            </h4>
            <?php
                $htmlDetail = '';
                if (!empty($item['detail'])) {
                    $htmlDetail = sprintf(
                        '<span class="pull-right"><a href="%s" target="%s">%s</a></span>',
                        $item['detail'],
                        $target,
                        __('Detail')
                    );
                }
                echo sprintf(
                    '<div class="pi-ellipsis">%s%s</div>',
                    $item['desc'],
                    $htmlDetail
                );
            ?>
        </div>
    </div>
<?php } ?>
</div>
