<?php
$options    = (array) $block['options'];
$items      = (array) $block['items'];
?>
<div class="widget-video-list">
    <?php foreach($items as $item) { ?>
        <?php if (!empty($item['link'])) { ?>
            <div class="widget-video-single pi-player clearfix">
                <?php echo $this->videojs($item['link'], $item['image']); ?>
            </div>
        <?php } ?>
    <?php } ?>
</div>