<?php
$this->css(array($this->assetModule('script/tag-front.css')));
$url = $this->url('', array('controller' => 'index', 'action' => 'list'));
?>
<ul class="breadcrumb">
      <li><a href="<?php echo $url ?>">Tags</a> <span class="divider">/</span></li>
      <li class="active"><?php echo $tagTerm ?></li>
</ul>
<h2 class="page-header"><?php echo $tagTerm; ?></h2>
<div class="row-fluid">
    <div class="span3">
        <div class="sub-nav">
            <?php
            $items = array();
            $item = array(
                'href'  => $this->url('', array('controller' => 'index', 'action' => 'detail', 'id' => $tagid)),
                'label' => __('ALL'),
            );
            if (null == $curModule) {
                $item['active'] = 1;
            }
            $items[] = $item;
            foreach ($moduleArray as $row) {
                $item = array(
                    'href'    => $this->url('', array('controller' => 'index', 'action' => 'detail', 'm' => $row, 'id' => $tagid)),
                    'label'   => ucfirst($row),
                );
                if ($curModule === $row) {
                    $item['active'] = 1;
                }
                $items[] = $item;
            }
            echo $this->navMenu($items);
            ?>
        </div>
    </div>
    <div class="span9">
        <?php if ($datas == null) { ?>
            <div class="alert">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <p><?php echo $tagTerm . ' ' . __('not related an obj in ') . $curModule; ?></p>
            </div>
        <?php } else { ?>
            <table class="table table-hover table-bordered">
                <tr class="box-bordered-header">
                    <th><?php _e('Title'); ?></th>
                    <th class="span2"><?php _e('Module'); ?></th>
                    <th class="span2"><?php _e('Time'); ?></th>
                </tr>
            <?php foreach ($datas as $row) { ?>
                <tr>
                    <?php $url = sprintf('<a href="%s">%s</a>', $row['url'], $row['title']); ?>
                    <td><?php echo $url; ?></td>
                    <td>
                        <?php $moduleUrl = $this->url('', array('controller' => 'index', 'action' => 'detail', 'm' => $row['module'], 'id' => $tagid)); ?>
                        <?php echo sprintf('<a href="%s" title="%s">%s</a>', $moduleUrl, $row['module'], ucfirst($row['module'])); ?>
                    </td>
                    <td><?php echo date("Y-m-d", $row['time']);?></td>
                </tr>
            <?php } ?>
            </table>
        <?php } ?>
        <?php if ($find != 'n') { ?>
        <div class="pagination-right">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
        <?php } ?>
    </div>
</div>