<?php
$this->css(array($this->assetModule('script/tag-front.css')));
?>
<ul class="breadcrumb">
      <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'list')); ?>"><?php _e('Tags'); ?></a> <span class="divider">/</span></li>
      <li class="active"><?php echo $tagTerm; ?></li>
</ul>
<h2 class="page-header"><?php echo $tagTerm; ?></h2>
<div class="row-fluid">
    <div class="span3">
        <div class="sub-nav">
            <?php
            $items = array();
            $item = array(
                'href'  => $this->url('', array('controller' => 'index', 'action' => 'detail', 'id' => $tagId)),
                'label' => __('ALL'),
            );
            if (null == $curModule) {
                $item['active'] = 1;
            }
            $items[] = $item;
            foreach ($modules as $name => $title) {
                $item = array(
                    'href'    => $this->url('', array('controller' => 'index', 'action' => 'detail', 'm' => $name, 'id' => $tagid)),
                    'label'   => $title,
                );
                if ($curModule === $name) {
                    $item['active'] = 1;
                }
                $items[] = $item;
            }
            echo $this->navMenu($items);
            ?>
        </div>
    </div>
    <div class="span9">
        <?php if (!$data) { ?>
            <div class="alert">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <p><?php
                    $message = __('There is no related items for %s in module %s.');
                    echo sprintf($message, $tagTerm, $curModule);
                    ?>
                </p>
            </div>
        <?php } else { ?>
            <table class="table table-hover table-bordered">
                <tr class="box-bordered-header">
                    <th><?php _e('Title'); ?></th>
                    <th class="span2"><?php _e('Module'); ?></th>
                    <th class="span2"><?php _e('Time'); ?></th>
                </tr>
            <?php foreach ($data as $row) { ?>
                <tr>
                    <td><?php
                        $url = $row['url'];
                        $title = _escape($row['title']);
                        ?>
                        <a href="<?php echo $url; ?>" title="<?php echo $title; ?>"><?php echo $title; ?></a>
                    </td>
                    <td><?php
                        $url = $this->url('', array('controller' => 'index', 'action' => 'detail', 'm' => $row['module'], 'id' => $tagid));
                        $title = _escape($modules[$row['module']]);
                        ?>
                        <a href="<?php echo $url; ?>" title="<?php echo $title; ?>"><?php echo $title; ?></a>
                    </td>
                    <td><?php echo _date($row['time']);?></td>
                </tr>
            <?php } ?>
            </table>
        <?php } ?>
        <?php
        if ($paginator) {
            echo $this->pagination(
                $paginator,
                'Sliding',
                'paginator.phtml',
                array('class' => 'pagination-right')
            );
        }
        ?>
    </div>
</div>