<div class="page-header" style="margin: 0 0 20px;">
    <?php if(!empty($cur_module)) { ?>
    <a href="<?php echo $this->url('', array('action' => 'list', 'tag' => $tag_id)); ?>"
       class="pull-right" style="margin-top: 5px;">
        <?php _e('View all tags'); ?>
    </a>
    <?php } ?>
    <h3>
        <?php echo sprintf(__('About "%s" content'), $tag); ?>
    </h3>
</div>
<div class="tag-list">
<?php
$i = 1; 
foreach ($list as $item) { 
    echo sprintf(
        '<div class="tag-list-item">
            <span class="pull-right">%s</span>
            <span class="text-muted">[%s]</span>
            <a href="%s">%s</a>
        </div>
        ',
        $item['time'],
        $item['module'],
        $item['item_link'],
        $item['item']
    );
    if ($i % 5 == 0) {
        echo '<hr class="pi-dashed">';
    }
    $i++;
}
?>
</div>
<?php
if (isset($paginator)) {
    echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml');
}
?>