<?php 
//$this->I18nModule('main');
$this->css(array($this->assetModule('script/tag-front.css')));
?>
<h2 class="page-header"><?php _e('Tags'); ?></h2>
<div class="row-fluid">
    <div class="span3">
        <div class="sub-nav">
            <?php
            $items = array();
            $item = array(
                'href'  => $this->url('', array('controller' => 'index', 'action' => 'list')),
                'label' => __('ALL'),
            );
            if (null == $curModule) {
                $item['active'] = 1;
            }
            $items[] = $item;
            foreach ($modules as $name => $title) {
                $item = array(
                    'href'    => $this->url('', array('controller' => 'index', 'action' => 'list', 'm' => $name)),
                    'label'   => $title,
                );
                if ($curModule === $name) {
                    $item['active'] = 1;
                }
                $items[] = $item;
            }
            echo $this->navMenu($items);
            ?>
        </div>
    </div>
    <div class="span9">
        <div>
            <?php
            echo $this->form()->openTag($form);
            ?>

            <?php
            $element = $form->get('tagname');
            $element->setAttributes(array(
                'class'         => 'input',
                'placeholder'   => $element->getOption('label'),
            ));
            echo $this->formElement($element);
            echo ' ';

            $element = $form->get('submit');
            $element->setAttributes(array(
                'class'         => 'btn btn-primary',
            ));
            echo $this->formElement($element);
            ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
        <table class="table table-hover table-bordered">
            <tr class="box-bordered-header">
                <th><?php _e('Tag Name'); ?></th>
                <th class="span2"><?php _e('Count'); ?></th>
            </tr>
            <?php 
            foreach ($data as $tag) {
                $url = $this->url('', array(
                    'module'        => Pi::service('module')->current(),
                    'controller'    => 'index',
                    'action'        => 'detail',
                    'id'            => $tag['id'],
                ));
            ?>
            <tr>
                <td><a href="<?php echo $url; ?>"><?php echo _escape($tag['term']); ?></td>
                <td><?php echo $tag['count']; ?></td>
            </tr>
            <?php } ?>
        </table>
        <?php
        if ($paginator) {
            echo $this->pagination(
                $paginator,
                'Sliding',
                'paginator.phtml',
                array('class' => 'pagination-right')
            );
        }
        ?>
    </div>
</div>