<?php 
//$this->I18nModule('admin', 'zh-CN');
$this->css(array($this->assetModule('script/tag-admin.css')));
?>
<h2 class="page-header"><?php _e('Search'); ?></h2>
<h3><?php echo sprintf(__('Search result for "%s"'), _escape($tagName)); ?></h3>
<?php if ($find == 'n') { ?>
<div class="alert">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><?php echo sprintf(__('No item found for "%s".'), _escape($tagName)); ?></strong>
</div>
<?php } else {  ?>
    <table class="table table-hover table-bordered">
    <tr class="box-bordered-header">
        <th><?php _e('Tag Name'); ?></th>
        <th class="span2"><?php _e('Count'); ?></th>
        <th class="span1"><?php _e('Operation') ?></th>
    </tr>
    <?php
    foreach ($items as $row) { ?>
    <tr>
        <?php
        $url = $this->url('', array(
            'module'        => Pi::service('module')->current(),
            'controller'    => 'index',
            'action'        => 'detail',
            'id'            => $row['id']
        ));
        $deleteUrl = $this->url('', array(
            'controller'    => 'index',
            'action'        => 'delete',
            'id'            => $row['id'],
            'name'          => $tagName,
            'search'        => 'y'
        ));
        ?>
        <td><a href="<?php echo $url; ?>"><?php echo _escape($row['term']); ?></a></td>
        <td><?php echo $row['count'];  ?></td>
        <td><a href="<?php echo $deleteUrl; ?>"><?php echo __('Delete'); ?></a></td>
    </tr>
    <?php }?>
    </table>
<?php } ?>
<?php
if ($paginator) {
    echo $this->pagination(
        $paginator,
        'Sliding',
        'paginator.phtml',
        array('class' => 'pagination-right')
    );
}
?>
