<?php
// Options: interval, pause, height
$options = (array) $block['options'];
$class = 'carousel';
if (isset($options['class'])) {
    $class .= ' ' . $options['class'];
    unset($options['class']);
} else {
    $class .= ' slide';
}
$items = $block['items'];
$activeItem = array_shift($items);
$count = count($items);

$_this = $this;
$render = function ($item) use ($_this)
{
    $caption = $_this->escape($item['caption']);
    $description = $_this->escape($item['desc']);
    $image = '<img class="center-block" src="' . $item['image'] . '" alt="' . $caption . '" />';

    $content = '';
    if (!empty($item['link'])) {
        $content .= '<a target="_blank" href="' . $item['link'] . '" title="' . $caption . '">' . $image . '</a>';
    } else {
        $content .= $image;
    }
    if ($caption || $description) {
        $content .= '<div class="carousel-caption"><h4>' . $caption . '</h4><p>' . $description . '</p></div>';
    }
    return $content;
};

$carouselId = uniqid('carousel');
$style = ".carousel-control .fa-chevron-left,
.carousel-control .fa-chevron-right {
    position: absolute;
    top: 50%;
}";
$this->headStyle()->appendStyle($style);
?>
<div id="<?php echo $carouselId; ?>" class="<?php echo $class; ?>">
    <ol class="carousel-indicators">
        <li data-target="#<?php echo $carouselId; ?>" data-slide-to="0" class="active"></li>
        <?php for ($i = 1; $i <= $count; $i++) { ?>
        <li data-target="#<?php echo $carouselId; ?>" data-slide-to="<?php echo $i; ?>"></li>
        <?php } ?>
    </ol>

    <!-- Carousel items -->
    <div <?php if ($options['height']) { echo 'style="height: ' . $options['height'] . 'px;"'; } ?> class="carousel-inner">
        <div class="active item">
            <?php echo $render($activeItem); ?>
        </div>
        <?php foreach ($items as $item) { ?>
        <div class="item">
            <?php echo $render($item); ?>
        </div>
        <?php } ?>
    </div>

    <!-- Carousel nav -->
    <a class="left carousel-control" href="#<?php echo $carouselId; ?>" data-slide="prev">
        <span class="fa fa-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#<?php echo $carouselId; ?>" data-slide="next">
        <span class="fa fa-chevron-right"></span>
    </a>
</div>
<?php
$script = sprintf('$("#%s").carousel(%s);',
        $carouselId,
        json_encode($block['options'])
    );
$this->footScript()->appendScript($script);
?>
