<?php
    // Load activity.css
    $this->css(array(
        Pi::url('static/custom/user/register.css'),
    ));

    $this->bootstrap('js/bootstrap.min.js');
    $tabItemView = '
        <tr>
            <td>
                <div style="width: 360px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
            <td class="muted">%s
            <td>
                <div style="width: 180px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
    ';
    $tabItemMoreView = '
        <tr>
            <td>
                <div style="width: 260px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
            <td class="muted">%s
            <td class="muted">%s
            <td>
                <div style="width: 180px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
    ';
    $tabEmpty = '
        <tr>
            <td colspan="%s">
                <span class="muted">%s</span>
    ';
?>
<div class="span9">
    <ul class="activity-tab">
        <li class="active">
            <a href="#js-topic" data-toggle="tab">
                <?php _e('Topic'); ?>
            </a>
        <li>
            <a href="#js-reply" data-toggle="tab">
                <?php _e('Reply'); ?>
            </a>
        <li>
            <a href="#js-question" data-toggle="tab">
                <?php _e('Question'); ?>
            </a>
        <li>
            <a href="#js-answer" data-toggle="tab">
                <?php _e('Answer'); ?>
            </a>
       <li>
            <a href="#js-project" data-toggle="tab">
                <?php _e('Project'); ?>
            </a> 
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="js-topic">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($topics) {
                        foreach($topics as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['community'],
                                 $item['communityUrl']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-reply">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($replies) {
                        foreach($replies as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['community'],
                                 $item['communityUrl']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-question">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($questions) {
                        foreach($questions as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['community'],
                                 $item['communityUrl']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-answer">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($answers) {
                        foreach($answers as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['community'],
                                 $item['communityUrl']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-project">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Create time'); ?>
                        <td>
                            <?php _e('Update time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($projects) {
                        foreach($projects as $item) {
                            echo sprintf($tabItemMoreView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['createTime'],
                                 $item['updateTime'],
                                 $item['community'],
                                 $item['communityUrl']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 4, __('No content'));
                    }
                    ?>
            </table>
        </div>
    </div>
</div>
<div class="span3">
    <div class="activity-panel">
        <div class="activity-panel-header">
            <a class="pull-right" href="<?php echo $blog[0]['url']; ?>" target="_blank">
                <?php _e('Manage'); ?>
            </a>
            <span class="activity-icon activity-icon-blog"><?php _e('Blog'); ?></span>
        </div>
        <ul class="activity-panel-body activity-panel-body-blog">
            <?php foreach ($blog as $item) { ?>
            <li>
                <a href="<?php echo $item['url']; ?>" target="_blank">
                    <?php echo $item['count']; ?>
                    <br>
                    <?php echo $item['action']; ?>
                </a>
            <?php } ?>
        </ul>
    </div>
    <div class="activity-panel">
        <div class="activity-panel-header">
            <a class="pull-right" href="<?php echo $rel[0]['url']; ?>" target="_blank">
                <?php _e('Manage'); ?>
            </a>
            <span class="activity-icon activity-icon-rel"><?php _e('Relationship'); ?></span>
        </div>
        <ul class="activity-panel-body">
            <?php foreach ($rel as $item) { ?>
            <li>
                <a href="<?php echo $item['url']; ?>" target="_blank">
                    <?php echo $item['count']; ?>
                    <br>
                    <?php echo $item['action']; ?>
                </a>
            <?php } ?>
        </ul>
    </div>
</div>
