<?php
    // Load activity.css
    $this->css(array(
        Pi::url('static/custom/user/activity.css'),
    ));
?>

<?php if ($community) { ?>
<ul class="unstyled">
    <?php foreach($community as $key => $item) { ?>
    <?php if ($key % 3 == 0) { ?> 
    <li class="row-fluid">
    <?php } ?>
        <div class="span4">
            <div class="activity-community-item">
                <div style="margin-left: 10px;" class="pull-right">
                    <?php _e('Point'); ?> <?php echo $item['point']; ?>
                </div>
                <div class="ellipsis">
                    <a href="<?php echo $item['url']; ?>" target="_blank" 
                       title="<?php echo $item['name']; ?>">
                        <?php echo $item['name']; ?>
                    </a>   
                </div>                
            </div>
        </div>
    <?php } ?>
</ul>
<?php } else { ?>
<div>
    <?php _e('You do not join in community'); ?>
</div>
<?php } ?>
