<?php
// Load register.css
$this->css(array(
    $this->assetTheme('css/register.css'),
));
?>

<!-- Subheader -->
<div class="pi-subheader">
    <a href="/login/register" title="EEFOCUS 与非网 通行证">
        <img src="<?php echo $this->assetTheme('image/logo-eefocus-permit.png'); ?>" alt="EEFOCUS 与非网 通行证">
    </a>
</div>

<div class="row-fluid pi-minheight">
    <div class="page-header">
        <h3>
            <?php _e('密码设置'); ?>
        </h3>
    </div>
    
    <div>
        <?php if (!(isset($result) && $result['status'])) {
            if (!(isset($result) && $result['message'])) {
                include $this->templateComponent('form-horizontal');
            } else { ?>
                <p class="text-error text-center text-large">
                    <?php _e('密码找回失败，请'); ?>
                    <a href="<?php echo $this->url('', array('controller' => 'password', 'action' => 'find')); ?>">
                        <?php _e('重新找回密码'); ?>
                    </a>
                </p>
        <?php }
        } else { ?>
            <p class="text-center text-large">
                <img style="margin-right: 10px; vertical-align: middle;" src="<?php echo $this->assetTheme('image/icon-success-large.png'); ?>">
                <?php _e('密码找回成功，请'); ?>
                <a href="<?php echo Pi::service('authentication')->getUrl('login'); ?>"><?php _e('登录'); ?></a>
            </p>
        <?php } ?>
    </div>
</div>
