<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
?>

<!-- Subheader -->
<div class="pi-subheader">
    <a href="/login/register" title="EEFOCUS 与非网 通行证">
        <img src="<?php echo Pi::url('static/custom/user/logo-eefocus-permit.png'); ?>" alt="EEFOCUS 与非网 通行证">
    </a>
</div>

<div class="row-fluid pi-minheight">
    <div class="span8">
        <div class="page-header">
            <h3><?php _e('找回密码'); ?></h3>
        </div>

        <div>
        <?php if (!(isset($result) && $result['status'])) {
            if (isset($result)) {
                echo sprintf(
                    '<div class="alert %s"><a href="#" data-dismiss="alert" class="close">&times;</a>%s</div>',
                    'alert-error',
                    $result['message']);
            }
            include $this->templateComponent('form-horizontal');
        } else { ?>
            <p class="text-center text-large">
                <?php _e('重设密码的链接已经发往您的邮箱。'); ?>
            </p>
        <?php } ?>
        </div>
    </div>

    <div class="span4">
        <h4><?php _e('找回密码流程：'); ?></h4>
        <ol>
            <li><?php _e('填写 Email 地址, 发送找回密码邮件');?>
            <li><?php _e('查收邮件，点击邮件中的修改密码链接'); ?>
            <li><?php _e('修改密码');?>
            <li><?php _e('完成');?>
        </ol>
    </div>
</div>
