<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
Pi::service('i18n')->load('custom/user:default');
?>

<!-- Subheader -->
<div class="pi-subheader">
    <a href="<?php echo Pi::service('authentication')->getUrl('login'); ?>" title="EEFOCUS 与非网 通行证">
        <img src="<?php echo Pi::url('static/custom/user/logo-eefocus-permit.png'); ?>" alt="EEFOCUS 与非网 通行证">
    </a>
</div>

<div class="row-fluid pi-minheight">
    <div class="span8">
        <div class="page-header">
            <h3><?php _e('Find password'); ?></h3>
        </div>

        <div>
        <?php if (!(isset($result) && $result['status'])) {
            if (isset($result)) {
                echo sprintf(
                    '<div class="alert %s"><a href="#" data-dismiss="alert" class="close">&times;</a>%s</div>',
                    'alert-error',
                    $result['message']);
            }
            include $this->templateComponent('form-horizontal');
        } else { ?>
            <p class="text-center text-large">
                <?php _e('An reset password link has been sent to your email'); ?>
            </p>
        <?php } ?>
        </div>
    </div>

    <div class="span4">
        <h4><?php _e('Find password proceed:'); ?></h4>
        <ol>
            <li><?php _e('input email address,send find password email');?>
            <li><?php _e('click the link in email'); ?>
            <li><?php _e('change password');?>
            <li><?php _e('done');?>
        </ol>
    </div>
</div>
