<?php
// Load register.css
$this->css(array(
    $this->assetTheme('css/register.css'),
));
?>

<!-- Subheader -->
<div class="pi-subheader">
    <a href="/login/register" title="EEFOCUS 与非网 通行证">
        <img src="<?php echo $this->assetTheme('image/logo-eefocus-permit.png'); ?>" alt="EEFOCUS 与非网 通行证">
    </a>
</div>

<div class="row-fluid pi-minheight">
    <div class="page-header">
        <h3><?php _e('用户激活'); ?></h3>
    </div>

    <div class="text-center text-large">
        <?php if (isset($result) && $result['status']) { ?>
            <img style="margin-right: 10px; vertical-align: middle;" src="<?php echo $this->assetTheme('image/icon-success-large.png'); ?>">
            <?php _e('激活成功，请'); ?>
            <a href=""><?php _e('登录'); ?></a>
        <?php } else { ?>
            <p>
                <?php _e('对不起，此链接已失效。可能您已完成激活，或者超过有效激活时间。'); ?>
            </p>
            <p>
                <?php _e('你可以选择'); ?>
                <a href="" title="<?php _e('登录'); ?>"><?php _e('登录'); ?></a>
                <?php _e('，或'); ?>
                <span class="user-js-reactivate">
                    <a class="user-js-reactivate-link" style="margin-left: 4px;" href="javascript:;" title="<?php _e('重新发送激活邮件');?>">
                        <?php _e('重新发送激活邮件');?>
                    </a>
                    <span class="hide user-js-reactivate-tip">
                        ( <span class="user-js-reactivate-message"></span><span class="user-js-reactivate-countdown"></span> )
                    </span>
                </span>
            </p>

            <style>
                a.disabled {
                    opacity: 0.65;
                    filter: alpha(opacity=65);
                    cursor: not-allowed;
                }

                a.disabled:hover {
                    text-decoration: none;
                }
            </style>
            <script src="<?php echo $this->assetTheme('js/register-reactivate.js'); ?>"></script>
            <script>
                jQuery(function() {
                    userRegisterReactivate.init({
                        reactivateUrl: '<?php echo $this->url('', array('controller' => 'register', 'action' => 'reactivate', 'uid' => $result['uid']));?>',
                        AlREADY_SENT: '<?php _e('邮件已发送'); ?>'
                    });
                });
            </script>
        <?php } ?>
    </div>
</div>
