<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
?>

<!-- Subheader -->
<div class="pi-subheader">
    <a href="/login/register" title="EEFOCUS 与非网 通行证">
        <img src="<?php echo Pi::url('static/custom/user/logo-eefocus-permit.png'); ?>" alt="EEFOCUS 与非网 通行证">
    </a>
</div>

<div class="row-fluid pi-minheight">
    <div class="page-header">
        <h3><?php _e('用户激活'); ?></h3>
    </div>

    <div class="text-center text-large">
        <?php if (isset($result) && $result['status']) { ?>
            <img style="margin-right: 10px; vertical-align: middle;" src="<?php echo Pi::url('static/custom/user/icon-success-large.png'); ?>">
            <?php _e('激活成功，请'); ?>
            <a href="<?php echo Pi::service('authentication')->getUrl('login'); ?>"><?php _e('登录'); ?></a>
        <?php } else { ?>
            <p>
                <?php _e('对不起，此链接已失效。可能您已完成激活，或者超过有效激活时间。'); ?>
            </p>
            <p>
                <?php _e('你可以选择'); ?>
                <a href="<?php echo Pi::service('authentication')->getUrl('login'); ?>"><?php _e('登录'); ?></a>
                <?php _e('，或'); ?>
                <a href="<?php echo $this->url('', array('controller' => 'register', 'action' => 'resend.active.mail')); ?>"><?php _e('重新发送激活邮件');?></a>
            </p>
        <?php } ?>
    </div>
</div>
