<?php
//$this->css($this->assetModule('admin/admin.css', 'system'));
?>
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th><?php echo _a('Page title'); ?></th>
            <th style="width: 5%;"><?php echo _a('Name'); ?></th>
            <th style="width: 5%;"><?php echo _a('Slug'); ?></th>
            <th style="width: 5%;"><?php echo _a('Type'); ?></th>
            <th style="width: 20%;"><?php echo _a('Time published'); ?></th>
            <th style="width: 20%;"><?php echo _a('Last Update'); ?></th>
            <th><?php echo _a('Action'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pages as $page) { ?>
            <tr>
                <td>
                    <?php echo _escape($page['title']); ?>
                </td>
                <td>
                    <?php echo _escape($page['name']); ?>
                </td>
                <td>
                    <?php echo _escape($page['slug']); ?>
                </td>
                <td>
                    <?php echo _escape($page['markup']); ?>
                </td>
                <td>
                    <?php echo _date($page['time_created']); ?>
                </td>
                <td>
                    <?php echo $page['time_updated'] ? _date($page['time_updated']) : ''; ?>
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-primary" href="<?php echo $page['url']; ?>"  target="_blank"><?php echo _a('View'); ?></a>
                        <a class="btn btn-sm btn-primary" href="<?php echo $this->url('', array('action' => 'edit', 'id' => $page['id'])); ?>"><?php echo _a('Edit'); ?></a>
                        <a class="btn btn-sm btn-primary" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $page['id'])); ?>"><?php echo _a('Delete'); ?></a>
                        <?php if ($page['active']) { ?>
                        <a class="btn btn-sm btn-primary" href="<?php echo $this->url('', array('action' => 'activate', 'id' => $page['id'])); ?>"><?php echo _a('Disable'); ?></a>
                        <?php } else { ?>
                            <a class="btn btn-sm btn-warning" href="<?php echo $this->url('', array('action' => 'activate', 'id' => $page['id'])); ?>"><?php echo _a('Enable'); ?></a>
                        <?php }?>
                    </div>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
