<div id="confirm-modal" class="modal" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true" style="display: none;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4><?php _e('Delete this message?')?></h4>
    </div>
    <div class="modal-body">
        <?php _e('Once you delete this message, it cannot be undone.')?>
    </div>
    <div class="modal-footer">
        <a class="btn btn-primary confirm-ok">  
            <?php _e('Delete message') ?>
        </a>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    </div>
</div>

<div id="confirm-modals" class="modal" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true" style="display: none;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4><?php _e('Delete these messages?')?></h4>
    </div>
    <div class="modal-body">
        <?php _e('Once you delete these messages, they cannot be undone.')?>
    </div>
    <div class="modal-footer">
        <a class="btn btn-primary confirm-ok">  
            <?php _e('Delete messages') ?>
        </a>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    </div>
</div>    