<div id="confirm-modal" class="modal fade" role="dialog" aria-labelledby="dataConfirmLabel" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4><?php _e('Delete this message?')?></h4>
            </div>
            <div class="modal-body">
                <?php _e('Once you delete this message, it cannot be undone.')?>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary confirm-ok">
                    <?php _e('Delete message') ?>
                </a>
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php _e('Cancel')?></button>
            </div>
        </div>
    </div>
</div>