<?php $this->css($this->assetModule('script/front.css')); ?>
<div class="clearfix">
    <div class="col-md-3">
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?php _e('Message archive'); ?></h1>
        </div>
        <ul class="nav nav-tabs message-nav-tabs">
            <li>
                <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>"
                   title="<?php _e('Private message'); ?>"><?php _e('Private message');; ?></a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'archive')); ?>"
                   title="<?php _e('Archive'); ?>"><?php _e('Archive'); ?></a>
            </li>
        </ul>
    </div>
</div>