<div class="clearfix">
    <div class="col-md-3">
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <a class="pull-right message-return"
               href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>">
                <?php _e('Return message list page'); ?>
            </a>
            <h3><?php _e('Write message'); ?></h3>
        </div>
        <?php echo $this->form($form); ?>
    </div>
</div>