<?php $this->css($this->assetModule('script/front.css')); ?>
<div class="clearfix">
    <div class="col-md-3">
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <ul class="nav nav-tabs message-nav-tabs">
            <li class="active">
                <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>"
                   title="<?php _e('Private message'); ?>"><?php echo $messageTitle; ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>"
                   title="<?php _e('Notification'); ?>"><?php echo $notificationTitle; ?></a>
            </li>
        </ul>
        <?php if (!empty($errMessage)) { $class = ' alert-error'; ?>
            <div class="alert<?php echo $class; ?>">
                <?php echo $errMessage; ?>
            </div>
        <?php } ?>
        <?php if (!empty($list)) { ?>
            <?php foreach($list as $singleMessage) { ?>
                <div class="messages" id="message-js">
                <div class="media message-detail">
                    <div class="message-detail-head">
                        <h4 class="media-heading pull-left message-head">
                            <span><?php echo $uid == $singleMessage['uid_from'] ? __('To') : __('From'); ?></span>
                            <a href="<?php echo $singleMessage['profileUrl']; ?>"><?php echo $singleMessage['name']; ?></a>
                        </h4>
                        <p class="message-time text-right">
                            <span class="muted"><?php echo _date($singleMessage['time_send']); ?></span>
                        </p>
                    </div>
                    <div class="media message-detail-primary">
                        <a href="<?php echo $singleMessage['profileUrl']; ?>" class="pull-left">
                            <?php echo $singleMessage['avatar']; ?>
                        </a>
                        <div class="media-body message-detail-con">
                            <p><?php echo $singleMessage['content']; ?></p>
                            <div class="message-detail-hidden">
                                <p class="pull-right">
                                    <a href="<?php echo $this->url('', array('action' => 'delete', 'ids' => $singleMessage['id'], 'tid' => $singleMessage['uid_to'])); ?>"
                                       class="js-delete">
                                        <?php _e('Delete'); ?>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
                <div class="clearfix well">
                    <?php echo $this->form($form, 'horizontal'); ?>
                </div>
            </div>
        <?php } ?>
        <?php include $this->template('./_confirm-modal.phtml'); ?>
    </div>
</div>
<?php
$paginator = isset($paginator) ? $paginator->getCurrentPageNumber() : '';
$host = $this->url('', array('module' => 'message'));
$confirm = __('Once you delete this message, it cannot be undone.');
$script = "messageIndex({p: '%s', host: '%s', confirm: '%s'});";
$script = sprintf($script, $paginator, $host, $confirm);

$this->footScript()->appendFile($this->assetModule('script/index-detail.js'));
$this->footScript()->appendScript($script);
?>