<?php $this->css($this->assetModule('script/front.css')); ?>
    <div class="clearfix">
        <div class="col-md-3">
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h1><?php _e('Message'); ?></h1>
            </div>
            <ul class="nav nav-tabs message-nav-tabs">
                <li class="active">
                    <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>"
                       title="<?php _e('Private message'); ?>"><?php echo $messageTitle; ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>"
                       title="<?php _e('Notification'); ?>"><?php echo $notificationTitle; ?></a>
                </li>
            </ul>
            <div class="messages" id="message-js">
                <?php if (!empty($messages)) { ?>
                    <?php foreach ($messages as $message) { ?>
                        <div class="clearfix message-item<?php if (!$message['is_read']) { echo ' message-item-read'; } ?>">
                            <div class="pull-left text-center">
                                <div class="pull-left message-checkbox">
                                    <input type="checkbox" class="message-js-check" data-id="<?php echo $message['id']; ?>">
                                </div>
                                <div class="pull-left message-avatar">
                                    <a href="<?php echo $message['profileUrl']; ?>">
                                        <?php echo $message['avatar']; ?>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-10">
                                <ul class="list-inline small">
                                    <li class="message-time muted"><?php echo $uid == $message['uid_from'] ? __('To') : __('From'); ?></li>
                                    <li>
                                        <a href="<?php echo $message['profileUrl']; ?>" class="message-user-name">
                                            <?php echo $message['name']; ?>
                                        </a>
                                    </li>
                                    <li class="message-divider">|</li>
                                    <li class="message-time muted"><?php echo _date($message['time_send']); ?></li>
                                    <li class="message-divider">|</li>
                                    <li>
                                        <a href="<?php if (isset($paginator)) {
                                            echo $this->url('', array(
                                                'action' => 'delete',
                                                'ids' => $message['id'],
                                                'p' => $paginator->getCurrentPageNumber()
                                            ));
                                        } else {
                                            echo $this->url('', array('action' => 'delete', 'ids' => $message['id']));
                                        } ?>" class="message-js-delete"
                                           data-confirm="<?php _e('Once you delete this message, it cannot be undone.'); ?>">
                                            <?php _e('Delete'); ?>
                                        </a>
                                    </li>
                                    <li class="message-divider">|</li>
                                    <li class="message-mark">
                                        <a href="<?php if (isset($paginator)) {
                                            echo $this->url('', array(
                                                'action' => 'mark',
                                                'ids' => $message['id'],
                                                'p' => $paginator->getCurrentPageNumber()
                                            ));
                                        } else {
                                            echo $this->url('', array('action' => 'mark', 'ids' => $message['id']));
                                        } ?>">
                                            <?php _e('Mark as read'); ?>
                                        </a>
                                    </li>
                                    <li class="message-divider">|</li>
                                    <li class="message-mark">
                                        <a href="<?php echo $this->url('', array('action' => 'detail', 'mid' => $message['id'])); ?>">
                                            <?php _e('Read'); ?>
                                        </a>
                                    </li>
                                </ul>
                                <div class="message-content">
                                    <a href="<?php echo $this->url('', array('action' => 'detail', 'mid' => $message['id'])); ?>"
                                       class="message-content-link"> <?php echo $message['content']; ?>
                                    </a>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                <?php } else { ?>
                    <div class="alert alert-info message-alert"><?php _e('No message for you!'); ?></div>
                <?php } ?>
                <?php if (isset($paginator)) {
                    echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml', array(
                        'class' => 'pagination-right pull-right message-pagination'
                    ));
                } ?>
                <div class="clearfix">
                    <form class="form-inline pull-left message-foot-form col-md-12" action="">
                        <input type="checkbox" class="message-js-batch" title="<?php _e('Checked all'); ?>">
                        <select class="message-batch-action">
                            <option value=""><?php _e('Massive operation'); ?></option>
                            <option value="mark"><?php _e('Mark as read'); ?></option>
                            <option value="delete"><?php _e('Delete'); ?></option>
                        </select>
                    </form>
                </div>
                <?php include $this->template('./_confirm-modal.phtml'); ?>
            </div>
        </div>
    </div>
<?php
$paginator = isset($paginator) ? $paginator->getCurrentPageNumber() : '';
$host = $this->url('', array('module' => 'message'));
$confirm = __('Once you delete those message, it cannot be undone.');
$script = "messageIndex({p: '%s', host: '%s', confirm: '%s'});";
$script = sprintf($script, $paginator, $host, $confirm);
$this->footScript()->appendFile($this->assetModule('script/index-index.js'));
$this->footScript()->appendScript($script);
?>