<?php
    $this->css($this->assetModule('script/front.css'));
?>
<ul class="nav nav-tabs message-nav-tabs">
    <li class="active">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>" title="<?php _e('Private message'); ?>"><?php echo $messageTitle; ?></a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'archive')); ?>" title="<?php _e('Archive'); ?>"><?php _e('Archive'); ?></a>
    </li>
<!--    <li>-->
<!--        <a href="--><?php //echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?><!--" title="--><?php //_e('Notification'); ?><!--">--><?php //echo $notificationTitle; ?><!--</a>-->
<!--    </li>-->
<!--    <li>-->
<!--        <button type="button" class="btn message-nav-btn" onclick="location.href=-->
<!--        '--><?php //echo $this->url('', array('controller' => 'index', 'action' => 'send')); ?><!--'" -->
<!--        title="--><?php //_e('New message'); ?><!--">--><?php //_e('New message'); ?><!--</button>-->
<!--    </li>-->
</ul>

<?php
    if (!empty($errMessage)) {
        $class = ' alert-error';
?>
<div class="alert<?php echo $class; ?>">
    <button data-dismiss="alert" class="close" type="button">
        ×
    </button>
    <?php echo $errMessage; ?>
</div>

<?php }
if (!empty($message)) { ?>
<div class="messages" id="message-js">
    <div class="media message-detail">
        <div class="message-detail-head">
            <h5 class="media-heading pull-left message-head">                
                <span><?php echo $uid == $message['uid_from']?'To':'From';?></span>
                <a href="<?php echo $message['profileUrl']; ?>"><?php echo $message['name'] . ':'; ?></a>
            </h5>
            <p class="message-time text-right">
               <span class="muted"><?php echo _date($message['time_send']); ?></span>
            </p>
        </div>
        <div class="media message-detail-primary">
            <a href="<?php echo $message['profileUrl']; ?>" class="pull-left">
                <?php echo $message['avatar']; ?>
            </a>
            <div class="media-body message-detail-con">
                <p>
                    <?php echo $message['content']; ?>
                </p>
                <div class="message-detail-hidden">
                    <p class="pull-right">
                        <span>
                            <a href="<?php echo $this->url('', array('action' => 'delete', 'ids' => $message['id'], 'tid' => $message['uid_to'])); ?>" class="js-delete">
                                <?php _e('Delete'); ?></a>
                        </span>
                    </p>
                </div>
            </div> 
        </div>  
    </div>        
    <?php 
        $form->setAttribute('class', 'message-form-posi');
        echo $this->form()->openTag($form); 
    ?>
    <?php 
        $element = $form->get('content');
        $element->setAttributes(array(
            'class' => 'form-control message-textarea',
            'rows' => '6'
        ));
        echo '<div class="message-send-text message-detail-text">' . $this->formElement($element);
        echo $this->formElementErrors($element);
        echo '</div>'
    ?>
    <?php
        echo $this->formElement($form->get('uid_to'));
        $element = $form->get('submit');
        $element->setAttributes(array(
            'class' => 'btn btn-primary pull-right',
        ));
        echo $this->formSubmit($element); 
        echo $this->form()->closeTag($form); 
    ?>
</div>
<?php } ?>
<script src="<?php echo $this->assetModule('script/index-detail.js'); ?>"></script>
    
<script>
messageIndex({
    p: '<?php echo isset($paginator) ? $paginator->getCurrentPageNumber() : ''; ?>',
    host: '<?php echo $this->url('', array('module' => 'message')); ?>',
    confirm: '<?php _e('Once you delete this message, it cannot be undone.'); ?>'
});
</script>  
