<?php $this->css($this->assetModule('script/front.css')); ?>
    <div class="clearfix">
        <div class="col-md-3">
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h1><?php _e('Notification'); ?></h1>
            </div>
            <ul class="nav nav-tabs message-nav-tabs">
                <li>
                    <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>"
                       title="<?php _e('Private message'); ?>"><?php echo $messageTitle; ?></a>
                </li>
                <li class="active">
                    <a href="<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>"
                       title="<?php _e('Notification'); ?>"><?php echo $notificationTitle; ?></a>
                </li>
            </ul>
            <div class="messages" id="message-js">
                <?php if (!empty($notifications)) { ?>
                    <?php foreach ($notifications as $notification) { ?>
                        <div class="media message-item<?php if (!$notification['is_read']) { echo ' message-item-read';} ?>">
                            <div class='pull-left'>
                                <input type="checkbox" class="message-js-check" data-id="<?php echo $notification['id']; ?>">
                                <a class="message-content-link" href="<?php echo $this->url('', array('action' => 'detail', 'mid' => $notification['id'])); ?>">
                                    <?php echo _escape($notification['subject']); ?>
                                </a>
                            </div>
                            <div class="pull-right text-right message-media-right">
                                <p class="message-time">
                                    <span class="muted"><?php echo _date($notification['time_send']); ?></span>
                                </p>
                            </div>
                        </div>
                    <?php } ?>
                <?php } else { ?>
                    <div class="alert alert-info message-alert"><?php _e('No notification for you!'); ?></div>
                <?php  } ?>
                <?php
                if (isset($paginator)) {
                    echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml', array(
                        'class' => 'pagination-right pull-right message-pagination'
                    ));
                }
                ?>
                <form class="form-inline message-foot-form" action="">
                    <input type="checkbox" class="message-js-batch" title="<?php _e('Checked all'); ?>">
                    <select class="message-batch-action">
                        <option value=""><?php _e('Massive operation'); ?></option>
                        <option value="mark"><?php _e('Mark as read'); ?></option>
                        <option value="delete"><?php _e('Delete'); ?></option>
                    </select>
                </form>
                <?php include $this->template('./_confirm-modal.phtml'); ?>
            </div>
        </div>
    </div>
<?php
$paginator = isset($paginator) ? $paginator->getCurrentPageNumber() : '';
$host = $this->url('', array('module' => 'message'));
$script = "messageIndex({p: '%s', host: '%s'});";
$script = sprintf($script, $paginator, $host);
$this->footScript()->appendFile($this->assetModule('script/notify-index.js'));
$this->footScript()->appendScript($script);
?>