<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/front.css'));
    $this->jQuery();
    $this->bootstrap('js/bootstrap.min.js');
?>
<ul class="nav nav-tabs message-nav-tabs">
    <li><a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>" title="<?php _e('Messages'); ?>"><?php echo $messageTitle; ?></a></li>
    <li class="active"><a href=
        "<?php echo $this->url('', array('controller' => 'notify', 'action' => 'index')); ?>" 
        title="<?php _e('Notification'); ?>"><?php echo $notificationTitle; ?></a></li>
    <li><button type="button" class="btn message-nav-btn" onclick="location.href=
        '<?php echo $this->url('', array('controller' => 'index', 'action' => 'send')); ?>'" 
        title="<?php _e('New message'); ?>"><?php _e('New message'); ?></button></li>
</ul>

<?php
    if (!empty($errMessage)) {
        $class = ' alert-error';
?>
<div class="alert<?php echo $class; ?>">
    <button data-dismiss="alert" class="close" type="button">
        ×
    </button>
    <?php echo $errMessage; ?>
</div>

<script>$(".alert").alert();</script>

<?php }

if (!empty($notification)) { ?>
<div class="messages" id="message-js">
    <div class="media message-detail">
        <div class="message-detail-head">
            <h5 class="media-heading pull-left message-head">                
                <?php echo $notification['subject']?>
                <span class="label label-info message-label-type">
                    <?php
                        if (!empty($notification['tag'])) {
                            echo  $notification['tag'];
                        }
                    ?>
                </span>
            </h5>
            <p class="message-time text-right">
                <span class="muted">
                    <?php echo date('Y/m/d H:i', $notification['time_send']); ?>
                </span>
            </p>
        </div>
        <div class="media message-detail-primary">
            <div class="media-body">
                <p class="message-body"><?php echo $notification['content']; ?></p>
                <div class="message-detail-hidden">
                    <p class="message-hidden pull-right">
                        <span>
                            <a href="<?php echo $this->url('', array('action' => 'delete', 'ids' => $notification['id'])); ?>" data-confirm="Once you delete this message, it cannot be undone.">
                                <?php _e('Delete'); ?>
                            </a>
                        </span>
                    </p>
                </div>
            </div> 
        </div>  
    </div>
</div>
<?php } ?>
<?php include '_confirm-modal.phtml' ?>
<script src="<?php echo $this->assetModule('script/notify-index.js'); ?>"></script>

<script>
messageIndex({
    p: '<?php echo isset($paginator) ? $paginator->getCurrentPageNumber() : ''; ?>',
    host: '<?php echo $this->url('', array('module' => 'message')); ?>'
});
</script>