<!--
<div id="pi-engine-feature">Pi Engine features</a>
<script>
$.ajax({
    url: "<?php echo $block['api']; ?>",
    dataType: "jsonp",
    success: function(data){
        $('#pi-engine-feature').html(data);
    }
});
</script>
-->

<p>
  Pi Engine is a role oriented application development engine for web and mobile, designed as the next generation and a successor to Xoops.
  Pi is developed upon PHP and MySQL with selected third-party frameworks including but not limited to Zend Framework library, jQuery, Bootstrap and Backbone.
<p>
  Pi Project follows the philosophy of open standard, open design, open development and open structure. Pi is born as a complete open source project and intended to build a sustainable ecosystem that benefits all contributors and users.
<p>
  The Engine is released under a New BSD License.
</p>
Selected features and practices:
<ol>
    <li>Modularization for functionality and applications
    <li>Components for basic libraries and services for fundamental system functions
    <li>Theming for presentation and appearance
    <li>Design-friendly templating
    <li>DevOps oriented architecture
    <li>Centralized security enhancement
</ol>
Quick start:
<ul>
    <li>Pi Engine website: <a href="http://pialog.org" title="Pi Engine">Pi Dialog</a>
    <li>Latest download: <a href="https://github.com/pi-engine/pi/zipball/master" title="Latest stable code">Stable Download</a>
    <li>Pi Engine documents: <a href="https://github.com/pi-engine/pi/wiki" title="Pi Wiki">Pi Documentation</a>
    <li>Feature and Issues: <a href="https://github.com/pi-engine/pi/issues" title="Issue Tracker">Pi Tracker</a>
</ul>
