<?php
// Options: interval, pause
$options = empty($block['options']) ? '' : json_encode($block['options']);
$class = 'carousel';
if (isset($options['class'])) {
    $class .= ' ' . $options['class'];
    unset($options['class']);
} else {
    $class .= ' slide';
}
$items = $block['items'];
$activeItem = array_shift($items);

$_this = $this;

$render = function ($item) use ($_this)
{
    $caption = $_this->escape($item['caption']);
    $description = $_this->escape($item['desc']);
    $image = '<img src="'. $item['image'] . '" alt="">';

    $content = '';
    if (!empty($item['link'])) {
        $content .= '<a target="_blank" href="' . $item['link'] . '" title="' . $caption .'">' . $image . '</a>';
    } else {
        $content .= $image;
    }
    $content .= '<div class="carousel-caption">' . '<h4 class="ellipsis">' . $caption . '</h4>' . '</div>';
    return $content;
};
$this->css($this->assetModule('script/focusPic/focusPic.css', 'widget'));
$this->jQuery();
$this->js($this->assetModule('script/focusPic/focusPic-min.js', 'widget'));
$carouselId = uniqid('carousel-');
?>
<div id="<?php echo $carouselId; ?>" class="<?php echo $class; ?>">
  <!-- Carousel items -->
  <ul class="carousel-inner">
    <li class="active item">
        <?php echo $render($activeItem); ?>
    <?php foreach ($items as $item) { ?>
    <li class="item">
        <?php echo $render($item); ?>
    <?php } ?>
  </ul>
  <!-- Carousel nav -->
  <ul class="carousel-control-bg">
    <li class="carousel-control-item current">
    <?php foreach ($items as $item) { ?>
    <li class="carousel-control-item">
    <?php } ?>
  </ul>
</div>
<script>
new FocusPic("<?php echo $carouselId; ?>");
</script>
