<?php
$config = $block;
$items = $block['items'];
$class = isset($block['class']) ? $block['class'] : 'jcarousel-skin';
$options = empty($block['options']) ? '' : json_encode($block['options']);
$carouselId = uniqid('carousel-');

$this->css($this->assetModule('script/jcarousel/jcarousel.css', 'widget'));
$this->jQuery();
$this->js($this->assetModule('script/jcarousel/jcarousel-min.js', 'widget'));
?>
<div id="<?php echo $carouselId; ?>" class="<?php echo $class; ?>">
    <ul>
        <?php foreach($items as $item) {
            $href = !empty($item['link']) ? $item['link'] : 'javascript:void(0)';
        ?>
        <li class="jcarousel-item">
            <a target="_blank" href="<?php echo $href; ?>">
                <img src="<?php echo $item['image']; ?>" style="height: 114px; width: 152px;" >
            </a>
            <div style="text-align: center; margin-top: 5px;">
                <a target="_blank" href="<?php echo $href ?>" title="<?php echo $item['caption']; ?>" class="link"><?php echo $item['caption']; ?></a>
            </div>
        <?php } ?>
    </ul>
</div>
<script>
$('#<?php echo $carouselId; ?>').jcarousel({
    auto: 4,
    wrap: 'circular',
    initCallback: function($jcarousel) {
        $jcarousel.container.hover(function() {
            $jcarousel.stopAuto();
        }, function() {
            $jcarousel.startAuto();
        });
    }
});
</script>