<?php
// Options: interval, pause
$options = empty($block['options']) ? '' : json_encode($block['options']);
$class = 'carousel';
if (isset($options['class'])) {
    $class .= ' ' . $options['class'];
    unset($options['class']);
} else {
    $class .= ' slide';
}
$items = $block['items'];
$activeItem = array_shift($items);

$_this = $this;

$render = function ($item) use ($_this)
{
    $caption = $_this->escape($item['caption']);
    $description = $_this->escape($item['desc']);
    $image = '<img src="'. $item['image'] . '" alt="">';

    $content = '';
    if (!empty($item['link'])) {
        $content .= '<a target="_blank" href="' . $item['link'] . '" title="' . $caption .'">' . $image . '</a>';
    } else {
        $content .= $image;
    }
    $content .= '<div class="carousel-caption">' . '<h4>' . $caption . '</h4>' . '<p>' . $description . '</p>' . '</div>';
    return $content;
};

$this->jQuery();
$this->bootstrap('js/bootstrap-carousel.js', false);
$carouselId = uniqid('carousel-');
?>
<div id="<?php echo $carouselId; ?>" class="<?php echo $class; ?>">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
        <?php echo $render($activeItem); ?>
    </div>
    <?php foreach ($items as $item) { ?>
    <div class="item">
        <?php echo $render($item); ?>
    </div>
    <?php } ?>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#<?php echo $carouselId; ?>" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#<?php echo $carouselId; ?>" data-slide="next">&rsaquo;</a>
</div>
<script>
$('.carousel').carousel(<?php echo $options; ?>)
</script>
