
<legend>
    <a href="<?php echo $block['url']; ?>" target="_blank"><?php echo _escape($block['subline']); ?></a>
</legend>

<div class="list-group">
    <?php foreach ($block['items'] as $item) { ?>
    <div style="padding: 10px 5px;">
        <h4 class="list-group-item-heading"><?php echo $item['time']; ?></h4>
        <p class="list-group-item-text">
            <?php echo $item['actor'] . ' ' . $item['action']; ?>
        </p>
    </div>
    <?php } ?>
</div>
