<h2 class="page-header"><?php _e('Find password'); ?></h2>
<?php if (!(isset($result) && $result['status'])) {
    if (isset($result)) {
        echo sprintf(
            '<div class="alert %s"><a href="#" data-dismiss="alert" class="close">&times;</a>%s</div>',
            'alert-error',
            $result['message']);
    }
    include $this->templateComponent('form');
} else { ?>
    <p><?php _e('A reset link has been sent to your email.'); ?></p>
    <p><?php _e('Please check it to reset your password in 24 hours.'); ?></p>
<?php } ?>
