<?php
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.7.0.js',
    'pi.js'
));
?>
<script>
angular
    .module('<?php echo $module; ?>', ['ngRoute', 'ui.bootstrap', 'pi'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('module' => $module)) . $controller . '/'; ?>',
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', false); ?>',
        t: {
            SELECT_ROLES: '<?php echo _a('Select roles'); ?>',
            ANY_ROLE: '<?php echo _a('Any'); ?>',
            NONE_ROLE: '<?php echo _a('None'); ?>',
            APPLY: '<?php echo _a('Apply'); ?>',
            USERNAME: '<?php echo _a('Username'); ?>',
            DISPLAYNAME: '<?php echo _a('Display name'); ?>',
            ROLE: '<?php echo _a('Role'); ?>',
            REGISTER_TIME: '<?php echo _a('Register time'); ?>',
            RETURN: '<?php echo _a('Back to users list'); ?>',
            EMAIL: '<?php echo _a('Email'); ?>',
            FRONT_ROLE: '<?php echo _a('Front role'); ?>',
            ADMIN_ROLE: '<?php echo _a('Admin role'); ?>',
            ASSIGN_ROLE: '<?php echo _a('Assign role'); ?>',
            UNASSIGN_ROLE: '<?php echo _a('Remove role'); ?>',
            ASSIGN_FRONT_ROLE: '<?php echo _a('Front role'); ?>',
            ASSIGN_ADMIN_ROLE: '<?php echo _a('Admin role'); ?>',
            SUBMIT: '<?php echo _a('Submit'); ?>',
            REGISTER_IP: '<?php echo _a('Register IP'); ?>',
            USER_ID: '<?php echo _a('User ID'); ?>',
            NONE_USER: '<?php echo _a('No user matched your request.'); ?>',
            FROM: '<?php echo _a('From'); ?>',
            TO: '<?php echo _a('To'); ?>',
            FRONT: '<?php echo _a('Front'); ?>',
            ADMIN: '<?php echo _a('Admin'); ?>',
            BATCH_CHECKED: '<?php echo _a('Choose at least one item before submission.'); ?>',
            ADMIN_TITLE: '<?php echo _a('Admin roles'); ?>',
            FRONT_TITLE: '<?php echo _a('Front roles'); ?>',
            NAME: '<?php echo _a('Name'); ?>',
            TITLE: '<?php echo _a('Title'); ?>',
            USER_COUNT: '<?php echo _a('Users in role'); ?>',
            ACTION: '<?php echo _a('Action'); ?>',
            ROLE_TITLE: '<?php echo _a('Title'); ?>',
            REQUIRED: '<?php echo _a('Required'); ?>',
            TYPE: '<?php echo _a('Type'); ?>',
            EDIT_TITLE: '<?php echo _a('Users in role'); ?>',
            UID_OR_IDENTITY: '<?php echo _a('User id or name'); ?>',
            UID: '<?php echo _a('User id'); ?>',
            USERNAME: '<?php echo _a('Username'); ?>',
            DISPLAY_NAME: '<?php echo _a('Display name'); ?>',
            ADD_USER: '<?php echo _a('Add user'); ?>'
        },
        roles: <?php echo json_encode($roles); ?>
    });
</script>
<script src="<?php echo $this->assetModule('admin/' . $controller . '.js'); ?>"></script>