<?php
$this->angular(array(
    'angular-route.js',
    'angular-translate.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi-form.js'
));
?>
<div ng-view ng-app="systemRoleModule"></div>
<script>
var systemRoleModule = angular.module('systemRoleModule', ['ngRoute', 'pascalprecht.translate', 
    'ui.bootstrap', 'piForm']);
var systemRoleModuleConfig = {
    urlRoot: '<?php echo $this->url('', array('controller' => 'role')); ?>',
    assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
    t: {
        ADMIN_TITLE: '<?php _e('Admin roles'); ?>',
        FRONT_TITLE: '<?php _e('Front roles'); ?>',
        NAME: '<?php _e('Name'); ?>',
        TITLE: '<?php _e('Title'); ?>',
        USER_COUNT: '<?php _e('Users in role'); ?>',
        ACTION: '<?php _e('Action'); ?>',
        ROLE_TITLE: '<?php _e('Title'); ?>',
        SUBMIT: '<?php _e('Submit'); ?>',
        REQUIRED: '<?php _e('Required'); ?>',
        TYPE: '<?php _e('Type'); ?>',
        FRONT: '<?php _e('Front'); ?>',
        ADMIN: '<?php _e('Admin'); ?>',
        EDIT_TITLE: '<?php _e('Users in role'); ?>',
        UID_OR_IDENTITY: '<?php _e('User id or name'); ?>',
        USERS: '<?php _e('Users'); ?>',
        FIRST: '<?php _e('First'); ?>',
        ADD_USER: '<?php _e('Add user'); ?>'
    }
}
</script>
<?php $debug = 'production' == Pi::environment() ? '.min' : ''; ?>
<script src="<?php echo $this->assetModule('admin/role' . $debug . '.js'); ?>"></script>