<?php
$this->css($this->assetModule('script/admin.css'));
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi.js'
));
?>
<script>
angular
    .module('<?php echo $module; ?>', ['ngRoute', 'ui.bootstrap', 'pi'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('controller' => 'index', 'action' => 'var')); ?>'.replace(/var\/?$/, ''),
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
        t: {
            SELECT_ROLES: '<?php echo _a('Select roles'); ?>',
            ANY_ROLE: '<?php echo _a('Any'); ?>',
            NONE_ROLE: '<?php echo _a('None'); ?>',
            APPLY: '<?php echo _a('Apply'); ?>',
            USERNAME: '<?php echo _a('Username'); ?>',
            DISPLAY_NAME: '<?php echo _a('Display name'); ?>',
            ROLE: '<?php echo _a('Role'); ?>',
            REGISTER_TIME: '<?php echo _a('Register time'); ?>',
            RETURN: '<?php echo _a('Back to users list'); ?>',
            EMAIL: '<?php echo _a('Email'); ?>',
            FRONT_ROLE: '<?php echo _a('Front role'); ?>',
            ADMIN_ROLE: '<?php echo _a('Admin role'); ?>',
            ASSIGN_ROLE: '<?php echo _a('Assign role'); ?>',
            UNASSIGN_ROLE: '<?php echo _a('Remove role'); ?>',
            ASSIGN_FRONT_ROLE: '<?php echo _a('Front role'); ?>',
            ASSIGN_ADMIN_ROLE: '<?php echo _a('Admin role'); ?>',
            SUBMIT: '<?php echo _a('Submit'); ?>',
            REQUIRED: '<?php echo _a('required'); ?>',
            REGISTER_IP: '<?php echo _a('Register IP'); ?>',
            USER_ID: '<?php echo _a('User ID'); ?>',
            NONE_USER: '<?php echo _a('No user matched your request.'); ?>',
            FROM: '<?php echo _a('From'); ?>',
            TO: '<?php echo _a('To'); ?>',
            FRONT: '<?php echo _a('Front'); ?>',
            ADMIN: '<?php echo _a('Admin'); ?>',
            BATCH_CHECKED: '<?php echo _a('Choose at least one item before submission.'); ?>'
        },
        roles: <?php echo json_encode($roles); ?>
    });
</script>
<script src="<?php echo $this->assetModule('admin/user.js'); ?>"></script>