<?php
    $form->setAttribute('class', 'form-horizontal');
    $this->FormElementErrors()->setMessageOpenFormat('<span class="help-inline">')->setMessageCloseString('</span>');
    $elements = $form->elementList();
    echo $this->form()->openTag($form);
    foreach ($elements['active'] as $element) {
        echo sprintf('<div class="control-group%s"><label class="control-label">%s</label>
            <div class="controls">%s%s</div></div>',
            $element->getMessages() ? ' error' : '',
            $element->getOption('label'),
            $this->formElement($element),
            $this->formElementErrors($element));
    }
    foreach ($elements['hidden'] as $element) {
        echo $this->formElement($element);
    }
    echo sprintf('<div class="controls controls-action">%s%s</div>', 
        $this->formElement($elements['submit']),
        empty($ResetShow) ? '' : '<input type="reset" value="cancel" class="btn btn-link js-cancel">');
    echo $this->form()->closeTag();
?>