<?php
/*
 * Message at form top
 */
if (!empty($formResult)) {
    if (is_string($formResult)) {
        $type = 'error';
        $message = $formResult;
    } else {
        $type = $formResult['status'] ? 'success' : 'error';
        $message = $formResult['message'];
    }
    if ('success' == $type) {
        $class = 'alert-success';
    } else {
        $class = 'alert-danger';
    }
    echo sprintf('<div class="alert %s">%s</div>', $class, $message);
}

$emptyControl = array('checkbox', 'multi_checkbox', 'radio', 'file');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->FormElementErrors()->setMessageOpenFormat('')->setMessageCloseString('');
$elements = $form->elementList();
echo $this->form()->openTag($form);
foreach ($elements['active'] as $element) {
    $type = $element->getAttribute('type') ? : 'text';
    $isEmptyControl = in_array($type, $emptyControl);
    $isCheckbox = $type == 'checkbox';
    $desc = $element->getAttribute('description');
    
    if (!$isEmptyControl && !$element->getAttribute('class')) {
        $element->setAttribute('class', 'form-control');
    }

    $rendered = sprintf(
        '<div class="form-group%s"><label class="col-md-2 control-label">%s</label>',
        $element->getMessages() ? ' has-error' : '',
        $isCheckbox ?  '' : $element->getOption('label')
    );

    $rendered .= sprintf(
        '<div class="col-md-4">%s%s</div><div class="col-md-4 help-block">%s</div></div>',
        $this->formElement($element),
        $desc && !$isCheckbox ? '<div class="text-muted">' . $desc . '</div>' : '',
        $this->formElementErrors($element)
    );
    echo $rendered;
}
foreach ($elements['hidden'] as $element) {
    echo $this->formElement($element);
}
echo sprintf(
    '<div class="form-group"><div class="col-md-offset-2 col-md-10">%s%s</div></div>', 
    $this->formElement($elements['submit']),
    empty($ResetShow) ? '' : '<input type="reset" value="' . __('Cancel') . '" class="btn btn-link js-cancel">'
);
echo $this->form()->closeTag();
?>