<?php
/**
 * Renders a one-column horizontal popup form
 */
$this->jQuery();
$this->bootstrap('js/bootstrap.min.js');

$hiddenMessages = $form->getHiddenMessages();
if ($hiddenMessages) {
    ?>
    <div class="alert alert-danger">
        <?php
        if (!empty($hiddenMessages['security'])) {
            foreach ($hiddenMessages['security'] as $elMessage) {
                echo '<p>' . $elMessage . '</p>';
            }
            unset($hiddenMessages['security']);
        }
        ?>

        <?php foreach ($hiddenMessages as $elName => $elMessages) { ?>
            <h4><?php echo $elName; ?></h4>
            <ol>
                <?php
                foreach ($elMessages as $elMessage) {
                    echo '<li>' . $elMessage;
                }
                ?>
            </ol>
        <?php } ?>
    </div>
<?php
}

$form->prepare();
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'id'    => 'popup-form'
));
echo $this->form()->openTag($form);

$elements = $form->elementList();
$markRequired = '<i class="text-danger" style="margin-right: 5px;">*</i>';
?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><?php echo _escape($title); ?></h4>
        </div>
        <div class="modal-body">

        <?php
        foreach ($elements['active'] as $element) {
        ?>
            <div class="form-group" data-name="<?php echo $element->getName(); ?>">
                <?php
                $labelClass = 'col-md-3';
                if ($element->getAttribute('type') != 'checkbox') {
                    echo sprintf(
                        '<label class="%s control-label">%s%s</label>',
                        $labelClass,
                        $element->getAttribute('required') ? $markRequired : '',
                        $element->getLabel()
                    );

                    $desc = $element->getAttribute('description');
                    if ($desc && $element->getAttribute('type') != 'description') {
                        echo '<i class="icon-question-sign" data-original-title="' . _escape($desc) . '"></i>';
                    }
                } else {
                    echo sprintf(
                        '<label class="%s control-label">%s%s</label>',
                        $labelClass,
                        $element->getAttribute('required') ? $markRequired : '',
                        ''
                    );
                }
                ?>

                <div class="col-sm-8">
                    <?php echo $this->formElement($element); ?>
                    <span class="help-block"></span>
                </div>

            </div>
        <?php }
            foreach ($elements['hidden'] as $element) {
                echo $this->formElement($element);
            }
        ?>
        </div>

            <div class="modal-footer">
            <img src="<?php echo $this->assetTheme('image/wait.gif'); ?>" class="hide">
            <?php
                $elements['submit']->setAttribute('class', 'btn btn-primary');
                echo $this->formElement($elements['submit']);
            ?>
            </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>


<script>
var formModule = (function($) {
    var formModule = {},
        form = $("#popup-form"),
        imgWait = form.find("img.hide");
    var items = form.find(".form-group").removeClass("has-error").find(".help-block").html("").end();
    form.submit(function(e) {
        imgWait.removeClass("hide");
        e.preventDefault();
        $.post(form.attr("action"), form.serialize()).done(function(result) {
            result = $.parseJSON(result);
            if (result.status == 1) {
                formModule.success(result);
            } else {
                var msg = result.message;
                for (var i in msg) {
                    if (msg.hasOwnProperty(i)) {
                        items.filter("[data-name=" + i + "]").addClass("has-error").find(".help-block").html(msg[i][0]);
                    }
                }
                formModule.fail();
            }
            imgWait.addClass("hide");
        });
    });
    /* two port
     * success: This event fires immediately when form submit success
     * fail:  This event fires immediately when form submit has wrong
     */
    formModule.success = function() {};
    formModule.fail = function() {};
    return formModule;
})(jQuery)
</script>