<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <a href="<?php echo $this->url('', array('action' => 'detail', 'id' => $tag_id)); ?>"
               class="list-group-item<?php if(!$cur_module) { echo ' active'; } ?>">
                <?php _e('All'); ?>
            </a>
            <?php
            foreach ($modules as $key => $item) {
                echo sprintf(
                    '<a class="list-group-item%s" href="%s">%s</a>',
                    $key == $cur_module ? ' active' : '',
                    $this->url('', array('action' => 'detail', 'id' => $tag_id, 'm' => $key)),
                    $item
                );
            }
            ?>
        </div>
    </div>
    <div class="col-md-9">
        <h3 style="margin-top: 0;">
            <?php echo sprintf(__('About %s content'), $tag); ?>
            <small>(<?php echo $count; ?>)</small>
        </h3>
        <hr>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><?php _e('Module'); ?>
                    <th><?php _e('Title'); ?>
                    <th><?php _e('Time'); ?>
                        <tbody>
                        <?php foreach ($list as $item) { ?>
                <tr>
                    <td><?php echo _escape($item['module']);  ?>
                    <td>
                        <a href="<?php echo $item['item_link']?>">
                            <?php echo _escape($item['item']); ?>
                        </a>
                    </td>
                    <td><?php echo _escape($item['time']); ?>
                        <?php } ?>
            </table>
        </div>
        <?php
        if (isset($paginator)) {
            echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml');
        }
        ?>
    </div>
</div>