<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <a href="<?php echo $this->url('', array('action' => 'link.list')); ?>"
               class="list-group-item<?php if(!$cur_module) { echo ' active'; } ?>">
                <?php _e('All'); ?>
            </a>
            <?php
            foreach ($modules as $key => $item) {
                echo sprintf(
                    '<a class="list-group-item%s" href="%s">%s</a>',
                    $key == $cur_module ? ' active' : '',
                    $this->url('', array('action' => 'link.list', 'm' => $key)),
                    $item
                );
            }
            ?>
        </div>
    </div>
    <div class="col-md-9">
        <h3 style="margin-top: 0;">
            <?php _e('Link list'); ?>
        </h3>
        <hr>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><?php _e('Tag'); ?></th>
                    <th><?php _e('Item'); ?></th>
                    <th><?php _e('Module'); ?></th>
                    <th><?php _e('Type'); ?></th>
                    <th><?php _e('Time'); ?></th>
                </tr>
               </thead>
               <tbody>
                   <?php foreach ($links as $link) { ?>
                   <tr>
                       <td>
                           <a href="<?php echo $link['tag_link']; ?>">
                               <?php echo _escape($link['tag']); ?>
                           </a>
                       </td>
                       <td>
                           <a href="<?php echo $link['item_link']; ?>">
                               <?php echo _escape($link['item']); ?>
                           </a>
                       </td>
                       <td>
                           <?php echo _escape($link['module']); ?>
                       </td>
                       <td>
                           <?php echo _escape($link['type']); ?>
                       </td>
                       <td>
                           <?php echo _escape($link['time']); ?>
                       </td>
                   </tr>
                   <?php } ?>
               </tbody>
            </table>
        </div>
        <?php
        if (isset($paginator)) {
            echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml');
        }
        ?>
    </div>
</div>