<?php
$this->I18nModule('admin', 'zh-CN');
$this->css(array($this->assetModule('script/tag-admin.css')));
?>
<h2 class="page-header"><?php echo _a('Search'); ?></h2>
<h3><?php echo '"' . $this->escape($tagName) . '" ' . _a('Search result'); ?></h3>
<?php if ($find == 'n') { ?>
<div class="alert">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><?php echo '"' . $this->escape($tagName) . '" ' . _a('is not found Try some other words') . '.'; ?></strong>
</div>
<?php } else {  ?>
<table class="table table-hover table-bordered">
    <tr class="box-bordered-header">
        <th><?php echo _a('Tag Name'); ?></th>
        <th class="span2"><?php echo _a('Count'); ?></th>
        <th class="span1"><?php echo _a('Operator') ?></th>
    </tr>
    <?php
    foreach ($items as $row) { ?>
        <tr>
            <?php
            $url = $this->url('admin', array('controller' => 'index', 'action' => 'detail', 'id' => $row['id']));
            $deleteUrl = $this->url('admin', array('controller' => 'index', 'action' => 'delete', 'id' => $row['id'], 'name' => $tagName, 'search' => 'y'));
            ?>
            <td><a href="<?php echo $url; ?>"><?php echo $this->escape($row['term']); ?></a></td>
            <td><?php echo $row['count'];  ?></td>
            <td><?php echo sprintf('<a href="%s">%s</a>', $deleteUrl, _a('Delete')); ?></td>
        </tr>
        <?php }?>
</table>
<?php } ?>
<?php if ($find != 'n') { ?>
<div class="pagination-right">
    <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
</div>
<?php } ?>