<?php
//$this->I18nModule('admin', 'zh-CN');
?>

<h2 class="page-header"><?php echo _a('Statistics'); ?></h2>
<h3><?php echo _a('Global Top tags'); ?></h3>
<table class="table table-hover table-bordered">
    <tr class="box-bordered-header">
        <th class="span1"><?php echo _a('No'); ?></th>
        <th><?php echo _a('Tag Name'); ?></th>
        <th class="span2"><?php echo _a('Count'); ?></th>
    </tr>
    <?php $i = 0; ?>
    <?php
    foreach ($topTag as $row) { ?>
        <tr>
            <?php
            $url = $this->url('admin', array('controller' => 'index', 'action' => 'detail', 'id' => $row['id']));
            ?>
            <td><?php echo ++$i; ?></td>
            <td><a href="<?php echo $url; ?>"><?php echo $this->escape($row['term']); ?></a></td>
            <td><?php echo $row['count'];  ?></td>
        </tr>
        <?php }?>
</table>

<h3><?php echo _a('Latest tags'); ?></h3>
<table class="table table-hover table-bordered">
    <tr class="box-bordered-header">
        <th class="span1"><?php echo _a('No'); ?></th>
        <th><?php echo _a('Tag Name'); ?></th>
        <th class="span2"><?php echo _a('Link time'); ?></th>
    </tr>
    <?php $i = 0;?>
    <?php foreach ($newestTag as $tag) { ?>
    <tr><?php
        $url = $this->url('admin', array('controller' => 'index', 'action' => 'detail', 'id' => $tag['tagId']));
        ?>
        <td><?php echo ++$i; ?></td>
        <td><a href="<?php echo $url; ?>"><?php echo $this->escape($tag[$tag['tagId']]); ?></a></td>
        <td><?php echo $this->escape($tag['time']); ?></td>
    </tr>
    <?php } ?>
</table>