<?php
/**
 * Pi Engine (http://pialog.org)
 *
 * @link            http://code.pialog.org for the Pi Engine source repository
 * @copyright       Copyright (c) Pi Engine http://pialog.org
 * @license         http://pialog.org/license.txt BSD 3-Clause License
 */

namespace Module\Demo\Block;

class Block
{
    public static function blocka($options, $module = null)
    {
        $block = array(
            'caption'   => _b('Block A'),
            'content'   => sprintf(
                _b('Called by %s through %s'),
                $module,
                __METHOD__
            ),
            'options'   => $options,
        );

        return $block;
    }

    public static function blockb($options, $module = null)
    {
        $block = array(
            'caption'   => _b('Block B'),
            'content'   => sprintf(
                _b('Called by %s through %s'),
                $module,
                __METHOD__
            ),
            'options'   => $options,
        );

        return $block;
    }

    public static function random($options, $module = null)
    {
        $block = sprintf(
            _b('Block generated by %s through %s w/o template'),
            $module,
            __METHOD__
        );

        return $block;
    }
}
