<?php
/*

 Block parameters;
    title   - Block title
    class   - Custom class name for stylesheet, optional
    subline - Subline, HTML, optional
    content - block contents:
            string  - regular content
            array   - compound content:
                []  => Element Title (or tab title)
                       Element content

 Regular block: header + body
 |=============================================================================|
 | Block Title                                                                 |
 |-----------------------------------------------------------------------------|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block w/o title
 |=============================================================================|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block with subline
 |=============================================================================|
 | Block Title                             (Subline: link | link | link | more)|
 |-----------------------------------------------------------------------------|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block with tabs
 |=============================================================================|
 | | tab | tab | tab | tab | tab |
 |------------------------------------------------------------------------------|
 | Block content of first tab ...                                                |
 | Block content of first tab ...                                                |
 | Block content of first tab ...                                                |
 |=============================================================================|

 */
?>
<?php
$isTab = is_array($block['content']);
$class = '';
if ($block['class']) {
    $class .= ' ' . $block['class'];
}
if ($isTab) {
    $class .= ' pi-panel-tab';
}
$isHiddenTitle = $block['title_hidden'] && !$isTab;
//Render heading and body
if ($isTab) {
    $heading = '<ul class="pi-panel-tab-indicators">';
    $body = '<div class="panel-body tab-content">';
    foreach ($block['content'] as $key => $item) {
        $heading .= sprintf(
            '<li class="%s"><a href="%s" data-toggle="tab" data-target="#panel-%s">%s</a>',
            $key == 0 ? 'active' : '',
            $item['link'] ? $item['link'] : '#',
            $block['id'] . $key,
            $item['caption']
        );
        $body .= sprintf(
            '<div class="tab-pane%s" id="panel-%s">%s</div>',
             $key == 0 ? ' active' : '',
             $block['id'] . $key,
             $item['content']
        );
    }
    $heading .= '</ul>';
    $body .= '</div>';
} else {
    if (!empty($block['subline'])) {
        $heading = sprintf(
            '<div class="pi-panel-subline">%s</div>%s',
            $block['subline'],
            $block['title']
        );
    } else {
        $heading = $block['title'];
    }
    if (empty($block['body_fullsize'])) {
        $body = sprintf('<div class="panel-body">%s</div>', $block['content']);
    } else {
        $body = $block['content'];
    }
}
?>
<div class="panel panel-default<?php echo $class; ?>">
<?php
    if (!$isHiddenTitle) {
        echo sprintf('<div class="panel-heading">%s</div>', $heading);
    }
    echo $body;
?>
</div>