<?php
/*

 Block parameters;
    title   - Block title
    class   - Custom class name for stylesheet, optional
    subline - Subline, HTML, optional
    content - block contents:
            string  - regular content
            array   - compound content:
                []  => Element Title (or tab title)
                       Element content

 Regular block: header + body
 |=============================================================================|
 | Block Title                                                                 |
 |-----------------------------------------------------------------------------|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block w/o title
 |=============================================================================|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block with subline
 |=============================================================================|
 | Block Title                             (Subline: link | link | link | more)|
 |-----------------------------------------------------------------------------|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block with tabs
 |=============================================================================|
 | | tab | tab | tab | tab | tab |
 |------------------------------------------------------------------------------|
 | Block content of first tab ...                                                |
 | Block content of first tab ...                                                |
 | Block content of first tab ...                                                |
 |=============================================================================|

 */
?>
<?php
// Render heading and body
if (is_array($block['content'])) {
    // Tab block
    $class   = sprintf('card card-default pi-card-tab %s', $block['class']);
    $heading = '<ul class="pi-panel-tab-indicators">';
    $body    = '<div class="card-body tab-content">';
    foreach ($block['content'] as $key => $item) {
        $heading .= sprintf(
            '<li class="%s"><a href="%s" data-toggle="tab" data-target="#card-%s">%s</a>',
            $key == 0 ? 'active' : '',
            $item['link'] ? $item['link'] : '#',
            $block['id'] . $key,
            $item['caption']
        );
        $body    .= sprintf(
            '<div class="tab-pane%s" id="card-%s">%s</div>',
            $key == 0 ? ' active' : '',
            $block['id'] . $key,
            $item['content']
        );
    }
    $heading .= '</ul>';
    $body    .= '</div>';
    $heading = sprintf('<div class="card-heading">%s</div>', $heading);
} else {
    // Check subline
    if (!empty($block['subline'])) {
        $heading = sprintf(
            '<div class="pi-card-subline">%s</div>%s',
            $block['subline'],
            $block['title']
        );
    } else {
        $heading = $block['title'];
    }
    // Check fullsize
    if ($block['body_fullsize']) {
        $class = sprintf('pi-block %s', $block['class']);
        if (!$block['title_hidden']) {
            $heading = sprintf('<div class="pi-block-title"><h2>%s</h2></div>', $heading);
        }
        $body = sprintf('<div class="pi-block-content">%s</div>', $block['content']);
    } else {
        $class = sprintf('card card-default %s', $block['class']);
        if (!$block['title_hidden']) {
            $heading = sprintf('<div class="card-heading p-3"><h2 class="card-title">%s</h2></div>', $heading);
        }
        $body = sprintf('<div class="card-body">%s</div>', $block['content']);
    }
}
?>
<div class="<?php echo $class; ?> mb-4 shadow-sm">
    <?php
    echo $heading;
    echo $body;
    ?>
</div>