<div class="alert alert-warning">
    <h2 class="page-header"><?php _e('Access denied'); ?></h2>
    <p>
    <?php
    // Display custom message
    if (!empty($message)) {
        echo _escape($message);

    // Prompt to login for guests
    } elseif (401 == (int) $code) {
        $url = Pi::user()->getUrl('login');
        $link = '<a href="' . $url . '" title="' . __('login') . '">' . __('login') . '</a>';
        echo sprintf(__('You are not allowed to access the page, please %s and try again.'), $link);

    // Point to website user guide otherwise
    } else {
        $url = Pi::user()->getUrl('logout');
        $link = '<a href="' . $url . '" title="' . __('logout') . '">' . __('logout') . '</a>';
        echo sprintf(__('You are not allowed to access the page, please %s and try other account.'), $link);
    }
    ?>
    </p>

    <p class="text-right">
        <a href="<?php echo Pi::url('www'); ?>">
            <?php echo _escape(Pi::config('sitename')); ?>
        </a>
    </p>
</div>