<?php $this->i18nTheme('default', 'default'); ?>

<div class="alert alert-danger">
    <h2 class="page-header"><?php _e('Access denied'); ?></h2>
    <p>
    <?php
    // Display custom message
    if (!empty($message)) {
        echo $message;

    // Prompt to login for guests
    } elseif (401 == (int) $code) {
        $url = Pi::service('authentication')->getUrl('login');
        $link = '<a href="' . $url . '" title="' . __('login') . '">' . __('login') . '</a>';
        echo sprintf(__('You are not allowed to access the page. Please %s and try again.'), $link);

    // Point to website user guide otherwise
    } else {
        if ('admin' == Pi::engine()->application()->getSection()) {
            $url = Pi::service('url')->assemble('admin');
        } else {
            $url = Pi::service('url')->assemble('home');
        }
        $linkHome = '<a href="' . $url . '" title="' . __('homepage') . '">' . __('homepage') . '</a>';
        $url = Pi::service('authentication')->getUrl('logout');
        $linkLogout = '<a href="' . $url . '" title="' . __('logout') . '">' . __('logout') . '</a>';
        echo sprintf(
            __('You are not allowed to access the page. Please go to %s or %s and try other account.'),
            $linkHome,
            $linkLogout
        );
    }
    ?>
    </p>

    <div class="text-right">
        <a href="<?php echo Pi::url('www'); ?>">
            <?php echo _escape(Pi::config('sitename')); ?>
        </a>
    </div>
</div>