<?php
$flashMessenger = $this->flashMessenger();
/*
$messages = array();
$typeMap = array(
    'getErrorMessages'      => 'alert alert-error',
    'getMessages'           => 'alert alert-info',
    'getSuccessMessages'    => 'alert alert-success',
);
foreach ($typeMap as $type => $class) {
    $messages = $flashMessenger->{$type}();
    if ($messages) {
        break;
    }
}
*/

$result = $flashMessenger->load();
if (!$result) {
    return;
}
$namespace = $result['namespace'];
$messages = $result['messages'];
switch ($namespace) {
    case 'success':
    case 'error':
        $class = sprintf('alert alert-%s', $namespace);
        break;
    default:
        $class = 'alert alert-info';
        break;
}
$this->bootstrap('js/bootstrap.min.js');
?>

<div class="<?php echo $class; ?>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php foreach ($messages as $msg): ?>
        <div><?php echo $msg ?></div>
    <?php endforeach; ?>
</div>
