<?php
$flashMessenger = $this->flashMessenger();
/*
$messages = array();
$typeMap = array(
    'getErrorMessages'      => 'alert alert-danger',
    'getMessages'           => 'alert alert-info',
    'getSuccessMessages'    => 'alert alert-success',
);
foreach ($typeMap as $type => $class) {
    $messages = $flashMessenger->{$type}();
    if ($messages) {
        break;
    }
}
*/

$result = $flashMessenger->load();
if (!$result) {
    return;
}
$namespace = $result['namespace'];
$messages = $result['messages'];
$pattern = 'alert alert-dismissable alert-%s';
switch ($namespace) {
    case 'success':
        $type = 'success';
        break;
    case 'error':
        $type = 'danger';
        break;
    default:
        $type = 'info';
        break;
}
$class = sprintf($pattern, $type);
$this->bootstrap('js/bootstrap.min.js');
?>

<div class="<?php echo $class; ?>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <?php foreach ($messages as $msg): ?>
        <div><?php echo $msg ?></div>
    <?php endforeach; ?>
</div>
