<?php
$typeMap = array(
    'getMessages'           => 'alert alert-info',
    'getErrorMessages'      => 'alert alert-error',
    'getSuccessMessages'    => 'alert alert-success',
);
$flashMessenger = $this->flashMessenger();
$messages = array();

foreach ($typeMap as $type => $class) {
    $messages = $flashMessenger->{$type}();
    if ($messages) {
        break;
    }
}

if (!$messages) {
    return;
}
$this->bootstrap('js/bootstrap.min.js');
?>

<div class="<?php echo $class; ?>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php foreach ($messages as $msg): ?>
        <?php echo $msg ?>
    <?php endforeach; ?>
</div>
