<?php
// Load translation data
$this->i18nTheme('main');

// Load Bootstrap css by Twitter Team
$this->bootstrap(array(
    'css/font-awesome.min.css'      => array(),
    'css/font-awesome-ie7.min.css'  => array(
        'conditional'   => 'IE 7',
    ),
));
// Load style.css
$this->css(array(
    $this->assetTheme('css/style.css')
));
$this->jQuery();

/**#@+
 * For demonstration
 */
/*
// Load jQuerty
$this->jQuery();
// Load locale css/js, optional
$this->css($this->assetLocale('rtl.css'));
$this->js($this->assetLocale('rtl.js'));
*/
/**#@-*/
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <?php echo $this->assemble('headTitle', 4); ?>
    <?php echo $this->assemble('headMeta', 4); ?>
    <?php echo $this->assemble('headLink', 4); ?>
    <?php echo $this->assemble('headStyle', 4); ?>
    <?php echo $this->assemble('headScript', 4); ?>
</head>
<body id="pi-<?php echo Pi::service('module')->current(); ?>" class="<?php echo $locale; ?>">
    <!-- Header: sitename -->
    <div class="container header">
        <a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>" class="sitename"><?php echo $this->escape($sitename); ?></a>
        <div class="pull-right pi-user-bar">
           <?php echo $this->widget('system-user-bar'); ?>
        </div>
    </div>
    <!-- Navigation  -->
    <div class="container nav-container">
        <?php
            $navigation = $this->nav('front'/*, array('cache_ttl' => null, 'cache_level' => 'role')*/);
            echo $navigation->menu()->setUlClass('unstyled menu');
        ?>
        <!-- Breadcrumbs: check if it exists  -->
        <?php $breadcrumbs = $navigation->breadcrumbs()->setSeparator('<span class="divider">/</span>')->render(); ?>
        <?php if ($breadcrumbs) { ?>
        <div class="breadcrumb">
           <?php echo $breadcrumbs; ?>
        </div>
        <?php } ?>
    </div>
    <!-- Page main content: blocks and module content -->
    <?php
        $blocks = $this->blocks();
        $blockTemplate = $this->template('block');
        $gutter1 = 'style="padding-right: 10px; width: 50%;"';
        $gutter2 = 'style="padding-left: 10px;"';
        $colspan = 'colspan="2"';
    ?>
    <!-- Top head zone -->
    <?php if (isset($blocks['0'])) { ?>
    <div class="container pi-zone-0">
        <?php foreach ($blocks['0'] as $block) {
            include $blockTemplate;
        } ?>
    </div>
    <?php } ?>
    <!-- Main zones -->
    <table class="container main">
        <tr>
            <?php if (isset($blocks['1'])) { ?>
            <td class="pi-zone-1">
                <?php foreach ($blocks['1'] as $block) {
                    include $blockTemplate;

                } ?>
            <?php } ?>
            <td>
                <table>
                    <?php if (isset($blocks['2'])) { ?>
                    <tr>
                        <td class="pi-zone-2" colspan="2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                    <?php } ?>
                    <tr>
                        <?php if (isset($blocks['3'])) { ?>
                        <td class="pi-zone-3" <?php if (isset($blocks['4'])) { echo $gutter1; } else { echo $colspan; } ?>>
                            <?php foreach ($blocks['3'] as $block) {
                                    include $blockTemplate;
                            } ?>
                        <?php } ?>
                        <?php if (isset($blocks['4'])) { ?>
                        <td class="pi-zone-4" <?php if (isset($blocks['3'])) { echo $gutter2; } else { echo $colspan; } ?>>
                            <?php foreach ($blocks['4'] as $block) {
                                    include $blockTemplate;
                            } ?>
                        <?php } ?>
                    <?php if ($content) { echo '<tr><td class="row-fluid pi-module-content">' . $content . '</td></tr>'; } ?>
                    <?php if (isset($blocks['5'])) { ?>
                    <tr>
                        <td class="pi-zone-5" colspan="2">
                            <?php foreach ($blocks['5'] as $block) {
                                include $blockTemplate;
                            } ?>
                    <?php } ?>
                    <tr>
                        <?php if (isset($blocks['6'])) { ?>
                        <td class="pi-zone-6" <?php if (isset($blocks['7'])) { echo $gutter1; } else { echo $colspan; } ?>>
                            <?php foreach ($blocks['6'] as $block) {
                                    include $blockTemplate;
                            } ?>
                        <?php } ?>
                        <?php if (isset($blocks['7'])) { ?>
                        <td class="pi-zone-7" <?php if (isset($blocks['6'])) { echo $gutter2; } else { echo $colspan; } ?>>
                            <?php foreach ($blocks['7'] as $block) {
                                    include $blockTemplate;
                            } ?>
                        <?php } ?>
                </table>
            <?php if (isset($blocks['8'])) { ?>
            <td class="pi-zone-8">
                <?php foreach ($blocks['8'] as $block) {
                    include $blockTemplate;
                } ?>
            <?php } ?>
    </table>
    <!-- Foot zone -->
    <?php if (isset($blocks['99'])) { ?>
    <div class="container pi-zone-99">
        <?php foreach ($blocks['99'] as $block) {
            include $blockTemplate;
        } ?>
    </div>
    <?php } ?>
    <!-- Footer: sitelink -->
    <div class="footer">
        <div class="container">
            <div class="footer-line"></div>
            <a href="<?php echo Pi::url('page/terms'); ?>" title="<?php _e('Terms of use'); ?>"><?php _e('Terms of use'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/privacy'); ?>" title="<?php _e('Privacy guidelines'); ?>"><?php _e('Privacy guidelines'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/license'); ?>" title="<?php _e('License'); ?>"><?php _e('License'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/about'); ?>" title="<?php _e('About us'); ?>"><?php _e('About us'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/contact'); ?>" title="<?php _e('Contact us'); ?>"><?php _e('Contact us'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/join'); ?>" title="<?php _e('Join us'); ?>"><?php _e('Join us'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/help'); ?>" title="<?php _e('Help'); ?>"><?php _e('Help'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/sitemap'); ?>" title="<?php _e('Sitemap'); ?>"><?php _e('Sitemap'); ?></a> <br/>
            <a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>">&copy;<?php echo $this->escape($sitename); ?></a><span class="divider">|</span>
            <a href="http://www.pialog.org" title="Pi Engine" target="_blank">Powered by Pi Engine</a><span class="divider">|</span>
            <a href="http://www.pialog.org" title="Pi Engine" target="_blank">Design of Pi Engine</a>
        </div>
        <!-- Show execution time -->
        <?php $time = microtime(true) - Pi::startTime(); ?>
        <span style="font-size: 80%;" title="<?php _e('Execution time'); ?>"><?php echo $time; ?></span>
    </div>
    <?php echo $this->assemble('footScript', 4); ?>
</body>
</html>
