<?php
// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'href'  => $this->favicon(),
));

// Load google analytics code
$this->ga();

$module = Pi::service('module')->current();
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
    <!-- Header: brand, slogan, user bar -->
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <h1 class="hide">
                <?php echo _escape($sitename . ' - ' . $slogan); ?>
            </h1>
            <a class="navbar-brand" href="<?php echo $this->url('home'); ?>"
               title="<?php echo _escape($slogan); ?>">
               <?php echo _escape($sitename); ?>
            </a>
            <?php
            echo $this->widget('system-user-bar', array('type' => 'js'));
            ?>
        </div>
    </div>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <?php
                $navigation = $this->nav('front');
                echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav');
                ?>
                <div class="navbar-form navbar-left">
                    <?php echo $this->widget('search-search'); ?>
                </div>
            </div>
        </div>
    </div>
    <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
    <?php
        $blocks         = $this->blocks();
        $blockTemplate  = $this->template('block');
    ?>
    <div class="container pi-main-container">
        <?php
        $breadcrumbs = $this->breadcrumb(array('prefix' => array(array('label' => __('Home')))));
        if ($breadcrumbs) {
            echo $breadcrumbs;
        }
        ?>
        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>
        <!-- Top head zone -->
        <?php if (!empty($blocks['0'])) { ?>
        <div class="pi-zone-0">
            <?php foreach ($blocks['0'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
        <?php } ?>
        <div class="row">
            <!-- Left zone -->
            <?php if (!empty($blocks['1'])) { ?>
            <div class="pi-zone-1 col-md-4">
                <?php foreach ($blocks['1'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-md-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-md-8';
                } else {
                    echo 'col-md-12';
                }
                ?>">
                <!-- Center top zone -->
                <?php if (isset($blocks['2'])) { ?>
                <div class="pi-zone-2">
                    <?php foreach ($blocks['2'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
                <?php } ?>
                <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                <div class="row">
                    <div class="col-md-6 pi-zone-3">
                        <?php
                        if (isset($blocks['3'])) { 
                            foreach ($blocks['3'] as $block) {
                                include $blockTemplate;
                            }
                        } 
                        ?>
                    </div>
                    <div class="col-md-6 pi-zone-4">
                        <?php
                        if (isset($blocks['4'])) { 
                            foreach ($blocks['4'] as $block) {
                                include $blockTemplate;
                            }
                        } 
                        ?>
                    </div>
                </div>
                <?php } ?>

                <!-- Module content starts -->
                <?php if (!empty($content)) { ?>
                <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                    <?php echo $content; ?>
                </div>
                <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                <?php } ?>
                <!-- Module content ends -->

                <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                <div class="row">
                    <div class="col-md-6 pi-zone-5">
                        <?php
                        if (isset($blocks['5'])) { 
                            foreach ($blocks['5'] as $block) {
                                include $blockTemplate;
                            }
                        } 
                        ?>
                    </div>
                    <div class="col-md-6 pi-zone-6">
                        <?php
                        if (isset($blocks['6'])) { 
                            foreach ($blocks['6'] as $block) {
                                include $blockTemplate;
                            }
                        } 
                        ?>
                    </div>
                </div>
                <?php } ?>
                <!-- Center bottom zone -->
                <?php if (isset($blocks['7'])) { ?>
                <div class="pi-zone-7">
                    <?php foreach ($blocks['7'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
                <?php } ?>
            </div>

            <!-- Right zone -->
            <?php if (isset($blocks['8'])) { ?>
            <div class="col-md-4 pi-zone-8">
                <?php foreach ($blocks['8'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
        </div>
        <!-- Bottom foot zone -->
        <?php if (isset($blocks['99'])) { ?>
        <div class="pi-zone-99">
            <?php foreach ($blocks['99'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
        <?php } ?>
    </div>

    <!-- Footer: sitelink -->
    <div class="pi-footer text-center">
        <div class="container">
            <?php
            $footer = Pi::config('footer');
            if ($footer) {
                echo $footer;
            } else {
            ?>

            <ul class="pi-footer-links muted">
                <li>
                    <a href="<?php echo Pi::url('www'); ?>" title="<?php echo _escape($sitename); ?>">
                        &copy; <?php echo date('Y') . ' ' . _escape($sitename); ?>
                    </a>
                </li>
                <li>·</li>
                <li>
                    <a href="http://www.pialog.org" title="Pi Engine" target="_blank">
                        Powered by Pi Engine
                    </a>
                </li>
                <li>·</li>
                <li>
                    <a rel="license" href="http://www.pialog.org" title="Pi Engine" target="_blank">
                        Design of Pi Engine
                    </a>
                </li>
                <li>·</li>
                <li><a title="<?php echo sprintf(__('Execution time: %.4f s'), microtime(true) - Pi::startTime()); ?>"><i class="fa fa-spinner fa-spin"></i></a></li>      
            </ul>
            <?php } ?>
        </div>    
    </div>
    <?php $this->footScript()->appendFile($this->assetTheme('js/front.js')); ?>
</body>
</html>
