<?php
// Load translation data
$this->i18nTheme('default', 'default');

$this->bootstrap(array(
    'js/bootstrap.js',
    'font-awesome/css/font-awesome.css'
));
$this->css($this->assetTheme('css/admin.css'));
// Explicitly load favicon
// @see http://en.wikipedia.org/wiki/Favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'href'  => Pi::url('www/favicon.ico')
));
$module = Pi::service('module')->current();
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="<?php echo $locale; ?>">
    <!-- header: brand, navbar-nav, user link -->
    <header class="navbar navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">
                <i class="fa fa-leaf"></i>
                <strong>Pi</strong>
            </a>
        </div>
        <nav class="navbar-collapse collapse">
            <?php echo $this->adminNav()->modes('nav navbar-nav'); ?>
            <ul class="nav navbar-nav navbar-right">
                <?php echo $this->widget('system-user-bar', array('params' => array('route' => 'sysuser'), 'type' => 'flat')); ?>
                <li>
                    <a href="<?php echo Pi::url('www'); ?>" title="<?php echo _escape($sitename); ?>" target="_blank">
                        <i class="fa fa-external-link"></i>
                        <?php _e('Front'); ?>
                    </a>
            </ul>
        </nav>
    </header>
    <aside class="pi-sidebar">
        <div id="js-modules-nav">
            <?php echo $this->adminNav()->main('nav pi-modules-nav'); ?>
            &nbsp;
        </div>
        <div class="pi-sidebar-bg"></div>
    </aside>
    <section class="pi-content">

        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>

        <?php echo $this->adminNav()->top('nav nav-tabs'); ?>
        <article class="pi-module-content">
            <?php echo $content; ?>
        </article>
        <footer class="pi-footer">
            <a href="<?php echo Pi::url('www'); ?>" title="<?php echo _escape($sitename); ?>">
                &copy; <?php echo _escape($sitename); ?>
            </a>
             <a href="http://www.pialog.org" title="Pi Engine" target="_blank">
                Powered by Pi Engine
            </a>
            <a href="http://www.pialog.org" title="Pi Engine" target="_blank">
                Design of Pi Engine
            </a>
            <div style="font-size: 80%; padding-right: 10px;" class="pull-right" title="<?php _e('Execution time'); ?>">
                <?php printf('%.4fs', microtime(true) - Pi::startTime()); ?>
            </div>
        </footer>
    </section>
    <script>
        $('#js-modules-nav').data('config', {
            emptyNav: '<?php _e('Empty nav'); ?>'
        });
    </script>
    <script src="<?php echo $this->assetTheme('js/admin.js'); ?>"></script>
</body>
</html>