<?php
// Load translation data
$this->i18nTheme('default');

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'href'  => $this->favicon(),
));

// Load google analytics code
$this->ga();

$module = Pi::service('module')->current();
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
   <!-- Header: brand, slogan, user bar -->
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <h1 class="hide">
                <?php echo _escape($sitename . ' - ' . $slogan); ?>
            </h1>
            <a class="navbar-brand" href="<?php echo $this->url('home'); ?>"
               title="<?php echo _escape($slogan); ?>">
               <?php echo _escape($sitename); ?>
            </a>
            <?php
            echo $this->widget('system-user-bar');
            ?>
        </div>
    </div>

    <div class="container pi-main-container">

        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>

        <!-- Module content starts -->
        <?php if (!empty($content)) { ?>
            <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                <?php echo $content; ?>
            </div>
        <?php } ?>
        <!-- Module content ends -->

    </div>

    <!-- Footer: sitelink -->
   <!-- Footer: sitelink -->
   <div class="pi-footer text-center">
       <div class="container">
           <ul class="pi-footer-links muted">
               <li>
                   <a href="<?php echo Pi::url('www'); ?>" title="<?php echo _escape($sitename); ?>">
                       &copy; <?php echo date('Y') . ' ' . _escape($sitename); ?>
                   </a>
               </li>
               <li>·</li>
               <li>
                   <a href="http://www.pialog.org" title="Pi Engine" target="_blank">
                       Powered by Pi Engine
                   </a>
               </li>
               <li>·</li>
               <li>
                   <a rel="license" href="http://www.pialog.org" title="Pi Engine" target="_blank">
                       Design of Pi Engine
                   </a>
               </li>
               <li>·</li>


               <i class="fa fa-spinner fa-spin" title="<?php echo sprintf(__('Execution time: %.4f s'), microtime(true) - Pi::startTime()); ?>"></i>
           </ul>
       </div>
   </div>
</body>
</html>