<?php
$this->i18nTheme();
$this->bootstrap();
$this->css($this->assetTheme('css/style.css'));

// Explicitly load favicon
// @see http://en.wikipedia.org/wiki/Favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'href'  => $this->favicon()
));
// Load google analytics code
$this->ga();

$module = Pi::service('module')->current();
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">

    <div class="container pi-main-container">

        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>

        <?php if (!empty($content)) { ?>
            <div class="<?php echo $module; ?>">
                <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                    <?php echo $content; ?>
                </div>
            </div>
        <?php } ?>
    </div>

</body>
</html>