<table>
    <tr>
        <td>{1}</td>
        <td>
        <table>
            <tr>
                <td colspan="2">{2}</td>
            </tr>
            <tr>
                <td>{3}</td>
                <td>{4}</td>
            </tr>
            <tr>
                <td colspan="2">{content}</td>
            </tr>
            <tr>
                <td>{5}</td>
                <td>{6}</td>
            </tr>
        </table></td>
        <td>{7}</td>
    </tr>
    <tr>
        <td colspan="3">{8}</td>
    </tr>
</table>

