<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
?>

<div class="pi-minheight">
    <div class="page-header">
        <h3><?php _e('Change email'); ?></h3>
    </div>

    <div class="text-center text-large" style="padding-top: 40px;">
        <?php if ($result['status']) { ?>
            <p><?php _e('Congratulations!'); ?></p>
            <p><?php _e('Your email has been changed.'); ?></p>
        <?php } else { ?>
            <p><?php _e('Sorry, the link has expired, or maybe your email has been changed.'); ?></p>
        <?php } ?>
    </div>
</div>
