<?php
    // Load activity.css
    $this->css(array(
        Pi::url('static/custom/user/activity.css'),
        $this->assetModule('front/front.css', 'user')
    ));
    $this->bootstrap('js/bootstrap.min.js');
    $tabItemView = '
        <tr>
            <td>
                <div style="width: 360px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
            <td class="muted">%s
            <td>
                <div style="width: 180px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
    ';
    $tabItemMoreView = '
        <tr>
            <td>
                <div style="width: 260px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
            <td class="muted">%s
            <td class="muted">%s
            <td>
                <div style="width: 180px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
    ';
    $tabEmpty = '
        <tr>
            <td colspan="%s">
                <span class="muted">%s</span>
    ';
?>
<div class="span9">
    <ul class="activity-tab">
        <li class="active">
            <a href="#js-topic" data-toggle="tab">
                <?php _e('Topic'); ?>
            </a>
        <li>
            <a href="#js-reply" data-toggle="tab">
                <?php _e('Reply'); ?>
            </a>
        <li>
            <a href="#js-question" data-toggle="tab">
                <?php _e('Question'); ?>
            </a>
        <li>
            <a href="#js-answer" data-toggle="tab">
                <?php _e('Answer'); ?>
            </a>
       <li>
            <a href="#js-project" data-toggle="tab">
                <?php _e('Project'); ?>
            </a> 
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="js-topic">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($bbs['data']) {
                        foreach($bbs['data'] as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['communityUrl'],
                                 $item['community']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-reply">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($reply['data']) {
                        foreach($reply['data'] as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['communityUrl'],
                                 $item['community']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-question">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($question['data']) {
                        foreach($question['data'] as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['communityUrl'],
                                 $item['community']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-answer">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($answer['data']) {
                        foreach($answer['data'] as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['communityUrl'],
                                 $item['community']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-project">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Create time'); ?>
                        <td>
                            <?php _e('Update time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($project['data']) {
                        foreach($project['data'] as $item) {
                            echo sprintf($tabItemMoreView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['createTime'],
                                 $item['updateTime'],
                                 $item['communityUrl'],
                                 $item['community']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 4, __('No content'));
                    }
                    ?>
            </table>
        </div>
    </div>
</div>
<div class="span3">
    <div class="activity-panel">
        <div class="activity-panel-header">
            <?php if ($is_owner) { ?>
            <a class="pull-right" href="<?php echo $panel_bbs[0]['url']; ?>" target="_blank">
                <?php _e('Manage'); ?>
            </a>
            <?php } ?>
            <span class="activity-icon activity-icon-cndzzbbs"><?php _e('Topic'); ?></span>
        </div>
        <ul class="activity-panel-body">
            <?php foreach ($panel_bbs as $item) { ?>
            <li>
                <?php if ($is_owner) { ?>
                <a href="<?php echo $item['url']; ?>" target="_blank">
                    <?php echo $item['count']; ?>
                    <br>
                    <?php echo $item['action']; ?>
                </a>
                <?php } else { 
                    echo $item['count'] . '<br>' . $item['action'];
                }
                ?>
            <?php } ?>
        </ul>
    </div>
    <div class="activity-panel">
        <div class="activity-panel-header">
            <?php if ($is_owner) { ?>
            <a class="pull-right" href="<?php echo $panel_rela[0]['url']; ?>" target="_blank">
                <?php _e('Manage'); ?>
            </a>
            <?php } ?>
            <span class="activity-icon activity-icon-rel"><?php _e('Relationship'); ?></span>
        </div>
        <ul class="activity-panel-body">
            <?php foreach ($panel_rela as $item) { ?>
            <li>
                <?php if ($is_owner) { ?>
                <a href="<?php echo $item['url']; ?>" target="_blank">
                    <?php echo $item['count']; ?>
                    <br>
                    <?php echo $item['action']; ?>
                </a>
                <?php } else { 
                    echo $item['count'] . '<br>' . $item['action'];
                }
                ?>
            <?php } ?>
        </ul>
    </div>
</div>
