<?php
    // Load activity.css
    $this->css(array(
        Pi::url('static/custom/user/activity.css'),
        $this->assetModule('front/front.css', 'user')
    ));
    $this->bootstrap('js/bootstrap.min.js');
    $tabItemView = '
        <tr>
            <td>
                <div style="width: 360px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
            <td class="muted">%s
            <td>
                <div style="width: 180px;" class="ellipsis">
                    <a href="%s" target="_blank">%s</a>
                </div>
    ';
    $tabEmpty = '
        <tr>
            <td colspan="%s">
                <span class="muted">%s</span>
    ';
?>
<div class="span9">
  <ul class="activity-tab">
        <li class="active">
            <a href="#js-topic" data-toggle="tab">
                <?php _e('Topic'); ?>
            </a>
        <li>
            <a href="#js-reply" data-toggle="tab">
                <?php _e('Reply'); ?>
            </a>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="js-topic">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($myTopic['dataList']) {
                        foreach($myTopic['dataList'] as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['community'],
                                 $item['communityUrl']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
        <div class="tab-pane" id="js-reply">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <?php _e('Title'); ?>
                        <td>
                            <?php _e('Publish time'); ?>
                        <td>
                            <?php _e('Belong to community'); ?>
                </thead>
                <tbody>
                    <?php
                    if ($myReply['dataList']) {
                        foreach($myReply['dataList'] as $item) {
                            echo sprintf($tabItemView, 
                                 $item['url'],
                                 $item['title'],
                                 $item['time'],
                                 $item['community'],
                                 $item['communityUrl']
                                 );
                        }
                    } else {
                        echo sprintf($tabEmpty, 3, __('No content'));
                    }
                    ?>
            </table>
        </div>
    </div>
</div>
<div class="span3">
  <div class="activity-panel">
        <div class="activity-panel-header">
            <?php if ($is_owner) { ?>
            <a class="pull-right" href="<?php echo $blog[0]['url']; ?>" target="_blank">
                <?php _e('Manage'); ?>
            </a>
            <?php } ?>
            <span class="activity-icon activity-icon-cndzzbbs"><?php _e('Topic'); ?></span>
        </div>
        <ul class="activity-panel-body">
            <?php foreach ($bbs as $item) { ?>
            <li>
                <a href="<?php echo $item['url']; ?>" target="_blank">
                    <?php echo $item['count']; ?>
                    <br>
                    <?php echo $item['action']; ?>
                </a>
            <?php } ?>
        </ul>
    </div>
    <div class="activity-panel">
        <div class="activity-panel-header">
            <?php if ($is_owner) { ?>
            <a class="pull-right" href="<?php echo $rel[0]['url']; ?>" target="_blank">
                <?php _e('Manage'); ?>
            </a>
            <?php } ?>
            <span class="activity-icon activity-icon-circuit"><?php _e('Circuit diagram'); ?></span>
        </div>
        <ul class="activity-panel-body">
            <?php foreach ($circuit as $item) { ?>
            <li>
                <a href="<?php echo $item['url']; ?>" target="_blank">
                    <?php echo $item['count']; ?>
                    <br>
                    <?php echo $item['action']; ?>
                </a>
            <?php } ?>
        </ul>
    </div>
</div>
