<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
Pi::service('i18n')->load('custom/user:default');
?>

<!-- Subheader -->
<div class="pi-subheader">
    <a href="<?php echo Pi::service('authentication')->getUrl('login'); ?>" title="EEFOCUS 与非网 通行证">
        <img src="<?php echo Pi::url('static/custom/user/logo-eefocus-permit.png'); ?>" alt="EEFOCUS 与非网 通行证">
    </a>
</div>

<div class="row-fluid pi-minheight">
    <div class="page-header">
        <h3>
            <?php _e('set password'); ?>
        </h3>
    </div>
    
    <div>
        <?php if (!(isset($result) && $result['status'])) {
            if (!(isset($result) && $result['message'])) {
                include $this->templateComponent('form-horizontal');
            } else { ?>
                <p class="text-error text-center text-large">
                    <?php _e('Password Recovery fails'); ?>
                    <a href="<?php echo $this->url('', array('controller' => 'password', 'action' => 'find')); ?>">
                        <?php _e('Retrieve password'); ?>
                    </a>
                </p>
        <?php }
        } else { ?>
            <p class="text-center text-large">
                <img style="margin-right: 10px; vertical-align: middle;" src="<?php echo Pi::url('static/custom/user/icon-success-large.png'); ?>">
                <?php _e('Password Recovery is successful'); ?>
                <a href="<?php echo Pi::service('authentication')->getUrl('login'); ?>"><?php _e('log in'); ?></a>
            </p>
        <?php } ?>
    </div>
</div>
