<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
?>
<div class="pi-minheight">
    <div class="page-header">
        <h3><?php _e('Find password'); ?></h3>
    </div>

    <div>
    <?php if (!(isset($result) && $result['status'])) {
        if (isset($result)) {
            $this->bootstrap('js/bootstrap.min.js');
            echo sprintf(
                '<div class="alert %s"><a href="#" data-dismiss="alert" class="close">&times;</a>%s</div>',
                'alert-error',
                $result['message']);
        }
        include $this->templateComponent('form-horizontal');
    } else { ?>
        <p class="text-center text-large">
            <?php _e('An reset password link has been sent to your email'); ?>
        </p>
    <?php } ?>
    </div>
</div>
