<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
?>
<div class="row-fluid pi-minheight">
    <div class="page-header">
        <h3><?php _e('User activates'); ?></h3>
    </div>
    <div class="text-center text-large">
        <?php if (isset($result) && $result['status']) { ?>
            <img style="margin-right: 10px; vertical-align: middle;" src="<?php echo Pi::url('static/custom/user/icon-success-large.png'); ?>">
            <?php _e('Activation was successful'); ?>
            <a href="<?php echo Pi::service('authentication')->getUrl('login'); ?>"><?php _e('log in'); ?></a>
        <?php } else { ?>
            <p>
                <?php _e('Sorry, this link has expired. Maybe you have to complete the activation, or exceed the effective activation time.'); ?>
            </p>
            <p>
                <a href="<?php echo $this->url('', array('controller' => 'register', 'action' => 'resend.active.mail')); ?>"><?php _e('Resend activation email');?></a>
            </p>
        <?php } ?>
    </div>
</div>
