<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
?>

<div class="page-header">
    <h3><?php _e('Complete profile'); ?></h3>
</div>
<p class="register-desc">
  <?php _e('请完善您的资料，以便100多万个与非用户认识您！'); ?>
</p>
<?php include $this->templateComponent('form-horizontal'); ?>

<script>
    jQuery(function($) {
        $('#profileComplete input, #profileComplete select').focus(function(){
            var $controlGroupParent = $(this).closest('.control-group');
            $controlGroupParent.removeClass('error').find('.help-inline').html('');
        });
    });
</script>
