<?php
// Load register.css
$this->css(array(
    Pi::url('static/custom/user/register.css'),
));
?>

<?php if (!(isset($result) && $result['status'])) { ?>
    <!-- Step -->
    <div class="pi-step-reg pi-step-reg<?php echo empty($complete) ? '1' : '2'; ?>"></div>

    <div class="row-fluid">
        <div class="span9">
            <?php include $this->templateComponent('form-horizontal'); ?>

            <?php if (empty($complete)) { ?>
            <div style="margin: 50px 0 50px 180px;">
                <?php _e('already registered,havent activited'); ?>
                <a href="<?php echo $this->url('', array('controller' => 'register', 'action' => 'resend.active.mail')); ?>"><?php _e('resend activited email');?></a>
            </div>
            <?php } ?>
        </div>

        <div class="span3 muted">
        <?php if (empty($complete)) { ?>
            <h4>
                <?php _e('shenglingyufeitongxingzheng'); ?><br>
                <?php _e('qinsongshixianrengwoxing'); ?>
            </h4>
            <ul class="unstyled">
                <li><?php _e('queefocus'); ?></li>
                <li><?php _e('qucndzz'); ?></li>
                <li><?php _e('qud5'); ?></li>
                <li><?php _e('queeboard'); ?></li>
            </ul>

            <script src="<?php echo Pi::url('static/custom/user/register-index.js'); ?>"></script>
            <script src="<?php echo Pi::url('static/custom/user/temp-email.js'); ?>"></script>
            <script>
                jQuery(function($) {
                    $('[name="captcha\\[input\\]"]').closest('.control-group').css('margin-bottom', '-4px');
					$('[name="terms_of_service"]').filter('[type=checkbox]').after('<?php _e('I have read and agree to'); ?><a target="_blank" href="http://www.eefocus.com/passport/Tpl/index/xieyi.html"><?php _e('Terms of Service'); ?></a>');

                    <?php $configs = Pi::service('module')->config('', 'user'); ?>
                    userRegisterIndex.init({
                        checkExistUrl: "<?php echo $this->url('api', array('module' => 'user', 'controller' => 'user', 'action' => 'check.exist')); ?>",
                        NAME_MIN: '<?php echo $configs['name_min']; ?>',
                        NAME_MAX: '<?php echo $configs['name_max']; ?>'
                    });
                });
            </script>
        <?php } else { ?>
            <h4>
                <?php _e('tell eefocus what you like'); ?><br>
                <?php _e('eefocus offer what you want'); ?>
            </h4>
            <ul class="unstyled">
                <li><?php _e('we will provide service according to your interest'); ?></li>
                <li><?php _e('send gift'); ?></li>
                <li><?php _e('We will cherish your trust'); ?></li>
                <li class="pi-dashed"></li>
                <li><?php _e('eefocus solemnly promise:'); ?></li>
                <li><?php _e('We will protect the security of your information'); ?></li>
            </ul>

            <script>
                jQuery(function($) {
                    $('#register_complete input, #register_complete select').focus(function(){
                        var $controlGroupParent = $(this).closest('.control-group');
                        $controlGroupParent.removeClass('error').find('.help-inline').html('');
                    });
                });
            </script>
        <?php } ?>
        </div>
    </div>
<?php } else { ?>
    <!-- Step -->
    <div class="pi-step-reg pi-step-reg3"></div>

    <div class="row-fluid pi-minheight">
        <div class="span8 text-large" style="padding-top: 10px;">
            <p>
                <?php _e('System has been to you mailbox'); ?>
                <span class="text-error"><?php echo $result['email']; ?></span>
                <?php _e('Send an email'); ?>。
            </p>
            <p><?php _e('Please click on the link in the email to complete your registration'); ?>。</p>
        </div>

        <div class="span4">
            <h4>
                <?php _e('What to do when you did not receive the activation email?'); ?>
            </h4>
            <ol>
                <li>
                    <?php _e('Email addresses are wrong?');?>
                    <a href="<?php echo $this->url('', array('controller' => 'register', 'action' => 'index')); ?>" 
                       title="<?php _e('Reregister') ?>">
                        <?php _e('Reregister') ?>
                    </a>
                </li>
                <li><?php _e('To see is it in the trash'); ?></li>
                <li><?php _e('Wait a few minutes to check');?></li>
                <li>
                    <?php _e('or');?>
                    <span class="user-js-reactivate">
                        <a class="user-js-reactivate-link" href="javascript:;" title="<?php _e('Resend activation email');?>">
                            <?php _e('Resend activation email');?>
                        </a>
                        <span class="hide user-js-reactivate-tip">
                            (<span class="user-js-reactivate-message"></span><span class="user-js-reactivate-countdown"></span>)
                        </span>
                    </span>
                </li>
            </ol>
        </div>
    </div>


    <style>
        a.disabled {
            opacity: 0.65;
            filter: alpha(opacity=65);
            cursor: not-allowed;
        }

        a.disabled:hover {
            text-decoration: none;
        }
    </style>
    <script src="<?php echo Pi::url('static/custom/user/register-reactivate.js'); ?>"></script>
    <script>
        jQuery(function() {
            userRegisterReactivate.init({
                reactivateUrl: '<?php echo $this->url('', array('controller' => 'register', 'action' => 'reactivate', 'uid' => $result['uid']));?>',
                AlREADY_SENT: '<?php _e('Message has been sent'); ?>'
            });
        });
    </script>
<?php } ?>
