<?php
    $form->setAttribute('class', 'form-horizontal');
    $elements = $form->elementList();
    echo $this->form()->openTag($form);
    foreach ($elements['active'] as $element) {
        echo sprintf('<div class="control-group"><label class="control-label">%s</label>
            <div class="controls">%s<span class="help-inline"></span></div></div>',
            $element->getOption('label'),
            $this->formElement($element));
    }
    foreach ($elements['hidden'] as $element) {
        echo $this->formElement($element);
    }
    echo sprintf('<div class="controls controls-action">%s
        <input type="button" value="cancel" class="btn btn-link js-reset"></div>', 
        $this->formElement($elements['submit']));
    echo $this->form()->closeTag();
?>