<div class="media user-avatar-media">
    <a class="pull-left">
        <img  class="media-object" src="<?php echo Pi::user()->avatar()->get($uid, 'large', false); ?>">
    </a>
    <?php if ($is_owner) {?>
    <a href="<?php echo $this->url('', array('controller' => 'avatar', 'action' => 'index')); ?>"><?php _e('Setting'); ?></a>
    <?php } ?>
    <div class="pull-right">
        <?php if ($is_owner) { ?>
        <a href="<?php echo $this->url('', array('controller' => 'account', 'action' => 'index')); ?>">
            <?php _e('Account settings'); ?>
        </a>
        <?php } else { ?>
        <a href=""><?php _e('Send message'); ?></a>
        <?php }?>
    </div>
    <div class="media-body">
        <h2 class="media-heading user-name"><?php echo _escape($user['name']); ?></h2>
        <p>
            <?php echo _escape($user['gender']);?>
        <p>
            <?php _e('Born at'); ?> <?php echo _escape($user['birthdate']); ?>
    </div>
</div>

<ul class="nav nav-tabs">
    <?php foreach ($nav['items']  as $item) { ?>
    <li class="<?php echo $item['name'] == $nav['cur'] ? 'active' : ''; ?>">
        <a href="<?php echo $item['url']?>"><?php echo $item['title'];?></a>
    </li>
    <?php } ?>
</ul>