<div class="user-avatar-header">
    <div class="inline user-avatar-header-col user-avatar-header-left" style="width: 120px; height: 120px;">
        <img class="media-object" src="<?php echo Pi::user()->avatar()->get($uid, 'large', false); ?>">
        <?php if ($is_owner) {?>
        <a class="user-avatar-upload" href="<?php echo $this->url('', array('controller' => 'avatar', 'action' => 'index')); ?>">
            <?php _e('Change avatar'); ?>
        </a>
        <?php } ?>
    </div>
    <div class="inline user-avatar-header-col user-avatar-header-center">
        <h2 class="user-name"><?php echo _escape($user['name']); ?></h2>
        <p class="p-small">
            <?php echo _escape($user['gender']);?>
        <div>
            <?php _e('Born at'); ?> <?php echo _escape($user['birthdate']); ?>
        </div>
    </div>
    <div class="inline user-avatar-header-col" style="float: right;">
        <?php if ($is_owner) { ?>
        <a class="btn" href="<?php echo $this->url('', array('controller' => 'account', 'action' => 'index')); ?>">
            <i class="icon-cog"></i>
            <?php _e('Setting'); ?>
        </a>
        <?php } else { ?>
        <a class="btn" href="">
            <i class="icon-envelope"></i>
            <?php _e('Send message'); ?>
        </a>
        <?php } ?>
    </div>
</div>
<ul class="nav nav-tabs">
    <?php foreach ($nav['items']  as $item) { ?>
    <li class="<?php echo $item['name'] == $nav['cur'] ? 'active' : ''; ?>">
        <a href="<?php echo $item['url']?>"><?php echo $item['title'];?></a>
    </li>
    <?php } ?>
</ul>