<div class="span3">
    <a class="media user-profile-back" href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'home')); ?>">
        <img src="<?php echo Pi::user()->avatar()->get($user['id'], 'small', false); ?>" class="pull-left">
        <div class="media-body">
            <h4 class="media-heading"><?php echo $this->escape($user['name']); ?></h4>
            <span class="muted"><?php _e('View my profile'); ?></span>
        </div>
    </a>
    <div class="well" style="padding: 8px 0;">
        <ul class="nav nav-list">
            <li class="<?php echo $cur_group == 'account' ? 'active' : '';?>">
                <a href="<?php echo $this->url('', array('controller' => 'account', 'action' => 'index'));?>">
                    <?php _e('Account settings')?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('', array('controller' => 'password', 'action' => 'index')); ?>">
                    <?php _e('Password');?>
                </a>
            </li>
            <li><a href="#"><?php _e('Avatar settings');?></a></li>
            <li class="nav-header"><?php _e('Profile settings');?></li>
            <?php  foreach ($groups as $key => $group) { ?>
            <li class="<?php  echo $cur_group == $key ? 'active' : ''; ?>">
                <a href="<?php echo $group['link']; ?>">
                    <?php echo $this->escape($group['title']); ?>
                </a>
            </li>
            <?php } ?>
            <li class="divider"></li>
            <li><a href="#"><?php _e('Privacy settings'); ?></a></li>
        </ul>
    </div>
</div>