<?php
   $is_owner = _get('uid') ? false : true;
?>
<div class="user-avatar-header">
    <div class="inline user-avatar-header-col user-avatar-header-left" style="width: 120px; height: 120px;">
        <div class="pull-left">
            <?php echo Pi::avatar()->get($uid, 'xlarge'); ?>
        </div>
        <?php if ($is_owner) { ?>
        <style>
            .user-avatar-header-left:hover .user-avatar-upload {
                display: block;
            }
        </style>
        <a class="hide user-avatar-upload" href="<?php echo $this->url('', array('controller' => 'avatar', 'action' => 'index')); ?>">
            <?php _e('Change avatar'); ?>
        </a>
        <?php } ?>
    </div>
    <div class="inline user-avatar-header-col user-avatar-header-center">
        <h2 class="user-name"><?php echo _escape($user['name']); ?></h2>
        <p style="margin-bottom: 5px;">
            <?php echo _escape($user['gender']); ?>
        <?php if($user['birthdate']) { ?>
        <div>
            <?php _e('Birthdate:'); ?>
            <?php echo _escape($user['birthdate']); ?> 
        </div>
        <?php } ?>
    </div>
    <div class="inline user-avatar-header-col" style="float: right; margin-top: 90px;">
        <?php if ($is_owner) { ?>
        <a style="margin-right: 15px;" class="btn btn-small pull-left" href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'view', 'uid' => $uid)); ?>">
            <i class="icon-eye-open"></i>
            <?php _e('Switch to view of others'); ?>
        </a>
        <div class="pull-right">
            <style>
                .user-dropdown-quicklinks:hover .dropdown-menu {
                    display: block;
                }
            </style>
            <div class="dropdown user-dropdown-quicklinks">
                <a style="margin-bottom: 2px;" href="javascript:;" class="btn btn-small">
                    <i class="icon-sort-by-attributes"></i>
                    <?php _e('Quicklinks'); ?><span style="margin-left: 5px;" class="caret"></span>
                </a>
                <ul style="margin-top: 0;" class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->url('', array('controller' => 'account', 'action' => 'index')); ?>">
                            <?php _e('Setting'); ?>
                        </a>
                    </li>
                    <li class="divider" style="margin: 1px;"></li>
                    <?php foreach ($quicklink as $item) { ?>
                    <li>
                        <a href="<?php echo $item['link']; ?>" title="<?php echo $item['title']; ?>" target="_blank">
                            <?php 
                            if ($item['icon']) {
                                echo sprintf(
                                    '<i class="%s"></i>',
                                    $item['icon']
                                );
                            }
                            ?>
                            <?php echo $item['title']; ?>
                        </a>
                    </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <?php } else { ?>
        <?php if (Pi::user()->getId() == $uid) { ?>
        <a style="margin-right: 15px;" class="btn btn-small" href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'index')); ?>">
            <i class="icon-eye-open"></i>
            <?php _e('Back to view of own'); ?>
        </a>
        <?php } ?>
    
        <a class="btn btn-small" href="<?php echo $this->url('default', array('module' => 'message', 'controller' => 'index', 'action' => 'send', 'uid' => $uid)); ?>">
            <i class="icon-envelope"></i>
            <?php _e('Send message'); ?>
        </a>
        <?php } ?>
    </div>
</div>
<style>
    .user-nav-icon {
        margin-right: 3px;
        vertical-align: middle;
    }

    .user-nav-dropdown:hover .dropdown-menu {
        display: block;
    }
</style>
<ul class="nav nav-tabs user-nav">
    <?php
        $items = $nav['items'];
        $length = count($items);
        $isOverflow = $length > 7 ? true : false;

        if (!$isOverflow) {
            /* Nav items length = < 7 */
            foreach ($items  as $item) { ?>
                <li class="<?php echo $item['name'] == $nav['cur'] ? 'active' : ''; ?>">
                    <a href="<?php echo $item['url']; ?>">
                        <?php echo $item['icon'] ? '<img class="user-nav-icon" src="' . $item['icon'] . '">' : ''; ?>
                        <?php echo $item['title']; ?>
                    </a>
                </li>
            <?php }
        } else {
            /* Nav length > 7 */
            $isNeedMoveCur = false;
            for ($i = 0; $i < $length; $i++) { 
                $item = $items[$i];
                if ($item['name'] == $nav['cur']) {
                    if ($i > 5) {
                        $isNeedMoveCur = true;
                        $curNum = $i;
                    }
                    break;
                }
            }

            if (!$isNeedMoveCur) {
                /* Cur nav item order < 6 */
                for ($i = 0; $i < 6; $i++) { 
                    $item = $items[$i]; ?>
                    <li class="<?php echo $item['name'] == $nav['cur'] ? 'active' : ''; ?>">
                        <a href="<?php echo $item['url']; ?>">
                            <?php echo $item['icon'] ? '<img class="user-nav-icon" src="' . $item['icon'] . '">' : ''; ?>
                            <?php echo $item['title']; ?>
                        </a>
                    </li>
                <?php }
            } else {
                /* Cur nav item order > 6 */
                for ($i = 0; $i < 5; $i++) {
                    $item = $items[$i]; ?>
                    <li>
                        <a href="<?php echo $item['url']; ?>">
                            <?php echo $item['icon'] ? '<img class="user-nav-icon" src="' . $item['icon'] . '">' : ''; ?>
                            <?php echo $item['title']; ?>
                        </a>
                    </li>
                <?php } ?>

                <li class="active">
                    <a href="<?php echo $items[$curNum]['url']; ?>">
                        <?php echo $item['icon'] ? '<img class="user-nav-icon" src="' . $item['icon'] . '">' : ''; ?>
                        <?php echo $items[$curNum]['title']; ?>
                    </a>
                </li>
            <?php } ?>

            <li class="dropdown user-nav-dropdown">
                <a style="margin-bottom: 2px;" class="dropdown-toggle" href="javascript:;">
                    <?php echo $item['icon'] ? '<img class="user-nav-icon" src="' . $item['icon'] . '">' : ''; ?>
                    <?php _e('More'); ?><b style="margin-left: 5px;" class="caret"></b>
                </a>
                <ul style="margin-top: 0;" class="dropdown-menu">
                    <?php for (; $i < $length; $i++) {
                        if ($isNeedMoveCur && $curNum == $i) continue;
                        $item = $items[$i]; ?>
                        <li>
                            <a href="<?php echo $item['url']; ?>">
                                <?php echo $item['icon'] ? '<img class="user-nav-icon" src="' . $item['icon'] . '">' : ''; ?>
                                <?php echo $item['title']; ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </li>
    <?php } ?>
</ul>
