<h2 class="page-header"><?php _e('Change email'); ?></h2>
<?php if ($result['status']) { ?>
    <p><?php _e('Congratulations !'); ?></p>
    <p><?php _e('Your email has been changed.'); ?></p>
    <p><?php echo sprintf(
            __('<a href="%s">Login right now</a>'),
            Pi::service('user')->getUrl('login')
        ); ?></p>
<?php } else { ?>
    <p><?php _e('Sorry !'); ?></p>
    <p><?php _e('The link has expired, or maybe your email has been changed.'); ?></p>
<?php } ?>
