<?php include '_user-media.phtml'; ?>
<div>
    <ul class="nav nav-tabs">
        <li>
            <a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'home', 'uid' => $uid)); ?>"><?php _e('Homepage');?></a>
        </li>
        <li>
            <a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'index', 'uid' => $uid));?>">
                <?php _e('Profile'); ?>
            </a>
        </li>
        <?php foreach ($activity_list as $key => $value) {?>
        <li class="<?php echo $cur_activity == $key ? 'active' : ''; ?>">
            <a href="<?php echo $this->url('', array('controller' => 'activity', 'action' => 'index', 'name' => $key));?>">
                <?php echo $this->escape($value['title']); ?>
            </a>
        </li>
        <?php } ?>
    </ul>
<div>
<?php
    vd($activity_contents);
?>
