<?php
$this->css($this->assetModule('script/front.css'));
?>
<?php include '_user-media.phtml'; ?>
<div class="clearfix">
    <a class="pull-right" href="<?php echo $activity_contents['title'];?>">
        <?php _e('View all');?>
    </a>
    <h3 class="user-activity-title"><?php echo $activity_contents['title'];?></h3>
    <?php foreach($activity_contents['log'] as $item) { ?>
    <div class="user-underline-list">
        <p class="p-small"><?php echo $item['message']; ?></p>
        <span class="muted"><?php echo _date($item['time']); ?></span>
    </div>
    <?php } ?>
</div>