<?php
    $this->css(array(
        $this->assetModule('script/front.css')
    ));
    $this->jQuery(array(
        'extension/ajax-upload.min.js',
        'extension/jquery.Jcrop.min.js',
        'extension/jquery.Jcrop.min.css'
    ));
    $this->bootstrap('js/bootstrap.min.js');

    $viewNavTabs = array(
        array(
            'source' => 'upload',
            'text'   => __('Upload images'),
            'href'   => '#fromUpload'
        ),
        array(
            'source' => 'gravatar',
            'text'   => __('From Gavatar'),
            'href'   => '#fromGravatar'
        ),
        array(
            'source' => 'repository',
            'text'   => __('From responsitery'),
            'href'   => '#formRepository'
        ),
        array(
            'source' => 'local',
            'text'   => __('System avatar'),
            'href'   => '#formLocal'
        )
    );
    d($config);
?>
<?php include '_user-side-nav.phtml' ?>
<div class="span9" id="js-user-avatar">
    <div class="page-header">
        <h3><?php _e('Avatar setting'); ?></h3>
        <div class="muted"><?php _e('Choose one way for your avatar source:'); ?></div>
    </div>
    <div>
        <h4><?php _e('Current avatar'); ?></h4>
        <p>
            <?php echo Pi::service('user')->avatar()->get($uid, '', array('class' => 'img-polaroid')); ?>
        <p class="text-warning">
            <?php _e('once switch source and saved,the avatar data from other source will be deleted.'); ?>
    </div>
    <ul class="nav nav-tabs">
        <?php 
            foreach ($viewNavTabs as $item) {
                echo sprintf('<li><a data-toggle="tab" data-source="%s" href="%s" class="avatar-source-nav">%s</a>',
                        $item['source'],
                        $item['href'],
                        $item['text']);
            }
        ?>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" id="fromUpload">
            <div class="avatar-upload-box">
                <div class="avatar-upload-hit">
                    <button class="btn avatar-upload-btn"><?php _e('Upload avatar'); ?></button>
                    <div class="muted">
                        <?php _e('Support'); ?>
                        <?php echo $config['avatar_extension']; ?>
                        (<?php echo $config['max_size']; ?>MB)
                    </div>
                </div>
                <img class="hide avatar-upload-image">
            </div>
            <div class="page-header">
                <strong><?php _e('Avatar previews'); ?></strong>
            </div>
            <ul class="unstyled avatar-preview-inline">
                <?php 
                    foreach ($allSize as $key => $item) {
                        echo sprintf('<li><p>%s</p><div class="avatar-preview-box" style="width: %spx; height: %spx;">%s</div>',
                                $key,
                                $item,
                                $item,
                                Pi::service('user')->avatar()->get($uid, $key, 
                                    array('class' => 'avatar-preview-img', 'data-size' => $item))
                             );
                    }
                ?>
            </ul>
        </div>
        <div class="tab-pane" id="fromGravatar">
            123213
        </div>
        <div class="tab-pane" id="formRepository">
            435345
        </div>
        <div class="tab-pane" id="formLocal">
            56756
        </div>
    </div>
    <div style="margin-top: 30px;" class="hide js-actions">
        <button class="btn btn-primary js-save"><?php _e('Save'); ?></button>
        <button class="btn btn-link js-cancel"><?php _e('Cancel'); ?></a>
    </div>
</div>
<script>
$('#js-user-avatar').data('config', {
    source: '<?php echo $source ?>',
    urlRoot: '<?php echo $this->url('', array('controller' => 'avatar')); ?>',
    fake_id: '<?php echo $form->get('fake_id')->getValue() ?>',
    format: '<?php echo $config['avatar_extension']; ?>'.split(','),
    uploadText: '<?php _e('Upload avatar'); ?>',
    processText: '<?php _e('Uploading'); ?>',
    uploadBoxSize: 300
});
</script>
<script src="<?php echo $this->assetModule('front/avatar.js'); ?>"></script>

