<div class="span3">
    <ul class="nav nav-list">
        <li class="nav-header"><?php _e('Account');?></li>
        <li><a href="<?php echo $this->url('default', array('controller' => 'account', 'action' => 'index')); ?>"><?php _e('Basic info')?></a></li>
        <li><a href="<?php echo $this->url('default', array('controller' => 'password', 'action' => 'index')); ?>"><?php _e('Change password');?></a></li>
        <li class="active"><a href=""><?php _e('Change email');?></a></li>
        <li class="divider"></li>
        <li><a href=""><?php _e('Avatar');?></a></li>
        <li class="divider"></li>
        <li class="nav-header"><?php _e('Profile');?></li>
        <li><a href=""><?php _e('Basic info') ?></a></li>
        <li><a href=""><?php _e('Address info');?></a></li>
        <li><a href=""><?php _e('Work info'); ?></a></li>
        <li class="divider"></li>
        <li><a href=""><?php _e('Privacy'); ?></a></li>
        <li class="divider"></li>
        <li><a href=""><?php _e('Preference'); ?></a></li>
    </ul>
</div>

<div class="span9">
    <h2 class="page-header"><?php echo $this->escape($title); ?></h2>
    <div class="span6">
        <p >Check your new email to complete the change<br \>
            The link will expired in 12 hours
        </p>
    </div>
    <div class="span3">
        <p>Get no email?</p>
        <ul>
            <li>1.wait a few minutes</li>
            <li>2.Check your email rubbish</li>
            <li>3.<a href="<?php echo $changeEmailLink; ?>">Try another reset</a></li>
        </ul>
    </div>
</div>