<?php
$this->css($this->assetModule('front/front.css'));
$this->headMeta('noindex', 'robots');

?>
<div class="row">
    <div class="col-md-3">
        <?php include $this->template('./profile-sidebar.phtml'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?php _e('Your dashboard'); ?></h1>
        </div>


            <div class="row">
                <?php if ($bookings !== null) : ?>
                    <div class="col-md-8">
                        <h2><?php _e('Your pending requests'); ?></h2>
                        <table id="booking-list" class="table table-striped table-bordered table-condensed">
                            <tr>
                                <th class="text-center"><?php _e('Request date'); ?></th>
                                <th class="text-center"><?php _e('Item'); ?></th>
                                <th class="text-center"><?php _e('Booker'); ?></th>
                                <th class="text-center"><?php _e('Booking period'); ?></th>
                                <th class="text-center"><?php _e('Number of person'); ?></th>
                            </tr>
                            <?php if(!$bookings) : ?>
                                <tr>
                                    <td colspan="100" class="text-center">
                                        <br />
                                        <?php _e('There is no pending booking request for now'); ?>
                                        <br /><br />
                                    </td>
                                </tr>
                            <?php endif; ?>
                            <?php foreach ($bookings as $booking) { ?>
                                <?php switch ($booking['status']) {
                                    case 0:
                                        $classIcon = 'fa-question';
                                        $classLabel = 'label label-warning';
                                        break;

                                    case 1:
                                        $classIcon = 'fa-check';
                                        $classLabel = 'label label-success';
                                        break;

                                    case 2:
                                        $classIcon = 'fa-times';
                                        $classLabel = 'label label-danger';
                                        break;

                                    case 3:
                                        $classIcon = 'fa-times';
                                        $classLabel = 'label label-closed';
                                        break;
                                }
                                ?>
                                <tr data-href='<?php echo $this->url('guide', array('module' => 'guide', 'controller' => 'manage', 'action' => 'calendar', 'item' => $booking['item'])); ?>' id="booking-list-<?php echo $this->escape($booking['id']); ?>" rel="<?php echo $this->escape($booking['id']); ?>" class="clickable-row date-<?php echo _date($booking['time_create']) ?>" >
                                    <td class="text-center"><?php echo $this->escape($booking['time_create_view'])  ; ?></td>
                                    <td class="text-center"><?php echo $list['commercial'][$booking['item']]['title'] ?></td>
                                    <td class="text-center">
                                        <?php echo $this->escape($booking['first_name']); ?>
                                        <?php echo $this->escape($booking['last_name']); ?>
                                    </td>
                                    <td class="text-center">
                                        <div class="clearfix">
                                            <?php echo $this->escape($booking['date_range']); ?>
                                        </div>
                                    </td>
                                    <td class="text-center"><?php echo $this->escape($booking['number_person']); ?></td>
                                </tr>
                            <?php } ?>
                        </table>

                        <p>
                            <?php echo sprintf(__('There are %s pending requests out of a total of %s booking requests'), count($bookings), $countTotalBookings) ?>
                        </p>

                        <script>
                            $(document).ready(function($) {
                                $(".clickable-cell").click(function() {
                                    window.document.location = $(this).parent().data("href");
                                });
                                $(".clickable-row").click(function() {
                                    window.open($(this).data("href"));
                                });

                            });
                        </script>
                    </div>
                <?php endif; ?>

                <div class="<?php echo $bookings !== null ? 'col-md-4' : 'col-sm-12' ?>">
                    <?php $colClass = $bookings !== null ? 'col-md-6' : 'col-md-3' ?>

                    <h2 class="<?php echo $bookings === null ? 'hide' : '' ?>"><?php _e('Shortcuts'); ?></h2>

                    <div class="row text-center match-height-list">
                        <?php if (Pi::service('module')->isActive('guide')) { ?>
                            <?php $guideConfig = Pi::service('registry')->config->read('guide'); ?>
                            <?php if ($guideConfig['manage_active']) { ?>
                                <div class="<?php echo $colClass ?>">
                                    <a class="thumbnail" title="<?php _e('My items'); ?>" href="<?php echo Pi::url($this->url('guide', array('module' => 'guide', 'controller' => 'manage', 'action' => 'dashboard'))); ?>">
                                        <i class="fa fa-map fa-3x"></i>
                                        <div class="caption">
                                            <?php _e('My items'); ?>
                                        </div>
                                    </a>
                                </div>

                            <?php } ?>

                            <?php if ($guideConfig['sponsor_active']) { ?>
                                <div class="<?php echo $colClass ?>">
                                    <a class="thumbnail" title="<?php _e('Sponsorship'); ?>" href="<?php echo Pi::url($this->url('guide', array('module' => 'guide', 'controller' => 'manage', 'action' => 'sponsor'))); ?>">
                                        <i class="fa fa-gift fa-3x"></i>
                                        <div class="caption">
                                            <?php _e('Sponsorship'); ?>
                                        </div>
                                    </a>
                                </div>
                            <?php } ?>
                        <?php } ?>

                        <?php if (Pi::service('module')->isActive('message')) { ?>
                            <?php $message = _number(Pi::api('api', 'message')->getUnread($uid, 'message')); ?>
                            <?php $notification = _number(Pi::api('api', 'message')->getUnread($uid, 'notification')); ?>
                            <div class="<?php echo $colClass ?>">
                                <a class="thumbnail" title="<?php _e('My messages'); ?>" href="<?php echo Pi::url($this->url('default', array('module' => 'message', 'controller' => 'index', 'action' => 'index'))); ?>">
                                    <i class="fa fa-envelope fa-3x"></i>
                                    <div class="caption">
                                        <?php _e('My messages'); ?> <?php if($message) : ?><span class="badge"><?php echo $message; ?><?php endif; ?></span>
                                    </div>
                                </a>
                            </div>
                            <div class="<?php echo $colClass ?>">
                                <a class="thumbnail" title="<?php _e('My notifications'); ?>" href="<?php echo Pi::url($this->url('default', array('module' => 'message', 'controller' => 'notify', 'action' => 'index'))); ?>">
                                    <i class="fa fa-bell fa-3x"></i>
                                    <div class="caption">
                                        <?php _e('My notifications'); ?> <?php if($notification) : ?><span class="badge"><?php echo $notification; ?><?php endif; ?></span>
                                    </div>
                                </a>
                            </div>
                        <?php } ?>

                        <?php if (Pi::service('module')->isActive('event')) { ?>
                            <div class="<?php echo $colClass ?>">
                                <a class="thumbnail" title="<?php _e('My events'); ?>" href="<?php echo Pi::url($this->url('event', array('module' => 'event', 'controller' => 'manage', 'action' => 'index'))); ?>">
                                    <i class="fa fa-calendar fa-3x"></i>
                                    <div class="caption">
                                        <?php _e('My events'); ?>
                                    </div>
                                </a>
                            </div>
                        <?php } ?>

                        <?php if (Pi::service('module')->isActive('order')) { ?>
                            <?php $orderConfig = Pi::service('registry')->config->read('order'); ?>
                            <div class="<?php echo $colClass ?>">
                                <a class="thumbnail" title="<?php _e('My orders'); ?>" href="<?php echo Pi::url($this->url('order', array('module' => 'order', 'controller' => 'index', 'action' => 'index'))); ?>">
                                    <i class="fa fa-shopping-basket fa-3x"></i>
                                    <div class="caption">
                                        <?php _e('My orders'); ?>
                                    </div>
                                </a>
                            </div>
                            <?php if ($orderConfig['credit_active']) { ?>
                                <?php $credit = Pi::api('credit', 'order')->getCredit($uid); ?>
                                <div class="<?php echo $colClass ?>">
                                    <a class="thumbnail" title="<?php _e('My credit'); ?>" href="<?php echo Pi::url($this->url('order', array('module' => 'order', 'controller' => 'credit', 'action' => 'index'))); ?>">
                                        <i class="fa fa-archive fa-3x"></i>
                                        <div class="caption">
                                            <?php _e('My credit'); ?> <?php if($credit['amount_view'] && intval($credit['amount_view'])) : ?><span class="badge"><?php echo $credit['amount_view']; ?><?php endif; ?></span>
                                        </div>
                                    </a>
                                </div>
                            <?php } ?>
                        <?php } ?>

                        <?php if (Pi::service('module')->isActive('favourite')) { ?>
                            <div class="<?php echo $colClass ?>">
                                <a class="thumbnail" title="<?php _e('My favorites'); ?>" href="<?php echo Pi::url($this->url('default', array('module' => 'favourite', 'controller' => 'index', 'action' => 'index'))); ?>">
                                    <i class="fa fa-star fa-3x"></i>
                                    <div class="caption">
                                        <?php _e('My favorites'); ?>
                                    </div>
                                </a>
                            </div>
                        <?php } ?>

                        <?php if (Pi::service('module')->isActive('video')) { ?>
                            <div class="<?php echo $colClass ?>">
                                <a class="thumbnail" title="<?php _e('My videos'); ?>" href="<?php echo Pi::url($this->url('video', array('module' => 'video', 'controller' => 'channel', 'action' => 'index'))); ?>">
                                    <i class="fa fa-video-camera fa-3x"></i>
                                    <div class="caption">
                                        <?php _e('My videos'); ?>
                                    </div>
                                </a>
                            </div>
                        <?php } ?>

                        <?php if (Pi::service('module')->isActive('support')) { ?>
                            <?php $support = _number(Pi::api('ticket', 'support')->getCount($uid)); ?>
                            <div class="<?php echo $colClass ?>">
                                <a class="thumbnail" title="<?php _e('My support tickets'); ?>" href="<?php echo Pi::url($this->url('support', array('module' => 'support', 'controller' => 'index', 'action' => 'index'))); ?>">
                                    <i class="fa fa-life-ring fa-3x"></i>
                                    <div class="caption">
                                        <?php _e('My support tickets'); ?> <?php if($support) : ?><span class="badge"><?php echo $support; ?><?php endif; ?></span>
                                    </div>
                                </a>
                            </div>
                        <?php } ?>

                    </div>
                </div>
            </div>
    </div>
</div>


