<?php
$this->css($this->assetModule('front/front.css'));
$this->headMeta('noindex', 'robots');

$userSection = $this->isUserSection(Pi::service('module')->current());
?>

<div class="row">
    <?php if($userSection) : ?>
        <div class="col-md-3">
            <?php include $this->template('./profile-sidebar.phtml'); ?>
        </div>
    <?php endif; ?>
    <div class="<?php echo $userSection ? 'col-md-9' : 'col-md-12' ?>">
        <div class="page-header">
            <h1><?php _e('My profile'); ?></h1>
        </div>

        <?php include $this->template('./profile-topbar.phtml'); ?>
        <div class="user-min-body pi-comment-list" id="pi-comment-lead">
            <p>&nbsp;</p>
            <?php if ($count) {
                foreach ($favourites as $favourite) { ?>
                    <div class="tab-pane <?php echo $first ? 'active' : '' ?> " id="panel-<?php echo $this->escape($favourite['name']); ?>">
                    <?php $first = false; ?>
                    <?php if (!empty($favourite['list'])) { ?>
                        <?php
                            $favouriteList = $favourite['list'];
                            $favouriteName = $favourite['name']; 
                            
                            $partial = $this->templateModule('front/partial/favourite-list.phtml',  $favourite['name']);
                            if ($partial) {
                            } else {
                                $partial = $this->template('front/partial/favourite-list.phtml');
                            }
                            include $partial;
                        ?>
                    
                    <?php } else { ?>
                        <div>
                            <?php echo $this->escape($favourite['message']); ?>
                        </div>
                    <?php } ?>
                </div>
                <?php } ?>
            <?php } else { ?>
                <div class="well">
                    <?php _e('No data available.'); ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>

