<?php
$this->css($this->assetModule('script/front.css'));
?>
<?php include '_user-media.phtml'; ?>
<div>
    <div>
        <?php foreach ($timeline as $item) { ?>
            <div class="clearfix user-media">
                <div class="pull-left">
                    <?php
                    echo $item['icon'] ? : '<i class="icon-search icon-2x"></i>';
                    ?>
                </div>
                <div class="media-body">
                    <p class="media-heading">
                        <strong class="user-media-name"><?php echo $this->escape($user['name']); ?></strong>
                        <span class="muted"><?php echo _date($item['time']); ?></span>
                    <p class="media-heading">
                        <?php echo $this->escape($item['message']); ?>
                    </p>
                    <?php
                    if ($item['link']) {
                        echo sprintf('<a href="%s" target="_blank">%s</a>',
                            $item['link'],
                            $item['link']);
                    }
                    ?>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php
    if ($paginator) {
        echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml',array('class' => 'pagination-left'));
    }
    ?>
</div>