<?php
    $this->css($this->assetModule('front/front.css'));
?>
<div class="row">
    <?php include $this->template('./profile-sidebar.phtml'); ?>
    <div class="col-md-9">
        <div class="user-page-header">
            <h3><?php echo _escape($title); ?></h3>
            <div class="text-muted"><?php _e('Please select a common mode to invite your friends to register'); ?></div>
        </div>
        
        <div>
            <?php foreach ($content as $key => $html) { ?>
            <div>
                <?php echo $html; ?>
            </div>
            <?php } ?>
        </div>
    </div>
</div>
