<div class="page-header">
    <h2><?php echo _escape($title); ?></h2>
</div>
<div class="login-message">
    <?php
    $home_url = $this->url('home');
    $home_string = sprintf('<a href="%s" title="%s">%s</a>', $home_url, __('homepage'), __('homepage'));
    $redirect = '';
    $login_url = Pi::service('authentication')->getUrl('login', $redirect);
    $login_string = sprintf('<a href="%s" title="%s">%s</a>', $login_url, __('re-login'), __('re-login'));
    echo sprintf(__('You have logged out successfully, please go to %s or to %s.'), $home_string, $login_string);
    ?>
</div>

<div class="empty">
    <strong><?php _e('Choose: '); ?></strong>
    <span><a href="<?php echo Pi::service('authentication')->getUrl('login', ''); ?>" title="<?php _e('Login'); ?>"><?php _e('Login'); ?></a></span>
    <span><a href="<?php echo Pi::service('user')->getUrl('register'); ?>" title="<?php _e('Register'); ?>"><?php _e('Register'); ?></a></span>
</div>