<?php $this->css($this->assetModule('front/front.css')); ?>
<div class="page-header">
    <h2><?php echo _escape($title); ?></h2>
</div>
<div class="login-message">
    <?php
    $home_url = $this->url('home');
    $home_string = sprintf('<a href="%s" title="%s">%s</a>', $home_url, __('homepage'), __('homepage'));
    $redirect = '';
    $login_url = Pi::service('authentication')->getUrl('login', $redirect);
    $login_string = sprintf('<a href="%s" title="%s">%s</a>', $login_url, __('re-login'), __('re-login'));
    echo sprintf(__('You have logged out successfully, please go to %s or to %s.'), $home_string, $login_string);
    ?>
</div>

<div class="user-action-bar">
    <div class="col-md-offset-2 col-md-10">
        <ul class="list-inline">
            <li>
                <a title="<?php _e('Login'); ?>" href="<?php echo Pi::service('authentication')->getUrl('login', ''); ?>"><?php _e('Login'); ?></a>
            </li>
            <li>
                <a title="<?php _e('Register'); ?>" href="<?php echo Pi::service('user')->getUrl('register'); ?>"><?php _e('Register'); ?></a>
            </li>
        </ul>
    </div>
</div>
