<h2 class="page-header"><?php _e('Reset password'); ?></h2>
<?php if (!(isset($result) && $result['status'])) {
    if (!(isset($result) && $result['message'])) {
        include $this->templateComponent('form');
    } else { ?>
        <p><?php _e('The link has expired.'); ?></p>
        <p><?php echo sprintf(
                __('Please <a href="%s">click</a> to find your password again.'),
                $this->url('', array('controller' => 'password', 'action' => 'find'))
            ); ?></p>
<?php }
} else { ?>
    <p><?php _e('Congratulations!'); ?></p>
    <p><?php echo sprintf(
                __('Your new password is setup successfully. Please <a href="%s">login</a>.'),
                Pi::service('user')->getUrl('login')
        ); ?></p>
<?php } ?>
