<?php $this->headMeta('noindex', 'robots'); ?>
    <div class="page-header">
        <h1><?php _e('Find password'); ?></h1>
    </div>
<?php if (empty($result['status'])) {
    if (!empty($result)) {
        echo sprintf(
            '<div class="alert alert-warning"><a href="#" data-dismiss="alert" class="close">&times;</a>%s</div>',
            $result['message']);
    }
    echo $this->form($form);
} else { ?>
    <p><?php echo _escape($result['message']); ?></p>
<?php } ?>