<?php $this->headMeta('noindex', 'robots'); ?>
<div class="page-header">
    <h1><?php _e('Reset password'); ?></h1>
</div>
<?php if (empty($result['status'])) { ?>
    <p><?php _e('Enter your email address below and we’ll send you an email allowing you to reset it.'); ?></p>
    <?php if (!empty($result)) {
        echo sprintf(
            '<div class="alert alert-warning"><a href="#" data-dismiss="alert" class="close">&times;</a>%s</div>',
            $result['message']);
    } ?>
    <?php echo $this->form($form); ?>
<?php } else { ?>
    <p><?php echo _escape($result['message']); ?></p>
    <p><?php
        echo sprintf('<a class="btn btn-primary" href="%s">' . __('Login') . '</a>.',
            Pi::service('authentication')->getUrl('login', ['redirect' => $result['redirect']])
        ); ?></p>
<?php } ?>
