<?php
$this->css($this->assetModule('front/front.css'));
?>
<div class="row">
    <?php include $this->template('./profile-sidebar.phtml'); ?>
    <div class="col-md-9">
        <div class="user-page-header">
            <h3><?php _e('Change password'); ?></h3>
            <div class="text-muted"><?php _e('To ensure your account security, complex password is required.'); ?></div>
        </div>
        <?php
        if (isset($result)) {
            echo sprintf('
                <div class="alert %s">
                    <button data-dismiss="alert" class="close" type="button">&times;</button>
                    %s
                </div>',
                $result['status'] ? 'alert-info' : 'alert-warning',
                $result['message']);
        }
        ?>
        <?php include $this->templateComponent('form'); ?>
    </div>
</div>
