<div class="page-header">
    <h2><?php _e('Find password'); ?></h2>
</div>
<?php if (empty($result['status'])) {
    if (!empty($result)) {
        echo sprintf(
            '<div class="alert alert-warning"><a href="#" data-dismiss="alert" class="close">&times;</a>%s</div>',
            $result['message']);
    }
    include $this->templateComponent('form');
} else { ?>
    <p><?php echo _escape($result['message']); ?></p>
<?php } ?>
