<?php
    $this->css($this->assetModule('script/front.css'));
?>
<?php include '_user-side-nav.phtml' ?>
<div class="span9">
    <h2 class="page-header"><?php _e('Reset password'); ?></h2>
    <?php
    if (isset($result)) {
        echo sprintf(
            '<div class="alert %s"><button class="close">&times;</button>%s</div>',
            $result['status'] ? 'alert-success' : 'alert-error',
            $result['message']);
    }
    ?>
    <?php include $this->templateComponent('form'); ?>
</div>