<h2 class="page-header"><?php _e('Reset password'); ?></h2>
<?php if (!(isset($result) && $result['status'])) {
    if (!(isset($result) && $result['message'])) {
        include $this->templateComponent('form');
    } else { ?>
        <p><?php _e('Sorry, your link has expired.'); ?></p>
        <p><?php echo sprintf('<a href="%s">' . __('Try to find password again') . '</a>.',
                $this->url('', array('controller' => 'password', 'action' => 'find'))
            ); ?></p>
<?php }
} else { ?>
    <p><?php _e('Congratulations!'); ?></p>
    <p><?php _e('Your new password has worked'); ?></p>
    <p><?php echo sprintf('<a href="%s">' . __('Please login') . '</a>.',
                Pi::service('authentication')->getUrl('login')
        ); ?></p>
<?php } ?>
