<?php
    $this->css($this->assetModule('script/front.css'));
    d($timeline);
?>
<?php include '_user-media.phtml'; ?>
<div>
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="<?php echo $this->url('default', array('controller' => 'profile', 'action' => 'home', 'uid' => $uid)); ?>"><?php _e('Homepage');?></a>
        </li>
        <li>
            <a href="<?php echo $this->url('default', array('controller' => 'profile', 'action' => 'index', 'uid' => $uid));?>">
                <?php _e('Profile'); ?>
            </a>
        </li>
        <?php foreach ($activityList as $row) {?>
        <li>
            <a href="<?php echo $this->url('default', array('controller' => 'activity', 'action' => 'index', 'module' => $row['module'], 'type' => $row['name']));?>">
            <?php echo $this->escape($row['title']); ?>
            </a>
        </li>
        <?php } ?>
    </ul>

    <div>
        <h3><?php _e('Homepage'); ?></h3>
        <?php foreach ($timeline as $item) { ?>
        <div>
            <ul class="inline">
                <?php if ($item['icon']) { ?>
                <?php echo $this->escape($item['icon']);?>
                <?php } else { ?>
                <span></span><i class="icon-search"></i><span>
                <?php }?>
                <li>
                    <p>
                        <?php echo $this->escape($item['message']);?>
                    </p>
                </li>
                <li><?php echo $this->escape(_date($item['time'])); ?></li>
            </ul>
        </div>
        <?php } ?>
    </div>
    <?php
    if ($paginator) {
        echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml',array('class' => 'pagination-left'));
    }
    ?>
</div>