<?php
$uid       = Pi::user()->getId();
$userName  = Pi::user()->get($uid, 'name');
$firstName = Pi::user()->get($uid, 'first_name');

if (!isset($groups)) {
    $groups = Pi::registry('display_group', 'user')->read();
}
array_walk($groups, function (&$group, $gid) {
    $action       = $group['compound'] ? 'edit.compound' : 'edit.profile';
    $group['url'] = Pi::service('url')->assemble('user', [
        'module'     => 'user',
        'controller' => 'profile',
        'action'     => $action,
        'group'      => $gid,
    ]);
});
$userConfig = Pi::service('registry')->config->read('user');
?>
<div class="clearfix" id="sticky-sidebar-manage">

    <div class="list-group">
        <div class="">
            <a href="<?php echo Pi::url($this->url('user', ['module' => 'user', 'controller' => 'dashboard'])); ?>"
               class="list-group-item<?php if ($controller == 'dashboard') {
                   echo ' active';
               } ?>">
                <span class="fa fa-dashboard vertical-align-text-top"></span>&nbsp; <?php _e('Dashboard') ?>
            </a>
        </div>
    </div>


    <div class="list-group">
        <?php if (in_array('guide', $userConfig['side_menu']) && Pi::service('module')->isActive('guide')) { ?>
            <?php $guideConfig = Pi::service('registry')->config->read('guide'); ?>
            <?php if ($guideConfig['manage_active']) { ?>
                <a title="<?php _e('My items'); ?>"
                   href="<?php echo Pi::url($this->url('guide', ['module' => 'guide', 'controller' => 'manage', 'action' => 'dashboard'])); ?>"
                   class="list-group-item<?php if (isset($sideActive) && $sideActive == 'dashboard') {
                       echo ' active';
                   } ?>"><?php _e('My items'); ?></a>
                
                <?php if ($guideConfig['sponsor_active']) { ?>
                    <a title="<?php _e('Sponsorship'); ?>"
                       href="<?php echo Pi::url($this->url('guide', ['module' => 'guide', 'controller' => 'manage', 'action' => 'sponsor'])); ?>"
                       class="list-group-item<?php if (isset($sideActive) && $sideActive == 'sponsor') {
                           echo ' active';
                       } ?>"><?php _e('Sponsorship'); ?></a>
                <?php } ?>
            <?php } ?>
            <a title="<?php _e('My requests'); ?>"
               href="<?php echo Pi::url($this->url('guide', ['module' => 'guide', 'controller' => 'request', 'action' => 'index'])); ?>"
               class="list-group-item<?php if (isset($sideActive) && $sideActive == 'request') {
                   echo ' active';
               } ?>"><?php _e('My requests'); ?></a>
        <?php } ?>

        <?php if (in_array('media', $userConfig['side_menu']) && Pi::service('module')->isActive('media')) { ?>
            <a title="<?php _e('My media'); ?>"
               href="<?php echo Pi::url($this->url('default', ['module' => 'media', 'controller' => 'list', 'action' => 'index'])); ?>"
               class="list-group-item<?php if (isset($sideActive) && $sideActive == 'media') {
                   echo ' active';
               } ?>"><?php _e('My media'); ?></a>
        <?php } ?>

        <?php if (in_array('stats', $userConfig['side_menu']) && Pi::service('module')->isActive('guide')) { ?>
            <a title="<?php _e('My stats'); ?>"
               href="<?php echo Pi::url($this->url('default', ['module' => 'guide', 'controller' => 'stats', 'action' => 'index'])); ?>"
               class="list-group-item<?php if (isset($sideActive) && $sideActive == 'stats') {
                   echo ' active';
               } ?>"><?php _e('My stats'); ?></a>
        <?php } ?>

        <?php if (in_array('message', $userConfig['side_menu']) && Pi::service('module')->isActive('message')) { ?>
            <?php $message = _number(Pi::api('api', 'message')->getUnread($uid, 'message')); ?>
            <a title="<?php _e('My messages'); ?>"
               href="<?php echo Pi::url($this->url('default', ['module' => 'message', 'controller' => 'index', 'action' => 'index'])); ?>"
               class="list-group-item<?php if (isset($sideActive) && $sideActive == 'message') {
                   echo ' active';
               } ?>"><?php _e('My messages'); ?> <span class="badge"><?php echo $message; ?></span></a>
            <?php $notification = _number(Pi::api('api', 'message')->getUnread($uid, 'notification')); ?>
            <a title="<?php _e('My notifications'); ?>"
               href="<?php echo Pi::url($this->url('default', ['module' => 'message', 'controller' => 'notify', 'action' => 'index'])); ?>"
               class="list-group-item<?php if (isset($sideActive) && $sideActive == 'notification') {
                   echo ' active';
               } ?>"><?php _e('My notifications'); ?> <span class="badge"><?php echo $notification; ?></span></a>
        <?php } ?>

        <?php if (in_array('support', $userConfig['side_menu']) && Pi::service('module')->isActive('support')) { ?>
            <?php $support = _number(Pi::api('ticket', 'support')->getCount($uid)); ?>
            <a title="<?php _e('My support tickets'); ?>"
               href="<?php echo Pi::url($this->url('support', ['module' => 'support', 'controller' => 'index', 'action' => 'index'])); ?>"
               class="list-group-item<?php if (isset($sideActive) && $sideActive == 'support') {
                   echo ' active';
               } ?>"><?php _e('My support tickets'); ?> <span class="badge"><?php echo $support; ?></span></a>
        <?php } ?>

        <?php if (in_array('event', $userConfig['side_menu']) && Pi::service('module')->isActive('event')) { ?>
            <a title="<?php _e('My events'); ?>"
               href="<?php echo Pi::url($this->url('event', ['module' => 'event', 'controller' => 'manage', 'action' => 'index'])); ?>"
               class="list-group-item<?php if ($module == 'event') {
                   echo ' active';
               } ?>"><?php _e('My events'); ?></a>
        <?php } ?>

        <?php if (in_array('order', $userConfig['side_menu']) && Pi::service('module')->isActive('order')) { ?>
            <?php $orderConfig = Pi::service('registry')->config->read('order'); ?>
            <a title="<?php _e('My orders'); ?>"
               href="<?php echo Pi::url($this->url('order', ['module' => 'order', 'controller' => 'index', 'action' => 'index'])); ?>"
               class="list-group-item<?php if (isset($sideActive) && $sideActive == 'order') {
                   echo ' active';
               } ?>"><?php _e('My orders'); ?></a>
            <?php if ($orderConfig['credit_active']) { ?>
                <?php $credit = Pi::api('credit', 'order')->getCredit($uid); ?>
                <a title="<?php _e('My credit'); ?>"
                   href="<?php echo Pi::url($this->url('order', ['module' => 'order', 'controller' => 'credit', 'action' => 'index'])); ?>"
                   class="list-group-item<?php if (isset($sideActive) && $sideActive == 'credit') {
                       echo ' active';
                   } ?>"><?php _e('My credit'); ?> <span class="badge"><?php echo $credit['amount_view']; ?></span></a>
            <?php } ?>
        <?php } ?>

        <?php if (in_array('favourite', $userConfig['side_menu']) && Pi::service('module')->isActive('favourite')) { ?>
            <a title="<?php _e('My favorites'); ?>"
               href="<?php echo Pi::url($this->url('default', ['module' => 'favourite', 'controller' => 'index', 'action' => 'index'])); ?>"
               class="list-group-item<?php if ($module == 'favourite') {
                   echo ' active';
               } ?>"><?php _e('My favorites'); ?></a>
        <?php } ?>
        <?php if (in_array('comment', $userConfig['side_menu']) && Pi::service('module')->isActive('comment')) { ?>
            <a title="<?php _e('My reviews/comments'); ?>"
               href="<?php echo Pi::url($this->url('default', ['module' => 'comment', 'controller' => 'my'])); ?>"
               class="list-group-item<?php if ($module == 'comment') {
                   echo ' active';
               } ?>"><?php _e('My reviews/comments'); ?></a>
        <?php } ?>
        <?php $guideConfig = Pi::service('registry')->config->read('guide'); ?>
        <?php if (in_array('guide_favourite', $userConfig['side_menu']) && Pi::service('module')->isActive('favourite') && Pi::service('module')->isActive('guide') && $guideConfig['favourite_bar']) { ?>
            <a title="<?php _e('My favorites'); ?>"
               href="<?php echo Pi::url($this->url('default', ['module' => 'guide', 'controller' => 'favourite', 'action' => 'index'])); ?>"
               class="list-group-item<?php if ($module == 'guide' && $controller == 'favourite') {
                   echo ' active';
               } ?>"><?php _e('My favorites'); ?></a>
        <?php } ?>

        <?php if (in_array('video', $userConfig['side_menu']) && Pi::service('module')->isActive('video')) { ?>
            <a title="<?php _e('My videos'); ?>"
               href="<?php echo Pi::url($this->url('video', ['module' => 'video', 'controller' => 'channel', 'action' => 'index'])); ?>"
               class="list-group-item<?php if ($module == 'video') {
                   echo ' active';
               } ?>"><?php _e('My videos'); ?></a>
        <?php } ?>
    </div>
    
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <a class="btn btn-primary btn-block collapsed" role="button" data-toggle="collapse"
                       data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <?php _e('My account / Profile') ?> <span class='caret'></span>
                    </a>
                </h4>
            </div>

            <div id="collapseOne"
                 class="panel-collapse collapse <?php if ($module == 'user' && $controller != 'dashboard') echo 'in' ?>"
                 role="tabpanel" aria-labelledby="headingOne">
                 <div class="list-group">
                    <a href="<?php echo Pi::url($this->url('user', ['module' => 'user', 'controller' => 'profile'])); ?>" title="<?php echo _b('Manage account'); ?>" 
                        class="list-group-item<?php if ($controller == 'profile') {
                           echo ' active';
                       } ?>">
                        <?php echo _e('Manage account'); ?>
                    </a>
                                
                    <a href="<?php echo Pi::url($this->url('user', ['module' => 'user', 'controller' => 'account'])); ?>"
                       class="list-group-item<?php if ($controller == 'account') {
                           echo ' active';
                       } ?>">
                        <?php _e('Account settings') ?>
                    </a>
                    <a href="<?php echo Pi::url($this->url('user', ['module' => 'user', 'controller' => 'password'])); ?>"
                       class="list-group-item<?php if ($controller == 'password') {
                           echo ' active';
                       } ?>">
                        <?php _e('Change password'); ?>
                    </a>
                    <a href="<?php echo Pi::url($this->url('user', ['module' => 'user', 'controller' => 'avatar'])); ?>"
                       class="list-group-item<?php if ($controller == 'avatar') {
                           echo ' active';
                       } ?>">
                        <?php _e('Change avatar'); ?>
                    </a>
                    <?php
                    foreach ($groups as $key => $group) {
                        ?>
                        <a href="<?php echo $group['url']; ?>"
                           class="list-group-item<?php if (isset($group_id)) {
                               echo $group_id == $key ? ' active' : '';
                           } ?>">
                            <?php echo _escape($group['title']); ?>
                        </a>
                    <?php } ?>
                    <a href="<?php echo Pi::url($this->url('user', ['module' => 'user', 'controller' => 'privacy'])); ?>"
                       class="list-group-item<?php if ($controller == 'privacy') {
                           echo ' active';
                       } ?>">
                        <?php _e('Privacy'); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
    
    
</div>

<script>
    $(document).ready(function () {
        if ($("#sticky-sidebar-manage").hcSticky == undefined) {
            return;
        }
        var affixWrapperHeight = 0;
        var affixWrapper = $('#affixWrapper');
        if (affixWrapper.length > 0) {
            affixWrapper.find('.nav').addClass('forceVisible');
            var affixWrapperHeight = affixWrapper.height();
            affixWrapper.find('.nav').removeClass('forceVisible');
        }

        var Sticky = new hcSticky('#sticky-sidebar-manage', {
            responsive : true,
            top: $('#pi-header nav').height() + affixWrapperHeight + 20,
            stickTo: '#sticky-container',
            queries: {
                992: {
                    disable: true
                }
            },
            bottomEnd: -100
        });

        $('#sticky-sidebar div.modal').insertAfter('.wrapper-sticky');

    });

</script>
