<?php
/**
 * User profile page top-bar for pages inside user module
 *
 * Variables:
 * `$uid`: int, user id
 * `$name`: string, user name
 * `$owner`: bool, if current visitor is the user himself
 * `$extra`: extra information to display on user topbar
 */

// Set uid if not set on controller
if (!isset($uid)) {
    $uid = Pi::user()->getId();
}

// Set name if not set on controller
if (!isset($name)) {
    $name = 'profile';
}

// Get user base info
if (!isset($user) || empty($user)) {
    $user = Pi::api('user', 'user')->get(
        $uid,
        ['name', 'gender', 'birthdate'],
        true,
        true
    );
}

// Check user
if (!$user) {
    Pi::service('url')->redirect(Pi::user()->getUrl('profile'));
    return;
}

// Check if the current visitor is owner of the user
if (!isset($owner)) {
    $owner = !_get('uid') && $uid ? true : false;
}

// Load nav
if ($owner) {
    $nav = Pi::api('nav', 'user')->getList($name);
} else {
    $nav = Pi::api('nav', 'user')->getList($name, $uid);

    $requestId = $uid == Pi::user()->getId() ? 0 : null;
    $level     = Pi::api('privacy', 'user')->getLevel($uid, $requestId);
    $user      = Pi::api('privacy', 'user')->filterProfile(
        $uid,
        $level,
        $user,
        'user'
    );
}

// Get module
$module = Pi::service('module')->current();

// Load quicklinks
$quicklink = Pi::api('quicklink', 'user')->getList();

// Check show nav
$showNav = isset($showNav) ? $showNav : 1;

// Check show setting
$showSetting = isset($showSetting) ? $showSetting : 1;
?>
<div class="clearfix user-avatar-header">
    <div class="user-info-right">
        <?php
        if (!empty($extra)) {
            echo '<span class="user-extra">' . $extra . '</span>';
        }
        ?>
        <?php if ($owner) { ?>
            <?php if ($module == 'user') { ?>
                <a class="btn btn-default"
                   href="<?php echo $this->url('user', ['controller' => 'profile', 'action' => 'view', 'uid' => $uid]); ?>">
                    <i class="fa fa-eye"></i>
                    <?php _e('View my profile'); ?>
                </a>
            <?php } ?>
            <?php if ($showSetting) { ?>
                <a class="btn btn-default"
                   href="<?php echo $this->url('user', ['controller' => 'account', 'action' => 'index']); ?>">
                    <i class="fa fa-cog"></i>
                    <?php _e('Settings'); ?>
                </a>
            <?php } ?>
            <?php if ($quicklink) { ?>
                <div class="dropdown inline">
                    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-magic"></i>
                        <?php _e('Quicklinks'); ?>
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <?php foreach ($quicklink as $item) { ?>
                            <li>
                                <a href="<?php echo $item['link']; ?>" title="<?php echo $item['title']; ?>"
                                   target="_blank">
                                    <?php
                                    if ($item['icon']) {
                                        echo sprintf('<i class="fa %s"></i>', $item['icon']);
                                    }
                                    ?>
                                    <?php echo $item['title']; ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            <?php } ?>
        <?php } else { ?>
            <?php if (Pi::user()->getId() == $uid && $module == 'user') { ?>
                <a class="btn btn-default"
                   href="<?php echo $this->url('user', ['controller' => 'profile', 'action' => 'index']); ?>">
                    <i class="fa fa-edit"></i>
                    <?php _e('Manage my profile'); ?>
                </a>
            <?php } ?>
            <?php if (Pi::user()->getId() != $uid && Pi::service('module')->isActive('message')) { ?>

                <?php if (!Pi::user()->getId()) { ?>
                    <button class="btn btn-default"
                            data-redirect="<?php echo $this->url('default', ['module' => 'message', 'controller' => 'index', 'action' => 'send', 'uid' => $uid]); ?>"
                            href="<?php echo (Pi::user()->config('enable_modal')) ? '#' : $this->url('default', ['module' => 'message', 'controller' => 'index', 'action' => 'send', 'uid' => $uid]); ?>"
                            <?php if (Pi::user()->config('enable_modal')) : ?>data-action="login" data-toggle="modal"
                            data-target="#loginRegisterModal"<?php endif; ?>
                    >
                        <i class="fa fa-envelope"></i>
                        <?php _e('Send message'); ?>
                    </button>
                <?php } else { ?>
                    <a class="btn btn-default"
                       href="<?php echo $this->url('default', ['module' => 'message', 'controller' => 'index', 'action' => 'send', 'uid' => $uid]); ?>">
                        <i class="fa fa-envelope"></i>
                        <?php _e('Send message'); ?>
                    </a>
                <?php } ?>
            <?php } else { ?>
                <a class="btn btn-default disabled">
                    <i class="fa fa-envelope"></i>
                    <?php _e('Send message'); ?>
                </a>
            <?php } ?>
        <?php } ?>
    </div>
    <div class="inline user-info-left">
        <div class="pull-left <?php if (!$owner) { ?>border-radius<?php } ?>">
            <?php echo Pi::avatar()->get($uid, 'xlarge', _escape($user['name'])); ?>
        </div>
        <?php if ($owner) { ?>
            <a class="user-avatar-upload"
               href="<?php echo $this->url('user', ['controller' => 'avatar', 'action' => 'index']); ?>">
                <?php _e('Change avatar'); ?>
            </a>
        <?php } ?>
    </div>
    <div class="inline user-info-center">
        <h1 class="user-name"><?php echo _escape($user['name']); ?></h1>
        <?php if (!empty($user['time_activated'])) { ?>
            <div style="margin-top: 10px;">
                <?php _e('Member since'); ?>
                <?php echo $user['time_activated']; ?>
            </div>
        <?php } ?>
        <?php if (!empty($user['gender'])) { ?>
            <div style="margin-top: 5px;">
                <?php _e('Gender:'); ?>
                <?php echo _escape($user['gender']); ?>
            </div>
        <?php } ?>
        <?php if (!empty($user['birthdate'])) { ?>
            <div style="margin-top: 5px;">
                <?php _e('Birthdate:'); ?>
                <?php echo _escape($user['birthdate']); ?>
            </div>
        <?php } ?>
        <?php if (!empty($user['city'])) { ?>
            <div style="margin-top: 5px;">
                <?php echo _escape($user['city']); ?>
                <?php if (!empty($user['country'])) { ?>
                    (<?php echo _escape($user['country']); ?>)
                <?php } ?>
            </div>
        <?php } ?>

    </div>
</div>
<?php if ($showNav) { ?>
    <ul class="nav nav-tabs">
        <?php
        $maxItem = 7;
        $items   = $nav['items'];
        $length  = count($items);
        $index   = 0;
        for ($i = 0; $i < $length; $i++) {
            if ($items[$i]['name'] == $nav['cur']) {
                $index = $i;
                break;
            }
        }
        $isHighlight = $length > $maxItem && $index > $maxItem - 1 ? true : false;
        if ($isHighlight) {
            for ($i = 0; $i < $maxItem - 1; $i++) {
                $list[] = $items[$i];
            }
            $list[] = $items[$index];
            for ($i = $maxItem - 1; $i < $length; $i++) {
                if ($i != $index) {
                    $list[] = $items[$i];
                }
            }
            $index = $maxItem - 1;
        } else {
            $list = $items;
        }

        /* Cur nav item order < $maxItem - 1 */
        for ($i = 0; $i < $maxItem; $i++) {
            if ($i >= $length) {
                break;
            }
            $item = $list[$i];
            ?>
            <li class="<?php echo $i == $index ? 'active' : ''; ?>">
                <a href="<?php echo $item['url']; ?>">
                    <?php
                    if ($item['icon']) {
                        echo '<i class="fa ' . $item['icon'] . '"></i> ';
                    }
                    echo _escape($item['title']);
                    if (isset($item['count'])) {
                        echo ' (' . $item['count'] . ')';
                    }
                    ?>
                </a>
            </li>
        <?php }
        if ($length > $maxItem) {
            ?>
            <li class="dropdown">
                <a data-toggle="dropdown" href="#">
                    <?php _e('More'); ?>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <?php for ($i = $maxItem; $i < $length; $i++) {
                        $item = $list[$i]; ?>
                        <li>
                            <a href="<?php echo $item['url']; ?>">
                                <?php
                                if ($item['icon']) {
                                    echo '<i class="fa ' . $item['icon'] . '"></i> ';
                                }
                                echo _escape($item['title']);
                                ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </li>
        <?php } ?>
    </ul>
<?php } ?>
