<div class="span3">
    <img src="<?php echo Pi::service('user')->avatar('medium'); ?>">
</div>
<div class="span6">
    <ul class="unstyled">
        <li><?php echo $this->escape($user['name']); ?></li>
        <li><?php echo $this->escape($user['gender']);?></li>
        <li><?php echo $this->escape($user['birthdate']); ?></li>
        <li><?php echo __('Profile completion: ') . $this->escape($user['completion']); ?></li>
    </ul>
</div>
<div>
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'index')); ?>"><?php _e('Homepage');?></a>
        </li>
        <li><a href="#"><?php _e('Profile'); ?></a></li>
        <li><a href="#"><?php _e('Activity'); ?></a></li>
    </ul>
    <?php foreach ($timeline as $item) { ?>
    <div>
        <ul class="inline">
            <li><?php echo $this->escape($item['timeline']['title']);?></li>
            <li><?php echo $this->escape($item['time']); ?></li>
        </ul>
        <p><?php echo $this->escape($item['message']);?></p>
    </div>
    <?php } ?>
</div>