<!-- Side nav -->
<div class="span3">
    <ul class="nav nav-list">
        <li class="nav-header"><?php _e('Account settings');?></li>
        <li>
            <a href="<?php echo $this->url('default', array('controller' => 'account', 'action' => 'index'));?>">
                <?php _e('Basic info')?>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url('default', array('controller' => 'password', 'action' => 'index')); ?>">
                <?php _e('Change password');?>
            </a>
        </li>
        <li class="divider"></li>
        <li><a href="#"><?php _e('Avatar settings');?></a></li>
        <li class="divider"></li>
        <li class="nav-header"><?php _e('Profile settings');?></li>
        <?php  foreach ($groups as $name => $group) { ?>
        <li class="<?php echo  $curGroup == $name ? 'active' : ''; ?>">
            <a href="<?php echo $group['link']; ?>">
                <?php echo $this->escape($group['title']); ?>
            </a>
        </li>
        <?php } ?>
        <li class="divider"></li>
        <li><a href="#"><?php _e('Privacy settings'); ?></a></li>
        <li class="divider"></li>
    </ul>
</div>
<div class="span9">
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>
<?php include $this->templateComponent('form'); ?>
</div>