<?php
    $this->css($this->assetModule('script/front.css'));
?>
<?php include '_user-media.phtml'; ?>
<div>
    <div>
        <?php foreach ($profileGroup as $group) {?>
        <div class="clearfix user-legend">
            <h4 class="user-legend-title"><?php echo $this->escape($group['title']);?></h4>
            <?php
                if ($group['compound']) {
                    $editUrl = $this->url('', array('controller' => 'profile', 'action' => 'edit.compound', 'group' => $group['name']));
                } else {
                    $editUrl = $this->url('', array('controller' => 'profile', 'action' => 'edit.profile', 'group' => $group['name']));
                }
            ?>
            <a class="btn user-legend-edit" href="<?php echo $editUrl; ?>">
                <i class="icon-pencil"></i>
                <?php _e('Edit'); ?>
            </a>
            <div class="user-legend-linea"></div>
        </div>
        <div class="user-field">
        <?php
            foreach ($group['fields'] as $key => $field) {
                echo '<dl class="dl-horizontal user-field-dl">';
                foreach ($field as $value) {
                    echo sprintf('<dt>%s<dd>%s', 
                        $value['title'],
                        $value['value'] ? : '<em class="muted">Unfiled</em>'
                    );
                }
                echo '</dl>';
            }
        ?>
        </div>
        <?php } ?>
    </div>
</div>