<?php if (!(isset($result) && $result['status'])) {
    echo sprintf('<h2 class="page-header">%s</h2>',
        __('Register')
    );

    if (isset($result)) {
        echo sprintf('<div class="alert %s"><button class="close">&times;</button>%s</div>',
            'alert-error',
            $result['message']);
    }
    
    include $this->templateComponent('form');
} else { ?>
    <h2 class="page-header"><?php _e('Register Activation'); ?></h2>
    <div class="span12">
        <div class="span8">
            <p>A register link has been sent to your email</p>
            <p>Please check it to finish regestion in 24 hours</p>
        </div>
        <div class="span4">
            <p>Get no email?</p>
            <ol>
                <li>Wait a few minutes</li>
                <li>Check your email rubbish</li>
                <li class="user-js-reactivate"><a class="user-js-reactivate-link" href="javascript:;">Resend a email</a><span style="margin-left: 20px;" class="user-js-reactivate-message"></span></li>
            </ol>
        </div>
    </div>

    <script>
        (function($) {
            var app = {
                options: {},

                $: function(selector) {
                    return this.$el.find(selector);
                },

                init: function(opts) {
                    $.extend(this.options, opts);
                    this.cacheElements();
                    this.bindEvents();
                },

                cacheElements: function() {
                    this.$el = $('.user-js-reactivate');
                    this.$reactivateLink = this.$('.user-js-reactivate-link');
                    this.$reactivateMessage = this.$('.user-js-reactivate-message');
                },

                bindEvents: function() {
                    this.$reactivateLink.on('click', $.proxy(this.reactivateAction, this));
                },

                reactivateAction: function(e) {
                    e.preventDefault();

                    $.getJSON(this.options.reactivateUrl, $.proxy(function(result) {
                        this.renderReactivateMessage(result.message);
                    }, this));
                },

                renderReactivateMessage: function(message) {
                    this.$reactivateMessage.text('( ' + message + ' )').hide().fadeIn();
                }
            };

            this.userRegisterReactivate = function(opts) {
                app.init(opts);
            }
       })(jQuery);

        userRegisterReactivate({
            reactivateUrl: '<?php echo $this->url('', array('controller' => 'register', 'action' => 'reactivate', 'uid' => $result['uid']));?>'
        });
    </script>
<?php } ?>
