<?php if (!(isset($result) && $result['status'])) {
    echo sprintf(
        '<h2 class="page-header">%s</h2>',
        __('Register sitename')
    );

    if (isset($result)) {
        echo sprintf(
            '<div class="alert %s"><a href="#" data-dismiss="alert" class="close">&times;</a>%s</div>',
            'alert-error',
            $result['message']
        );
    }
    
    include $this->templateComponent('form');
} else { ?>
    <h2 class="page-header"><?php _e('Register sitename'); ?></h2>
    <div class="span12">
        <div class="span8">
            <p><?php _e('An activation link has been sent to your email'); ?></p>
            <p><?php _e('Please check it to finish registration in 24 hours'); ?></p>
        </div>
        <div class="span4">
            <p><?php _e('Get no email'); ?>?</p>
            <ol>
                <li><?php _e('Wait a few minutes'); ?></li>
                <li><?php _e('Check your email rubbish'); ?></li>
                <li class="user-js-reactivate"><a class="user-js-reactivate-link" href="javascript:;"><?php _e('Resend a email'); ?></a><span style="margin-left: 20px;" class="user-js-reactivate-message"></span></li>
            </ol>
        </div>
    </div>

    <script>
        (function($) {
            var app = {
                options: {},

                $: function(selector) {
                    return this.$el.find(selector);
                },

                init: function(opts) {
                    $.extend(this.options, opts);
                    this.cacheElements();
                    this.bindEvents();
                },

                cacheElements: function() {
                    this.$el = $('.user-js-reactivate');
                    this.$reactivateLink = this.$('.user-js-reactivate-link');
                    this.$reactivateMessage = this.$('.user-js-reactivate-message');
                },

                bindEvents: function() {
                    this.$reactivateLink.on('click', $.proxy(this.reactivateAction, this));
                },

                reactivateAction: function(e) {
                    e.preventDefault();

                    $.getJSON(this.options.reactivateUrl, $.proxy(function(result) {
                        if (result.status) {
                            this.renderReactivateMessage('<?php _e('Alreaday sent'); ?>');
                        } else {
                            this.renderReactivateMessage(result.message);
                        }
                        
                    }, this));
                },

                renderReactivateMessage: function(message) {
                    this.$reactivateMessage.text('( ' + message + ' )').hide().fadeIn();
                }
            };

            this.userRegisterReactivate = function(opts) {
                app.init(opts);
            }
       })(jQuery);

        userRegisterReactivate({
            reactivateUrl: '<?php echo $this->url('', array('controller' => 'register', 'action' => 'reactivate', 'uid' => $result['uid']));?>'
        });
    </script>
<?php } ?>
