<?php $this->headMeta('noindex', 'robots'); ?>
    <div class="page-header">
        <h1><?php _e('Resend activation email.'); ?></h1>
    </div>
<?php
if (!empty($result)) {
    echo sprintf(
        '<div class="alert %s">%s<button data-dismiss="alert" class="close" type="button">&times;</button></div>',
        $result['status'] ? 'alert-success' : 'alert-error',
        $result['message']
    );
}
?>
<?php if (!empty($form)) {
    echo $this->form($form);
} ?>