<h2 class="page-header"><?php echo _escape($title); ?></h2>

<?php if ($type == 'register') { ?>
<p>
    <?php _e('A link for activation has been sent to you. Please check it in 24 hours.'); ?>
</p>
<p>
    <a href="<?php echo $this->url('', array('controller' => 'register', 'action' => 'reactivate', 'uid' => $data['uid'])); ?>">
        <?php _e('Resend activation email.'); ?>
    </a>
</p>
<?php } ?>