<?php
/**
 * Pi Engine (http://pialog.org)
 *
 * @link            http://code.pialog.org for the Pi Engine source repository
 * @copyright       Copyright (c) Pi Engine http://pialog.org
 * @license         http://pialog.org/license.txt BSD 3-Clause License
 */

namespace Module\Demo\Controller\Front;

use Pi;
use Pi\Mvc\Controller\ActionController;

/**
 * Class for user activity fetching
 *
 */
class ActivityController extends ActionController
{
    public function indexAction()
    {
        return 'Demo for external user activity.';
    }

    public function getAction()
    {
        $uid = _get('uid') ?: Pi::user()->getId();
        $data = array(
            'uid'       => $uid,
            'title'     => 'Demo activity with template',
            'content'   => sprintf(
                'Demo activity contents generated by module %s.',
                $this->getModule()
            )
        );

        return $data;
    }
}
