<div class="clearfix">
    <?php if (!empty($nav)) { ?>
    <div class="col-md-2">
        <ul class="nav nav-pills">
        <?php foreach ($nav as $id => $item) { ?>
            <li<?php if (!empty($item['active'])) { echo ' class="active"'; } ?>>
                <a href="<?php echo $item['url']; ?>"><?php echo _escape($item['title']); ?></a>
            </li>
        <?php } ?>
        </ul>
    </div>
    <div class="col-md-10">
    <?php } ?>
    <?php if ('phtml' == $markup && $content) { ?>
        <div class="article-header page-header">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
        <div class="article-body">
            <?php include $this->template('./' . $content); ?>
        </div>
        <div class="article-footer">
            <?php if ($config['social_sharing']) {
                $items = array(
                    'email',
                    'facebook',
                    'twitter',
                    'gplus',
                );
                echo $this->socialSharing($items, $this->escape($title), $this->escape($url));
            } ?>
        </div>
    <?php } else {  ?>
        <div class="article-header page-header">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
        <div class="article-body clearfix">
            <?php echo $content; ?> 
        </div>
        <div class="article-footer">
            <?php if ($config['social_sharing']) {
                $items = array(
                    'email',
                    'facebook',
                    'twitter',
                    'gplus',
                );
                echo $this->socialSharing($items, $this->escape($title), $this->escape($url));
            } ?>
        </div>
    <?php } ?>
    <?php if (!empty($nav)) { ?>
    </div>
    <?php } ?>
</div>