<ul class="nav nav-tabs">
    <li class="<?php echo $controller == 'edit' && $action == 'index' ? 'active' : ''?>">
        <a href=""><?php _e('User info'); ?></a>
    </li>
    <li class="<?php echo $controller == 'avatar' ? 'active' : ''?>">
        <a href=""><?php _e('Avatar'); ?></a>
    </li>
    <?php  foreach ($groups as $key => $group) { ?>
        <li class="<?php  echo $cur_group == $key ? 'active' : ''; ?>">
            <a href="<?php echo $group['link']; ?>">
                <?php echo _escape($group['title']); ?>
            </a>
        </li>
    <?php } ?>
</ul>