<ul class="nav nav-tabs">
    <li class="<?php echo $curNav == 'active' ? 'active' : ''; ?>">
        <a href="">
            <?php _e('Activated'); ?>
        </a>
    </li>
    <li class="<?php echo $curNav == 'pending' ? 'active' : ''; ?>">
        <a href="#">
            <?php _e('Pending');?>
        </a>
    </li>
    <li class="<?php echo $curNav == 'add' ? 'active' : ''; ?>">
        <a href="#">
            <?php _e('Add new'); ?>
        </a>
    </li>
</ul>