<ul class="nav nav-tabs">
    <li class="<?php echo $cur_nav == 'activated' ? 'active' : ''; ?>">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>">
            <?php _e('Activated'); ?>
        </a>
    </li>
    <li class="<?php echo $cur_nav == 'pending' ? 'active' : ''; ?>">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'pending')); ?>">
            <?php _e('Pending');?>
        </a>
    </li>
    <li class="<?php echo $cur_nav == 'add' ? 'active' : ''; ?>">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'add.user')); ?>">
            <?php _e('Add new'); ?>
        </a>
    </li>
</ul>