<ul class="nav nav-tabs">
    <li class="<?php echo $action == 'index' ? 'active' : ''; ?>">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>">
            <?php _e('Activated'); ?>
        </a>
    </li>
    <li class="<?php echo $action == 'activated' ? 'active' : ''; ?>">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'pending')); ?>">
            <?php _e('Pending');?>
        </a>
    </li>
    <li class="<?php echo $action == 'pending' ? 'active' : ''; ?>">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'add.user')); ?>">
            <?php _e('Add new'); ?>
        </a>
    </li>
    <li class="<?php echo $action == 'search' ? 'active' : ''; ?>">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'add.user')); ?>">
            <?php _e('Add new'); ?>
        </a>
    </li>
    <li class="<?php echo $action == 'add.user' ? 'active' : ''; ?>">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'add.user')); ?>">
            <?php _e('Add new'); ?>
        </a>
    </li>
</ul>