<?php
	$this->bootstrap();
	$this->css($this->assetModule('script/admin.css'));
?>
<ul class="nav nav-tabs">
	<li class="<?php if ($action == 'index') { echo 'active'; } ?>">
		<a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'index')); ?>">
			<?php _e('Profile field'); ?>
		</a>
	<li class="<?php if ($action == 'dressup') { echo 'active'; } ?>">
		<a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'dressup')); ?>">
			<?php _e('Profile dress up'); ?>
		</a>
	<li class="<?php if ($action == 'privacy') { echo 'active'; } ?>">
		<a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'privacy')); ?>">
			<?php _e('Field Privacy'); ?>
		</a>
</ul>