<ul class="nav nav-tabs">
	<li class="<?php if ($action == 'index') { echo 'active'; } ?>">
		<a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'index')); ?>">
			<?php _e('Profile field'); ?>
		</a>
	<li class="<?php if ($action == 'display') { echo 'active'; } ?>">
		<a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'display')); ?>">
			<?php _e('Field display'); ?>
		</a>
	<li class="<?php if ($action == 'privacy') { echo 'active'; } ?>">
		<a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'privacy')); ?>">
			<?php _e('Field Privacy'); ?>
		</a>
</ul>