<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add CGU'); ?>"
           href="<?php echo $this->url('', array('controller' => 'cgu', 'action' => 'update')); ?>"><i
                    class="fa fa-folder-open"></i> <?php _e('Add CGU'); ?></a>
    </p>
    <h3><?php _e('CGU list'); ?></h3>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Version'); ?></th>
            <th><?php _e('Filename'); ?></th>
            <th><?php _e('Created at'); ?></th>
            <th><?php _e('Active at'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $cgu) { ?>
            <tr>
                <td>
                    <span class="label label-info"><?php echo $cgu['id']; ?></span>
                </td>
                <td><?php echo $this->escape($cgu['version']); ?></td>
                <td><?php echo $this->escape($cgu['filename']); ?></td>
                <td><?php echo $this->escape($cgu['created_at']); ?></td>
                <td><?php echo $this->escape($cgu['active_at']); ?></td>
                <td>
                    <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', array('action' => 'update', 'id' => $cgu['id'])); ?>">
                        <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                    </a>

                    <a class="btn btn-danger btn-xs" title="<?php _e('Remove'); ?>"
                       href="<?php echo $this->url('', array('action' => 'remove', 'id' => $cgu['id'])); ?>">
                        <i class="fa fa-edit"></i> <?php _e('Remove'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>