<div class="row">
    <?php foreach ($forms as $set => $form) { ?>
    <div class="pi-widget span6">
        <div class="clearfix pi-widget-header" style="margin-bottom: 20px;">
            <button type="button" class="close" ng-click="deleteAction()">&times;</button>
        </div>
        <form method="post" class="form-horizontal" name="<?php echo $form->getName(); ?>" 
              ng-submit="submit('<?php echo $form->getName(); ?>')">
            <?php
            $form->prepare();
            $elements = $form->elementList();
            echo $this->form()->openTag($form);
            foreach ($elements['active'] as $element) {
                echo sprintf('
                    <div class="control-group" ng-class="{error: formError%s.%s}">
                        <label class="control-label" style="width: 140px;">%s</label>
                        <div class="controls" style="margin-left: 160px;">
                            %s
                            <span class="help-inline">{{formError%s.%s}}</span>
                        </div>
                    </div>',
                    $set,
                    $element->getName(),
                    $element->getOption('label'),
                    $this->formElement($element),
                    $set,
                    $element->getName());
            }
            foreach ($elements['hidden'] as $element) {
                echo $this->formElement($element);
            }
            echo sprintf('<div class="controls controls-action" style="margin-left: 160px;">%s</div>',
                $this->formElement($elements['submit']));
            ?>
        </form>
    </div>
    <?php } ?>
</div>