<ul class="nav nav-tabs">
    <li>
        <a href="<?php echo $this->url('', array('controller' => 'form', 'action' => 'register')); ?>">
            <?php echo _a('Register form'); ?>
        </a>
    </li>
    <li class="active">
        <a href="<?php echo $this->url('', array('controller' => 'form', 'action' => 'profile.complete')); ?>">
            <?php echo _a('Profile complete form'); ?>
        </a>
    </li>
</ul>
<?php include $this->templateComponent('form'); ?>