<ul class="nav nav-tabs">
    <li>
        <a href="<?php echo $this->url('', array('controller' => 'form', 'action' => 'register')); ?>">
            <?php _e('Register form'); ?>
        </a>
    </li>
    <li class="active">
        <a href="<?php echo $this->url('', array('controller' => 'form', 'action' => 'complete.profile')); ?>">
            <?php _e('Complete profile form'); ?>
        </a>
    </li>
</ul>
<?php include $this->templateComponent('form'); ?>