<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="<?php echo $this->url('', ['controller' => 'form', 'action' => 'register']); ?>">
            <?php echo _a('Register form'); ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="<?php echo $this->url('', ['controller' => 'form', 'action' => 'profile.complete']); ?>">
            <?php echo _a('Profile complete form'); ?>
        </a>
    </li>
</ul>
<?php echo $this->form($form); ?>