<?php include "_user-nav.phtml";?>
<form class="form-inline" method="post" name="select-search">
    <select name="front-role">
        <?php foreach ($front_role as $key => $value) { ?>
        <option value="<?php echo $key?>"><?php echo $value?></option>
        <?php } ?>
    </select>

    <select name="admin-role">
        <?php foreach ($admin_role as $key => $value) { ?>
        <option value="<?php echo $key?>"><?php echo $value?></option>
        <?php } ?>
    </select>

    <select name="register-time">
        <option value=""><?php _e('Register date'); ?></option>
        <option value="<?php echo 'today'; ?>"><?php _e('Today'); ?></option>
        <option value="<?php echo 'last-week'; ?>"><?php _e('Last week'); ?></option>
        <option value="<?php echo 'last-month'; ?>"><?php _e('Last month'); ?></option>
        <option value="<?php echo 'last-3-month'; ?>"><?php _e('Last 3 month'); ?></option>
        <option value="<?php echo 'last-6-month'; ?>"><?php _e('Last 6 month'); ?></option>
        <option value="<?php echo 'last-year'; ?>"><?php _e('Last year');?></option>
    </select>
</form>

<form class="form-inline" method="post" name="spotlight">
    <input type="text" name="key">
    <input type="submit" value="<?php _e('Search');?>">
    <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'search'));?>"><?php _e('Advance search');?></a>
</form>

<form name="user-operate">
    <div class="form-inline">
        <input type="checkbox">
        <a class="btn" href=""><?php _e('Activate'); ?></a>
        <a class="btn" href=""><?php _e('Delete'); ?></a>
    </div>
    <div><?php echo $count?><?php _e('Members'); ?></div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th><?php _e('Username'); ?></th>
            <th><?php _e('Display name'); ?></th>
            <th><?php _e('Email'); ?></th>
            <th><?php _e('Active'); ?></th>
            <th><?php _e('Front role'); ?></th>
            <th><?php _e('Admin role'); ?></th>
            <th><?php _e('Register ip'); ?></th>
            <th><?php _e('Register time'); ?></th>
            <th><?php _e('Uid'); ?></th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($users as $user) { ?>
        <tr>
            <td>
                <input type="checkbox" value="<?php echo $user['id']; ?>" name="check-one">
            </td>
            <td>
                <a href="<?php echo $this->url('', array('controller' => 'profile', 'action' => 'index', 'uid' => $user['id']));?>">
                    <?php echo $this->escape($user['identity'])?>
                </a>
            </td>
            <td>
                <?php echo $this->escape($user['name']); ?>
            </td>
            <td>
                <?php echo $this->escape($user['email']); ?>
            </td>
            <td><?php vd($user['time_activated']); ?>
                <input type="checkbox" <?php echo $user['time_activated'] ? 'checked' : ''?> >
            </td>
            <td>
                <select>
                    <option value="<?php echo $user['front_role'] ?: 'none';?>">
                        <?php echo $user['front_role'] ? $this->escape($front_role[$user['front_role']]) : __('Front role');?>
                    </option>
                    <?php foreach ($front_role as $col => $val) { ?>
                        <?php if ($col != $user['front_role']) { ?>
                            <option value="<?php echo $col; ?>"><?php echo $this->escape($val); s?></option>
                        <?php } ?>
                    <?php } ?>
                </select>
            </td>
            <td>
                <select>
                    <option value="<?php echo $user['admin_role'] ?: 'none'; ?>">
                        <?php echo $user['admin_role'] ? $this->escape($admin_role[$user['admin_role']]) : __('Admin role'); ?>
                    </option>
                    <?php foreach ($admin_role as $col => $val) { ?>
                        <?php if ($col != $user['admin_role']) { ?>
                            <option value="<?php echo $col; ?>"><?php echo $this->escape($val); ?></option>
                        <?php } ?>
                    <?php } ?>
                </select>
            </td>
            <td>
                <?php echo $this->escape($user['register_ip']); ?>
            </td>
            <td>
                <?php echo $this->escape(_date($user['time_created'])); ?>
            </td>
            <td>
                <?php echo $this->escape($user['id']); ?>
            </td>
        </tr>
            <?php } ?>
        </tbody>
    </table>
</form>

<?php if ($paginator) {?>
<?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
<?php } ?>
