<?php include "_user-nav.phtml";?>
<h2>Advanced search result</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <th><?php _e('Username'); ?></th>
        <th><?php _e('Display name'); ?></th>
        <th><?php _e('Email'); ?></th>
        <th><?php _e('Active'); ?></th>
        <th><?php _e('Enable'); ?></th>
        <th><?php _e('Activated'); ?></th>
        <th><?php _e('Front role'); ?></th>
        <th><?php _e('Admin role'); ?></th>
        <th><?php _e('Register time'); ?></th>
        <th><?php _e('Register ip'); ?></th>
        <th><?php _e('Uid'); ?></th>
    </tr>
    </thead>
    <tbody>

    <?php foreach ($users as $user) {?>
        <tr>
            <td>
                <a href="<?php echo $this->url('user', array('controller' => 'profile', 'action' => 'index', 'uid' => $user['id']));?>">
                    <?php echo _escape($user['identity'])?>
                </a>
            </td>
            <td>
                <?php echo _escape($user['name']); ?>
            </td>
            <td>
                <?php echo _escape($user['email']); ?>
            </td>
            <td>
                <?php echo $user['active'] ? 'yes' : 'no'; ?>
            </td>
            <td>
                <?php echo $user['time_disable'] ? 'disable' : 'enable'?>
            </td>
            <td>
                <?php echo $user['time_activated'] ? 'activated' : 'pending'?>
            </td>
            <td>
                <?php echo _escape($user['front_role']); ?>
            </td>
            <td>
                <?php echo _escape($user['admin_role']); ?>
            </td>
            <td>
                <?php echo _escape(_date($user['time_created'])); ?>
            </td>
            <td>
                <?php echo _escape($user['ip_register']); ?>
            </td>
            <td>
                <?php echo _escape($user['id']); ?>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php if ($paginator) {?>
    <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
<?php } ?>
