<?php include "_user-nav.phtml";?>
<?php
    d($admin_role);
    d($front_role);
    d($users);
?>
<div ng-controller="userListCtr" ng-app="userListModule">
    <form class="form-inline user-list-form">
        <select class="input-medium">
            <option value=""><?php _e('Active State'); ?></option>
            <option value="enable"><?php _e('Enable'); ?></option>
            <option value="disable"><?php _e('Disable'); ?></option>
        </select>
        <select class="input-medium">
            <option value=""><?php _e('Enable State'); ?></option>
            <option value="enable"><?php _e('Enable'); ?></option>
            <option value="disable"><?php _e('Disable'); ?></option>
        </select>
        <select class="input-medium" ng-model="front_role" ng-options="key as value for (key, value) in frontRoles">
            <option value=""><?php _e('Front role'); ?></option>
        </select>
        <select class="input-medium" ng-model="admin_role" ng-options="key as value for (key, value) in adminRoles">
            <option value=""><?php _e('Admin role'); ?></option>
        </select>
        <select class="input-medium" ng-model="register_date">
            <option value=""><?php _e('Register date'); ?></option>
            <option value="today"><?php _e('Today'); ?></option>
            <option value="last_week"><?php _e('Last week'); ?></option>
            <option value="last-month"><?php _e('Last month'); ?></option>
            <option value="last_3_month"><?php _e('Last 3 month'); ?></option>
            <option value="last_6_month"><?php _e('Last 6 month'); ?></option>
            <option value="last_year"><?php _e('Last year');?></option>
        </select>
        <input type="text" placeholder="<?php _e('Username/Email'); ?>" class="input-medium">
        <button class="btn" ng-click="searchAction()"><?php _e('Apply'); ?></button>
    </form>
    <div class="clearfix user-list-action">
        <strong class="pull-right">{{count}} <?php _e('members'); ?></strong>
        <input type="checkbox" style="margin-right: 6px;"
               ng-model="allChecked" ng-click="markAll(allChecked)">
        <div class="btn-group">
            <button class="btn">
                <i class="icon-ok-sign"></i>
                <?php _e('Activate'); ?>
            </button>
            <button class="btn">
                <i class="icon-ok text-success"></i>
                <?php _e('Enable'); ?>
            </button>
            <button class="btn">
                <i class="icon-power-off"></i>
                <?php _e('Disable'); ?>
            </button>
            <button class="btn">
                <i class="icon-remove text-error"></i>
                <?php _e('Delete'); ?>
            </button>
        </div>
        <tr>
            <th>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th width="1%">
                <th><?php _e('Username'); ?>
                <th><?php _e('Display name'); ?>
                <th><?php _e('Email'); ?>
                <th width="5%"><?php _e('Active'); ?>
                <th width="5%"><?php _e('Enable'); ?>
                <th width="5%"><?php _e('Activated'); ?>
                <th width="10%"><?php _e('Front role'); ?>
                <th width="10%"><?php _e('Admin role'); ?>
                <th width="12%"><?php _e('Register time'); ?>
                <th><?php _e('Uid'); ?>
        <tbody>
            <tr ng-repeat="user in users">
                <td>
                    <input type="checkbox" ng-model="user.checked">
                <td>{{user.identity}}
                <td>{{user.name}}
                <td>{{user.email}}
                <td>
                    <i ng-class="{'icon-ok text-success': user.active, 'icon-remove text-error': !user.active }">
                    </i>
                <td>
                    <button class="btn" ng-click="enableAction(user)">
                        <i ng-class="{'icon-ok text-success': !user.time_disabled, 'icon-remove text-error': user.time_disabled }">
                        </i>
                    </button>
                <td>
                    <i ng-if="user.time_activated" class="icon-ok text-success"></i>
                    <button ng-if="!user.time_activated" class="btn" ng-click="activeAction(user)">
                        <i class="icon-remove text-error"></i>
                    </button>
                <td>
                    <select ng-model="user.front_role" ng-options="key as value for (key, value) in frontRoles"
                            ng-change="roleAction(user, 'front')">
                    </select>
                <td>
                    <select ng-model="user.admin_role" ng-options="key as value for (key, value) in adminRoles"
                            ng-change="roleAction(user, 'admin')">
                        <option value=""><?php _e('None'); ?></option>
                    </select>
                <td>
                    {{user.time_created | date: 'yyyy-MM-dd HH:mm'}}
                <td>
                    {{user.id}}
    </table>
    <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
</div>
<style>
.user-list-form {
    border-bottom: 1px solid #ddd;
    padding-bottom: 15px;
    margin-bottom: 15px;
}
.user-list-action {
    margin-bottom: 10px;
    padding: 0 30px 0 8px;
}
</style>
<script src="<?php echo $this->assetModule('script/angular.js'); ?>"></script>
<script>
var userListModule = angular.module('userListModule', [], function($locationProvider) {
    $locationProvider.html5Mode(true);
});
userListModule.value('data', {
    users: <?php echo json_encode(array_values($users)); ?>,
    frontRoles: <?php echo json_encode($front_role); ?>,
    adminRoles:  <?php echo json_encode($admin_role); ?>,
    count: <?php echo $count; ?>
}).value('urlRoot', '<?php echo $this->url('', array('controller' => 'index', 'action' => 'var')); ?>'.replace(/var\/?$/, ''));

userListModule.controller('userListCtr', function($scope, $injector, $http, $location) {
    var data = $injector.get('data');
    var users = data.users;
    var urlRoot = $injector.get('urlRoot');
    var search = $location.search();


    angular.extend($scope, search);
    angular.extend($scope, data);

    $http.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded;charset=utf-8';
    $http.defaults.transformRequest = [function(d) {
        return $.param(d);
    }];
    //handler php data to js
    for (var i = 0, l = users.length; i < l; i++) {
        users[i].time_disabled *= 1000;
        users[i].time_created *= 1000;
        users[i].time_activated *= 1000;
        users[i].checked = 0;
        users[i].active = parseInt(users[i].active, 10);
    }
    $scope.markAll = function(checked) {
        angular.forEach(users, function(user) {
            user.checked = checked;
        });
    };
    $scope.enableAction = function(user) {
        if (user.time_disabled) {
            $http.post(urlRoot + 'enable', {
                ids: user.id 
            }).success(function(data) {
                if (data.status) {
                    user.time_disabled = 0;
                    if (user.time_activated) user.active = 1;
                }
            });
        } else {
            $http.post(urlRoot + 'disable', {
                ids: user.id 
            }).success(function(data) {
                if (data.status) {
                    user.time_disabled = 1;
                    user.active = 0;
                }
            });
        }
    };
    $scope.activeAction = function(user) {
        $http.post(urlRoot + 'active', {
            ids: user.id
        }).success(function(data) {
            if (data.status) {
                user.time_activated = 1;
                if (!user.time_disabled) user.active = 1;
            }
        });
    };
    $scope.roleAction = function(user, section) {
        var data = {
            uid: user.id,
            section: section
        };
        if (section == 'front') {
            data.role = user.front_role;
        } else {
            data.role = user.admin_role;
        }
        $http.post(urlRoot + 'setRole', data);
    }
    $scope.searchAction = function() {
        var ret = ['front_role', 'admin_role', 'register_date'];
        var search = {};
        for (var i = 0, l = ret.length; i < l; i++) {
            if ($scope[ret[i]]) {
                search[ret[i]] = $scope[ret[i]];
            }
        }
        location.search = $.param(search);
    };
});
</script>
