<?php
$this->angular(array(
    'angular-route.js',
    'pi.js',
));
?>
<div ng-app="userInquiryModule">
  <div pi-message="alert"></div>
  <div ng-view></div>
</div>
<script>
angular
    .module('userInquiryModule', ['ngRoute', 'pi'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('controller' => $controller)); ?>',
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
        t: {
            DISPLAYNAME: '<?php _e('Display name'); ?>',
            SEARCH: '<?php _e('Submit'); ?>',
            SEARCH_TEXT: '<?php _e('Inquire of user information via his ID, username, display name or email.'); ?>',
            USERNAME: '<?php _e('Username'); ?>',
            EMAIL: '<?php _e('Email'); ?>',
            ACTIVATION: '<?php _e('Activation'); ?>',
            ACTIVATED: '<?php _e('Activated'); ?>',
            NOTACTIVATED: '<?php _e('Not activated'); ?>',
            ENABLED: '<?php _e('Enabled'); ?>',
            DISABLED: '<?php _e('Disabled'); ?>',
            YES: '<?php _e('Yes'); ?>',
            ACCOUNT: '<?php _e('Account'); ?>',
            PROFILE: '<?php _e('Profile'); ?>',
            ENABLED: '<?php _e('Enabled'); ?>',
            EMPTY: '<?php _e('Unavailable'); ?>'
        }
    });
</script>
<script src="<?php echo $this->assetModule('admin/inquiry.js'); ?>"></script>
