<?php
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi.js',
    'pi-tabs.js',
));
?>
<div ng-app="userMaintenanceModule">
    <div pi-message="alert"></div>
    <div pi-nav-tabs></div>
    <div ng-view></div>
</div>
<script>
angular
  .module('userMaintenanceModule', ['ngRoute', 'pi', 'piTabs', 'ui.bootstrap'])
  .constant('config', {
    urlRoot: '<?php echo $this->url('', array('controller' => 'maintenance')); ?>',
    assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
    navTabs: [
      { text: '<?php _e('Stats'); ?>', href: '#!/stats' },
      { text: '<?php _e('User log'); ?>', href: '#!/logs' },
      { text: '<?php _e('Deleted users'); ?>', href: '#!/deleted' }
    ],
    t: {
      TODAY: '<?php _e('Today'); ?>',
      LAST_WEEK: '<?php _e('Last week'); ?>',
      LAST_MONTH: '<?php _e('Last month'); ?>',
      HISTORY: '<?php _e('History'); ?>',
      REGISTER_NUM: '<?php _e('Register num'); ?>',
      ACTIVATED_NUM: '<?php _e('Activated num'); ?>',
      PENDING_NUM: '<?php _e('Pending num'); ?>',
      TOP_10_IP: '<?php _e('Top 10 registered IP'); ?>',
      NONE_REGISTER: '<?php _e('None'); ?>',
      SORT_BY: '<?php _e('Sort by key:'); ?>',
      UID: '<?php _e('uid'); ?>',
      EDIT: '<?php _e('Edit'); ?>',
      VIEW_LOG: '<?php _e('View log'); ?>',
      USERNAME: '<?php _e('Username'); ?>',
      REGISTER_TIME: '<?php _e('Register time'); ?>',
      REGISTER_IP: '<?php _e('Register ip'); ?>',
      ACTIVATE_TIME: '<?php _e('Activated time'); ?>',
      LAST_LOGIN_TIME: '<?php _e('Last login time'); ?>',
      LAST_LOGIN_IP: '<?php _e('Last loin ip'); ?>',
      LOGIN_TIMES: '<?php _e('Login times'); ?>',
      SORT_BY: '<?php _e('Sort by:'); ?>',
      DELETE_ONE: '<?php _e('Are you sure to delete this user?'); ?>',
      DELETE_BATCH: '<?php _e('Are you sure to delete these users?'); ?>',
      DELETE_ALL: '<?php _e('Are you sure to delete all of these users?'); ?>',
      DELETE_TIME: '<?php _e('Deleted time'); ?>',
      IP_ADDRESS: '<?php _e('IP'); ?>',
      CLEAR: '<?php _e('Clear the users'); ?>',
      CLEAR_ALL: '<?php _e('CLear all deleted users'); ?>',
      NONE_USER: '<?php _e('No user matched your request.'); ?>'
    }
});
</script>
<?php $debug = 'production' == Pi::environment() ? '.min' : ''; ?>
<script src="<?php echo $this->assetModule('admin/maintenance' . $debug . '.js'); ?>"></script>