<ul class="nav nav-tabs">
    <li>
        <a href="<?php echo $this->url('', array('controller' => 'plugin', 'action' => 'timeline')); ?>">
            <?php _e('Timeline'); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url('', array('controller' => 'plugin', 'action' => 'activity')); ?>">
            <?php _e('Activity'); ?>
        </a>
    </li>
    <li class="active">
        <a href="<?php echo $this->url('', array('controller' => 'plugin', 'action' => 'quicklink')); ?>">
            <?php _e('Quicklin'); ?>
        </a>
    </li>
</ul>