<?php include '_user-profile-nav.phtml'; ?>
<div class="row-fluid">
	<div class="span7">
		<legend><?php _e('Basic field'); ?></legend>
		<table class="table table-hover user-table">
			<thead>
				<tr>
					<th width="2%">
					<th width="35%"><?php _e('Field title'); ?>
					<th width="8%"><?php _e('Display'); ?>
					<th width="8%"><?php _e('Search'); ?>
					<th width="8%"><?php _e('Editable'); ?>
					<th><?php _e('From module'); ?>
			<tbody>
				<?php foreach ($profile as $item) { ?>
				<tr>
					<td>
					<td>
						<i class="icon-list-alt icon-large"></i>
						<input type="text" value="<?php echo $item['title']; ?>" class="input-medium js-field-input"
							data-name='<?php echo $item['name']; ?>'>
					<td>
						<?php if ($item['is_display']) { ?>
						<i class="icon-ok icon-large text-success"></i>
						<?php } ?>
					<td>
						<?php if ($item['is_search']) { ?>
						<i class="icon-ok icon-large text-success"></i>
						<?php } ?>
					<td>
						<?php if ($item['is_edit']) { ?>
						<i class="icon-ok icon-large text-success"></i>
						<?php } ?>
					<td>
						<?php echo $item['module']; ?>
				<?php } ?>
		</table>
	</div>
	<div class="span5">
		<legend><?php _e('compound'); ?></legend>
		<table class="table table-hover user-table">
			<thead>
				<tr>
					<th width="2%">
					<th width="30%"><?php _e('Field title'); ?>
					<th><?php _e('From module'); ?>
			<tbody>
			<?php foreach ($compounds as $value) { ?>
				<tr>
					<td>
					<td>
						<i class="icon-list-alt icon-large"></i>
						<input type="text" value="<?php echo $value['title']; ?>" class="input-medium js-field-input"
							data-compound="<?php echo $value['compound']; ?>">
					<td>
						<?php echo $value['module']; ?>
				<?php foreach ($value['fields'] as $item) { ?>
				<tr>
					<td>
					<td>
						<input type="text" value="<?php echo $item['title']; ?>" style="margin-left: 48px;" 
							class="input-medium js-field-input" data-name="<?php echo $item['name']; ?>">
					<td>
				<?php } ?>
			<?php } ?>
		</table>
	</div>
</div>
<script src="<?php echo $this->assetModule('script/system-msg.js', 'system'); ?>"></script>
<script>
(function($) {
	var saveUrl = '<?php echo $this->url('', array('controller' => 'profile', 'action' => 'updateField')); ?>';
	var successMsg = '<?php _e('Data saved successfully'); ?>';
	var failMsg = '<?php _e('Data saved failed'); ?>';
	var inputs = $('.js-field-input');
	inputs.on('save', function() {
		var $this = $(this);
		$.post(saveUrl, {
			title: $.trim($this.val()),
			compound: $this.attr('data-compound'),
			name: $this.attr('data-name')
		}).done(function(res) {
			res = $.parseJSON(res);
			if (res.status) {
            	systemMessage.succ(successMsg);
          	} else {
            	systemMessage.fail(failMsg)
          	}
		});
	});
	inputs.blur(function() {
		$(this).trigger('save');
	}).keypress(function(e) {
		if (e.keyCode == 13) {
			$(this).trigger('save');
		}
	});
})(jQuery)
</script>