<?php
$this->jQuery('ui/jquery-ui-1.10.3.custom.js');
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi.js',
    'pi-dropdown.js',
    'pi-sortable.js'
));
?>
<div pi-nav-tabs></div>
<div ng-view></div>
<script>
angular
    .module('<?php echo $module; ?>', ['ngRoute', 'pi', 'ui.bootstrap', 'ui.sortable'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('controller' => $controller)); ?>',
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
        navTabs: [
            { text: '<?php echo _a('Profile field'); ?>', href: '#!/field' },
            { text: '<?php echo _a('Profile dress up'); ?>', href: '#!/dress' },
            { text: '<?php echo _a('Field privacy'); ?>', href: '#!/privacy' }
        ],
        t: {
           BASIC_FIELD: '<?php echo _a('Basic field'); ?>',
           BASIC_FIELD_DESC: '<?php echo _a('Raw filed provied by the user module,you can change the display title'); ?>',
           FIELD_TITLE: '<?php echo _a('Field title'); ?>',
           DISPLAY: '<?php echo _a('Display'); ?>',
           SEARCH: '<?php echo _a('Search'); ?>',
           EDITABLE: '<?php echo _a('Editable'); ?>',
           FORM_MODULE: '<?php echo _a('From module'); ?>',
           COMPOUND: '<?php echo _a('Compound'); ?>',
           COMPOUND_DESC: '<?php echo _a('Compound filed :Some fileds organized initially. Sub elements in the compound is directly displayed on the page,while the compound title is for programming'); ?>',
           PRIVACY_DESC: '<?php echo _a('Determine the default visible objects of the profile filed and which filed can be changed by the user self'); ?>',
           ADD_GROUP: '<?php echo _a('Add group'); ?>',
           FIELD_DISPLAY: '<?php echo _a('Field display on profile page'); ?>',
           BASIC_FIELD: '<?php echo _a('Basic field'); ?>',
           TITLE: '<?php echo _a('Title'); ?>',
           SAVE_TIP: '<?php echo _a('Data will not be saved before you click save button'); ?>',
           ADD_FIELD_TIP: '<?php echo _a('Click to select a group added in'); ?>',
           ADD_GROUP_TIP: '<?php echo _a('Click to added a group'); ?>',
           CANCEL: '<?php echo _a('Cancel'); ?>',
           SAVE: '<?php echo _a('Save'); ?>',
           LEAVE_CONFIRM: '<?php echo _a('You have made unsaved changes. Would you still like to leave this page?'); ?>',
           CHECK_GROUP: '<?php echo _a('Create a group before adding'); ?>'
        }
    });
</script>
<script src="<?php echo $this->assetModule('admin/profile.js'); ?>"></script>