<?php
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi.js'
));
?>
<div ng-app="userRoleModule">
    <div pi-message="alert"></div>
    <div ng-view style="width: 900px;"></div>
</div>
<script>
angular
    .module('userRoleModule', ['ngRoute', 'ui.bootstrap', 'pi'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('controller' => 'role')); ?>',
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
        t: {
            ADMIN_TITLE: '<?php _e('Admin roles'); ?>',
            FRONT_TITLE: '<?php _e('Front roles'); ?>',
            NAME: '<?php _e('Name'); ?>',
            TITLE: '<?php _e('Title'); ?>',
            USER_COUNT: '<?php _e('Users in role'); ?>',
            ACTION: '<?php _e('Action'); ?>',
            ROLE_TITLE: '<?php _e('Title'); ?>',
            SUBMIT: '<?php _e('Submit'); ?>',
            REQUIRED: '<?php _e('Required'); ?>',
            TYPE: '<?php _e('Type'); ?>',
            FRONT: '<?php _e('Front'); ?>',
            ADMIN: '<?php _e('Admin'); ?>',
            EDIT_TITLE: '<?php _e('Users in role'); ?>',
            UID_OR_IDENTITY: '<?php _e('User id or name'); ?>',
            USERS: '<?php _e('Users'); ?>',
            FIRST: '<?php _e('First'); ?>',
            UID: '<?php _e('User id'); ?>',
            USER_NAME: '<?php _e('User name'); ?>',
            DISPLAY_NAME: '<?php _e('Display name'); ?>',
            EMAIL: '<?php _e('Email'); ?>',
            ADD_USER: '<?php _e('Add user'); ?>',
            NONE_USERS: '<?php _e('None users in this role'); ?>'
        }
    });
</script>
<?php $debug = 'production' == Pi::environment() ? '.min' : ''; ?>
<script src="<?php echo $this->assetModule('admin/role' . $debug . '.js'); ?>"></script>