<?php
$this->angular(array(
    'angular-route.js',
    'angular-translate.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi-form.js'
));
?>
<div ng-view ng-app="systemRoleModule"></div>
<script>
var systemRoleModule = angular.module('systemRoleModule', ['ngRoute', 'pascalprecht.translate', 
    'ui.bootstrap', 'piForm']);
var systemRoleModuleConfig = {
    urlRoot: '<?php echo $this->url('', array('controller' => 'role')); ?>',
    assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
    t: {
        ADMIN_TITLE: '<?php _e('Admin roles'); ?>',
        ADMIN_ADD: '<?php _e('Add admin role'); ?>',
        FRONT_TITLE: '<?php _e('Front roles'); ?>',
        FRONT_ADD: '<?php _e('Add front role'); ?>',
        ROLE_ADD: '<?php _e('Add role'); ?>',
        DELETE: '<?php _e('Delete'); ?>',
        EDIT: '<?php _e('Edit permission'); ?>',
        NAME: '<?php _e('Name'); ?>',
        TITLE: '<?php _e('Title'); ?>',
        USER_COUNT: '<?php _e('Users in role'); ?>',
        STATUS: '<?php _e('Status'); ?>',
        ACTIVE: '<?php _e('Active'); ?>',
        ACTIVATED: '<?php _e('Activated'); ?>',
        INACTIVE: '<?php _e('Inactive'); ?>',
        ACTION: '<?php _e('Action'); ?>',
        ROLE_NAME: '<?php _e('Unique name'); ?>',
        ROLE_TITLE: '<?php _e('Title'); ?>',
        SUBMIT: '<?php _e('Submit'); ?>',
        CANCEL: '<?php _e('Cancel'); ?>',
        REQUIRED: '<?php _e('Required'); ?>',
        TYPE: '<?php _e('Type'); ?>',
        FRONT: '<?php _e('Front'); ?>',
        ADMIN: '<?php _e('Admin'); ?>',
        ROLE_NAME_TAKEN: '<?php _e('Role name is already taken.'); ?>',
        DELETE_CONFIRM: '<?php _e('Are you sure to delete this role?'); ?>',
        EDIT_TITLE: '<?php _e('Users in role'); ?>',
        UID_OR_IDENTITY: '<?php _e('User id or name'); ?>',
        USERS: '<?php _e('Users'); ?>',
        FIRST: '<?php _e('First'); ?>',
        ADD_USER: '<?php _e('Add user'); ?>'
    }
}
</script>
<?php $debug = 'production' == Pi::environment() ? '.min' : ''; ?>
<script src="<?php echo $this->assetModule('admin/role' . $debug . '.js'); ?>"></script>