<?php
$this->angular(array(
    'angular-route.js',
    'pi.js',
));
?>
<div ng-app="userSearchModule">
  <div pi-message="alert"></div>
  <div ng-view></div>
</div>
<script>
angular
    .module('userSearchModule', ['ngRoute', 'pi'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('controller' => $controller)); ?>',
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
        t: {
           DISPLAY_NAME: '<?php _e('Display name'); ?>',
           SEARCH: '<?php _e('Search'); ?>',
           SEARCH_TEXT: '<?php _e('Search someone to view info'); ?>',
           USER_NAME: '<?php _e('User name'); ?>',
           EMAIL: '<?php _e('Email'); ?>',
           ACTIVATED: '<?php _e('Activated'); ?>',
           INACTIVE: '<?php _e('Inactive'); ?>',
           ENABLE: '<?php _e('Enable'); ?>',
           ACOUNT_INFO: '<?php _e('Account info'); ?>',
           PROFILE_INFO: '<?php _e('Profile info'); ?>',
           ENABLED: '<?php _e('Enabled'); ?>',
           EMPTY: '<?php _e('Unfiled'); ?>'
        }
    });
</script>
<?php $debug = 'production' == Pi::environment() ? '.min' : ''; ?>
<script src="<?php echo $this->assetModule('admin/search' . $debug . '.js'); ?>"></script>
