<?php
$this->css($this->assetModule('script/admin.css'));
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi.js'
));
$locale = Pi::config('locale');
if ($locale != 'en') {
    $this->angular('i18n/angular-locale_' . $locale . '.js');
}
?>
<div ng-app="userListModule">
    <div pi-message="alert"></div>
    <div pi-nav-tabs></div>
    <div ng-view></div>
</div>
<dl class="page-header">Links</dl>
<ul>
    <li>
        <a href="<?php echo $this->url('', array('controller' => 'build', 'action' => 'index'));?>">
            <?php _e('Build user module data');?>
        </a>
    </li>
</ul>
<script>
angular
    .module('userListModule', ['ngRoute', 'ui.bootstrap', 'pi'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('controller' => 'index', 'action' => 'var')); ?>'.replace(/var\/?$/, ''),
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
        navTabs: [
            { text: '<?php _e('All'); ?>', href: '#!/all' },
            { text: '<?php _e('Activated'); ?>', href: '#!/activated' },
            { text: '<?php _e('Pending'); ?>', href: '#!/pending' },
            { text: '<?php _e('Add new'); ?>', href: '#!/new' },
            { text: '<?php _e('Advanced search'); ?>', href: '#!/search' }
        ],
        t: {
            ACTIVE_STATUS: '<?php _e('Active State'); ?>',
            ENABLE_STATUS: '<?php _e('Enable State'); ?>',
            SELECT_ROLES: '<?php _e('Select roles'); ?>',
            APPLY: '<?php _e('Apply'); ?>',
            USERNAME: '<?php _e('Username'); ?>',
            DISPLAY_NAME: '<?php _e('Display name'); ?>',
            ENABLED: '<?php _e('Enabled'); ?>',
            DISABLED: '<?php _e('Disabled'); ?>',
            ACTIVATED: '<?php _e('Activated'); ?>',
            ACTIVE: '<?php _e('Active'); ?>',
            INACTIVE: '<?php _e('Inactive'); ?>',
            PENDING: '<?php _e('Pending'); ?>',
            ROLE: '<?php _e('Role'); ?>',
            REGISTER_TIME: '<?php _e('Register time'); ?>',
            ACTION: '<?php _e('Action'); ?>',
            EDIT: '<?php _e('Edit'); ?>',
            DELETE: '<?php _e('Delete'); ?>',
            ADD_TITLE: '<?php _e('Add user'); ?>',
            PASSWORD_MATCH: '<?php _e("Passwords don\'t match"); ?>',
            USER_NAME_TOKEN: '<?php _e('Username is already token'); ?>',
            EMAIL_TOKEN: '<?php _e('Email is already token'); ?>',
            DISPLAY_NAME_TOKEN: '<?php _e('Display name is already token'); ?>',
            RETURN: '<?php _e('Back to users list'); ?>',
            REQUIRED: '<?php _e('Required'); ?>',
            USER_NAME: '<?php _e('Username'); ?>',
            EMAIL: '<?php _e('Email'); ?>',
            INVALID_EMAIL: '<?php _e('Email invalid'); ?>',
            PASSWORD: '<?php _e('Password'); ?>',
            CONFIRM_PASSWORD: '<?php _e('Password confirm'); ?>',
            ACTIVATE: '<?php _e('Active'); ?>',
            ENABLE: '<?php _e('Enable'); ?>',
            FRONT_ROLE: '<?php _e('Front role'); ?>',
            ADMIN_ROLE: '<?php _e('Admin role'); ?>',
            TODAY: '<?php _e('Today'); ?>',
            LAST_WEEK: '<?php _e('Last week'); ?>',
            LAST_MONTH: '<?php _e('Last month'); ?>',
            LAST_3_MONTH: '<?php _e('Last thress month'); ?>',
            LAST_6_MONTH: '<?php _e('Last six month'); ?>',
            LAST_YEAR: '<?php _e('Last year'); ?>',
            ASSIGN_ROLE: '<?php _e('Assign role'); ?>',
            UNASSIGN_ROLE: '<?php _e('Unassign role'); ?>',
            ASSIGN_FRONT_ROLE: '<?php _e('Front role'); ?>',
            ASSIGN_ADMIN_ROLE: '<?php _e('Admin role'); ?>',
            CONFIRM: '<?php _e('Are you sure delete this user'); ?>',
            CONFIRMS: '<?php _e('Are you sure delete this users'); ?>',
            ACTIVE_STATE:'<?php _e('Active State'); ?>',
            TITLE: '<?php _e('Add user'); ?>',
            USER_NAME: '<?php _e('Username'); ?>',
            CONFIRM_ACTIVATED: '<?php _e('Are you sure active this account, it can not be return'); ?>',
            EMAIL: '<?php _e('Email'); ?>',
            PASSWORD: '<?php _e('Password'); ?>',
            CONFIRM_PASSWORD: '<?php _e('Confirm password'); ?>',
            ACTIVATE: '<?php _e('Activate'); ?>',
            ENABLE: '<?php _e('Enable'); ?>',
            SUBMIT: '<?php _e('Submit'); ?>',
            REQUIRED: '<?php _e('required'); ?>',
            INVALID_EMAIL: '<?php _e('invalid email'); ?>',
            PASSWORD_MATCH: '<?php _e("Passwords don\'t match"); ?>',
            USER_NAME_TOKEN: '<?php _e('Username is already token'); ?>',
            EMAIL_TOKEN: '<?php _e('Email is already token'); ?>',
            DISPLAY_NAME_TOKEN: '<?php _e('Dispaly name is already token'); ?>',
            REGISTER_IP: '<?php _e('Register IP'); ?>',
            ACTIVATED_STATUS: '<?php _e('Activated state'); ?>',
            USER_ID: '<?php _e('User ID'); ?>',
            NONE_USER: '<?php _e('No users matched your search'); ?>',
            SEARCH_TITLE: '<?php _e('Advanced search'); ?>',
            REGISTER_IP: '<?php _e('Register IP'); ?>',
            FROM: '<?php _e('From'); ?>',
            TO: '<?PHP _e('To'); ?>',
            SEARCH_RESULT: '<?PHP _e('Search result'); ?>',
            VIEW_LOG: '<?PHP _e('View log'); ?>'
        },
        roles: <?php echo json_encode($roles); ?>,
        today: '<?php echo date("Y-m-d"); ?>'
    });
</script>
<?php $debug = 'production' == Pi::environment() ? '.min' : ''; ?>
<script src="<?php echo $this->assetModule('admin/user' . $debug . '.js'); ?>"></script>