<?php
$this->css(array(
    $this->assetModule('script/test.css')
));
?>
<h2 class="page-header">Customized module template: <?php _e('Paginator'); ?></h2>
<ul>
<?php foreach ($items as $article) { ?>
<li><?php echo $this->escape($article['title']); ?></li>
<?php } ?>
</ul>

<?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?>
<p class="test"><?php echo $module .'-'. $controller . '-' . $action; ?></p>