<div class="pi-comment-block-user">
    <table class="table table-striped">
        <tr>
            <th></th>
            <th><?php echo _b('Article title'); ?></th>
            <th><?php echo _b('Comments'); ?></th>
        </tr>
        <?php 
            $index = 0;
            foreach ($block['targets'] as $name => $data) { 
        ?>
        <tr>
            <td><?php echo _escape(++$index); ?></td>
            <td><?php echo _escape($data['title']); ?></td>
            <td>
                <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>" target="_blank">
                    <?php echo $data['count']; ?>
                </a>
            </td>
        </tr>
        <?php } ?>
    </table>
</div>