
<h2 class="page-header"><?php echo _escape($title); ?></h2>

<ul>
    <?php foreach ($routes as $route) { ?>
    <li>
        <div>
            <h4><?php echo $route['name']; ?></h4>
            <span><?php echo _a('Class: '); ?></span><?php echo $route['class']; ?></span>
            <span><a  href="<?php echo $this->url('', array('action' => 'edit', 'id' => $route['id'])); ?>" title="<?php echo _a('Edit'); ?>"><?php echo _a('Edit'); ?></a></span>
            <span><a  href="<?php echo $this->url('', array('action' => 'delete', 'id' => $route['id'])); ?>" title="<?php echo _a('Delete'); ?>"><?php echo _a('Delete'); ?></a></span>
        </div>
    <?php } ?>
</ul>

<h3><a  href="<?php echo $this->url('', array('action' => 'add')); ?>" title="<?php echo _a('Add a route'); ?>"><?php echo _a('Add a route'); ?></a></h3>
