
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>

<ul>
    <?php foreach ($routes as $route) { ?>
    <li>
        <div>
            <h4><?php echo $route['name']; ?></h4>
            <span><?php _e('Class: '); ?></span><?php echo $route['class']; ?></span>
            <span><a  href="<?php echo $this->url('', array('action' => 'edit', 'id' => $route['id'])); ?>" title="<?php _e('Edit'); ?>"><?php _e('Edit'); ?></a></span>
            <span><a  href="<?php echo $this->url('', array('action' => 'delete', 'id' => $route['id'])); ?>" title="<?php _e('Delete'); ?>"><?php _e('Delete'); ?></a></span>
        </div>
    <?php } ?>
</ul>

<h3><a  href="<?php echo $this->url('', array('action' => 'add')); ?>" title="<?php _e('Add a route'); ?>"><?php _e('Add a route'); ?></a></span>
