<div class="panel panel-default">
    <div class="panel-heading">
        <?php echo __('Demo for script page content.'); ?>
    </div>
    <div class="panel-body">
        <?php
            $content =<<<'EOT'
<h3>%s</h3>
<em>%s</em>
<p>%s</p>
EOT;

            $content = sprintf(
                $content,
                Pi::config('sitename'),
                Pi::config('slogan'),
                Pi::config('description')
            );
            echo $content;
        ?>
    </div>
</div>
