<?php
/**
 * Pi Engine (http://pialog.org)
 *
 * @link            http://code.pialog.org for the Pi Engine source repository
 * @copyright       Copyright (c) Pi Engine http://pialog.org
 * @license         http://pialog.org/license.txt BSD 3-Clause License
 */

return array(

    // Profile field list
    'field' => array(
        'sample'    => array(
            'title' => _a('Sample field'),
        ),
    ),

    // Activity list
    'activity' => array(
        // Regular activity generated by callback
        'test-callback'    => array(
            'title'     => _a('Activity by callback'),
            'icon'      => 'fa-code',
            'callback'  => 'Module\Demo\Api\UserActivity',
        ),
        // Activity generated by remote callback with template
        'test-template'   => array(
            'title'     => _a('Activity with template'),
            'icon'      => 'fa-cloud',
            'template'  => 'demo-user-activity',
            'callback'  => Pi::url(
                    Pi::service('url')->assemble(
                        'default',
                        array(
                            'module'        => 'demo',
                            'controller'    => 'activity',
                            'action'        => 'get'
                        )
                    ),
                    true
                ),
        ),
        // Activity by external link jump
        'test-external'    => array(
            'title'     => _a('Activity to external'),
            'icon'      => 'fa-external-link',
            'callback'  => 'Module\Demo\Api\UserActivityExternal',
        ),
    ),
);
