<?php
if (isset($root['active']) && empty($root['active'])) {
    echo '<div class="well well-sm">' . __('Comment is disabled.') . '</div>';
    return;
}

//$uid = Pi::user()->getId();

if (!empty($root['id'])) {
    $formData = array(
        'root' => $root['id']
    );
} else {
    $formData = array(
        'module'    => $root['module'],
        'type'  => $root['type'],
        'item'      => $root['item'],
    );
}
$formData['redirect'] = rawurlencode($uri);
$form = Pi::service('comment')->getForm($formData);
?>
<div class="comment-item" id="js-comment-form">
    <textarea placeholder="<?php _e('Type your content'); ?>" class="form-control js-comment-txt" rows="3"></textarea>
    <div class="hide clearfix comment-form">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <textarea placeholder="<?php _e('Type your content'); ?>" name="content" class="form-control" rows="3"></textarea>
        </div>
        <?php
        foreach (array( 'id', 'root', 'reply', 'module', 'type', 'item', 'redirect', 'markup') as $hiddenElement) {
            echo $this->formElement($form->get($hiddenElement));
        }
        ?>
        <div class="pull-right js-comment-btn">
            <button class="btn btn-primary">
                <?php _e('Post comment'); ?>
            </button>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <div class="hide well well-sm">
        <?php echo sprintf(__('Please <a href="%s">login</a> to leave comments.'), Pi::service('authentication')->getUrl('login', $uri)); ?>
    </div>
</div>
<?php
$url = Pi::service('url')->assemble('default', array(
    'module'        => 'system',
    'controller'    => 'index',
    'action'        => 'user',
));

?>
<script>
(function ($) {
var comment = {
    el: $('#js-comment-form'),
    $: function (selector) {
        return this.el.find(selector);
    },
    init: function () {
        this.textarea = this.$('.js-comment-txt');
        this.events();
    },
    events: function () {
        var self = this;
        this.textarea.focus(function () {
            $.getJSON('<?php echo $url; ?>?' + new Date().getTime()).done(function (data) {
                self.textarea.hide();
                if (data.uid) {
                    self.$('.comment-form').removeClass('hide');
                    self.$('[name=content]').focus();
                } else {
                    self.$('.well').removeClass('hide');
                }
            });
        });
    }
};
comment.init();
})(jQuery)
</script>

<div class="pi-status active js-video-status" data-id="">
    <div class="pi-status-director"></div>
</div>
<script>
$('.js-video-status').click(function() {
    location.href = '<?php $this->url(); ?>' + $(this).data('id');
});
</script>