<?php
$this->css($this->assetModule('css/front.css', 'comment'));
// Target data:
// title, time, user
// user: uid, name, avatar, url
$target = $comment['target'];

// Comment post
// content, time, user
$post = $comment['post'];

$uid = Pi::user()->getId();
$avatar = Pi::avatar()->get($uid, 'medium', false);
if ($uid) {
    $url = Pi::service('user')->getUrl('profile', $uid);
} else {
    $url = Pi::url('www');
}
?>
<div class="pi-comment">
    <h1 class="pi-comment-header">
        <?php _e('Comment edit'); ?>
    </h1>
    <?php if (!empty($comment['message'])) { ?>
    <div class="alert alert-danger"><?php echo _escape($comment['message']); ?></div>
    <?php } ?>
    <div class="media">
        <a class="pull-left" href="<?php echo $url; ?>">
            <img class="media-object" src="<?php echo $avatar; ?>">
        </a>
        <div class="media-body">
        <?php if ($post) { ?>
            <div class="clearfix">
                <span class="pi-comment-user">
                    <a href="<?php echo $url; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                        <?php echo $post['user']['name']; ?>
                    </a>
                </span>
                <span class="pull-right muted pi-comment-time"><?php echo _date($post['time']); ?></span>
            </div>
            <div class="pi-comment-desc">
                <span class="muted pull-left"><?php _e('Commented on '); ?></span>
                <a class="highlight comment-title-hidden" href="<?php echo $target['url']; ?>" title="<?php echo _escape($target['title']); ?>" style="max-width: 70%">
                    <?php echo $target['title']; ?>
                </a>
            </div>
            <?php
            echo $this->form()->openTag($form);
            echo $this->formElement($form->get('content'));
            echo $this->formElement($form->get('submit'));

            $elements = $form->elementList();
            foreach ($elements['hidden'] as $element) {
                echo $this->formElement($element);
            }
            echo $this->form()->closeTag();
        } else {
            ?>
            <div class="pi-comment-none"><?php _e('No content.'); ?></div>
        <?php } ?>
        </div>
    </div>
</div>