<?php
// Skip if comment is not available
if (!Pi::comment()->active()) {
    return;
}


// Load comment data
// - root[id, module, category, item, active]
// - count
// - posts[id, uid, IP, content, time, active]
// - users[uid, name, avatar, url]
// - url_list
// - url_submit
// - url_ajax

$data = Pi::api('comment')->load(
    $this->url()->routeMatch(),
    array('avatar' => 'medium')
);

if (!$data) {
    return;
}

if (isset($data['root']['active']) && empty($data['root']['active'])) :
    echo '<div class="alert">' . __('Comment is disabled.') . '</div>';
    return;
else:
if (!empty($data['root']['id'])) {
    $formData = array(
        'root' => $data['root']['id']
    );
} else {
    $formData = array(
        'module'    => $data['root']['module'],
        'category'  => $data['root']['category'],
        'item'      => $data['root']['item'],
    );
}
$formData['redirect'] = $this->url()->requestUri(true);

$form = Pi::service('comment')->getForm($formData);
endif;

$this->css($this->assetModule('css/front.css', 'comment'));
$uid = Pi::user()->getId();
?>
<div class="comments-panel">
    <div class="comments-header">
        <h4><?php _e('All comments '); ?> (<?php echo $data['count'] ?: 0; ?>)</h4>
    </div>
    
    <div class="media comment-item">
        <?php if($uid) { ?>
        <a class="pull-left" href="<?php echo Pi::service('user')->getUrl('profile', $uid); ?>" target="_blank">
            <?php echo Pi::avatar()->get($uid, 'medium'); ?>
        </a>
        <div class="media-body">
            <?php echo $this->form()->openTag($form); ?>
            <textarea placeholder="<?php _e('Type your content'); ?>" name="content" class="input-block-level"
                      rows="3"></textarea>
            <?php
            foreach (array(
                            'id', 'root', 'reply', 'module', 'category',
                            'item', 'redirect', 'markup') as $hiddenElement) {
                            echo $this->formElement($form->get($hiddenElement));
                        }
            ?>
            <div class="pull-right">
                <button class="btn btn-primary">
                    <?php _e('Post comment'); ?>
                </button>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
        <?php } else { ?>
        <div class="pull-left">
            <?php echo Pi::avatar()->get('', 'medium'); ?>
        </div>
        <div class="media-body well well-small">
            <a href="<?php echo Pi::service('authentication')->getUrl('login'); ?>">
                <?php _e('Login'); ?>
            </a>
            <?php _e(' to leave comments.'); ?>
        </div>
        <?php } ?>
    </div>
    
    <?php if (count($data['posts'])) { ?>
    <?php foreach ($data['posts'] as $item) { ?>
    <div class="media comment-item" id="comment-<?php echo $item['id']; ?>">
        <a class="pull-left" href="<?php echo $item['user']['url']; ?>" target="_blank">
            <?php echo $item['user']['avatar']; ?>
        </a>
        <div class="media-body">
            <?php
            echo sprintf('
                <div class="media-heading">
                    <a href="%s" target="_blank" style="margin-right: 20px;">%s</a>
                    <span class="muted">%s</span>
                </div>
                <p>%s
                ',
                $item['user']['url'],
                $item['user']['name'],
                _date($item['time']),
                $item['content']
            ); 
            ?>
            <div class="comment-operation">
                <?php
                if ($uid == $item['uid']) {
                    echo sprintf(
                        '<a href="%s" onclick="return confirm(\'%s\')">%s</a>',
                        $this->url('default', array('controller' => 'post', 'action' => 'delete', 'id' => $item['id'])),
                        __('Are you sure to delete this comment?'),
                        __('Delete')
                    );
                }
                ?>
            </div>
        </div>
    </div>
    <?php } ?>
    <a href="<?php echo $data['url_list']; ?>" class="btn btn-block comment-btn-all">
        <?php _e('View all comments'); ?>
    </a>
    <?php } else { ?>
    <div class="text-center comment-none">
        <strong class="muted"><?php _e('No one has commented yet.'); ?></strong>
    </div>
    <?php } ?>
</div>