<?php
// Skip if comment is not available
if (!Pi::comment()->active()) {
    return;
}

// Load comment data
// - root[id, module, category, item, active]
// - count
// - posts[id, uid, IP, content, time, active]
// - users[uid, name, avatar, url]
// - url_list
// - url_submit
// - url_ajax

$this->backbone();
$this->css($this->assetModule('css/front.css', 'comment'));
$data = Pi::api('comment')->load(
    $this->url()->routeMatch()
);
if (!$data) {
    return;
}

if (isset($data['root']['active']) && empty($data['root']['active'])) :
    echo '<div class="alert">' . __('Comment is disabled.') . '</div>';
else:
if (!empty($data['root']['id'])) {
    $formData = array(
        'root' => $data['root']['id']
    );
} else {
    $formData = array(
        'module'    => $data['root']['module'],
        'category'  => $data['root']['category'],
        'item'      => $data['root']['item'],
    );
}
$formData['redirect'] = $this->url()->requestUri(true);

$form = Pi::service('comment')->getForm($formData);
//include $this->templateComponent('form');
?>

<?php
$uid = Pi::user()->getId();
$avatar = Pi::avatar()->get($uid, 'medium', false);
if ($uid) {
    $url = Pi::service('user')->getUrl('profile', $uid);
} else {
    $url = Pi::url('www');
}
?>
    <div class="pi-comment">
        <div class="pi-comment-header">
            <span><?php _e('All comments '); ?></span>
            <span>(<?php echo $data['count'] ?: 0; ?>)
            </span>
        </div>
        <div class="pi-comment-form">
            <div class="media">
                <a class="pull-left" href="<?php echo $url; ?>">
                    <img class="media-object" src="<?php echo $avatar; ?>">
                </a>
                <div class="media-body">
                <?php 
                    if (empty($uid)) {
                        $redirect = Pi::engine()->application()->getRequest()->getUri()->getPath();
                        $loginUrl = Pi::user()->getUrl('login', $redirect);
                ?>
                    <div class="form-unsign">
                        <span><a href="<?php echo $loginUrl; ?>" class="highlight"><?php _e('Login'); ?></a></span>
                        <span><?php _e(' to leave comments.'); ?></span>
                    </div>
                <?php
                    } else {
                        echo $this->form()->openTag($form);
                ?>
                    <div class="form-textarea">
                        <textarea placeholder="<?php _e('Type your content'); ?>" name="content"></textarea>
                    </div>
                    <input class="btn form-submit pull-right hide" type="submit" value="<?php _e('Post'); ?>" name="submit">
                <?php 
                        foreach (array(
                            'id', 'root', 'reply', 'module', 'category',
                            'item', 'redirect', 'markup') as $hiddenElement) {
                            echo $this->formElement($form->get($hiddenElement));
                        }
                        echo $this->form()->closeTag();
                    }
                ?>
                </div>
            </div>
        </div>
        <?php
            if (count($data['posts'])) {
        ?>
        <div class="pi-comment-list">
        <?php 
            foreach ($data['posts'] as $post) {
        ?>
            <div class="media">
                <a class="pull-left" href="<?php echo $post['user']['url']; ?>" target="_blank">
                    <?php echo $post['user']['avatar']; ?>
                </a>
                <div class="media-body">
                    <div>
                        <span class="pi-comment-user">
                            <a href="<?php echo $post['user']['url']; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                                <?php echo $post['user']['name']; ?>
                            </a>
                        </span>
                        <span class="muted"><?php echo _date($post['time']); ?></span>
                    </div>
                    <div class="pi-comment-content"><?php echo $post['content']; ?></div>
                    <div class="pi-comment-operation">
                    <?php 
                        foreach ($post['operations'] as $operation => $optData) {
                    ?>
                        <span class="operation muted">
                            <a href="<?php echo $optData['url']; ?>"><?php echo _escape($optData['title']); ?></a>
                        </span>
                    <?php
                        }
                    ?>
                    </div>
                </div>
            </div>
        <?php 
            }
        ?>
        </div>
        <div class="pi-comment-view-all">
            <a href="<?php echo $data['url_list']; ?>" title="<?php _e('Read more'); ?>" target="_blank" class="btn">
                <?php _e('View all comments'); ?>
            </a>
        </div>
        <?php
            } else {
        ?>
        <div class="pi-comment-none"><?php _e('No one has commented yet.'); ?></div>
        <?php
            }
        ?>
    </div>
<?php
endif;
?>

<script>
(function($) {
var page = {
    range   : $("div.pi-comment"),
    $       : function(selector) {
       return this.range.find(selector);
    }
};

var CommentView = Backbone.View.extend({
    events          : {
        "click textarea"   :"expandTextarea"
    },
    initialize      : function() {
        this.$el   = $(".pi-comment");
    },
    expandTextarea  : function() {
        var text  = this.$("textarea");
        var textForm = this.$(".form-textarea");
        
        text.css({
            "height"     : "75px",
            "min-height" : "75px",
            "max-height" : "auto"
        });
        textForm.css({
            "height"     : "75px"
        });
        this.$(".form-submit").removeClass("hide");
    }
});
new CommentView;
})(jQuery)
</script>