<?php
$this->css($this->assetModule('css/front.css', 'comment'));
$this->headMeta('noindex', 'robots');

// Target data:
// Title, time, user
// uid, name, avatar, profile_url
$target = $comment['target'];

// Comment post
// content, time, user
$post = $comment['post'];

$uid = Pi::user()->getId();
$avatar = Pi::avatar()->get($uid, 'medium', false);
if ($uid) {
    $url = Pi::service('user')->getUrl('profile', $uid);
} else {
    $url = Pi::url('www');
}
// Add head style
$style = <<<'EOT'
    textarea {
        border: 0;
        padding: 0;
        margin: 0;
        box-shadow: none;
        width: 100%;
        min-width: 100%;
        max-width: 100%;
        height: 75px;
        max-height: 75px;
        min-height: 75px;
    }
    textarea:focus {
        border: 0px;
        box-shadow: none;
    }
    .media-body .form-textarea {
        margin-top: 20px;
        border: 1px solid #dddddd;
        padding: 4px 6px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
        border-radius: 4px;
        height: 75px;
    }
EOT;
$this->headStyle()->appendStyle($style);

?>
<div class="pi-comment">
    <h1 class="pi-comment-header">
        <?php echo sprintf(__('Comment reply to %s'), $post['user']['name']); ?>
    </h1>
    <div class="media">
        <a class="pull-left" href="<?php echo $url; ?>">
            <img class="media-object" src="<?php echo $avatar; ?>">
        </a>
        <div class="media-body">
            <?php if ($post) { ?>
                <div class="clearfix">
                <span class="pi-comment-user">
                    <a href="<?php echo $post['user']['url']; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                        <?php echo $post['user']['name']; ?>
                    </a>
                </span>
                    <span class="pull-right muted pi-comment-time"><?php echo _date($post['time']); ?></span>
                </div>
                <div class="pi-comment-desc">
                    <span class="muted pull-left"><?php _e('Commented on '); ?></span>
                    <a class="highlight comment-title-hidden" href="<?php echo $target['url']; ?>" title="<?php echo _escape($target['title']); ?>" style="max-width: 70%">
                        <?php echo _escape($target['title']); ?>
                    </a>
                </div>
                <div class="pi-comment-content">
                    <?php echo $post['content']; ?>
                </div>
                <?php
                echo $this->form()->openTag($form);
                echo $this->formElement($form->get('content'));
                echo $this->formElement($form->get('submit'));

                $elements = $form->elementList();
                foreach ($elements['hidden'] as $element) {
                    echo $this->formElement($element);
                }
                echo $this->form()->closeTag();
                ?>
            <?php } else { ?>
                <div class="pi-comment-none"><?php _e('No content.'); ?></div>
            <?php } ?>
        </div>
    </div>
</div>