<?php
$this->css($this->assetModule('css/front.css', 'comment'));
$this->headMeta('noindex', 'robots');
?>
<div class="pi-comment-portal">
    <h1 class="pi-comment-header"><?php echo _escape($title); ?></h1>
    <ul>
        <?php foreach ($links as $key => $link) { ?>
            <li>
                <a href="<?php echo $link['url']; ?>" title="<?php echo _escape($link['title']); ?>" target="_blank">
                    <?php echo _escape($link['title']); ?>
                </a>
            </li>
        <?php } ?>
    </ul>
</div>