<link href="<?php echo $this->assetModule('css/front.css', 'comment'); ?>" rel="stylesheet" type="text/css">
<div class="comments-panel">
    <div class="comments-header">
        <h4><?php _e('All comments '); ?> (<?php echo $count ?: 0; ?>)</h4>
    </div>

    <?php include '_post-form.phtml'; ?>

    <?php if (count($posts)) { ?>
    <?php foreach ($posts as $item) { ?>
    <div class="media comment-item" id="comment-<?php echo $item['id']; ?>">
        <a class="pull-left" href="<?php echo $item['user']['url']; ?>" target="_blank">
            <?php echo $item['user']['avatar']; ?>
        </a>
        <div class="media-body">
            <?php
            echo sprintf('
                <div class="media-heading">
                    <a href="%s" target="_blank" style="margin-right: 20px;">%s</a>
                    <span class="muted">%s</span>
                </div>
                <p>%s
                ',
                $item['user']['url'],
                $item['user']['name'],
                _date($item['time']),
                $item['content']
            ); 
            ?>
            <div class="comment-operation">
                <?php
                if ($uid == $item['uid']) {
                    echo sprintf(
                        '<a href="%s" onclick="return confirm(\'%s\')">%s</a>',
                        $this->url('comment', array('controller' => 'post', 'action' => 'delete', 'id' => $item['id'])),
                        __('Are you sure to delete this comment?'),
                        __('Delete')
                    );
                }
                ?>
            </div>
        </div>
    </div>
    <?php } ?>
    <a href="<?php echo $url_list; ?>" class="btn btn-block comment-btn-all">
        <?php _e('View all comments'); ?>
    </a>
    <?php } else { ?>
    <div class="text-center comment-none">
        <strong class="muted"><?php _e('No one has commented yet.'); ?></strong>
    </div>
    <?php } ?>
</div>