<?php
$this->css($this->assetModule('css/front.css', 'comment'));

// Target data:
// Title, time, user
// uid, name, avatar, profile_url
$target = $comment['target'];

// Comment post
// content, time, user
$post = $comment['post'];

$uid = Pi::user()->getId();
$avatar = Pi::avatar()->get($uid, 'medium', false);
if ($uid) {
    $url = Pi::service('user')->getUrl('profile', $uid);
} else {
    $url = Pi::url('www');
}
?>

<style>
    textarea {
        border: 0;
        padding: 0;
        margin: 0;
        box-shadow: none;
        width: 100%;
        min-width: 100%;
        max-width: 100%;
        height: 75px;
        max-height: 75px;
        min-height: 75px;
    }
    textarea:focus {
        border: 0px;
        box-shadow: none;
    }
    .media-body .form-textarea {
        margin-top: 20px;
        border: 1px solid #dddddd;
        padding: 4px 6px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
        border-radius: 4px;
        height: 75px;
    }
</style>

<div class="pi-comment">
    <div class="pi-comment-header"><?php echo sprintf(__('Comment reply to %s'), $post['user']['name']); ?></div>
    <div class="media">
        <a class="pull-left" href="<?php echo $url; ?>">
            <img class="media-object" src="<?php echo $avatar; ?>">
        </a>
        <div class="media-body">
        <?php
            if ($post) {
        ?>
            <div>
                <span class="pi-comment-user">
                    <a href="<?php echo $post['user']['url']; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                        <?php echo $post['user']['name']; ?>
                    </a>
                </span>
                <span class="pull-right muted pi-comment-time"><?php echo _date($post['time']); ?></span>
            </div>
            <div class="pi-comment-desc">
                <span class="muted pull-left"><?php _e('Commented on '); ?></span>
                <a class="highlight comment-title-hidden" href="<?php echo $target['url']; ?>" title="<?php echo _escape($target['title']); ?>" style="max-width: 70%">
                    <?php echo _escape($target['title']); ?>
                </a>
            </div>
            <div class="pi-comment-content">
                <?php echo $post['content']; ?>
            </div>
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-textarea">
                <textarea placeholder="<?php _e('Type your content'); ?>" name="content"><?php echo $form->get('content')->getValue(); ?></textarea>
            </div>
            <input class="btn form-submit pull-right" type="submit" value="<?php _e('Reply'); ?>" name="submit">
            <?php 
                foreach (array(
                    'id', 'root', 'reply', 'module', 'type',
                    'item', 'redirect', 'markup') as $hiddenElement) {
                    echo $this->formElement($form->get($hiddenElement));
                }
            ?>
            <?php echo $this->form()->closeTag(); ?>
        <?php
            } else {
        ?>
            <div class="pi-comment-none"><?php _e('No content.'); ?></div>
        <?php
            }
        ?>
        </div>
    </div>
</div>
