<?php
$this->css($this->assetModule('css/front.css', 'comment'));
?>
<div class="pi-comment">
    <div class="pi-comment-header"><?php _e('Comment detail'); ?></div>
    <div class="alert alert-danger">
        <p><?php echo __('The comment post is not found.'); ?></p>
        <p class="text-right">
            <a href="<?php echo Pi::url('www'); ?>">
                <?php echo _escape(Pi::config('sitename')); ?>
            </a>
        </p>
    </div>
</div>