<?php
// Target data:
// Title, time, user
// uid, name, avatar, profile_url
$target = $comment['target'];

// Comment post
// content, time, user
$post = $comment['post'];
?>
<div class="page-header"><?php echo _escape($comment['title']); ?></div>
<?php
if ($post) {
?>
    <div class="pi-comment-header">
        <dl class="dl-horizontal">
            <dt><?php _e('Source:') ?></dt>
            <dd><a href="<?php echo $target['url']; ?>" target="_blank" title="<?php echo _escape($target['title']); ?>">
                    <?php echo _escape($target['title']); ?>
                </a>
            </dd>

            <?php if ($post['reply']) { ?>
                <dt><?php _e('Reply to:') ?></dt>
                <dd><a href="<?php echo Pi::service('comment')->getUrl('post', array('post' => $post['reply'])); ?>" target="_blank" title="<?php _e('Click to open'); ?>">
                        <?php echo sprintf(__('Comment #%d'), $post['reply']); ?>
                    </a>
                </dd>
            <?php } ?>
        </dl>
    </div>
    <div class="pi-comment-list">
        <dl class="dl-horizontal pi-comment-post">
            <dt><?php _e('Author:') ?></dt>
            <dd><a href="<?php echo $post['user']['url']; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>">
                    <?php echo $post['user']['name']; ?>
                </a>
            </dd>

            <dt>&nbsp;</dt>
            <dd><?php echo $post['user']['avatar']; ?></dd>

            <dt><?php _e('Time:');?></dt>
            <dd><?php echo _date($post['time']); ?></dd>

            <?php if (!empty($post['time_updated'])) { ?>
                <dt><?php _e('Updated:');?></dt>
                <dd><?php echo _date($post['time_updated']); ?></dd>
            <?php } ?>

            <dt><?php _e('Content:');?></dt>
            <dd><?php echo $post['content']; ?></dd>

            <dt><?php _e('Operations:');?></dt>
            <dd>
            <?php foreach ($post['operations'] as $key => $op) { ?>
                <a href="<?php echo $op['url']; ?>" title="<?php echo _escape($op['title']); ?>" target="_blank">
                <?php echo _escape($op['title']); ?>
                </a>
            <?php } ?>
            </dd>
        </dl>
    </div>
<?php
} else {
    _e('No content');
}
?>
