<?php
// Skip if comment is not available
if (!Pi::comment()->active()) {
    return;
}

// Load comment data
// - root[id, module, category, item, active]
// - count
// - posts[id, uid, IP, content, time, active]
// - users[uid, name, avatar, url]
// - url_list
// - url_submit
// - url_ajax

$this->backbone();
$this->css($this->assetModule('css/front.css', 'comment'));

$data = Pi::api('comment')->load(
    $this->url()->routeMatch()
);
if (!$data) {
    return;
}

if (isset($data['root']['active']) && empty($data['root']['active'])) :
    echo '<div class="alert">' . __('Comment is disabled.') . '</div>';
else:
if (!empty($data['root']['id'])) {
    $formData = array(
        'root' => $data['root']['id']
    );
} else {
    $formData = array(
        'module'    => $data['root']['module'],
        'category'  => $data['root']['category'],
        'item'      => $data['root']['item'],
    );
}
$formData['redirect'] = $this->url()->requestUri(true);

$form = Pi::service('comment')->getForm($formData);
//include $this->templateComponent('form');
?>

<?php
$uid = Pi::user()->id;
$avatar = Pi::avatar()->get($uid, 'medium', false);
if ($uid) {
    $url = Pi::service('user')->getUrl('profile', $uid);
} else {
    $url = Pi::url('www');
}
if ($data['posts']) {
?>
    <div class="pi-comment">
        <div class="pi-comment-header">
            <span><?php _e('All comments ') ?></span>
            <span>(<a href="<?php echo $data['url_list'] ?>" class="highlight"><?php echo $data['count'] ?: 0 ?></a>)
            </span>
        </div>
        <div class="pi-comment-form">
            <div class="media">
                <a class="pull-left" href="<?php echo $url ?>">
                    <img class="media-object" src="<?php echo $this->escape($avatar) ?>">
                </a>
                <div class="media-body">
                <?php 
                    if (empty($uid)) {
                        $redirect = Pi::engine()->application()->getRequest()->getUri()->getPath();d($redirect);
                        $loginUrl = Pi::user()->getUrl('login', $redirect);
                ?>
                    <div class="form-unsign">
                        <span><a href="<?php echo $loginUrl ?>" class="highlight"><?php _e('Sign in') ?></a></span>
                        <span><?php _e(' to leave comments.') ?></span>
                    </div>
                <?php
                    } else {
                        echo $this->form()->openTag($form);
                ?>
                    <div class="form-textarea">
                        <textarea placeholder="<?php _e('Type your content') ?>" name="content"></textarea>
                    </div>
                    <input class="btn form-submit pull-right hide" type="submit" value="<?php _e('Post') ?>" name="submit">
                <?php 
                        foreach (array(
                            'id', 'root', 'reply', 'module', 'category',
                            'item', 'redirect', 'markup') as $hiddenElement) {
                            echo $this->formElement($form->get($hiddenElement));
                        }
                        echo $this->form()->closeTag();
                    }
                ?>
                </div>
            </div>
        </div>
        <div class="pi-comment-list">
        <?php 
            foreach ($data['posts'] as $post) {
        ?>
            <div class="media">
                <a class="pull-left" href="<?php echo $post['user']['url'] ?>" target="_blank">
                    <?php echo $post['user']['avatar'] ?>
                </a>
                <div class="media-body">
                    <div>
                        <span class="pi-comment-user">
                            <a href="<?php echo $post['user']['url'] ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                                <?php echo $post['user']['name'] ?>
                            </a>
                        </span>
                        <span class="muted"><?php echo date('Y/m/d H:i:s', $post['time']) ?></span>
                    </div>
                    <div class="pi-comment-content"><?php echo $post['content'] ?></div>
                    <div class="pi-comment-operation">
                    <?php 
                        foreach ($post['operations'] as $operation => $optData) {
                            $class = '';
                            switch ($operation) {
                                case 'disable':
                                    $class = 'icon-ban-circle';
                                    break;
                                case 'edit':
                                    $class = 'icon-pencil';
                                    break;
                                case 'delete':
                                    $class = 'icon-trash';
                                    break;
                                case 'reply':
                                    $class = 'icon-share-alt';
                                    break;
                            }
                    ?>
                        <span class="operation muted">
                            <a href="<?php echo $optData['url'] ?>">
                                <i class="<?php echo $class ?>" style="text-decoration: none"></i><?php echo $optData['title'] ?>
                            </a>
                        </span>
                    <?php
                        }
                    ?>
                    </div>
                </div>
            </div>
        <?php 
            }
        ?>
        </div>
        <div class="pi-comment-view-all">
            <a href="<?php echo $data['url_list'] ?>" title="<?php _e('Read more') ?>" target="_blank" class="btn">
                <?php _e('View all comments') ?>
            </a>
        </div>
    </div>
<?php
}
endif;
?>
<!--
<form name="comment-post" method="POST" action="<?php echo $data['url_submit']; ?>">
<dl>
    <dt><?php _e('Post a comment:'); ?></dt>
    <dd><textarea name="content"></textarea></dd>
    <?php if (!empty($data['root']['id'])) { ?>
        <input type="hidden" name="root" value="<?php echo $data['root']['id']; ?>" />
    <?php } else { ?>
        <input type="hidden" name="module" value="<?php echo $data['root']['module']; ?>" />
        <input type="hidden" name="category" value="<?php echo $data['root']['category']; ?>" />
        <input type="hidden" name="item" value="<?php echo $data['root']['item']; ?>" />
    <?php } ?>
    <input type="hidden" name="redirect" value="<?php echo $this->url()->requestUri(true); ?>" />
    <input type="submit" value="<?php _e('Submit'); ?>" />
</dl>
</form>
//-->

<script>
(function($) {
var page = {
    range   : $("div.pi-comment"),
    $       : function(selector) {
       return this.range.find(selector);
    }
};

var CommentView = Backbone.View.extend({
    template        : _.template('<div class="black-bg">'
                    + '<i class="category icon-remove"></i></div>'
                    + '<img src="<%=preview_url %>">'
    ),
    events          : {
        "click textarea"   :"expandTextarea",
        "mouseover .pi-comment-list .media" : "displayOperation",
        "mouseout .pi-comment-list .media"  : "hideOperation"
    },
    initialize      : function() {
        this.$el   = $(".pi-comment");
    },
    expandTextarea  : function() {
        var text  = this.$("textarea");
        var textForm = this.$(".form-textarea");
        
        text.css({
            "height"     : "75px",
            "min-height" : "75px",
            "max-height" : "auto"
        });
        textForm.css({
            "height"     : "75px"
        });
        this.$(".form-submit").removeClass("hide");
    },
    foldTextarea    : function() {
        var text  = this.$("textarea");
        var textForm = this.$(".form-textarea");
        
        text.css({
            "height"     : "38px",
            "min-height" : "38px",
            "max-height" : "38px"
        });
        textForm.css({
            "height"     : "38px"
        });
        this.$(".form-submit").addClass("hide");
    },
    displayOperation    : function(e) {
        var el = $(e.target).parents(".media");
        el.find(".pi-comment-operation").css("visibility", "visible");
    },
    hideOperation   : function(e) {
        var el = $(e.target).parents(".media");
        el.find(".pi-comment-operation").css("visibility", "hidden");
    }
});
new CommentView;
})(jQuery)
</script>