<?php
$this->css($this->assetModule('css/front.css', 'comment'));
// Target data:
// title, time, user
// user: uid, name, avatar, url
$target = $comment['target'];

// Comment post
// content, time, user
$post = $comment['post'];

$uid = Pi::user()->getId();
$avatar = Pi::avatar()->get($uid, 'medium', false);
if ($uid) {
    $url = Pi::service('user')->getUrl('profile', $uid);
} else {
    $url = Pi::url('www');
}
?>
<div class="pi-comment">
    <div class="pi-comment-header"><?php _e('Comment edit'); ?></div>
    <div class="media">
        <a class="pull-left" href="<?php echo $url; ?>">
            <img class="media-object" src="<?php echo $avatar; ?>">
        </a>
        <div class="media-body">
        <?php
            if ($post) {
        ?>
            <div>
                <span class="pi-comment-user">
                    <a href="<?php echo $post['user']['url']; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                        <?php echo $post['user']['name']; ?>
                    </a>
                </span>
                <span class="pull-right muted pi-comment-time"><?php echo _date($post['time']); ?></span>
            </div>
            <div class="pi-comment-desc">
                <span class="muted pull-left"><?php _e('Commented on '); ?></span>
                <a class="highlight comment-title-hidden" href="<?php echo $target['url']; ?>" title="<?php echo _escape($target['title']); ?>" style="max-width: 70%">
                    <?php echo $target['title']; ?>
                </a>
            </div>
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-textarea">
                <textarea placeholder="<?php _e('Type your content'); ?>" name="content"><?php echo $form->get('content')->getValue(); ?></textarea>
            </div>
            <div class="pull-right">
                <a href="<?php echo $redirect; ?>" class="form-cancel highlight"><?php _e('Cancel'); ?></a>
                <input class="btn form-submit" type="submit" value="<?php _e('Save'); ?>" name="submit">
            </div>
            <?php 
                foreach (array(
                    'id', 'root', 'reply', 'module', 'type',
                    'item', 'redirect', 'markup') as $hiddenElement) {
                    echo $this->formElement($form->get($hiddenElement));
                }
            ?>
            <?php echo $this->form()->closeTag(); ?>
        <?php
            } else {
        ?>
            <div class="pi-comment-none"><?php _e('No content.'); ?></div>
        <?php
            }
        ?>
        </div>
    </div>
</div>
