<div id="time-publish-element" style="width: 250px">
    <input type="hidden" value="<?php echo $value ? _date($value) : '';; ?>" name="<?php echo $name; ?>" <?php echo $attributes . ' ' . $required; ?>>
    <div class="pull-right">
        <div class="time-control-item">
            <input type="text" value="<?php echo $hour; ?>" class="input-small text-hour form-control" maxlength="2">
            <div class="text-muted" style="padding: 0 5px; width: 9px; font-size: 12px">
                <span class="fa fa-chevron-up hour-sort" data-action="1"></span>
                <span class="fa fa-chevron-down hour-sort"></span>
            </div>
        </div>
        <div class="time-control-item" style="margin-left: 10px">
            <input type="text" value="<?php echo $minute; ?>" class="input-small text-minute form-control" maxlength="2">
            <div class="text-muted" style="padding: 0 5px; width: 9px; font-size: 12px">
                <span class="fa fa-chevron-up minute-sort" data-action="1"></span>
                <span class="fa fa-chevron-down minute-sort"></span>
            </div>
        </div>
    </div>
    <input id="datepicker" class="form-control" value="<?php echo $date; ?>" type="text" style="width: 110px; margin: 0;">
</div>
<script type="text/javascript">
(function($) {
    var TimePublishView = Backbone.View.extend({
        el  : $("#time-publish-element"),
        events : {
            "click .hour-sort"   : "hourAction",
            "click .minute-sort" : "minuteAction"
        },
        initialize : function() {
            _.bindAll(this);
            
            $("#datepicker").datepicker({
                format   : "yyyy-mm-dd",
                language : "zh-CN"
            });
        },
        hourAction  : function(e) {
            var el = this.$(".text-hour"),
                v;
            if ($(e.target).attr("data-action")) {
                v = parseInt(el.val()) - 1;
                v = v < 0 ? 23 : v;
                el.val(v);
            } else {
                v = parseInt(el.val()) + 1;
                v = v > 24 ? 0 : v; 
                el.val(v);
            }
        },
        minuteAction : function(e) {
            var el = this.$(".text-minute"),
                v;
            if ($(e.target).attr("data-action")) {
                v = parseInt(el.val()) - 1;
                v = v < 0 ? 59 : v;
                el.val(v); 
                el.val(v);
            } else {
                v = parseInt(el.val()) + 1;
                v = v > 59 ? 0 : v;  
                el.val(v); 
            }
        }
    });
    new TimePublishView;
})(jQuery);
</script>
