<?php
/**
 * Pi Engine (http://pialog.org)
 *
 * @link            http://code.pialog.org for the Pi Engine source repository
 * @copyright       Copyright (c) Pi Engine http://pialog.org
 * @license         http://pialog.org/license.txt New BSD License
 */

namespace Pi\Filter\File;

use Closure;
use Pi;
use Zend\Filter\File\Rename as ZendRename;

/**
 * File name filter
 *
 * Rename a uploaded file with renaming strategy:
 *
 *  - %term%: file source name
 *  - %random%: unique text generated by {@uniqid()}
 *  - %date:l%: long date format generated by {@date('YmdHis')}
 *  - %date:m%: medium date format generated by {@date('Ymd')}
 *  - %date:s%: short date format generated by {@date('Ym')}
 *  - %time%: time stamp generated by {@time()}
 *  - %microtime%: time stamp in micro-seconds generated by {@microtime()}
 *
 * @author Taiwen Jiang <taiwenjiang@tsinghua.org.cn>
 */
class Rename extends ZendRename
{
    /**
     * File source attributes
     * @var array
     */
    protected $source;

    /**
     * Class constructor
     *
     * {@inheritDoc}
     * @param  string|Closure|array|Traversable $options
     *      Target file or directory to be renamed
     */
    public function __construct($options)
    {
        if ($options instanceof Closure) {
            $options = array('target' => $options);
        }

        parent::__construct($options);
    }

    /**
     * {@inheritDoc}
     */
    protected function _convertOptions($options)
    {
        $files = array();
        foreach ($options as $key => $value) {
            if (is_array($value)) {
                $this->_convertOptions($value);
                continue;
            }

            switch ($key) {
                case "source":
                    $files['source'] = (string) $value;
                    break;

                case 'target' :
                    /**#@+
                     * Enable Closure callback by Taiwen Jiang
                     */
                    //$files['target'] = (string) $value;
                    $files['target'] = $value;
                    /**#@-*/
                    break;

                case 'overwrite' :
                    $files['overwrite'] = (bool) $value;
                    break;

                case 'randomize' :
                    $files['randomize'] = (boolean) $value;
                    break;

                default:
                    break;
            }
        }

        if (empty($files)) {
            return $this;
        }

        if (empty($files['source'])) {
            $files['source'] = '*';
        }

        if (empty($files['target'])) {
            $files['target'] = '*';
        }

        if (empty($files['overwrite'])) {
            $files['overwrite'] = false;
        }

        if (empty($files['randomize'])) {
            $files['randomize'] = false;
        }

        $found = false;
        foreach ($this->files as $key => $value) {
            if ($value['source'] == $files['source']) {
                $this->files[$key] = $files;
                $found             = true;
            }
        }

        if (!$found) {
            $count               = count($this->files);
            $this->files[$count] = $files;
        }

        return $this;
    }

    /**
     * {@inheritDoc}
     */
    public function filter($value)
    {
        if (is_array($value)) {
            $this->setSource($value);
        }

        return parent::filter($value);
    }

    /**
     * {@inheritDoc}
     */
    protected function _getFileName($file)
    {
        $rename = array();
        foreach ($this->files as $value) {
            if ($value['source'] == '*') {
                if (!isset($rename['source'])) {
                    $rename           = $value;
                    $rename['source'] = $file;
                }
            }

            if ($value['source'] == $file) {
                $rename = $value;
                break;
            }
        }

        if (!isset($rename['source'])) {
            return $file;
        }

        if (!isset($rename['target']) || ($rename['target'] == '*')) {
            $rename['target'] = $rename['source'];
        }

        /**#@+
         * Added by Taiwen Jiang
         */
        $this->parseStrategy($rename);
        /**#@-*/

        if (is_dir($rename['target'])) {
            $name = basename($rename['source']);
            $last = $rename['target'][strlen($rename['target']) - 1];
            if (($last != '/') && ($last != '\\')) {
                $rename['target'] .= DIRECTORY_SEPARATOR;
            }

            $rename['target'] .= $name;
        }

        return $rename;
    }

    /**#@+
     * Added by Taiwen Jiang
     */
    /**
     * Generate upload target by parsing specified file target strategy
     *
     * File target strategy defined as a replace pattern with following tags:
     *
     *  - %term%: file source name
     *  - %random%: unique text generated by {@uniqid()}
     *  - %date:l%: long date format generated by {@date('YmdHis')}
     *  - %date:m%: medium date format generated by {@date('Ymd')}
     *  - %date:s%: short date format generated by {@date('Ym')}
     *  - %time%: time stamp generated by {@time()}
     *  - %microtime%: time stamp in micro-seconds generated by {@microtime()}
     *
     * @param array $file
     * @return void
     */
    protected function parseStrategy(&$file)
    {
        if (is_array($this->source)
            && $this->source['tmp_name'] == $file['source']) {
            $name = $this->source['name'];
        } else {
            $name = $file['source'];
        }
        if ($file['target'] instanceof Closure) {
            $target = $file['target']($name);
        } elseif (false !== strpos($file['target'], '%')) {
            $pos = strrpos($name, '.');
            if (false !== $pos) {
                $extension = substr($name, $pos);
                $name = substr($name, 0, $pos);
            } else {
                $extension = '';
            }

            $terms = array(
                '%term%'        => $name,
                '%random%'      => uniqid(),
                '%date:l%'      => date('YmdHis'),
                '%date:m%'      => date('Ymd'),
                '%date:s%'      => date('Ym'),
                '%time%'        => time(),
                '%microtime%'   => microtime(),
            );
            $target = str_replace(
                    array_keys($terms), array_values($terms), $file['target']
            ) . $extension;
        } else {
            return;
        }
        $file['target'] = $target;
    }

    /**
     * Set resource
     *
     * @param array $source
     * @return $this
     */
    public function setSource($source)
    {
        $this->source = $source;

        return $this;
    }
    /**#@-*/
}
