<?php
$this->css($this->assetModule('front/front.css'));
$mode = 'resultonly'; // 'resultonly', 'custom'
?>
<?php if ('default' == $mode) { ?>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo sprintf(__('Google search for %s'), _escape(Pi::config('sitename'))); ?></h3>
        </div>
        <div class="panel-body">
            <script>
                (function() {
                    var cx = '<?php echo $google['code']; ?>';
                    var gcse = document.createElement('script');
                    gcse.type = 'text/javascript';
                    gcse.async = true;
                    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                        '//<?php echo $google['host']; ?>/cse/cse.js?cx=' + cx;
                    var s = document.getElementsByTagName('script')[0];
                    s.parentNode.insertBefore(gcse, s);
                })();
            </script>
            <gcse:search>
                <div class="row" style="margin-top: 20px;">
                    <div class="col-md-offset-2 col-md-8">
                        <div class="well well-lg">
                            <h4>
                                <?php _e('Loading ...'); ?>
                            </h4>
                        </div>
                    </div>
                </div>
            </gcse:search>
        </div>
    </div>

<?php } elseif ('resultonly' == $mode) { ?>
<div class="row">
    <div class="col-md-2">
         <!-- You can define logo in theme -->
        <a class="search-logo" href="<?php echo $this->url('home'); ?>"
           title="<?php _e('Go to home page'); ?>" style="margin-top: 5px;">
            <?php echo _escape(Pi::config('sitename')); ?>
        </a>
    </div>
    <div class="col-md-6">
        <form id="pi-gcse-search-box">
            <div class="input-group">
                <input type="text" name="q" value="<?php echo _escape($google['q']); ?>" class="form-control">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-search"></span> 
                        <?php _e('Google search'); ?>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="google-result">
    <script>
        (function() {
            var cx = '<?php echo $google['code']; ?>';
            var gcse = document.createElement('script');
            gcse.type = 'text/javascript';
            gcse.async = true;
            gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                '//<?php echo $google['host']; ?>/cse/cse.js?cx=' + cx;
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(gcse, s);
        })();
    </script>
    <gcse:searchresults-only>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-offset-2 col-md-8">
                <div class="well well-lg">
                    <h4>
                        <?php _e('Loading ...'); ?>
                    </h4>
                </div>
            </div>
        </div>
    </gcse:searchresults-only>
</div>
<?php } else { ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo sprintf(__('Google search for %s'), _escape(Pi::config('sitename'))); ?></h3>
    </div>
    <div class="panel-body" id="cse" style='width: 100%;'><?php _e('Loading ...'); ?></div>

    <script src="https://<?php echo $google['host']; ?>/jsapi" type="text/javascript"></script>
    <script type="text/javascript">
        google.load('search', '1', {language: '<?php echo Pi::config('locale'); ?>'});
        google.setOnLoadCallback(function(){
            var customSearchControl = new google.search.CustomSearchControl('<?php echo $google['code']; ?>');
            //customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
            customSearchControl.draw('cse');

            // Preload query
            var match = location.search.match(/q=([^&]*)(&|$)/);
            if(match && match[1]){
                var search = decodeURIComponent(match[1]);
                customSearchControl.execute(search);
            }

        });
    </script>

</div>

<?php } ?>