<div class="row">
    <div class="col-md-2">
         <!-- You can define logo in theme -->
        <div class="search-logo">
            <?php echo _escape(Pi::config('sitename')); ?>
        </div>
    </div>
    <div class="col-md-6 ">
        <form method="get" id="js-search-form"
              data-module-url="<?php echo $this->url('search', array('m' => '_NAME')); ?>"
              data-service-url="<?php echo $this->url('search', array('service' => '_NAME')); ?>">
            <div class="search-tabs">
                <a href="#" class="js-search-module<?php if (!$searchModule) { echo ' active'; } ?>">
                    <?php _e('Global'); ?>
                </a>
                <?php 
                foreach ($modules as $name => $data) {
                    echo sprintf(
                        '<a data-name="%s" href="#" class="js-search-module%s">%s</a>',
                        $name,
                        $name == $searchModule ? ' active' : '',
                        _escape($data['title'])
                    );
                }
                ?>
            </div>
            <div class="input-group">
                <input type="text" name="q" class="form-control" 
                       value="<?php echo _escape($query); ?>"
                       placeholder="<?php _e('Keywords'); ?>">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary" onclick="this.form.action=''; this.form.target='';">
                        <span class="fa fa-search"></span> <?php _e('Search'); ?>
                    </button>
                </div>
            </div>
            <div class="search-service">
                <?php
                foreach ($service as $name => $data) {
                    echo sprintf(
                        '<a data-name="%s" href="#" class="js-search-service">%s</a>',
                        $name,
                        _escape($data['title'])
                    );  
                }
                ?>
            </div>
        </form>
    </div>
</div>
<hr>
<script src="<?php echo $this->assetModule('front/search-tabs.js'); ?>"></script>