<?php
$this->css($this->assetModule('front/front.css'));
?>
<style>
.search-tabs,
.search-service {
    text-align: center;
}
</style>
<div class="row">
    <form method="get" class="col-md-6 col-md-offset-3" id="js-search-form"
          data-url="<?php echo $this->url('search'); ?>"
          data-module-url="<?php echo $this->url('search', array('m' => '_NAME')); ?>"
          data-service-url="<?php echo $this->url('search', array('service' => '_NAME')); ?>"
          data-module="<?php echo $searchModule; ?>">
        <!-- You can define logo in theme -->
        <a class="text-hide search-index-logo" href="<?php echo $this->url('home'); ?>">
            <?php echo _escape(Pi::config('sitename')); ?>
        </a>
        <div class="search-tabs">
            <a href="#" class="js-search-global<?php if (!$searchModule) { echo ' active'; } ?>">
                <?php _e('Global'); ?>
            </a>
            <?php 
            foreach ($modules as $name => $data) {
                echo sprintf(
                    '<a data-name="%s" href="#" class="js-search-module%s">%s</a>',
                    $name,
                    $name == $searchModule ? ' active' : '',
                    _escape($data['title'])
                );
            }
            ?>
        </div>
        <div class="input-group">
            <input type="text" name="q" class="form-control" 
                   value="<?php echo !empty($query) ? _escape($query) : ''; ?>"
                   placeholder="<?php _e('Keywords'); ?>">
            <div class="input-group-btn">
                <button type="submit" class="btn btn-primary">
                    <span class="fa fa-search"></span> <?php _e('Search'); ?>
                </button>
            </div>
        </div>
        <div class="search-service">
            <?php
            foreach ($service as $name => $data) {
                echo sprintf(
                    '<a data-name="%s" href="#" class="js-search-service">%s</a>',
                    $name,
                    _escape($data['title'])
                );  
            }
            ?>
        </div>
    </form>
</div>
<script src="<?php echo $this->assetModule('front/search-tabs.js'); ?>"></script>