<?php
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<style>
.asset-itmes li {
    margin-bottom: 2px;
}
.asset-itmes span{
    display: inline-block;
    width: 165px;
    *display: inline;
    *zoom: 1;
}
.asset-itmes ul {
    padding-left: 15px;
}
.asset-itmes ul span {
    width: 150px;
}
</style>

<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('controller' => 'cache', 'action' => 'index')); ?>" title="<?php _e('Cache flush'); ?>"><?php _e('Cache flush'); ?></a>
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'asset', 'action' => 'index')); ?>" title="<?php _e('Asset publish'); ?>"><?php _e('Asset publish'); ?></a>
    <li><a href="<?php echo $this->url('', array('controller' => 'audit', 'action' => 'index')); ?>" title="<?php _e('Audit'); ?>"><?php _e('Audit'); ?></a>
</ul>

<h2 class="page-header"><?php echo $this->escape($title); ?></h2>

<ul class="asset-itmes" id="asset-list">
    <h3><?php _e('Modules'); ?></h3>
    <?php foreach ($modules as $name => $label) { ?>
    <li><span><?php echo $this->escape($label); ?></span><input type="button" value="<?php _e('Publish'); ?>" data-link="<?php echo $this->url('', array('action' => 'publish', 'type' => 'module', 'name' => $name)); ?>" />
    <?php } ?>
    <h3><?php _e('Themes'); ?></h3>
    <?php foreach ($themes as $name => $label) { ?>
    <li><span><?php echo $this->escape($label); ?></span><input type="button" value="<?php _e('Publish'); ?>" data-link="<?php echo $this->url('', array('action' => 'publish', 'type' => 'theme', 'name' => $name)); ?>" />
    <?php } ?>
    <p><input type="button" value="<?php _e('Re-publish all'); ?>" data-link="<?php echo $this->url('', array('action' => 'refresh')); ?>" />
</ul>

<script>
(function($) {
    $("#asset-list").on("click", "input", function() {
       systemMessage.wait("<?php _e('Asset publish in process'); ?>");
       $.getJSON($(this).attr("data-link")).done(function(result) {
          if (result.status == 1) {
             systemMessage.succ(result.message);
          } else {
             systemMessage.fail(result.message);
          }
       });
    });
})(jQuery)
</script>