<h2 class="page-header"><?php _e('Audit list') ?></h2>

<table>
    <tr>
        <td><?php _e('ID') ?></td>
        <td><?php _e('User') ?></td>
        <td><?php _e('IP') ?></td>
        <td><?php _e('Section') ?></td>
        <td><?php _e('Module') ?></td>
        <td><?php _e('Controller') ?></td>
        <td><?php _e('Action') ?></td>
        <td><?php _e('Method') ?></td>
        <td><?php _e('Message') ?></td>
        <td><?php _e('extra') ?></td>
        <td><?php _e('time') ?></td>
    </tr>
    <?php foreach ($items as $row) { ?>
    <tr>
        <td><?php echo $row['id']; ?></td>
        <td><?php echo $row['user']; ?></td>
        <td><?php echo $row['ip']; ?></td>
        <td><?php echo $row['section']; ?></td>
        <td><?php echo $row['module']; ?></td>
        <td><?php echo $row['controller']; ?></td>
        <td><?php echo $row['action']; ?></td>
        <td><?php echo $row['method']; ?></td>
        <td><?php echo $row['message']; ?></td>
        <td><?php echo $row['extra']; ?></td>
        <td><?php echo date('Y-m-d H:i:s', $row['time']); ?></td>
    </tr>
    <?php } ?>
</table>

<?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>

<div style="padding: 10px">
<form method='GET'>
    <?php _e('Count of items to display: '); ?><select id='audit-count' audit-url='<?php echo $this->url('admin', array('controller' => 'audit', 'count' => '')) ?>'>
        <option value='10' <?php echo (!isset($count) or (10 === $count) ? 'selected' : '')?>><?php _e('10') ?></option>
        <option value='20' <?php echo (20 === $count ? 'selected' : '') ?>><?php _e('20') ?></option>
        <option value='50' <?php echo (50 === $count ? 'selected' : '') ?>><?php _e('50') ?></option>
    </select>
</form>
</div>

<script>
(function($) {
    $("#audit-count").change(function() {
        var $this = $(this);
        location.href = $this.attr('audit-url') + $this.val();
    })
})(jQuery)
</script>