<?php
    $this->css($this->assetModule('admin/admin.css'));
    $this->jQuery();
    //$this->js($this->assetModule('script/system-msg.js', 'system'));
?>

<ul class="nav nav-tabs">
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'audit', 'action' => 'index')); ?>" title="<?php echo _a('Audit'); ?>"><?php echo _a('Audit'); ?></a></li>
    <li class="disabled"><a href="#" title="<?php echo _a('Mailing'); ?>"><?php echo _a('Mailing'); ?></a></li>
</ul>

<h2 class="page-header"><?php echo _a('Audit list') ?></h2>

<table class="table table-hover">
    <thead>
        <td width="12%"><?php echo _a('time') ?></td>
        <td width="5%"><?php echo _a('User') ?></td>
        <td width="5%"><?php echo _a('IP') ?></td>
        <td width="2%"><?php echo _a('Section') ?></td>
        <td width="8%"><?php echo _a('Module') ?></td>
        <td width="8%"><?php echo _a('Controller') ?></td>
        <td width="8%"><?php echo _a('Action') ?></td>
        <td width="2%"><?php echo _a('Method') ?></td>
        <td width="30%"><?php echo _a('Message') ?></td>
        <td><?php echo _a('extra') ?></td>
    </thead>
    <?php foreach ($items as $row) { ?>
    <tr>
        <td><?php echo _date($row['time']); ?></td>
        <td><?php echo $row['user']; ?></td>
        <td><?php echo $row['ip']; ?></td>
        <td><?php echo $row['section']; ?></td>
        <td><?php echo $row['module']; ?></td>
        <td><?php echo $row['controller']; ?></td>
        <td><?php echo $row['action']; ?></td>
        <td><?php echo $row['method']; ?></td>
        <td><?php echo $row['message']; ?></td>
        <td><?php echo $row['extra']; ?></td>
    </tr>
    <?php } ?>
</table>

<?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>

<div style="padding: 10px">
<form method='GET'>
    <?php echo _a('Count of items to display: '); ?><select id='audit-count' audit-url='<?php echo $this->url('admin', array('controller' => 'audit', 'count' => '')) ?>'>
        <option value='10' <?php echo (!isset($count) or (10 === $count) ? 'selected' : '')?>><?php echo _a('10') ?></option>
        <option value='20' <?php echo (20 === $count ? 'selected' : '') ?>><?php echo _a('20') ?></option>
        <option value='50' <?php echo (50 === $count ? 'selected' : '') ?>><?php echo _a('50') ?></option>
    </select>
</form>
</div>

<script>
(function($) {
    $("#audit-count").change(function() {
        var $this = $(this);
        location.href = $this.attr('audit-url') + $this.val();
    })
})(jQuery)
</script>