<?php
    $this->css($this->assetModule('admin/admin.css'));
    $this->jQuery();
    $this->backbone();
?>
<div id="block-list-page" class="block-list-page">
    <?php if(empty($blocks)) { ?>
    <div class="alert alert-info">
        <?php echo _a('No block available.'); ?>
    </div>
    <?php } else { ?>
    <input type="text" placeholder="<?php echo _a('Search in block title'); ?>" class="js-search">
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width: 20%;"><?php echo _a('Title'); ?></th>
                <th style="width: 30%;"><?php echo _a('Description'); ?></th>
                <th style="width: 20%;"><?php echo _a('Related pages'); ?></th>
                <th><?php echo _a('Action'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($blocks as $block) { ?>
            <tr data-id="<?php echo $block['id']; ?>">
                <td>
                    <span class="block-title"><?php echo _escape($block['title']); ?></span>
                </td>
                <td>
                    <?php echo _escape($block['description']); ?>
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
                            <?php echo _a('pages'); ?>
                            <span  class="caret"></span>
                        </a>
                        <ul class="dropdown-menu nav nav-list"></ul>
                    </div>
                </td>
                <td>
                    <div class="btn-group btns-indent">
                        <a class="btn btn-link"  href="<?php echo $this->url('', array('action' => 'edit', 'id' => $block['id'], 'name' => $block['module'])); ?>"><?php echo _a('Edit'); ?></a>
                        <?php if ($block['cloned']) { ?>
                        <a class="btn btn-link js-delete"><?php echo _a('Delete'); ?></a>
                        <?php } elseif ($block['clonable']) { ?>
                        <a class="btn btn-link" href="<?php echo $this->url('', array('action' => 'clone', 'root' => $block['root'], 'name' => $block['module'])); ?>"><?php echo _a('Clone'); ?></a>
                        <?php } ?>
                    </div>
                </td>    
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <?php } ?>
</div>
<script id="temp-popover" type="text/template">
    <% if(data.length) { %>
    <% _.each(data, function(item) { %>
    <li>
        <strong class="nav-header"><%= item.title %></strong>
        <% _.each(item.pages,function(page) { %>
        <li><a href="<%= page.url %>"><%= page.title %></a></li>
        <% }); %>
    </li>
    <% }); %>
    <% } else { %>
    <li class="label label-info"><?php echo _a('No page uses this block yet.'); ?></li>
    <% } %>
</script>
<script>
(function($){
    var page = {
        el: $('#block-list-page'),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            this.$('a[data-toggle]').click(_.bind(this.pageAction, this));
            this.$('.js-search').keyup(_.bind(this.search, this));
            this.$('.js-delete').click(_.bind(this.deleteAction, this))
        },
        deleteAction: function(e) {
            var tar = $(e.target);
            if (confirm('<?php echo _a('Are you sure to delete this block? '); ?>')) {
                $.get('<?php echo $this->url('', array('action' => 'delete', 'id' => '')); ?>' + this.getId(tar)).done(function(res) {
                    res == 1 && tar.parents('tr').remove();
                });
            }
        },
        pageAction: function(e) {
            var tar = $(e.target);
            if (!tar.attr('data-load')) {
                $.getJSON('<?php echo $this->url('', array('action' => 'page', 'id' => '')); ?>' + this.getId(tar)).done(function(res) {
                    res = _.toArray(res);
                    tar.siblings('ul').html(_.template($("#temp-popover").html(), res, { variable: 'data' }));
                    tar.attr('data-load', 1);
                });
            }
        },
        search: function(e) {
            var v = $.trim($(e.target).val());
            this.$('.block-title').each(function() {
                var $this = $(this);
                console.log($this.html().indexOf(v));
                if ($this.html().toLowerCase().indexOf(v.toLowerCase()) == -1) {
                    $this.parents('tr').hide();
                } else {
                    $this.parents('tr').show();
                }
            });
        },
        getId: function(tar) {
            return tar.parents('tr').attr('data-id');
        }
    }
    page.init();
})(jQuery)
</script>
