<?php
    $this->css($this->assetModule('admin/admin.css'));
    $this->jQuery();
    $this->backbone();
?> 
<div id="page-list-page" class="page-list-page">
    <form method="POST">
        <?php foreach ($pagesBySection as $key => $section) { ?>
        <fieldset>
            <legend><?php echo $section['title']; ?></legend>
            <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 40%;"><?php echo _a('Title'); ?></th>
                    <th><?php echo _a('Expiration'); ?></th>
                    <th><?php echo _a('Cache level'); ?></th>
                    <th><?php echo _a('Cache scope'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($section['pages'] as $page) { ?>
                <tr data-id="<?php echo $page['id']; ?>">
                    <td>
                        <?php echo _escape($page['title']); ?>
                    </td>
                    <td>
                        <?php echo $page['ttl']; ?>
                    </td>
                    <td>
                        <?php echo $page['level']; ?>
                    </td>
                    <td>
                        <?php echo $page['type']; ?>
                    </td>
                </tr>
                <?php } ?>
             </tbody>
            </table>
        </fieldset>
        <?php } ?>
        <input type="submit" class="btn btn-default btn-primary" name="submit" value="<?php _e('Submit'); ?>">
        <input type="reset" class="btn btn-default" name="cancel" value="<?php _e('Cancel'); ?>">
    </form>
</div>
