<div class="config-page">
    <?php if (empty($name)) { ?>
        <div class="alert alert-info"><?php _e('Select a module on the left to set up configurations.'); ?></div>
    <?php } elseif (empty($form)) { ?>
        <div class="alert alert-info"><?php _e('No configuration available.'); ?></div>
    <?php } else { ?>
    <?php include $this->templateComponent('form'); ?>
    <?php } ?>     
</div>