<div class="row">
   <div class="span3">
        <div class="sub-nav">
        <?php
        $items = array();
        foreach ($categories as $name => $cate) {
            $item = array(
                'href'  => $this->url('', array('action' => 'index', 'category' => $cate->name)),
                'label' => $cate->title,
            );
            if ($cate->name == $category) {
                $item['active'] = 1;
            }
            $items[] = $item;
        }
        echo $this->navMenu($items);
        ?>
        </div>
   </div>
    <div class="span9">
        <h2 class="page-header"><?php echo $this->escape($title); ?></h2>
        <?php include $this->templateComponent('form'); ?>
    </div>
</div>