<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="clearfix">
    <?php if ($cronActive) { ?>
        <div class="alert alert-success" role="alert">
            <?php echo _a('Cron system is active, you can inactive it from system configurations'); ?>
        </div>

        <div class="alert alert-info" role="alert">
            <?php echo sprintf(_a('Cron password is <strong>%s</strong> , you can change it from system configurations and Cron log save on <strong>%s/cron.log</strong>'), $cronPassword, Pi::path('log')); ?>
        </div>

        <div class="form-group">
            <label for="cronUrl"><?php _e('Cron URL'); ?></label>
            <input type="text" class="form-control" id="cronUrl" value="<?php echo $this->escape($cronUrl); ?>">
        </div>
        <div class="form-group">
            <label for="cronUrl"><?php _e('Cron Command'); ?></label>
            <input type="text" class="form-control" id="cronCommand" value="GET <?php echo $this->escape($cronUrl); ?>">
            <p class="help-block"><?php _e('Set cron command on your server and set cron time'); ?></p>
        </div>
        <div class="form-group">
            <button class="btn btn-primary manual-cron"><?php echo _a('Do cron manfully'); ?></button>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php echo _a('Cron system is inactive, you can active it from system configurations'); ?>
        </div>
    <?php } ?>
</div>
<script>
    (function ($) {
        $('.manual-cron').on('click', function () {
            if (confirm('<?php _e('Are you sure to do cron manually?'); ?>')) {
                systemMessage.wait("<?php _e('manual cron in process'); ?>");
                $.getJSON('<?php echo $this->escape($cronUrl); ?>').done(function (result) {
                    if (result.status == 1) {
                        systemMessage.succ(result.message);
                    } else {
                        systemMessage.fail(result.message);
                    }
                });
            }
        });
    })(jQuery)
</script>