<?php
    $this->jQuery('ui/jquery-ui.custom.min.js');
    $this->css(array(
        $this->assetModule('script/system-ui.css')
    ));
    $this->backbone();
?>
<div class="page-header">
    <h2><?php echo $this->escape($title); ?></h2>
</div>
<div class="row-fluid">
    <div class="span8">
        <div class="pi-widget system-notice" id="system-js-notice">
            <div class="media pi-widget-body">
                <span class="pull-left">
                    <i class="icon-bullhorn icon-large"></i>
                </span>
                <div class="media-body">
                    <div class="system-notice-show">
                        <p>
                            <span class="system-js-notice-content"><?php echo $message['content']; ?></span>
                            <em class="muted gutter-large system-js-notice-time"><?php echo $message['time']; ?></em>
                        <?php if ($messagePerm) { ?>
                        <div>
                            <a href="javascript:void(0)" class="system-js-edit">
                                <i class="icon-pencil"></i>
                                <?php _e('Edit'); ?>
                            </a>
                        </div>
                        <?php } ?>
                    </div>
                    <div class="hide system-notice-edit">
                        <textarea class="span8" placeholder="<?php _e('notice'); ?>"></textarea>
                        <p class="muted">
                            <?php _e('Add/update site announcement.'); ?>
                        <div>
                            <span class="btn system-js-save"><?php _e('Save'); ?></span>
                            <span class="btn btn-link system-js-cancel"><?php _e('Cancel'); ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-widget system-quick-link" id="system-js-quick-link">
            <div class="clearfix pi-widget-header">
                <div class="pull-right">
                    <span class="btn system-quick-all-edit system-js-all-edit"><?php _e('Edit'); ?></span>
                    <span class="hide btn system-quick-all-save system-js-all-save" data-placement="top" data-original-title="<?php _e('Click the button to switch to view mode.'); ?>"><?php _e('Save'); ?></span>
                </div>
                <strong><?php _e('Quick links')?></strong>
            </div>
            <div class="pi-widget-body">
                <div class="hide well form-horizontal system-quick-link-form">

                </div>
                <div class="system-quick-link-box">
                    <div class="inline-block system-quick-link-add system-js-add">
                        <i class="icon-plus icon-large"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-widget system-module-summary" id="system-js-module-summary">
            <div class="clearfix pi-widget-header">
                <div class="pull-right">
                    <span class="btn system-js-all"><?php _e('Toggle all'); ?></span>
                </div>
                <strong><?php _e('Module summary')?></strong>
            </div>
            <div class="pi-widget-body">
                <div class="accordion" id="summary-accordion">
                    <?php foreach($summaryList as $i => $item) { ?>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                             <span class="accordion-toggle" data-toggle="collapse" data-parent="#summary-accordion" href="#collapse<?php echo $item['name']; ?>"><?php echo $item['title']; ?></span>
                        </div>
                        <div id="collapse<?php echo $item['name']; ?>" class="accordion-body collapse <?php if($i == 0) { echo 'in'; } ?>">
                            <div class="accordion-inner">
                                <?php echo $item['content']; ?>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="pi-widget">
            <div class="pi-widget-header">
                <strong><?php _e('Powered by Pi Engine'); ?></strong>
            </div>
            <div class="pi-widget-body">
                <p><?php _e('
                    Pi Engine is a role oriented application development engine for web and mobile, designed as the next generation and a successor to Xoops.
                    Pi is developed upon PHP and MySQL with selected third-party frameworks including but not limited to Zend Framework library, jQuery, Bootstrap and Backbone.
                    ');?>
                </p>
                <p><?php _e('
                    Pi Project follows the philosophy of open standard, open design, open development and open structure.
                    Pi is born as a complete open source project and intended to build a sustainable ecosystem that benefits all contributors and users.
                    ');?>
                </p>
                <p>
                    <a href="http://www.pialog.org" title="Pi Engine" target="_blank">Find Pi</a> &raquo;
                    <a href="http://code.pialog.org" title="Pi Code" target="_blank">code</a> &bull;
                    <a href="http://doc.pialog.org" title="Pi Doc" target="_blank">doc</a> &bull;
                    <a href="http://bug.pialog.org" title="Pi Bug" target="_blank">talk</a> &bull;
                    <a href="http://ask.pialog.org" title="Ask Pi" target="_blank">ask</a> &bull;
                    <a href="http://api.pialog.org" title="Pi API" target="_blank">API</a>
                </p>
            </div>
        </div>
    </div>
</div>
<script id="temp-link" type="text/template">
    <div class="ellipsis inline-block system-quick-link-text">
        <a href="<%= url %>" title="<%= title %>"><%= title %></a>
    </div>
    <div class="inline-block system-quick-link-icon">
        <i class="icon-pencil system-js-edit" title="<?php _e('Edit'); ?>"></i>
        <i class="icon-remove system-js-remove" title="<?php _e('Remove'); ?>"></i>
    </div>
</script>
<script id="temp-form" type="text/template">
    <div class="control-group">
        <label class="control-label"><?php _e('Title'); ?></label>
        <div class="controls">
            <input type="text" name="title" value="<%= form.title %>">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label"><?php _e('URL'); ?></label>
        <div class="controls">
            <input type="text" name="url" value="<%= form.url %>">
        </div>
    </div>
    <div class="controls">
        <span class="btn system-js-save" data-action="<%= form.action %>"><?php _e('Save'); ?></span>
        <span class="btn btn-link system-js-cancel"><?php _e('Cancel'); ?></span>
    </div>
</script>
<script src="<?php echo $this->assetModule('/script/dashboard-system.js'); ?>"></script>
<script>
dashboardSystem({
    quicLinkCollection: new Backbone.Collection(<?php echo json_encode($links); ?>),
    messageUrl: '<?php echo $this->url('', array('action' => 'message')); ?>',
    linkUrl: '<?php echo $this->url('', array('action' => 'link')); ?>'
});
</script>