<?php
    $this->bootstrap();
    $this->css(array(
        $this->assetModule('script/system-ui.css', 'system')
    ));
?>
<div class="page-header">
    <h2><?php echo $this->escape($title); ?></h2>
</div>
<div class="row-fluid">
    <div class="span8">
        <div class="pi-widget">
             <div class="pi-widget-header">
                 <strong><?php _e('About')?></strong>
             </div>
             <div class="pi-widget-body">
                 <div class="media">
                     <img src="<?php echo $data['logo']; ?>" class="pull-left">
                     <div class="media-body">
                         <fieldset style="margin-top: -10px;">
                             <legend><?php _e('Module information'); ?></legend>
                             <dl class="dl-horizontal">
                                 <dt><?php _e('Title:'); ?>
                                 <dd><?php echo $this->escape($data['title']); ?>
                                 <dt><?php _e('Version:'); ?>
                                 <dd><?php echo $this->escape($data['version']); ?>
                                 <dt><?php _e('Update:'); ?>
                                 <dd><?php echo $this->escape($data['update']); ?>
                                 <dt><?php _e('Description:'); ?>
                                 <dd><?php echo $this->escape($data['description']); ?>
                                 <?php if (!empty($data['demo'])) { ?>
                                 <dt><?php _e('Demo:'); ?>
                                 <dd><?php echo $this->escape($data['demo']); ?>
                                 <?php } ?>
                             </dl>
                         </fieldset>
                         <fieldset>
                             <legend><?php _e('Author information'); ?></legend>
                             <dl class="dl-horizontal">
                                <?php foreach ($data['author'] as $key => $value) {
                                    echo '<dt>' . _escape($key) . ':';
                                    echo '<dd>' . _escape($value);
                                }?>
                             </dl>
                         </fieldset>
                     </div>
                 </div>
             </div>
        </div>
        <?php if ($summary) { ?>
        <div class="pi-widget">
             <div class="pi-widget-header">
                 <strong><?php _e('Summary'); ?></strong>
             </div>
             <div class="pi-widget-body">
                 <?php echo $summary; ?>
             </div>
        </div>
        <?php } ?>
    </div>
    <div class="span4"></div>
</div>
