<?php
    $this->css($this->assetModule('admin/admin.css'));
?>

<div class="clearfix">
    <?php if (isset($message)) { ?>
        <div class="alert alert-danger">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php echo $message; ?>
        </div>
    <?php } ?>
    <div class="alert alert-success" role="alert">
        <?php _e('You can use this page tools for check some database integrity'); ?>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo _a('Check for encoding'); ?>
                </div>
                <div class="panel-body">
                    <p>
                        <?php echo _a('This tool help you to check non-utf8 data fields for all tables'); ?>
                    </p>
                    <p>
                        <a href="<?php echo $this->url('', array('action' => 'check')); ?>" class="btn btn-primary btn-sm">
                            <i class="fa fa-cog" aria-hidden="true"></i>
                            <?php echo _a('Check UTF8'); ?>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>