<?php
    $this->css($this->assetModule('admin/admin.css'));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<style>
.event-itmes {
    font-size: 14px;
    line-height: 24px;
}
.event-itmes th {
    text-align: left;
    font: bold 16px/28px arial;
}
.disable {
    color: #888a8b;
}
</style>

<ul class="tabmenu">
    <li><a href="<?php echo $this->url('', array('action' => 'index')); ?>" title="<?php echo _a('Check events'); ?>"><?php echo _a('Events'); ?></a>
    <li class="tabmenu-active"><?php echo _a('Listeners'); ?>
</ul>
<ul class="submenu1">
<?php foreach ($modules as $module) { ?>
    <?php if ($name == $module->name) { ?>
    <li class="active"><?php echo _escape($module->title); ?></li>
    <?php } else { ?>
    <li><a href="<?php echo $this->url('', array('action' => 'listener', 'name' => $module->name)); ?>" title="<?php echo _escape($module->title); ?>"><?php echo _escape($module->title); ?></a></li>
    <?php } ?>
<?php } ?>
</ul>
<div class="submain">
<table class="event-itmes" id="event-list">
   <thead>
         <th style="width: 240px;">listeners
         <th style="width: 240px;">Events
         <th>Operation
   </thead>
   <tbody>
     <?php foreach ($listeners as $id => $listener) { ?>
    <tr class="<?php echo $event['active']?"":"disable";  ?>">
        <td><?php echo $listener['title']; ?></td>
        <td><?php echo $listener['event']; ?></td>
        <td><button class="pi-ui-btn1" data-action="<?php echo $listener['active']; ?>" data-link="<?php echo $this->url('', array('action' => 'active', 'type' => 'listener', 'id' => $listener['id'])); ?>"><?php $listener['active'] ? echo _a('Disable') : echo _a('Enable'); ?></button></td>
    <?php } ?>
   </tbody>

</table>
</div>
<script>
(function($) {
    $("#event-list").on("click", "button", function() {
        var $this = $(this);
        beautAlert.done("<?php echo _a('Being updated.'); ?>", "wait");
        $.getJSON($this.attr("data-link")).done(function(result) {
            if (result.status == 1) {
                if ($this.attr("data-action") == "0") {
                    $this.html("<?php echo _a('Disable'); ?>");
                    $this.attr("data-action", "1").parents("tr").removeClass("disable");
                } else {
                    $this.html("<?php echo _a('Enable'); ?>");
                    $this.attr("data-action", "0").parents("tr").addClass("disable");
                }
                beautAlert.done(result.message, "succ");
            } else {
                beautAlert.done(result.message, "fail");
            }
        });
    });
})(jQuery)
</script>