<div class="card card-body bg-light mb-3">
    <div class="card-heading">
        <h2 class="card-title"><?php echo $title; ?></h2>
    </div>
    <div class="card-text">
        <?php echo _a('There is no entry page for this module management. Please:'); ?>
    </div>
    <ul>
        <li>
            <a href="<?php echo $this->url('', ['module' => 'system', 'controller' => 'config', 'action' => 'module', 'name' => $module]); ?>"
               title="<?php echo _a('Module config'); ?>"><?php echo _a('Go to set up module configs;'); ?></a></li>
        <li><a href="<?php echo $this->url('', ['module' => 'system', 'controller' => 'dashboard']); ?>"
               title="<?php echo _a('System admin'); ?>"><?php echo _a('Go back to system dashboard.'); ?></a></li>
    </ul>
</div>