<?php
    $this->css($this->assetModule('script/system-ui.css'));
?>
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>
<div class="mb10">
    <a class="btn btn-primary" href="<?php echo $this->url('', array('action' => 'add')); ?>" title="<?php _e('Add a member'); ?>"><?php echo __('Add a member'); ?></a>
</div>

<div style="padding: 10px">
<form method='GET'>
    <?php _e('Select a role: '); ?><select id='role-selection' list-url='<?php echo $this->url('admin', array('controller' => 'member', 'action' => 'role', 'role' => '')) ?>'>
    <?php foreach ($roles as $roleName => $roleTitle) { ?>
        <option value="<?php echo $roleName; ?>"<?php if (isset($role) && $role == $roleName) { echo ' selected'; } ?>><?php echo $this->escape($roleTitle); ?></option>
    <?php } ?>
    </select>
</form>
</div>


<table class="table table-striped">
    <tbody>
        <tr>
            <th><?php _e('Identity'); ?></th>
            <th style="width:10%;"><?php _e('Name'); ?></th>
            <th style="width:14%"><?php _e('Email'); ?></th>
            <th style="width:8%"><?php _e('User role'); ?></th>
            <th style="width:8%"><?php _e('Staff role'); ?></th>
            <th style="width:8%"><?php _e('Active'); ?></th>
        </tr>
        <?php foreach ($users as $id => $user) { ?>
        <tr>
            <td>
                <?php echo $this->escape($user['identity']); ?>
                <div class="row-actions">
                    <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $user['id'])); ?>" title="<?php _e('Edit'); ?>"><?php _e('Edit'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'password', 'id' => $user['id'])); ?>" title="<?php _e('Password'); ?>"><?php _e('Password'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'delete', 'id' => $user['id'])); ?>" title="<?php _e('Delete'); ?>"><?php _e('Delete'); ?></a>
                </div>
            </td>
            <td><?php echo $user['name'] ? $this->escape($user['name']) : ''; ?></td>
            <td><?php echo $user['email'] ? $this->escape($user['email']) : __('Not set'); ?></td>
            <td><?php echo $this->escape($user['role']); ?></td>
            <td><?php echo $this->escape($user['role_staff']); ?></td>
            <td><?php echo $user['active'] ? __('Yes') : __('No'); ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
<script>
(function($) {
    $("#role-selection").change(function() {
        var $this = $(this);
        location.href = $this.attr('list-url') + $this.val();
    })
})(jQuery)
</script>