<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
?>
<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('action' => 'index')); ?>" title="<?php _e('Installed'); ?>"><?php _e('Installed'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('action' => 'available')); ?>" title="<?php _e('Availables'); ?>"><?php _e('Availables'); ?></a></li>
    <li class="disabled"><a title="<?php _e('Repository'); ?>"><?php _e('Repository'); ?></a></li>
</ul>
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>
<?php
    if ($error) {
        echo '<div class="alert alert-error"><button data-dismiss="alert" class="close" type="button">×</button>' . $this->escape($error) . '</div>';
    } else {
        echo sprintf('<div class="alert alert-success"><button data-dismiss="alert" class="close" type="button">×</button>%s<a href="%s" title="">%s</a></div>', $this->escape($message), $url, __('Press to continue ...'));
        //echo '<script>setTimeout(function() {location.href ="' . $url . '"}, 1500);</script>';
    }
    if ($details) {
        echo '<ol class="module-ol">';
        foreach ($details as $action => $state) {
            if (isset($state['status']) && $state['status'] === false) {
                echo '<li>' . $this->escape($action)  . ': <strong class="text-error">' . __('Failed') . '</strong><script>$(".alert-success").addClass("alert-error")</script></li>';
            } else {
                echo '<li>' . $this->escape($action)  . ': <strong class="text-success">' . __('Succeeded'). '</li>';
            }
            if (!empty($state['message'])) {
                foreach ((array) $state['message'] as $msg) {
                    echo '<div class="indent">' . $this->escape($msg) . '</div>';
                }
            }
        }
        echo '</ol>';
    }
?>
