<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->backbone();
?>
<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('action' => 'index')); ?>" title="<?php _e('Installed'); ?>"><?php _e('Installed'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url('', array('action' => 'available')); ?>" title="<?php _e('Availables'); ?>"><?php _e('Availables'); ?></a></li>
    <li class="disabled"><a><?php _e('Repository'); ?></a></li>
</ul>

<div class="avail-module-page" id="js-module">
    <table class="table">
        <thead>
            <tr>
                <th style="width: 10%;"><?php _e('Icon'); ?>
                <th style="width: 15%;"><?php _e('Title'); ?>
                <th style="width: 15%;"><?php _e('Version'); ?>
                <th style="width: 30%;"><?php _e('Description'); ?>
                <th><?php _e('Action'); ?>
        <tbody>
            <?php foreach ($modules as $directory => $module) { ?>
            <tr class="module-item"
                data-name="<?php echo $directory; ?>"
                data-clone="<?php echo $this->url('', array('action' => 'clone', 'directory' => $directory)); ?>">
                <td>
                    <img src="<?php echo $module['meta']['logo']; ?>" alt="<?php echo $this->escape($module['meta']['title']); ?>">
                <td>
                    <strong><?php echo $this->escape($module['meta']['title']); ?></strong>
                <td>
                    <?php echo $module['meta']['version']; ?>
                <td>
                    <div class="module-p"><?php echo $this->escape($module['meta']['description']); ?></div>
                    <a href="javascript:void(0)" class="invisible detail-action"><?php _e('Detail'); ?></a>
                    <div class="hide well well-small">
                        <dl class="dl-horizontal">
                            <dt><?php _e('Directory:'); ?>
                            <dd><?php echo $directory; ?>
                            <dt><?php _e('Author:'); ?>
                            <dd>
                                <?php if (!empty($module['author']['website'])) { ?>
                                <a href="<?php echo $module['author']['website']; ?>" target="_blank"><?php echo $this->escape($module['author']['name']);  ?></a><br>
                                <?php } ?>
                                <?php echo $module['author']['email'];  ?>
                             <?php if (!empty($module['meta']['demo'])) { ?>
                             <dt><?php _e('Demo:'); ?>
                             <dd><a href="<?php echo $module['meta']['demo']; ?>" target="_blank"><?php _e('In action'); ?></a>
                             <?php } ?>
                        </dl>
                    </div>
                <td>
                    <div class="btn-group">
                    <?php
                        if (empty($module['meta']['installed'])) {
                            $buttonClass = '';
                            $installUrl = $this->url('', array('action' => 'install', 'directory' => $directory));
                        } else {
                            $buttonClass = ' disabled';
                            $installUrl = 'javascript:void(0)';
                        }
                        echo sprintf('<a class="btn%s" href="%s">%s</a>', $buttonClass, $installUrl, __('Install'));
                    ?>
                    <?php if (!empty($module['meta']['clonable'])) { ?>
                    <span class="btn module-clone"><?php _e('Clone'); ?></span>
                    <?php } ?>
                    </div>
            <?php } ?>
    </table>
</div>
<script>
(function($) {
    // Note implemented yet
    //var checkUrl = "<?php echo $this->url('', array('controller' => 'repo', 'action' => 'check', 'type' => 'module', 'name' => '')); ?>";
    var page = {
        el: $('#js-module'),
        modal: $('<div class="modal hide fade">').appendTo(document.body),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            this.$('.module-clone').click(this.cloneAction);
            this.$('.detail-action').click(this.toggleDetail);
        },
        cloneAction: function(e) {
            var p = $(e.target).parents('tr'),
                self =this;
            $.get(p.attr('data-clone')).done(function(res) {
                self.modal.html(res).modal('show');
                formModule.success = function(res) {
                    var d = res.data;
                    location.href = '/admin/system/module/install/name/' + d.name + '/directory/' + d.directory + '/title/' + d.title;
                };
            });
        },
        toggleDetail: function(e) {
            $(e.target).siblings('.well').toggle();
        }
    }
    page.init();
})(jQuery)
</script>