<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->backbone();
?>
<ul class="nav nav-tabs">
    <li class="active"><a href="<?php echo $this->url('', array('action' => 'index')); ?>" title="<?php _e('Installed'); ?>"><?php _e('Installed'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('action' => 'available')); ?>" title="<?php _e('Availables'); ?>"><?php _e('Availables'); ?></a></li>
    <li class="disabled"><a><?php _e('Repository'); ?></a></li>
</ul>
<div id="js-module">
    <table class="table">
        <thead>
            <tr>
                <th style="width: 10%;"><?php _e('Logo'); ?></th>
                <th style="width: 15%;"><?php _e('Title'); ?></th>
                <th style="width: 10%;"><?php _e('Version'); ?></th>
                <th style="width: 15%;"><?php _e('Last Update'); ?></th>
                <th style="width: 30%;"><?php _e('Description'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($modules as $module) { ?>
            <tr class="<?php if (!$module['active']) { echo 'muted system-module-disable'; } else { echo 'system-module-item'; } ?>">
                <td>
                    <div class="module-item-logo">
                        <img src="<?php echo $module['logo']; ?>" alt="<?php echo $module['title']; ?>">
                    </div>
                </td>
                <td>
                    <div class="module-item-title">
                        <p><strong><?php echo $module['title']; ?></strong></p>
                        <div class="hide module-title-input">
                            <input type="text" class="input-medium" data-id="<?php echo $module['id']; ?>">
                        </div>
                        <a href="javascript:void(0)" class="invisible rename-action"><?php _e('Rename'); ?></a>
                    </div>
                </td>
                <td>
                    <?php echo $module['version']; ?>
                </td>
                <td>
                    <p><?php echo $module['update']; ?></p>
                    <a href="<?php echo $this->url('', array('action' => 'update', 'id' => $module['id'] )); ?>" class="invisible"><?php _e('update'); ?></a>
                </td>
                <td>
                    <p><?php echo $module['description']; ?></p>
                    <a href="javascript:void(0)" class="invisible detail-action"><?php _e('Detail'); ?></a>
                    <div class="hide well well-small">
                        <dl class="dl-horizontal">
                            <dt><?php _e('Name:'); ?></dt>
                            <dd><?php echo $module['name']; ?></dd>
                            <dt><?php _e('Directory:'); ?></dt>
                            <dd><?php echo $module['directory']; ?></dd>
                            <dt><?php _e('Author'); ?></dt>
                            <dd>&nbsp;</dd>
                            <?php foreach ($module['author'] as $key => $value) {
                                echo '<dt>' . _escape($key) . ':</dt>';
                                echo '<dd>' . _escape($value) . '</dd>';
                            }?>
                        </dl>
                    </div>
                </td>
                <td>
                    <div class="btn-group">
                        <?php
                        if($module['name'] != 'system') {
                            if ($module['active']) {
                                echo sprintf('<a class="btn" href="%s">%s</a>', $this->url('', array( 'action' => 'enable', 'id' => $module['id'], 'active' => 0 )), __('Disable'));
                            } else {
                                echo sprintf('<a class="btn" href="%s">%s</a>', $this->url('', array( 'action' => 'enable', 'id' => $module['id'], 'active' => 1 )), __('Enable'));
                            }
                            echo sprintf('<a class="btn" href="%s" onclick="return confirm(\'%s\')">%s</a>', $this->url('', array( 'action' => 'uninstall', 'id' => $module['id'] )), __('Are you sure uninstall this module?') ,__('Uninstall'));
                        } ?>
                    </div>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<script>
(function($){
    var page = {
        el: $('#js-module'),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            var self = this;
            this.$('.detail-action').click(this.toggleDetail);
            this.$('.rename-action').click(this.rename);
            this.$('input[type=text]').blur(this.renameAction).keyup(function(e) {
                if (e.keyCode == 13) {
                    self.renameAction(e);
                }
            });
        },
        toggleDetail: function(e) {
            $(e.target).siblings('.well').toggle();
        },
        rename: function(e) {
            var $this = $(e.target);
            var p = $this.parent();
            p.addClass('module-item-title-edit');
            p.find('input').focus().val($.trim(p.find('strong').html()));
        },
        renameAction: function(e) {
            var $this = $(e.target);
            var val = $.trim($this.val());
            var p = $this.parents('.module-item-title');
            if (val) {
                $.post("<?php echo $this->url('', array('action' => 'rename')); ?>", {
                    id: $this.attr('data-id'),
                    title: val
                }).done(function(res) {
                    res = $.parseJSON(res);
                    if (res.status) {
                        p.removeClass('module-item-title-edit');
                        p.find('strong').html(res.data.title);
                    }
                });
            } else {
                p.removeClass('module-item-title-edit');
            }
        }
    }
    page.init();
})(jQuery)
</script>