<?php
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->Backbone();
?>

<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('action' => 'index')); ?>" title="<?php _e('Navigation in action'); ?>"><?php _e('Navigation in action'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url('', array('action' => 'list')); ?>" title="<?php _e('Navigation list'); ?>"><?php _e('Navigation list'); ?></a></li>
</ul>
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>
<div id="js-nav-select" class="span12">
    <ul>
        <li class="self-nav">
            <div class="legend"><?php _e('Global navigations'); ?></div>
            <ul>
                <li class="box-hover">
                    <div class="pull-right">
                        <span class="btn nav-clone1" data-link="<?php echo $this->url('', array('action' => 'clone', 'name' => 'system-front')); ?>"><?php _e('Clone'); ?></span>
                        <a class="btn" target="_Manipulation" href="<?php echo $this->url('', array('action' => 'data', 'name' => 'system-front', 'readonly' => 1)); ?>" title="<?php _e('Click to view the details.'); ?>"><?php _e('View detail'); ?></a>
                    </div>
                    <span><?php _e('Global navigation'); ?></span>
                </li>    
            </ul>
        <?php foreach ($navModule['front'] as $module => $list) { ?>
        <li class="self-nav">
            <div class="legend"><?php echo $modules[$module]['title']; ?></div>
            <ul>
                <?php foreach ($list as $nav) { ?>
                <li class="box-hover">
                    <div class="pull-right">
                        <span class="btn nav-clone1" data-link="<?php echo $this->url('', array('action' => 'clone', 'name' => $nav['name'])); ?>"><?php _e('Clone'); ?></span>
                        <a class="btn" target="_Manipulation" href="<?php echo $this->url('', array('action' => 'data', 'name' => $nav['name'], 'readonly' => 1)); ?>" title="<?php _e('Click to view the details.'); ?>"><?php _e('View detail'); ?></a>
                    </div>
                    <span><?php echo $this->escape($nav['title']); ?></span>
                </li>
            <?php } ?>
            </ul>
        <?php } ?>
        <li>
            <div class="legend"><?php _e('Custom navigations'); ?></div>
            <ul class="navs-front-items">

            </ul>
        </li>   
    </ul>
    <button class="btn btn-primary nav-clone1 pull-right" data-link="<?php echo $this->url('', array('action' => 'add', 'section' => 'front')); ?>"><?php _e('Add a custom navigation'); ?></button>
</div>

<script id="temp-nav" type="text/template">
<div class="pull-right">
     <span class="btn nav-clone"><?php _e('Clone'); ?></span>
     <span class="btn nav-delete"><?php _e('Delete'); ?></span>
    <a class="btn" href="<?php echo $this->url('', array('action' => 'data', 'name' => '')); ?><%= name%>" target="_Manipulation" title="<?php _e('Click to edit the details.'); ?>"><?php _e('Manipulation'); ?></a>
</div>
<span><%= _.escape(title) %></span>
</script>
<script>
(function($) {
    var modal = $("<div>",{"class":"modal hide fade"}).appendTo(document.body);
    var navCustom = new Backbone.Collection(<?php echo json_encode(($navCustom['front'])); ?>);
    var NavItemView = Backbone.View.extend({
        template: _.template($("#temp-nav").html()),
        tagName: "li",
        className: "box-hover",
        events: {
          "click .nav-clone": "clone",
          "click .nav-delete": "navDelete"
        },
        initialize: function() {
            this.model.id = "name";
            this.model.on("destroy", this.remove, this);
        },
        clone: function() {
             this.toggleHand();
             $.get("<?php echo $this->url('', array('action' => 'clone', 'name' => $name)); ?>" + this.model.get("name")).done(_.bind(function(result) {
                   modal.html(result).modal("show");
                   formModule.success = this.submite.bind(this);
            }, this));
        },
        navDelete: function() {
            this.toggleHand();
            if (confirm("<?php _e('Are you sure to delete this navigation') ?>")) {
                this.model.destroy({
                    url: "<?php echo $this->url('', array('action' => 'delete', 'name' => '')); ?>" + this.model.get("name")
                });
            }
            this.toggleHand();
        },
        submite: function(resp) {
           modal.modal("hide");
           navCustom.add(resp.navigation);
        },
        render: function() {
            this.$el.html(this.template(this.model.toJSON()));
            return this;
        },
        toggleHand: function() {
            this.$el.toggleClass("handle");
        }
    });
    var NavListView = Backbone.View.extend({
        el: $("#js-nav-select"),
        events: {
            "click .nav-clone1":"clone"
        },
        initialize: function() {
            this.customEl = this.$(".navs-front-items");
            modal.on("hide", _.bind(function() {
                this.$(".handle").removeClass("handle");
            }, this));
            navCustom.on("add", this.addOne, this);
            this.render();
        },
        render: function() {
            var m = navCustom.models;
            for (var i = 0, l = m.length; i < l; i++) {
                 this.addOne(m[i]);
            }
        },
        addOne: function(model) {
            this.customEl.append(new NavItemView({
                model: model
            }).render().el);
        },
        clone: function(e) {
            var tar = $(e.target);
            $.get(tar.attr("data-link")).done(function(resp) {
                     modal.html(resp).modal("show");
                     formModule.success = function(resp) {
                         modal.modal("hide");
                         navCustom.add(resp.navigation);
                     }
            });
        }
    });
    new NavListView;
})(jQuery)
</script>
