<?php
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
?>

<ul class="nav nav-tabs">
    <li class="active"><a href="<?php echo $this->url('', array('action' => 'index')); ?>" title="<?php _e('Navigation in action'); ?>"><?php _e('Navigation in action'); ?></a>
    <li><a href="<?php echo $this->url('', array('action' => 'list')); ?>" title="<?php _e('Navigation list'); ?>"><?php _e('Navigation list'); ?></a>
</ul>


        <h2 class="page-header"><?php echo $this->escape($title); ?></h2>
        <form action="<?php echo $this->url('', array('action' => 'apply')); ?>" method="post" id="nav-form">
            <div class="legend"><?php _e('Select for front global navigation'); ?></div>
            <label class="radio">
                   <input type="radio" name="nav_front" value="front"  <?php if ($navGlobal['front'] == 'front') { ?> checked<?php } ?>>
                   <?php _e('System front navigation'); ?>
            </label>
            <?php  foreach ($navList['front'] as $name => $title) { ?>
                <label class="radio">
                    <input type="radio" name="nav_front" value="<?php echo $name; ?>"  <?php if ($navGlobal['front'] == $name) { ?> checked<?php } ?> >
                    <?php echo $this->escape($title); ?>
                </label>
            <?php } ?>
            <label class="radio">
                <input type="radio" name="nav_front" value=""  <?php if ($navGlobal['front'] == '') { ?> checked<?php } ?>><?php _e('None to use.'); ?>
            </label>
            <div class="legend"><?php _e('Select for admin global navigation'); ?></div>
            <label class="radio">
                   <input type="radio" name="nav_admin" value="admin"  <?php if ($navGlobal['admin'] == 'admin') { ?> checked<?php } ?>>
                   <?php _e('System admin navigation'); ?>
            </label>
            <?php  foreach ($navList['admin'] as $name => $title) { ?>
                <label class="radio">
                    <input type="radio" name="nav_admin" value="<?php echo $name; ?>"  <?php if ($navGlobal['admin'] == $name) { ?> checked<?php } ?> >
                    <?php echo $this->escape($title); ?>
                </label>
            <?php } ?>
            <label class="radio">
                <input type="radio" name="nav_admin" value=""  <?php if ($navGlobal['admin'] == '') { ?> checked<?php } ?>><?php _e('None to use.'); ?>
            </label>
        <input type="submit" value="<?php _e('Submit'); ?>" class="btn btn-primary">
        </form>

<script>
(function($) {
       var f = $("#nav-form");
       f.submit(function(e) {
           e.preventDefault();
            $.post(f.attr("action"),f.serialize()).done(function(result) {
                result=$.parseJSON(result);
                if (result.status == 1) {
                    location.href = location.href;
                }
            });
       });
})(jQuery)
</script>
