<?php
$this->angular(array(
    'angular-translate.js'
));
?>
<div ng-app="systemPermModule" ng-controller="index">
    <div class="alert" ng-if="alert" 
     ng-class="{'alert-success': alert.status,'alert-error': !alert.status}">
        <button type="button" class="close" ng-click="clearAlert()">×</button>
        {{alert.message}}
    </div>
    <legend>{{'FRONT' | translate}}</legend>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width: 12%;">
                <th ng-repeat="frontRole in frontRoles" class="text-center">
                  {{frontRole.title}}
        <tbody>
            <tr>
                <th colspan="{{frontCols}}">{{'GLOBAL' | translate}}
            <tr ng-repeat="item in frontResources.global">
                <td class="pi-indent">{{item.title}}
                <td ng-repeat="(key, value) in item.roles" class="text-center">
                    <button class="btn btn-small" ng-class="{'btn-success': value}"
                            ng-click="assignAction(key, item)">
                        <i class="icon-ok" ng-class="{'muted': !value}"></i>
                    </button>
            <tr ng-if="frontResources.module.length">
                <th colspan="{{frontCols}}">{{'MODULE' | translate}}
            <tr ng-repeat="item in frontResources.module">
                <td class="pi-indent">{{item.title}}
                <td ng-repeat="(key, value) in item.roles" class="text-center">
                    <button class="btn btn-small" ng-class="{'btn-success': value}"
                            ng-click="assignAction(key, item)">
                        <i class="icon-ok" ng-class="{'muted': !value}"></i>
                    </button>
            <tr ng-if="frontResources.block.length">
                <th colspan="{{frontCols}}">{{'BLOCK' | translate}}
            <tr ng-repeat="item in frontResources.block">
                <td class="pi-indent">{{item.title}}
                <td ng-repeat="(key, value) in item.roles" class="text-center">
                    <button class="btn btn-small" ng-class="{'btn-success': value}"
                            ng-click="assignAction(key, item)">
                        <i class="icon-ok" ng-class="{'muted': !value}"></i>
                    </button>
            <tr>
                <td>
                <td ng-repeat="frontRole in frontRoles" class="text-center">
                    <button class="btn btn-small">
                        <i class="icon-ok">{{'ALL' | translate}}</i>
                    </button>
    </table>
    <legend>{{'ADMIN' | translate}}</legend>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width: 12%;">
                <th ng-repeat="adminRole in adminRoles" class="text-center">
                  {{adminRole.title}}
        <tbody>
            <tr>
                <th colspan="{{adminCols}}">{{'GLOBAL' | translate}}
            <tr ng-repeat="item in adminResources.global">
                <td class="pi-indent">{{item.title}}
                <td ng-repeat="(key, value) in item.roles" class="text-center">
                    <button class="btn btn-small" ng-class="{'btn-success': value}">
                        <i class="icon-ok" ng-class="{'muted': !value}"></i>
                    </button>
            <tr ng-if="adminResources.module.length">
                <th colspan="{{adminCols}}">{{'MODULE' | translate}}
            <tr ng-repeat="item in adminResources.module">
                <td class="pi-indent">{{item.title}}
                <td ng-repeat="(key, value) in item.roles" class="text-center">
                    <button class="btn btn-small" ng-class="{'btn-success': value}">
                        <i class="icon-ok" ng-class="{'muted': !value}"></i>
                    </button>
    </table>
</div>
<script>
var systemPermModule = angular.module('systemPermModule', ['pascalprecht.translate']);
var systemPermModuleConfig = {
    urlRoot: '<?php echo $this->url('', array('controller' => 'perm')); ?>',
    assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
    roles: <?php echo json_encode($roles) ?>,
    resources: <?php echo json_encode($resources) ?>,
    module: '<?php echo $name ?>',
    t: {
        GLOBAL: '<?php _e('Module Global permission'); ?>',
        MODULE: '<?php _e('Module resource'); ?>',
        BLOCK: '<?php _e('Block'); ?>',
    }
}
</script>
<?php $debug = 'production' == Pi::environment() ? '.min' : ''; ?>
<script src="<?php echo $this->assetModule('admin/perm' . $debug . '.js'); ?>"></script>