<?php
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->Backbone();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<ul class="nav nav-tabs">
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'perm', 'action' => 'front')); ?>"><?php _e('Front'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('controller' => 'perm', 'action' => 'admin')); ?>"><?php _e('Admin'); ?></a></li>
</ul>
<div class="page-perm row-fluid">
    <div class="span2 well well-small">
        <ul class="nav nav-list">
            <?php foreach ($roles as $key => $value) { ?>
            <li <?php if ($key == $role) { echo 'class="active"'; } ?>>
                <a href="<?php echo $this->url('', array('controller' => 'perm', 'action' => 'front', 'section' => $section, 'role' => $key)); ?>"><?php echo $this->escape($value); ?></a>
            </li>
            <?php } ?>
        </ul>
    </div>
    <div class="span10">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 35%;"><?php _e('Modules'); ?></th>
                    <th style="width: 35%;"><?php _e('Action'); ?></th>
                    <th style="width: 30%;"><?php _e('Status'); ?></th>
                </tr>    
            </thead>
            <tbody id="js-modules"></tbody>
        </table>
        <table class="table">
            <thead>
                <tr>
                    <th style="width: 35%;"><?php _e('Blocks'); ?></th>
                    <th style="width: 35%;"><?php _e('Action'); ?></th>
                    <th style="width: 30%;"><?php _e('Status'); ?></th>
                </tr>     
            </thead>
            <tbody id="js-blocks">
               <?php foreach ($modules as $item) { ?>
               <tr class="js-perm-parent">
                   <td class="accordion-toggle perm-blocks js-blocks" colspan="3" title="<?php _e('Click to toggle blocks'); ?>" data-url="<?php echo $this->url('', array('controller' => 'perm', 'action' => 'blocks','role' => $role, 'name' => $item['name'])); ?>">
                       <i class="icon-plus"></i>
                       <i class="icon-minus"></i>
                       <span style="margin-left: 10px;"><?php echo $this->escape($item['title']); ?></span>
                   </td>    
               </tr>
               <?php } ?>
            </tbody>   
        </table>
    </div>
</div>
<script id="temp-item" type="text/template">
    <td><%= title %></td>
    <td>
        <div class="btn-group">
            <button class="btn">
            <%
            if (direct) {
                if (direct > 0) {
                    print("<?php _e('Allowed'); ?>");
                } else {
                    print("<?php _e('Denied'); ?>");
                }
            } else {
                print("<?php _e('Inherited'); ?>");
            }
            %>
            </button>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <% if (direct) { %>
                    <% if (direct > 0) { %>
                    <li>
                        <a href="javascript:void(0)" class="js-action" data-action="deny"><?php _e('Deny'); ?></a>
                    </li>
                    <li>
                        <a href="javascript:void(0)" class="js-action" data-action="inherit"><?php _e('Inherit'); ?></a>
                    </li>
                    <% } else{  %>
                    <li>
                        <a href="javascript:void(0)" class="js-action" data-action="allow"><?php _e('Allow'); ?></a>
                    </li>
                    <li>
                        <a href="javascript:void(0)" class="js-action" data-action="inherit"><?php _e('Inherit'); ?></a>
                    </li>
                    <% } %>
                <% } else { %>
                    <li>
                        <a href="javascript:void(0)" class="js-action" data-action="allow"><?php _e('Allow'); ?></a>
                    </li>
                    <% if (perm < 1) { %>
                    <li>
                        <a href="javascript:void(0)" class="js-action" data-action="deny"><?php _e('Deny'); ?></a>
                    </li>
                    <% } %>
                <% } %>
            </ul>
        </div>
    </td>
    <td>
        <% if (perm > 0) { %>
        <span class="label label-success"><?php _e('Allowed'); ?></span>
        <% } else { %>
        <span class="label label-important"><?php _e('Denied'); ?></span>
        <% } %>
    </td>
</script>
<script>
(function() {
    var obj = {
        tagName: 'tr',
        template: $('#temp-item').html(),
        events: {
            'click .js-action': 'assignAction'
        },
        initialize: function() {
            this.model.on('change', this.render, this);
        },
        assignAction: function(e) {
            var action = $(e.currentTarget).attr('data-action'),
                prev = this.model.previousAttributes(),
                self = this,
                obj;
            if (action == 'allow') {
                obj = {
                    direct: 1,
                    perm: 1
                }
            } else if (action == 'deny') {
                obj = {
                    direct: -1,
                    perm: -1
                }
            } else {
                obj = {
                    direct: 0
                }
            }
            this.model.set(obj);
            $.post('<?php echo $this->url('', array('controller' => 'perm', 'action' => 'assign', 'role' => $role)); ?>', this.model.attributes).done(function(res) {
                res = $.parseJSON(res);
                self.model.set(res.data);
            }).error(function() {
                systemMessage.fail("<?php _e('An error occurred, please try again later.'); ?>");
                self.model.set(prev);
            });
        },
        render: function() {
            this.$el.html(_.template(this.template, this.model.toJSON()));
            return this;
        }
    };
    var ModuleItemView = Backbone.View.extend(_.extend(obj, {}));
    var ModuleListView = Backbone.View.extend({
        el: $("#js-modules"),
        initialize: function() {
            this.render();
        },
        render: function() {
            var c = this.collection.models;
            for (var i = 0, l = c.length; i < l; i++) {
                this.$el.append(new ModuleItemView({
                    model: c[i]
                }).render().el);
            }
        }
    });
    var BlockItemView = Backbone.View.extend(_.extend(obj, {
        className: 'perm-blocks'
    }));
    var blockListView = Backbone.View.extend({
        el: $("#js-blocks"),
        events:{
            'click .js-blocks': 'loadModuleBlock'
        },
        initialize: function() {
        },
        loadModuleBlock: function(e) {
            var tar = $(e.currentTarget);
            if (tar.data('blocks')) {
                this.toggleBlock(tar);
            } else {
                $.getJSON(tar.attr('data-url')).done(_.bind(function(res){
                    tar.data('blocks', res);
                    this.renderBlock(tar)
                }, this));
            }
        },
        renderBlock: function(tar) {
            var blocks = tar.data('blocks'),
                p = tar.parents('tr'),
                l = blocks.length;
            if (l) {
                for (; l--; ) {
                    $(new BlockItemView({
                        model: new Backbone.Model(blocks[l])
                    }).render().el).insertAfter(p);
                }
            } else {
                $('<tr class="perm-blocks"><td colspan="3"><span class="label label-info"><?php _e('no blocks'); ?></span></td></tr>').insertAfter(p);
            }

            tar.data('show', 1).addClass('perm-blocks-show');
        },
        toggleBlock: function(tar) {
            var p = tar.parents('tr');
            if (tar.data('show')) {
                p.nextUntil('.js-perm-parent').hide();
                tar.data('show', 0).removeClass('perm-blocks-show');
            } else {
                p.nextUntil('.js-perm-parent').show();
                tar.data('show', 1).addClass('perm-blocks-show');
            }
        }
   });
   new ModuleListView({
       collection: new Backbone.Collection(<?php echo json_encode($modules); ?>)
   });
   new blockListView;
})(jQuery)
</script>