<?php
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi.js'
));
?>
<div ng-app="systemPermModule">
    <div pi-message="alert"></div>
    <div pi-nav-tabs></div>
    <div ng-view></div>
</div>
<script>
angular
    .module('systemPermModule', ['ngRoute', 'ui.bootstrap', 'pi'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('controller' => 'perm')); ?>',
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
        name: '<?php echo $name ?>',
        navTabs: [
            { text: '<?php _e('Front'); ?>', href: '#!/front' },
            { text: '<?php _e('Admin'); ?>', href: '#!/admin' },
        ],
        t: {
            GLOBAL: '<?php _e('Module Global permission'); ?>',
            MODULE: '<?php _e('Module resource'); ?>',
            BLOCK: '<?php _e('Block'); ?>',
            ERROR: '<?php _e('Error, please try again later.'); ?>',
            FRONT: '<?php _e('Front'); ?>',
            ADMIN: '<?php _e('Admin'); ?>'
        }
   });
</script>
<?php $debug = 'production' == Pi::environment() ? '.min' : ''; ?>
<script src="<?php echo $this->assetModule('admin/perm' . $debug . '.js'); ?>"></script>