<?php
    $this->css($this->assetModule('script/system-ui.css'));
?>
<div ng-view ng-app="systemRoleModule"></div>
<?php $angular = Pi::url('static/vendor/angular/'); ?>
<script src="<?php echo $angular . 'angular.js'; ?> "></script>
<script src="<?php echo $angular . 'angular-route.js'; ?> "></script>
<script src="<?php echo $angular . 'angular-translate.js'; ?> "></script>
<script>
var systemRoleModule = angular.module('systemRoleModule', ['ngRoute', 'pascalprecht.translate']);
var systemRoleModuleConfig = {
    urlRoot: '<?php echo $this->url('', array('controller' => 'role')); ?>',
    assetRoot: '<?php echo $this->assetModule('ng-template/admin/'); ?>',
    t: {
        ADMIN_TITLE: '<?php _e('Admin roles'); ?>',
        ADMIN_ADD: '<?php _e('Add admin role'); ?>',
        FRONT_TITLE: '<?php _e('Front roles'); ?>',
        FRONT_ADD: '<?php _e('Add front role'); ?>',
        ROLE_ADD: '<?php _e('Add role'); ?>',
        DELETE: '<?php _e('Delete'); ?>',
        EDIT: '<?php _e('Edit'); ?>',
        NAME: '<?php _e('Name'); ?>',
        TITLE: '<?php _e('Title'); ?>',
        USER_COUNT: '<?php _e('User in role'); ?>',
        STATUS: '<?php _e('Status'); ?>',
        ACTIVE: '<?php _e('Active'); ?>',
        INACTIVE: '<?php _e('Inactive'); ?>',
        ACTION: '<?php _e('Action'); ?>',
        ROLE_NAME: '<?php _e('Unique name'); ?>',
        ROLE_TITLE: '<?php _e('Title'); ?>',
        SUBMIT: '<?php _e('Submit'); ?>',
        CANCEL: '<?php _e('Cancel'); ?>',
        REQUIRED: '<?php _e('Required'); ?>',
        TYPE: '<?php _e('Type'); ?>',
        FRONT: '<?php _e('Front'); ?>',
        ADMIN: '<?php _e('Admin'); ?>'
    }
}
</script>
<script>
systemRoleModule.config(function($translateProvider, $routeProvider) {
    $translateProvider.translations(systemRoleModuleConfig.t);
    $routeProvider.otherwise({
        templateUrl: systemRoleModuleConfig.assetRoot + 'role-index.html',
        controller: 'RoleCtrl'
    });
}).directive('piFocus', function() {
    return {
        restrict: 'A',
        link: function(scope, element, attr) {
            scope.$watch(attr.piFocus, function(value) {
                if (value) {
                    element[0].focus();
                }
            });
        }
    }
}).service('server', function($http) {
    var root = systemRoleModuleConfig.urlRoot;
    var isFile = function(obj) {
        return Object.prototype.toString.apply(obj) === '[object File]';
    };
    //emulate jQuery post
    $http.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded;charset=utf-8';
    $http.defaults.transformRequest = [function(d) {
        return angular.isObject(d) && !isFile(d) ? $.param(d) : d;
    }];
    this.get = function() {
        return $http.get(root + 'list');
    }
    this.add = function(role) {
        return $http.post(root + 'add', role);
    };
    this.putTitle = function(role) {
        $http.post(root + 'rename', {
            id: role.id,
            title: role.title
        });
    };
}).controller('RoleCtrl', function($scope, server) {
    server.get().success(function(data) {
        var frontRoles = data.frontRoles;
        var adminRoles = data.adminRoles;
        var parse = function(item) {
            item.editTitle = 0;
            item.originTitle = item.title;
        };
        angular.forEach(frontRoles, parse);
        angular.forEach(frontRoles, parse);
        $scope.frontRoles = data.frontRoles;
        $scope.adminRoles = data.adminRoles;
    });
    $scope.cancelModal = function() {
        $scope.entity = null;
    }
    $scope.modal = function(type) {
        $scope.entity = {
            section: type,
            active: 1
        };
    }
    $scope.addRoleAction = function() {
        server.add($scope.entity).success(function(data) {
            if (data.status) {
                var role = data.data;
                if (role.section = 'front') {
                    $scope.frontRoles.push(role);
                } else {
                    $scope.adminRoles.push(role);
                }
            }
        });
    }
    $scope.renameAction = function(role) {
        if (role.title == '') {
            role.title = role.originTitle;
        }
        if (role.title != role.originTitle) {
            server.putTitle(role);
        }
        role.editTitle = 0;
    }
});
</script>