<style>
.dl-horizontal dt {
  width: 100px;
}
.dl-horizontal dd {
  margin-left: 120px;
}
</style>
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>

<table class="table table-hover">
    <thead>
        <td width="100px"><?php _e('Roles'); ?></td>
        <?php
        $roleList = array();
        foreach ($roles as $name => $data) {
            $title = $this->escape($data['role']['title']);
            if (!$data['role']['active']) {
                $title = sprintf('<i>%s</i>', $title);
            }
            $url = $this->url('', array('action' => 'edit', 'id' => $data['role']['id']));
            $module = $this->escape($data['role']['module']);
            $roleList[] = array($name, $title, $url, $module);
        ?>
            <td width="100px"><a href="<?php echo $url; ?>" title="<?php _e('Edit'); ?>"><?php echo $title; ?></a><br /><small><?php echo $module; ?></small></td>
        <?php } ?>
        <td clospan="4"><?php _e('Operations'); ?></td>
    </thead>
    <?php
    $i = 0;
    $count = count($roleList);
    foreach ($roles as $name => $data) {
        $role = $roleList[$i++];
    ?>
    <tr>
        <td><a href="<?php echo $role[2]; ?>" title="<?php _e('Edit'); ?>"><?php echo $role[1]; ?></a><br /><small><?php echo $role[3]; ?></small></td>
        <?php
        for ($k = 0; $k < $count; $k++) {
            $key = $roleList[$k][0];
        ?>
        <td><?php
            if (!empty($data['inherit'][$key])) {
                if ($data['inherit'][$key] > 0) {
                ?><strong>V</strong><?php
                } else {
                ?>o<?php
                }
            } ?>
        </td>
        <?php } ?>

        <td>
            <a href="<?php echo $this->url('', array('action' => 'clone', 'id' => $data['role']['id'])); ?>" title="<?php _e('Clone'); ?>"><?php _e('Clone'); ?></a>
        </td>
        <td>
            <?php if (empty($data['role']['module'])) { ?>
            <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $data['role']['id'])); ?>" title="<?php _e('Edit'); ?>"><?php _e('Edit'); ?></a>
            <?php } ?>
        </td>
        <td>
            <?php if (empty($data['role']['module'])) { ?>
            <a href="<?php echo $this->url('', array('action' => 'delete', 'id' => $data['role']['id'])); ?>" title="<?php _e('Delete'); ?>"><?php _e('Delete'); ?></a>
            <?php } ?>
        </td>
        <td>
            <?php if (empty($data['role']['module'])) {
                $title = empty($data['role']['active']) ? __('Activate') : __('Deactivate');
            ?>
            <a href="<?php echo $this->url('', array('action' => 'activate', 'id' => $data['role']['id'])); ?>" title="<?php $title; ?>"><?php $title; ?></a>
            <?php } ?>
        </td>

    </tr>
    <?php } ?>
</table>

<h4 class="page-header"><?php _e('Note:'); ?></h4>
<dl class="dl-horizontal">
    <dt><strong>V</strong></dt><dd><?php _e('Direct inheritance'); ?></dd>
    <dt>o</dt><dd><?php _e('Indirect inheritance'); ?></dd>
    <dt><i>Italic</i></dt><dd><?php _e('Inactive'); ?></dd>
</dl>

<p>
    <a href="<?php echo $this->url('', array('action' => 'add')); ?>" title="<?php _e('Add a new role'); ?>"><?php _e('Add a new role'); ?></a>
</p>