<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->Backbone();
?>
<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('controller' => 'theme', 'action' => 'index')); ?>" title="<?php _e('Theme in action'); ?>"><?php _e('Theme in action'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('action' => 'installed')); ?>" title="<?php _e('Installed'); ?>"><?php _e('Installed'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url('', array('action' => 'available')); ?>" title="<?php _e('Availables'); ?>"><?php _e('Availables'); ?></a></li>
    <li class="disabled"><a><?php _e('Repository'); ?></a></li>
</ul>
<div class="page-header">
    <h2><?php echo $title; ?></h2> 
</div>    
<div class="theme-list" id="js-theme">
    <div class="js-alert"></div>
</div>
<script id="temp-theme" type="text/template">
    <a href="" class="theme-screenshot">
        <img src="<%=screenshot %>" alt="<%= _.escape(title) %>"  title="<?php _e('Click To preview'); ?>" />
    </a>
    <div class="caption">
        <h5>
            <span class="pull-right label"><%= type %></span>
            <%- title %>
        </h5>
        <div class="clearfix theme-actions" style="margin-left: -5px;">
            <span class="pull-right btn theme-install"><?php _e('Install'); ?></span>
            <span class="no-select btn btn-link theme-btn theme-detail"><?php _e('Detail'); ?></span><span class="muted">|</span>
            <span class="btn btn-link theme-btn theme-Check"><?php _e('Check'); ?></span>
        </div>
        <dl class="hide">
            <dt><?php _e('Version'); ?></dt>
            <dd><%= version %></dd>
            <dt><?php _e('Type'); ?></dt>
            <dd><%= type %></dd>
            <dt><?php _e('Description'); ?></dt>
            <dd><%= description %></dd>
        </dl>  
   </div>
</script>
<script type="text/template" id="alert-template">
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= msg %>
    </div>
</script>
<script>
(function($){
    var themeCollection = new Backbone.Collection(<?php echo json_encode(array_values($themes)) ?>);
    var ThemeItemView = Backbone.View.extend({
        className: 'thumbnail theme-item',
        template: _.template($('#temp-theme').html()),
        events: {
            'click .theme-check': 'check',
            'click .theme-install': 'install',
            'click .theme-detail': 'toggleDetail'
        },
        initialize: function() {
            this.model.on('destroy', this.remove, this);
            this.model.id = 'name';
        },
        render: function() {
            this.$el.html(this.template(this.model.toJSON()));
            return this.el;
        },
        check: function() {

        },
        install:function() {
            var self = this;
            $.getJSON('<?php echo $this->url('', array('action' => 'install', 'name' => '')); ?>' + this.model.get('name')).done(function(res) {
                if (res.status) {
                    self.remove();
                } else {
                    themeList.$('.js-alert').html(_.template($('#alert-template').html(), { msg: res.message }));
                }
            });
        },
        toggleDetail: function() {
            this.$('dl').toggleClass('hide');
        }
    });
    var ThemeListView = Backbone.View.extend({
        el: $('#js-theme'),
        initialize: function() {
            this.render();
        },
        render: function(msg) {
            var el = this.$el,
                m = themeCollection.models;
            for (var i = 0, l = m.length; i < l; i++) {
                el.append(new ThemeItemView({
                    model: m[i]
                }).render());
            }
        }
    });
    var themeList = new ThemeListView;
})(jQuery)
</script>