<?php
$this->css($this->assetModule('admin/admin.css'));
$this->jQuery();
$this->backbone();
?>
<div class="page-header">
    <h2><?php echo $title; ?></h2>
</div>    
<ul class="nav nav-pills">
    <li class="<?php if ('_front' == $side) { echo 'active'; } ?>">
        <a href="<?php echo $this->url('', array('action' => 'index', 'side' => '_front')); ?>">
            <?php echo _a('Front'); ?>
        </a>
    </li>    
    <li class="<?php if ('_admin' == $side) { echo 'active'; } ?>">
        <a href="<?php echo $this->url('', array('action' => 'index', 'side' => '_admin')); ?>">
            <?php echo _a('Admin'); ?>
        </a>
    </li>    
</ul>   
<div id="js-page">
    <fieldset>
        <legend><?php echo _a('Theme in use'); ?></legend>
        <div class="media" style="margin-top: 0;">
            <img src="<?php echo $theme['screenshot']; ?>" alt="<?php echo _escape($theme['title']); ?>" class="pull-left" style="width: 300px;" />
            <div class="media-body">
                <h4 class="media-heading"><?php echo _escape($theme['title']); ?></h4>
                <h5><?php echo $theme['version']; ?></h5>
                <p style="margin-bottom:15px;">
                    <?php echo _escape($theme['description']); ?>
                </p>
                <a href="<?php echo $this->url('', array('action' => 'customize', 'name' => $theme['name'])); ?>"><?php _e('Customize'); ?></a>
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend><?php echo _a('Themes available to use'); ?></legend>
        <div class="theme-list"></div>
    </fieldset>
 </div>
<script type="text/template" id="temp-theme">
<div class="thumbnail">
    <a class="theme-screenshot">
        <img src="<%= screenshot %>" alt="<%= _.escape(title) %>"  title="<?php echo _a('Click To preview'); ?>">
    </a>
    <div class="caption">
        <h5><%- title %></h5>
        <div class="clearfix theme-actions">
            <span class="pull-right btn btn-default theme-apply"><?php echo _a('Apply'); ?></span>
            <span class="no-select btn btn-link theme-detail"><?php echo _a('Detail'); ?></span>
        </div>
        <dl class="hide">
            <dt><?php echo _a('Version'); ?></dt>
            <dd><%= version %></dd>
            <dt><?php echo _a('Description'); ?></dt>
            <dd><%= description %></dd>
        </dl>        
    </div>
</div>    
</script>
<script>
var themeCollection = new Backbone.Collection(<?php echo json_encode(array_values($themes)) ?>);
var ThemeItemView = Backbone.View.extend({
    className: 'col-md-4',
    template: _.template($('#temp-theme').html()),
    events: {
        'click .theme-apply': 'apply',
        'click .theme-detail': 'toggleDetail'
    },
    render: function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this.el;
    },
    apply: function() {
        var url = '<?php echo $this->url('', array('action' => 'apply', 'side' => $side, 'theme' => '__NAME__')); ?>';
        $.getJSON(url.replace('__NAME__', this.model.get('name'))).done(function(result) {
            if (result.status == 1) {
                location.href = location.href;
            }
        });
    },
    toggleDetail: function() {
        this.$('dl').toggleClass('hide');
    }
});
var ThemeListView = Backbone.View.extend({
    el: $('#js-page'),
    events: {
        'click .apply-all': 'applyAll'
    },
    initialize: function() {
        this.render();
    },
    render: function() {
        var el = this.$('.theme-list'),
            m = themeCollection.models;
        for (var i = 0, l = m.length; i < l; i++) {
            el.append(new ThemeItemView({
                model: m[i]
            }).render());
        }
    },
    applyAll: function(e) {
        var tar = $(e.target);
        $.getJSON(tar.attr('data-link')).done(function(result) {
            alert(result.message);
        });
    }
});
new ThemeListView;
</script>