<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->Backbone();
    $this->js($this->assetModule('script/system-msg.js'));
?>
<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('', array('controller' => 'theme', 'action' => 'index')); ?>" title="<?php _e('Theme in action'); ?>"><?php _e('Theme in action'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url('', array('action' => 'installed')); ?>" title="<?php _e('Installed'); ?>"><?php _e('Installed'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('action' => 'available')); ?>" title="<?php _e('Availables'); ?>"><?php _e('Availables'); ?></a></li>
    <li class="disabled"><a><?php _e('Repository'); ?></a></li>
</ul>
<div class="page-header">
    <h2><?php echo $title; ?></h2>
</div>
<div class="theme-list" id="js-theme"></div>
<script id="temp-theme" type="text/template">
    <a href="" class="theme-screenshot">
        <img src="<%=screenshot %>" alt="<%= _.escape(title) %>"  title="<?php _e('Click To preview'); ?>">
    </a>
    <div class="caption">
        <h5 class="clearfix">
            <span class="pull-right label"><%= type %></span>
            <%- title %>
        </h5>
        <div class="clearfix theme-actions" style="margin-left: -5px;">
            <% if(name!="default") { %>
            <span class="pull-right btn theme-uninstall"><?php _e('Uninstall'); ?></span>
            <% } %>
            <span class="no-select btn btn-link theme-detail theme-btn"><?php _e('Detail'); ?></span><span class="muted">|</span>
            <span class="btn btn-link theme-Check theme-btn"><?php _e('Check'); ?></span><span class="muted">|</span>
            <span class="btn btn-link theme-update theme-btn"><?php _e('Update'); ?></span>
        </div>
        <dl class="hide">
            <dt><?php _e('Version'); ?>
            <dd><%= version %>
            <dt><?php _e('Type'); ?>
            <dd><%= type %>
            <dt><?php _e('Description'); ?>
            <dd><%= description %>
        <dl>  
   </div>
</script>
<script>
var themeCollection = new Backbone.Collection(<?php echo json_encode(array_values($themes)) ?>);
var ThemeItemView = Backbone.View.extend({
    className: 'thumbnail theme-item',
    template: _.template($('#temp-theme').html()),
    events: {
        'click .theme-check': 'check',
        'click .theme-update': 'update',
        'click .theme-uninstall': 'uninstall',
        'click .theme-detail': 'toggleDetail'
    },
    initialize: function() {
        this.model.on('destroy', this.remove, this);
        this.model.on('change', this.render, this);
    },
    render: function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this.el;
    },
    check: function() {

    },
    update:function() {
        this.model.fetch({
            url:'<?php echo $this->url('', array('action' => 'update', 'name' => '')); ?>' + this.model.get('name'),
            success: function() {
                systemMessage.succ('<?php _e('theme Update ok!')?>');
            },
            error: function() {
                systemMessage.fail();
            } 
        });
    },
    uninstall: function() {
        if (confirm('<?php _e('Are you sure to uninstall this theme ? ') ?>')) {
            this.model.destroy({
               url:'<?php echo $this->url('', array('action' => 'uninstall', 'name' => '')); ?>' + this.model.get('name')
            });
        }
    },
    toggleDetail: function() {
        this.$('dl').toggleClass('hide');
    }
});
var ThemeListView = Backbone.View.extend({
    el: $('#js-theme'),
    initialize: function() {
        this.render();
    },
    render: function() {
        var el = this.$el,
            m = themeCollection.models;
        for (var i = 0, l = m.length; i < l; i++) {
            el.append(new ThemeItemView({
                model: m[i]
            }).render());
        }
    }
});
new ThemeListView;
</script>