<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->backbone();
?>
<ul class="nav nav-tabs">
    <li class="active"><a href="<?php echo $this->url('', array('controller' => 'theme', 'action' => 'index')); ?>" title="<?php _e('Theme in action'); ?>"><?php _e('Theme in action'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('action' => 'installed')); ?>" title="<?php _e('Installed'); ?>"><?php _e('Installed'); ?></a></li>
    <li><a href="<?php echo $this->url('', array('action' => 'available')); ?>" title="<?php _e('Availables'); ?>"><?php _e('Availables'); ?></a></li>
    <li class="disabled"><a><?php _e('Repository'); ?></a></li>
</ul>
<div class="page-header">
    <h2><?php echo $title; ?></h2>
</div>    
<ul class="nav nav-pills">
    <li class="<?php if ('_front' == $section) { echo 'active'; } ?>">
        <a href="<?php echo $this->url('', array('action' => 'index', 'section' => '_front')); ?>">
            <?php _e('Front'); ?>
        </a>
    </li>    
    <li class="<?php if ('_admin' == $section) { echo 'active'; } ?>">
        <a href="<?php echo $this->url('', array('action' => 'index', 'section' => '_admin')); ?>">
            <?php _e('Admin'); ?>
        </a>
    </li>    
</ul>   
<div id="js-page">
    <fieldset style="margin-bottom:20px;">
        <legend><?php _e('Theme in use'); ?></legend>
        <div class="media" style="margin-top: 0;">
            <img src="<?php echo $theme['screenshot']; ?>" alt="<?php echo $this->escape($theme['title']); ?>" class="pull-left" style="width: 300px;" />
            <div class="media-body">
                <h4 class="media-heading"><?php echo $this->escape($theme['title']); ?></h4>
                <h5><?php echo $theme['version']; ?></h5>
                <p style="margin-bottom:15px;">
                    <?php echo $this->escape($theme['description']); ?>
                </p>
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend><?php _e('Themes available to use'); ?></legend>
        <div class="theme-list">
        </div>
    </fieldset>
</div>
<script type="text/template" id="temp-theme">
    <a class="theme-screenshot">
        <img src="<%=screenshot %>" alt="<%= _.escape(title) %>"  title="<?php _e('Click To preview'); ?>">
    </a>
    <div class="caption">
        <h5><%- title %></h5>
        <div class="clearfix theme-actions">
            <span class="pull-right btn theme-apply"><?php _e('Apply'); ?></span> 
            <span class="no-select btn btn-link theme-detail"><?php _e('Detail'); ?></span>   
        </div>
        <dl class="hide">
            <dt><?php _e('Version'); ?></dt>
            <dd><%= version %></dd>
            <dt><?php _e('Description'); ?></dt>
            <dd><%= description %></dd>
        </dl>        
    </div>    
</script>
<script>
var themeCollection = new Backbone.Collection(<?php echo json_encode(array_values($themes)) ?>);
var ThemeItemView = Backbone.View.extend({
    className: 'thumbnail theme-item',
    template: _.template($('#temp-theme').html()),
    events: {
        'click .theme-apply': 'apply',
        'click .theme-detail': 'toggleDetail'
    },
    render: function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this.el;
    },
    apply: function() {
        $.getJSON('<?php echo $this->url('', array('action' => 'apply', 'section' => $section, 'theme' => '')); ?>' + this.model.get('name')).done(function(result) {
            if (result.status == 1) {
                location.href = location.href;
            }
        });
    },
    toggleDetail: function() {
        this.$('dl').toggleClass('hide');
    }
});
var ThemeListView = Backbone.View.extend({
    el: $('#js-page'),
    events: {
        'click .apply-all': 'applyAll'
    },
    initialize: function() {
        this.render();
    },
    render: function() {
        var el = this.$('.theme-list'),
            m = themeCollection.models;
        for (var i = 0, l = m.length; i < l; i++) {
            el.append(new ThemeItemView({
                model: m[i]
            }).render());
        }
    },
    applyAll: function(e) {
        var tar = $(e.target);
        $.getJSON(tar.attr('data-link')).done(function(result) {
            alert(result.message);
        });
    }
});
new ThemeListView;
</script>