<?php
    $this->angular(array(
        'angular-route.js',
        'angular-translate.js',
        'ui-bootstrap-custom-tpls-0.6.0.js',
        'pi-form.js'
    ));
?>
<div ng-view ng-app="systemUserModule">
</div>
<script>
var systemUserModule = angular.module('systemUserModule', ['ngRoute', 'pascalprecht.translate', 
    'ui.bootstrap', 'piForm']);
var systemUserModuleConfig = {
    urlRoot: '<?php echo $this->url('', array('controller' => 'user')); ?>',
    assetRoot: '<?php echo $this->assetModule('ng-template/admin/'); ?>',
    roles: <?php echo json_encode($roles) ?>,
    t: {
        TITLE: '<?php _e('User list'); ?>',
        Add_USER: '<?php _e('Add user'); ?>',
        EDIT_USER: '<?php _e('Edit user'); ?>',
        ACTIVE_STATUS: '<?php _e('Active State'); ?>',
        ENABLE_STATUS: '<?php _e('Enable State'); ?>',
        SELECT_ROLES: '<?php _e('Select roles'); ?>',
        PASSWORD_MATCH: '<?php _e("Passwords don\'t match"); ?>',
        USER_NAME_TOKEN: '<?php _e('Username is already token'); ?>',
        EMAIL_TOKEN: '<?php _e('Email is already token'); ?>',
        DISPLAY_NAME_TOKEN: '<?php _e('Dispaly name is already token'); ?>'
    }
}
</script>
<script>
systemUserModule.config(function($translateProvider, $routeProvider, $locationProvider) {
    $translateProvider.translations(systemUserModuleConfig.t);
    $locationProvider.hashPrefix('!');
    $routeProvider.when('/new', {
        controller: 'formCtrl',
        templateUrl: systemUserModuleConfig.assetRoot + 'user-form.html',
    }).when('/edit/:id', {
        controller: 'formCtrl',
        templateUrl: systemUserModuleConfig.assetRoot + 'user-form.html',
    }).otherwise({
        redirectTo: '/index',
        templateUrl: systemUserModuleConfig.assetRoot + 'user-index.html',
        controller: 'UserCtrl'
    });
}).service('server', function($http) {
    var root = systemUserModuleConfig.urlRoot;
    var isFile = function(obj) {
        return Object.prototype.toString.apply(obj) === '[object File]';
    };
    //emulate jQuery post
    $http.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded;charset=utf-8';
    $http.defaults.transformRequest = [function(d) {
        return angular.isObject(d) && !isFile(d) ? $.param(d) : d;
    }];
    this.roles = systemUserModuleConfig.roles;
    this.uniqueUrl =  root + 'check';
    this.get = function(params) {
        return $http.get(root + 'list', {
            params: params
        });
    }
    this.getUserById = function(id) {
        return $http.get(root + 'get', {
            params: {
                id: id
            }
        })
    }
}).controller('UserCtrl', function($scope, server) {
    $scope.roles = server.roles;
    $scope.filter = {};
    var list = function() {
        server.get($scope.filter).success(function(data) {
            angular.forEach(data.users, function(item) {
                if (item.front_role) {
                    item.front_role = item.front_role.join(',');
                }
                if (item.admin_role) {
                    item.admin_role = item.admin_role.join(',');
                }
            });
            $scope.users = data.users;
            $scope.paginator = data.paginator;
        });
    }
    $scope.$watchCollection('filter', list);
}).controller('formCtrl', function($scope, $location, server) {
    if ($location.path() == '/new') {
        $scope.title = systemUserModuleConfig.t.Add_USER;
    } else {
        $scope.title = systemUserModuleConfig.t.EDIT_USER;
    }
    $scope.entity = {};
    $scope.roles = server.roles;
    $scope.uniqueUrl = server.uniqueUrl;
    var checkedRoles = function() {
        var roles = [];
        angular.forEach($scope.roles, function(item) {
            if (item.checked) {
                roles.push(item.name)
            }
        });
        return roles;
    }

    $scope.submit = function() {
        $scope.entity.roles = checkedRoles();
    }
    
});
</script>
