<?php
$this->angular(array(
    'angular-route.js',
    'angular-translate.js',
    'ui-bootstrap-custom-tpls-0.6.0.js',
    'pi-form.js'
));
?>
<div ng-view ng-app="systemUserModule"></div>
<script>
var systemUserModule = angular.module('systemUserModule', ['ngRoute', 'pascalprecht.translate', 
    'ui.bootstrap', 'piForm']);
var systemUserModuleConfig = {
    urlRoot: '<?php echo $this->url('', array('controller' => 'user')); ?>',
    assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', true, false); ?>',
    roles: <?php echo json_encode($roles) ?>,
    t: {
        TITLE: '<?php _e('User list'); ?>',
        ADD_USER: '<?php _e('Add user'); ?>',
        EDIT_USER: '<?php _e('Edit user'); ?>',
        ACTIVE_STATUS: '<?php _e('Active State'); ?>',
        ENABLE_STATUS: '<?php _e('Enable State'); ?>',
        SELECT_ROLES: '<?php _e('Select roles'); ?>',
        PASSWORD_MATCH: '<?php _e("Passwords don\'t match"); ?>',
        USER_NAME_TOKEN: '<?php _e('Username is already token'); ?>',
        EMAIL_TOKEN: '<?php _e('Email is already token'); ?>',
        DISPLAY_NAME_TOKEN: '<?php _e('Display name is already token'); ?>',
        RETURN: '<?php _e('Back to users list'); ?>',
        REQUIRED: '<?php _e('Required'); ?>',
        USER_NAME: '<?php _e('Username'); ?>',
        DISPLAY_NAME: '<?php _e('Dispaly name'); ?>',
        EMAIL: '<?php _e('Email'); ?>',
        PASSWORD: '<?php _e('Password'); ?>',
        CONFIRM_PASSWORD: '<?php _e('Password confirm'); ?>',
        ACTIVATE: '<?php _e('Active'); ?>',
        ENABLE: '<?php _e('Enable'); ?>',
        ASSIGN_FRONT_ROLE: '<?php _e('Front role'); ?>',
        ASSIGN_ADMIN_ROLE: '<?php _e('Admin role'); ?>'
    }
}
</script>
<script src="<?php echo $this->assetModule('angular/user.js'); ?>"></script>
