<form method="get" action="<?php echo $block['action']; ?>"
    <?php if (!empty($block['options']['target'])) { echo ' target="' . $block['options']['target'] . '"'; } ?>>
    <div class="input-group">
        <input type="text" class="form-control" name="q"
               placeholder="<?php echo _b('Keywords'); ?>">
        <div class="input-group-btn">
            <?php if (!empty($block['list'])) { ?>
            <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-search"></i>
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu pull-right" id="js-search-menu">
                <?php foreach ($block['list'] as $name => $label) { ?>
                <li>
                    <a href="#" data-value="<?php echo _escape($name); ?>">
                        <?php echo _escape($label); ?>
                    </a>
                <?php } ?>
            </ul>
            <input type="hidden" name="m">
            <?php } else { ?>
            <button class="btn btn-default">
                <i class="fa fa-search"></i>
            </button>
            <?php } ?>
        </div>
    </div>
</form>
<?php if (!empty($block['list'])) { ?>
<script>
$('#js-search-menu').on('click', 'a', function(e) {
    var $this = $(this);
    var val = $this.data('value');
    var form = $this.parents('form');
    var m = form.find('[name=m]');

    e.preventDefault();
    m.val(val);
    form[0].submit();
});
</script>
<?php } ?>