<?php
    $this->css($this->assetModule('script/widget-admin.css', 'widget'));
?>
<ul class="widget-list">
    <?php  foreach ($widgets as $id => $widget) {  ?>
    <li>
        <div class="widget-hd clearfix">
            <strong title="<?php echo $this->escape($widget['block']['title']); ?>" class="ellipsis"><?php echo $this->escape($widget['block']['title']); ?></strong>
        </div>
        <div class="widget-description">
           <?php echo $this->escape($widget['block']['description']); ?>
        </div>
        <div class="widget-action">
           <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $widget['id'])); ?>" class="btn btn-link"><?php _e('Edit'); ?></a>
           <span class="muted">|</span>
           <a href="<?php echo $this->url('', array('action' => 'delete', 'id' => $widget['id'])); ?>" class="btn btn-link" onclick=" return confirm('<?php _e('Are you sure delete this widget?'); ?>')"><?php _e('Delete'); ?></a>
        </div>         
    <?php } ?>    
</ul>
