<div style="margin-bottom:10px;">
    <span class="text-info" style="margin-right: 10px"><?php _e('Add a block: '); ?></span>
    <a class="btn btn-primary" href="<?php echo $this->url('', array('action' => 'add', 'type' => 'html')); ?>" title="<?php _e('HTML tags allowed in content.'); ?>"><?php echo $types['html']; ?></a>
    <a class="btn" href="<?php echo $this->url('', array('action' => 'add', 'type' => 'text')); ?>" title="<?php _e('Only plaintext content is allowed.'); ?>"><?php echo $types['text']; ?></a>
    <a class="btn" href="<?php echo $this->url('', array('action' => 'add', 'type' => 'markdown')); ?>" title="<?php _e('Markdown syntax allowed in content.'); ?>"><?php echo $types['markdown']; ?></a>
</div>
<?php include 'common-list.phtml'; ?>
