<?php
$this->angular(array(
    'angular-route.js',
    'pi.js',
));
$js = $controller == 'index' ? 'index' : 'widgets';
//d($data);
?>
<script>
angular
    .module('<?php echo $module; ?>', ['ngRoute', 'pi'])
    .constant('config', {
        urlRoot: '<?php echo $this->url('', array('module' => $module)) . $controller . '/'; ?>',
        assetRoot: '<?php echo $this->assetModule('ng-template/admin/', '', false); ?>',
        data: <?php echo json_encode($data); ?>,
        t: {
            INSTALLED_WIDGETS: '<?php echo _a('Installed widgets'); ?>',
            AVAILABLE_WIDGETS: '<?php echo _a('Available widgets'); ?>',
            INSTALL: '<?php echo _a('Install'); ?>',
            UNINSTALL: '<?php echo _a('Uninstall'); ?>',
            EDIT: '<?php echo _a('Edit'); ?>',
            DELETE: '<?php echo _a('Delete'); ?>'
        }
    });
</script>
<link rel="stylesheet" href="<?php echo $this->assetModule('admin/admin.css'); ?>">
<script src="<?php echo $this->assetModule('admin/' . $js . '.js'); ?>"></script>