<?php
$this->css($this->assetModule('admin/admin.css'));
$this->jQuery('ui/jquery-ui.custom.min.js');
$this->jQuery('extension/fileupload-min.js');
$this->Backbone();

include $this->templateComponent('form');
?>

<div class="form-group" id="widget-items">
    <label class="col-md-2 control-label"><?php echo _a('Items'); ?></label>
    <div class="col-md-10">
        <div class="row">
            <div class="col-sm-6 col-md-3 widget-item-add">
                <div class="thumbnail widget-item-add-mark">
                    <i class="fa fa-plus fa-3x text-muted"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<script id="widget-item-template" type="text/template">
<div class="col-sm-6 col-md-3 widget-item">
    <button type="button" class="close">&times;</button>
    <div class="thumbnail">
        <p>
            <label><?php echo _a('Caption'); ?></label>
            <input type="text" value="<%= caption %>" name="caption" class="form-control">
        </p>
        <p>
            <label><?php echo _a('Link'); ?></label>
            <input type="text" value="<%= link %>" name="link" class="form-control">
        </p>
        <p>
            <label><?php echo _a('Summary'); ?></label>
            <textarea name="desc" class="form-control" rows="5"><%= desc %></textarea>
        </p>
    </div>
</div>
</script>
<script src="<?php echo $this->assetModule('admin/widget-list.js'); ?>"></script>
<script>
widgetAction({
    items: <?php echo $content ?: json_encode(array()); ?>
});
</script>