<?php
    $this->css($this->assetModule('script/widget-admin.css'));
?>
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>


<div style="margin-bottom: 20px;">
    <span class="text-info" style="margin-right: 10px"><?php _e('Add a block: '); ?></span>
    <a class="btn<?php if ('html' == $type) { echo ' btn-primary'; } ?>" href="<?php echo $this->url('', array('action' => 'add', 'type' => 'html')); ?>" title="<?php _e('HTML tags allowed in content.'); ?>"><?php echo $types['html']; ?></a>
    <a class="btn<?php if ('text' == $type) { echo ' btn-primary'; } ?>" href="<?php echo $this->url('', array('action' => 'add', 'type' => 'text')); ?>" title="<?php _e('Only plaintext content is allowed.'); ?>"><?php echo $types['text']; ?></a>
    <a class="btn<?php if ('markdown' == $type) { echo ' btn-primary'; } ?>" href="<?php echo $this->url('', array('action' => 'add', 'type' => 'markdown')); ?>" title="<?php _e('Markdown syntax allowed in content.'); ?>"><?php echo $types['markdown']; ?></a>
</div>

<?php
    if (!empty($success)) {
        $message = $success;
        $class = ' alert-success';
    } elseif (!empty($error)) {
        $message = $success;
        $class = ' alert-error';
    } elseif (!empty($message)) {
        $class = ' alert-error';
    }
?>
<?php if (!empty($message)) { ?>
<div class="alert<?php echo $class; ?>">
    <button data-dismiss="alert" class="close" type="button">
        ×
    </button>
    <?php echo $message; ?>
</div>

<script>$(".alert").alert();</script>
<?php } ?>

<?php include $this->templateComponent('form'); ?>