<?php
    $this->css($this->assetModule('script/widget-admin.css'));
?>
<div class="page-header">
    <h2><?php echo $this->escape($title); ?></h2>
</div>
<?php
    if (!empty($success)) {
        $message = $success;
        $class = ' alert-success';
    } elseif (!empty($error)) {
        $message = $success;
        $class = ' alert-error';
    } elseif (!empty($message)) {
        $class = ' alert-error';
    }
?>
<?php if (!empty($message)) { ?>
<div class="alert<?php echo $class; ?>">
    <button data-dismiss="alert" class="close" type="button">
        ×
    </button>
    <?php echo $message; ?>
</div>

<script>$(".alert").alert();</script>
<?php } ?>

<?php include $this->templateComponent('form'); ?>