<?php
    $this->css($this->assetModule('script/widget-admin.css'));
    $this->jQuery('ui/jquery-ui.custom.min.js');
    $this->jQuery('extension/fileupload-min.js');
    $this->Backbone();
    $imageRoot = Pi::url('upload') . '/' . $module . '/';
?>
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>
<?php
    if (!empty($success)) {
        $message = $success;
        $class = ' alert-success';
    } elseif (!empty($error)) {
        $message = $success;
        $class = ' alert-error';
    } elseif (!empty($message)) {
        $class = ' alert-error';
    }
?>
<?php if (!empty($message)) { ?>
<div class="alert<?php echo $class; ?>">
    <button data-dismiss="alert" class="close" type="button">
        ×
    </button>
    <?php echo $message; ?>
</div>

<script>$(".alert").alert();</script>
<?php } ?>

<?php
    $form->prepare();
    $form->setAttribute('id', 'widget-js-form');
    echo $this->form()->openTag($form);

    echo $this->formRow($form->get('title'));
    echo $this->formRow($form->get('name'));
    echo $this->formRow($form->get('description'));
    echo $this->formRow($form->get('template'));
/**
 * $content: model collection of 'caption', 'desc', 'image', 'link'
 */
?>
<div class="controls" id="widget-js-carousel">
    <div class="widget-upload-btn">
       <div class="upload-carousel-add">
         <i class="icon-plus fileinput-button">
            <input type="file" name="image" multiple style="width: 100%;" class="hide">
        </i>
       </div>
    </div>
</div>
<?php
    $elements = $form->elementList();
    foreach ($elements['hidden'] as $element) {
        echo $this->formElement($element);
    }
    echo $this->formRow($form->get('submit'));
    echo $this->form()->closeTag();
?>
<script id="carousel-template" type="text/template">
    <i class="icon-remove-sign"></i>
    <img src="<%= image %>">
    <div class="form-horizontal">
        <div class="control-group">
            <label class="control-label"><?php _e('Caption'); ?></label>
            <div class="controls">
                <input type="text" value="<%= caption %>" name="caption" class="input-medium">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label"><?php _e('Link'); ?></label>
            <div class="controls">
                <input type="text" value="<%= link %>" name="link" class="input-medium">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label"><?php _e('Desc'); ?></label>
            <div class="controls">
                <textarea name="desc" class="input-medium" rows="5"><%= desc %></textarea>
            </div>
        </div>
    </div>
</script>
<script src="<?php echo $this->assetModule('script/widget-carousel.js'); ?>"></script>
<script>
widgetCarouselAction({
    imageRoot: '<?php echo $imageRoot; ?>',
    imgs: <?php echo $content ?: '[]'; ?>,
    uploadUrl: '<?php echo $this->url('', array('action' => 'upload')); ?>'
});
</script>