<?php
$this->jQuery('ui/jquery-ui.custom.min.js');
$this->jQuery('extension/fileupload-min.js');
$this->Backbone();
$imageRoot = Pi::url('upload') . '/' . $module . '/';
/**
 * $content: model collection of 'caption', 'desc', 'image', 'link', 'detail'
 */
 include $this->templateComponent('form');
?>

<style>
    button.remove-block {
        font-size: 30px;
        position: absolute;
        right: 8px;
        top: -15px;
    }
    .widget-upload-image {
        margin-top: 10px;
    }
</style>
<div class="form-group" id="widget-js-list">
    <label class="col-md-2 control-label"><?php echo _a('Images'); ?></label>
    <div class="col-md-10">
        <div class="row">
            <div class="btn btn-default col-sm-1 widget-block-add" style="margin-left: 15px">
                <?php echo __('Add'); ?>
            </div>
        </div>
    </div>
</div>

<script id="upload-template" type="text/template">
    <div class="widget-upload-btn">
        <div class="thumbnail text-center upload-list-add">
         <i class="fa fa-plus fa-3x text-muted fileinput-button">
            <input type="file" name="image" multiple style="width: 100%;" class="hide">
        </i>
       </div>
    </div>
</script>

<script id="image-template" type="text/template">
    <button type="button" class="close remove-image">&times;</button>
    <img src="<%= image %>">
</script>

<script id="list-template" type="text/template">
<div class="col-sm-6 col-md-3 widget-block">
    <button type="button" class="remove-block close">&times;</button>
    <div class="thumbnail">
        <div class="widget-upload-image">
            <%= image %>
        </div>
        <p>
            <label><?php echo _a('Caption'); ?></label>
            <input type="text" value="<%= caption %>" name="caption" class="form-control">
        <p>
            <label><?php echo _a('Link'); ?></label>
            <input type="text" value="<%= link %>" name="link" class="form-control">
        <p>
            <label><?php echo _a('Desc'); ?></label>
            <textarea name="desc" class="form-control" rows="5"><%= desc %></textarea>
        <p>
            <label><?php echo _a('More detail'); ?></label>
            <input type="text" value="<%= detail %>" name="detail" class="form-control">
    </div>
</div>
</script>
<link rel="stylesheet" href="<?php echo $this->assetModule('admin/admin.css'); ?>">
<script src="<?php echo $this->assetModule('admin/widget-list.js'); ?>"></script>
<script>
widgetListAction({
    imageRoot: '<?php echo $imageRoot; ?>',
    imgs: <?php echo $content ?: '[]'; ?>,
    uploadUrl: '<?php echo $this->url('', array('action' => 'upload')); ?>'
});
</script>