<!DOCTYPE html>
<html lang="<?php echo $data['locale'];?>">
<head>
    <meta charset="<?php echo $data['charset'];?>" />
    <title><?php echo $data['title'];?></title>
    <meta name='generator' content='Pi Engine' />
    <link rel="shortcut icon" href="../../favicon.ico" type="image/x-icon" />
    <link rel="icon" href="../..favicon.ico" type="image/ico" />
    <link rel="stylesheet" href="./asset/css/style.css" />
    <script type="text/javascript" src="./asset/js/jquery.min.js"></script>
    <?php
        if (!empty($data['headContent'])) {
            echo $data['headContent'];
        }
    ?>
</head>
<body class="container_12">
    <!-- header -->
    <div id="header">
        <div class="grid_3">
            <div class="logo"></div>
            <h1 class="logo-text"><a href="<?php echo $data['baseUrl'];?>"><?php echo $data['title']?></a></h1>
        </div>
        <?php
            $countPages = count($data['navPages']);
            $no = 0;
            foreach ($data['navPages'] as $key => $pageData) {
                $no++;
                $classWidth = ($no < $countPages) ? 'grid_2' : 'grid_3';
                echo '<div class="' . $classWidth . '">';
                if ($no > $data['pageIndex'] + 1) {
                    echo '<span class="nav">' . $no . ' ' . $pageData['title'] . '</span>';
                } else {
                    $classCurrent = ($no == $data['pageIndex'] + 1) ? ' current' : '';
                    echo '<span class="nav' . $classCurrent . '"><a href="' . $pageData['url'] . '">' . $no . ' ' . $pageData['title'] . '</a></span>';
                }
                echo '</div>';
            }
        ?>
    </div>

    <!-- content -->
    <?php
        if (!empty($data['pageHasForm'])) {
            echo '<form action="' . $_SERVER['PHP_SELF'] . '" method="post" autocomplete="off">';
        }
    ?>
    <div id="content">
        <h1 class="slogan"><?php echo $data['desc']?></h1>
        <?php
            echo $data['content'];
        ?>
    </div>

    <div id="buttons">
        <?php if (!empty($data['previousUrl'])) { ?>
            <button type="button" accesskey="p" onclick="location.href='<?php echo $data['previousUrl']; ?>'">
            <?php echo _t("Previous"); ?>
            </button>
        <?php } ?>

        <button type="button" accesskey="r" onclick="location.href='<?php echo $data['currentPage']['url']; ?>'">
        <?php echo _t("Reload"); ?>
        </button>

        <?php
        if ($data['status'] > -1) {
            if (!empty($data['pageHasForm'])) {
        ?>

            <button type="submit">
        <?php echo _t("Next"); ?>
            </button>
        <?php
            } elseif (!empty($data['nextUrl'])) { ?>
            <button type="button" accesskey="n" onclick="location.href='<?php echo $data['nextUrl']; ?>'">
        <?php echo _t("Next"); ?>
            </button>
        <?php
            }
        }
        ?>
    </div>

    <?php
        if (!empty($data['pageHasForm'])) {
            echo '<input type="hidden" name="page" value="' . $data['currentPage']['key'] . '">';
            echo '</form>';
        }
    ?>

    <div id="footer">
        <p>Powered by <a href="http://www.xoopsengine.org" title="Pi Engine">Pi Engine</a></p>
    </div>
    <?php
        if (!empty($data['footContent'])) {
            echo $data['footContent'];
        }
    ?>
</body>
</html>