<!DOCTYPE html>
<html lang="<?php echo $data['locale']; ?>">
<head>
    <meta charset="<?php echo $data['charset']; ?>" />
    <title><?php echo $data['title']; ?></title>
    <meta name='generator' content='Pi Engine' />
    <link rel="shortcut icon" type="image/x-icon" href="../favicon.ico" />

    <link rel="stylesheet" href="../public/vendor/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="./asset/css/style.css" />
    <script src="./asset/js/jquery.min.js"></script>

    <?php
        if (!empty($data['headContent'])) {
            echo $data['headContent'];
        }
    ?>
</head>
<body>
    <!-- header -->
    <div id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h1 class="logo-text"><a title="<?php echo $data['title']; ?>" href="<?php echo $data['baseUrl']; ?>"><?php echo $data['title']; ?></a></h1>
                </div>
                <?php
                    $countPages = count($data['navPages']);
                    $no = 0;
                    foreach ($data['navPages'] as $key => $pageData) {
                        $no++;
                        $classWidth = ($no < $countPages) ? 'col-md-2' : 'col-md-2';
                        echo '<div class="' . $classWidth . '">';
                        if ($no > $data['pageIndex'] + 1) {
                            echo '<span class="nav">' . $no . ' ' . $pageData['title'] . '</span>';
                        } else {
                            $classCurrent = ($no == $data['pageIndex'] + 1) ? ' current' : '';
                            echo '<span class="nav' . $classCurrent . '"><a href="' . $pageData['url'] . '">' . $no . ' ' . $pageData['title'] . '</a></span>';
                        }
                        echo '</div>';
                    }
                ?>
            </div>
        </div>
    </div>

    <!-- content -->
    <div id="main-content">
        <div class="container">
            <div class="row">
            <?php
                if (!empty($data['pageHasForm'])) {
                    echo '<form action="' . $_SERVER['PHP_SELF'] . '" method="post" autocomplete="off">';
                }
            ?>
            <div id="content">
                <h2 class="slogan"><?php echo $data['desc']; ?></h2>
                <?php
                    echo $data['content'];
                ?>
            </div>

            <div id="buttons">
                <?php if (!empty($data['previousUrl'])) { ?>
                    <button class="btn btn-primary" type="button" accesskey="p" onclick="location.href='<?php echo $data['previousUrl']; ?>'">
                    <?php echo _s("Previous"); ?>
                    </button>
                <?php } ?>

                <button class="btn btn-primary<?php if (empty($data['currentPage']['url'])) { echo ' disabled'; } ?>" type="button" accesskey="r" onclick="location.href='<?php echo $data['currentPage']['url']; ?>'">
                <?php echo _s("Reload"); ?>
                </button>

                <?php
                if ($data['status'] > -1) {
                    if (!empty($data['pageHasForm'])) {
                ?>

                    <button class="btn btn-primary" type="submit"><?php echo _s("Next"); ?></button>
                <?php
                    } elseif (!empty($data['nextUrl'])) { ?>
                    <button class="btn btn-primary" type="button" accesskey="n" onclick="location.href='<?php echo $data['nextUrl']; ?>'">
                <?php echo _s("Next"); ?>
                    </button>
                <?php
                    }
                }
                ?>

                <?php
                    if (!empty($data['pageHasForm'])) {
                        echo '<input type="hidden" name="page" value="' . $data['currentPage']['key'] . '">';
                        echo '</form>';
                    }
                ?>
            </div>
        </div>
    </div>

    <!-- footer -->
    <div id="footer">
        <div class="container">
            <div class="row">
                <p>Powered by <a href="http://pialog.org" title="Pi Engine">Pi Engine</a></p>
            </div>
        </div>
    </div>
    <?php
        if (!empty($data['footContent'])) {
            echo $data['footContent'];
        }
    ?>
</body>
</html>