<?php
    $elements = $block['elements'];
    $column   = $block['column'];
    $target   = $block['target'];
    $articles = $block['articles'];

    $template = sprintf('list-%s.phtml', $column);
?>

<style>
    
</style>

<div class="article-block-custom-list">
    <?php 
        if ('single' == $column) {
            $items = $articles;
        }
        include $template; 
    ?>
</div>

<script>
    $('.article-block-custom-list').parent().addClass('block-nopadding');
</script>
