<?php
    $style    = $block['style'];
    $column   = $block['column'];
    $target   = $block['target'];
    $articles = $block['articles'];

    $template = sprintf('list-%s-%s.phtml', $column, $style);
?>

<style>
    
</style>

<div class="article-block-custom-list">
    <?php include $template; ?>
</div>

<script>
    $('.article-block-custom-list').parent().addClass('block-nopadding');
</script>
