<?php
    $topArticle = array_shift($articles);
?>
<div>
    <div>
        <h4 style="margin-top: 0">
            <strong>
                <a target="<?php echo $this->escape($target); ?>" href="<?php echo $this->escape($topArticle['url']); ?>">
                    <?php echo $this->escape($topArticle['subject']); ?>
                </a>
            </strong>
        </h4>
        <div class="text-muted article-size12"><?php echo $topArticle['summary'] ?></div>
    </div>
    <div style="margin-top: 10px; margin-left: 15px">
        <?php foreach ($articles as $article) { ?>
        <li class="text-muted" style="padding: 2px">
            <a target="<?php echo $this->escape($target); ?>" href="<?php echo $this->escape($article['url']); ?>" class="article-front-title">
                <?php echo $this->escape($article['subject']); ?>
            </a>
        </li>
        <?php } ?>
    </div>
</div>
