<?php
    $topArticle = array_shift($articles);
?>
<div class="row-fluid">
    <div>
        <h4 style="margin-top: 0">
            <strong>
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($topArticle['url']) ?>">
                    <?php echo $this->escape($topArticle['subject']) ?>
                </a>
            </strong>
        </h4>
        <div class="media">
            <img class="pull-left" src="<?php echo Pi::url($topArticle['image']) ?>">
            <div class="media-body muted article-size12">
                <?php echo $topArticle['summary'] ?>
            </div>
        </div>
    </div>
    <div style="margin-top: 15px">
        <ul style="margin: 0 0 0 15px">
            <?php foreach ($articles as $article) { ?>
            <li class="muted" style="padding: 2px">
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" class="article-front-title"><?php echo $this->escape($article['subject']) ?></a>
            </li>
            <?php } ?>
        </ul>
    </div>
</div>
