<div class="row-fluid">
    <div class="span6">
        <div style="margin-left: 10px">
            <?php $i = 0; ?>
            <?php foreach ($articles as $article) { ?>
                <?php if ($i++ % 2 == 0) { ?>
            <li class="muted" style="padding: 2px">
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" class="article-front-title"><?php echo $this->escape($article['subject']) ?></a>
            </li>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
    <div class="pull-right span6">
        <div style="margin-left: 10px">
            <?php $j = 0; ?>
            <?php foreach ($articles as $article) { ?>
                <?php if ($j++ % 2 == 1) { ?>
            <li class="muted" style="padding: 2px">
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" class="article-front-title"><?php echo $this->escape($article['subject']) ?></a>
            </li>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>
