<?php
    $topArticleOne = array_shift($articles);
    $topArticleTwo = array_shift($articles);
?>
<div class="row">
    <div class="col-md-6">
        <div>
            <h4 style="margin-top: 0">
                <strong>
                    <a target="<?php echo $this->escape($target); ?>" href="<?php echo $this->escape($topArticleOne['url']); ?>">
                        <?php echo $this->escape($topArticleOne['subject']); ?>
                    </a>
                </strong>
            </h4>
            <div class="text-muted article-size12"><?php echo $topArticleOne['summary'] ?></div>
        </div>
        <div style="margin: 15px 0 0 15px">
            <?php $i = 0; ?>
            <?php foreach ($articles as $article) { ?>
                <?php if ($i++ % 2 == 1) { ?>
                <li class="text-muted" style="padding: 2px">
                    <a target="<?php echo $this->escape($target); ?>" href="<?php echo $this->escape($article['url']); ?>" class="article-front-title"><?php echo $this->escape($article['subject']); ?></a>
                </li>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
    <div class="pull-right col-md-6">
        <div>
            <h4 style="margin-top: 0;">
                <strong>
                    <a target="<?php echo $this->escape($target); ?>" href="<?php echo $this->escape($topArticleTwo['url']); ?>">
                        <?php echo $this->escape($topArticleTwo['subject']); ?>
                    </a>
                </strong>
            </h4>
            <div class="text-muted article-size12"><?php echo $topArticleTwo['summary'] ?></div>
        </div>
        <div style="margin: 15px 0 0 15px">
            <?php $j = 0; ?>
            <?php foreach ($articles as $article) { ?>
                <?php if ($j++ % 2 == 0) { ?>
                <li class="text-muted" style="padding: 2px">
                    <a target="<?php echo $this->escape($target); ?>" href="<?php echo $this->escape($article['url']); ?>" class="article-front-title"><?php echo $this->escape($article['subject']); ?></a>
                </li>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>
