<ul class="list list-rank unstyled">
    <?php 
    $i = 0;
    foreach ($block['articles'] as $article) { ?>
        <li class="article-list-rank" style="padding: 2px">
            <span <?php if ($i <= 2) echo 'class="emphasize"' ?>><?php if ($i < 9) echo 0 ?><?php echo ++$i ?></span>
            <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" title="<?php echo $this->escape($article['subject']) ?>" class="article-front-title">
                <?php echo $this->escape($article['subject']) ?>
            </a>
        </li>
    <?php } ?>
</ul>
