<?php
$target    = $block['target'];
$documents = $block['documents'];
$render = '<ol class="pi-order-list">';
foreach ($documents as $document) {
    $count = 0;
    foreach ($document['file'] as $subFile) {
        foreach ($subFile as $file) {
            $count += $file['count'];
        }
    }
    $render .= sprintf(
        '<li>
            <span class="pull-right">%s</span>
            <a href="%s" target="%s" class="pi-ellipsis pi-ellipsis-1" title="%s">
                %s
            </a>',
        $count,
        $document['url'],
        $target,
        _escape($document['title']),
        _escape($document['title']),
        $count
    );
}
$render .= '</ol>';
echo $render;
?>