<div class="row-fluid">
    <div class="span6">
        <div>
            <?php $i = 0; ?>
            <?php foreach ($articles as $article) { ?>
                <?php if ($i++ % 2 == 0) { ?>
            <div class="media">
                <img class="pull-left" src="<?php echo $this->escape($article['image']) ?>">
                <div class="media-body">
                    <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" class="article-front-title">
                        <?php echo $this->escape($article['subject']) ?>
                    </a>
                    <div class="muted article-size12" style="margin-top: 5px">
                        <?php echo $article['summary'] ?>
                    </div>
                </div>
            </div>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
    <div class="pull-right span6">
        <div>
            <?php $j = 0; ?>
            <?php foreach ($articles as $article) { ?>
                <?php if ($j++ % 2 == 1) { ?>
            <div class="media">
                <img class="pull-left" src="<?php echo $this->escape($article['image']) ?>">
                <div class="media-body">
                    <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" class="article-front-title">
                        <?php echo $this->escape($article['subject']) ?>
                    </a>
                    <div class="muted article-size12" style="margin-top: 5px">
                        <?php echo $article['summary'] ?>
                    </div>
                </div>
            </div>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>
