<?php 
    $config = $block['config'];
    $target = $block['target'];
    $width  = isset($block['width']) ? $block['width'] : 80;
    $height = isset($block['height']) ? $block['height'] : 60;
?>

<div class="article-block-newest-topic">
    <?php foreach ($block['items'] as $item) { ?>
    <div class="media">
        <img class="pull-left" src="<?php echo _escape($item['image']); ?>" style="width: <?php echo _escape($width); ?>px; height: <?php echo _escape($height); ?>px;">
        <div class="media-body">
            <a target="<?php echo _escape($target); ?>" href="<?php echo _escape($item['url']); ?>" class="article-front-title">
                <?php echo _escape($item['title']); ?>
            </a>
            <div class="muted article-size12" style="margin-top: 5px;">
                <?php echo _escape($item['description']); ?>
            </div>
        </div>
    </div>
    <?php } ?>
</div>

<script>
    $('.article-block-newest-topic').parent().addClass('block-nopadding');
</script>
