<div class="row">
    <a href="<?php echo Pi::url('feed/article'); ?>" target="<?php echo _escape($block['target']); ?>">
        <img src="<?php echo _escape($block['url']); ?>" title="<?php _e('Click to subscribe content'); ?>" 
         style="width: <?php echo _escape($block['width']); ?>px; height: <?php echo _escape($block['height']); ?>px">
    </a>
    <span><?php echo _escape($block['description']); ?></span>
</div>
