<?php
    $this->css($this->assetModule('script/admin.css'));
?>

<div id="jsList">
    <div class="clearfix form-inline">
        <form class="pull-right" 
              method="get" 
              action="<?php echo $this->url('', array('action' => 'list')); ?>" style="margin: 0">
            <div class="input-append">
                <input type="text" 
                       value="" 
                       placeholder="<?php echo _a('Name'); ?>"
                       class="input-medium" 
                       name="name"> 
                <button type="submit" class="btn"><?php echo _a('Search'); ?></button>
            </div>
        </form>
    </div>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 10px"><?php echo _a('ID'); ?></th>
                <th style="width: 20%;"><?php echo _a('Name'); ?></th>
                <th><?php echo _a('Title'); ?></th>
            </tr>
            <?php foreach ($apps as $app) { ?>
            <tr>
                <td><?php echo $this->escape($app->id) ?></td>
                <td>
                    <?php echo $this->escape($app->name); ?>
                    <div class="row-actions">
                        <a href="<?php echo $this->url('', array(
                            'action' => 'edit',
                            'id'     => $app->id
                        )); ?>"><?php echo _a('Edit'); ?></a> |
                        <a href="<?php echo $this->url('', array(
                            'action' => 'delete',
                            'id'     => $app->id
                        )); ?>" onclick="return window.confirm('Really delete?');"><?php echo _a('Delete'); ?></a>
                    </div>
                </td>
                <td><?php echo $this->escape($app->title); ?></td>
            </tr>   
            <?php } ?>
        </tbody>
    </table>
    <div class="pull-right">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>
