<?php
    $this->css($this->assetModule('script/admin.css'));
?>

<div id="jsList">
    <div class="clearfix form-inline">
        <form class="navbar-form navbar-left" style="padding-left: 0; margin: 0"
              method="get" 
              action="<?php echo $this->url('', array('action' => 'list')); ?>" style="margin: 0">
            <div class="form-group">
                <input type="text" 
                       value="" 
                       placeholder="<?php echo _a('Name'); ?>"
                       class="form-control" 
                       name="name"> 
            </div>
            <button type="submit" class="btn"><?php echo _a('Search'); ?></button>
        </form>
    </div>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 10px"><?php echo _a('ID'); ?></th>
                <th style="width: 20%;"><?php echo _a('Appkey'); ?></th>
                <th><?php echo _a('Title'); ?></th>
            </tr>
            <?php foreach ($apps as $app) { ?>
            <tr>
                <td><?php echo $this->escape($app['id']) ?></td>
                <td>
                    <?php echo $this->escape($app['appkey']); ?>
                    <div class="row-actions">
                        <a href="<?php echo $this->url('', array(
                            'action' => 'edit',
                            'id'     => $app['id']
                        )); ?>"><?php echo _a('Edit'); ?></a> |
                        <a href="<?php echo $this->url('', array(
                            'action' => 'delete',
                            'appkey' => $app['appkey']
                        )); ?>" onclick="return window.confirm('Are you really want to delete it?');"><?php echo _a('Delete'); ?></a>
                    </div>
                </td>
                <td><?php echo $this->escape($app['title']); ?></td>
            </tr>   
            <?php } ?>
        </tbody>
    </table>
    <div class="pull-right">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>
