<?php
    $this->css($this->assetModule('script/admin.css'));
?>

<div class="pi-media-header"><?php echo _escape($title); ?></div>

<div id="pi-js-media">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 120px"><?php echo _a('Application'); ?></th>
                <th style="width: 60px"><?php echo _a('Module'); ?></th>
                <th style="width: 80px"><?php echo _a('Category'); ?></th>
                <th><?php echo _a('Action'); ?></th>
            </tr>
            <?php foreach ($items as $appId => $item) { ?>
            <tr>
                <td><?php echo _escape($apps[$appId]); ?></td>
                <td></td>
                <td></td>
                <td>
                    <a target="_blank" href="<?php echo $item['url']; ?>">
                        <?php echo _escape($item['count']); ?>
                    </a>
                </td>
            </tr>
                <?php 
                    foreach ($item as $module => $rows) { 
                        if (!is_array($rows)) {
                            continue;
                        }
                ?>
            <tr>
                <td></td>
                <td><?php echo _escape($module); ?></td>
                <td></td>
                <td>
                    <a target="_blank" href="<?php echo $rows['url']; ?>">
                        <?php echo _escape($rows['count']); ?>
                    </a>
                </td>
            </tr>
                    <?php 
                        foreach ($rows as $id => $row) { 
                            if (!is_array($row)) {
                                continue;
                            }
                    ?>
            <tr>
                <td></td>
                <td></td>
                <td><?php echo _escape($categories[$id]); ?></td>
                <td>
                    <a target="_blank" href="<?php echo $row['url']; ?>">
                        <?php echo _escape($row['count']); ?>
                    </a>
                </td>
            </tr>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>
</div>
