<?php
    $this->css($this->assetModule('script/admin.css'));
?>

<div id="pi-js-media">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 250px"><?php echo _a('Application'); ?></th>
                <th style="width: 120px"><?php echo _a('Module'); ?></th>
                <th style="width: 120px"><?php echo _a('Token'); ?></th>
                <th><?php echo _a('Action'); ?></th>
            </tr>
            <?php foreach ($items as $appkey => $item) { ?>
            <tr>
                <td>
                <?php 
                    if (isset($apps[$appkey])) {
                        echo _escape($apps[$appkey]);
                    } else {
                ?>
                    <a href="<?php echo $this->url('', array('controller' => 'application', 'action' => 'add', 'appkey' => $appkey)); ?>" title="<?php _e('Click to change application name'); ?>">
                        <?php echo _escape($appkey); ?>
                    </a>
                <?php
                    }
                ?>
                </td>
                <td></td>
                <td></td>
                <td>
                    <a target="_blank" href="<?php echo $item['url']; ?>">
                        <?php echo _escape($item['count']); ?>
                    </a>
                </td>
            </tr>
                <?php 
                    foreach ($item as $module => $rows) { 
                        if (!is_array($rows)) {
                            continue;
                        }
                ?>
            <tr>
                <td></td>
                <td><?php echo _escape($module); ?></td>
                <td></td>
                <td>
                    <a target="_blank" href="<?php echo $rows['url']; ?>">
                        <?php echo _escape($rows['count']); ?>
                    </a>
                </td>
            </tr>
                    <?php 
                        foreach ($rows as $token => $row) { 
                            if (!is_array($row)) {
                                continue;
                            }
                    ?>
            <tr>
                <td></td>
                <td></td>
                <td><?php echo _escape($token); ?></td>
                <td>
                    <a target="_blank" href="<?php echo $row['url']; ?>">
                        <?php echo _escape($row['count']); ?>
                    </a>
                </td>
            </tr>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>
</div>
