<?php
    $this->css($this->assetModule('script/admin.css'));
?>

<div id="pi-js-media">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 120px"><?php echo _a('Type'); ?></th>
                <th><?php echo _a('Action'); ?></th>
            </tr>
            <?php foreach ($items as $item) { ?>
            <tr>
                <td><?php echo _escape($item['type']); ?></td>
                <td>
                    <a target="_blank" href="<?php echo $item['url']; ?>">
                        <?php echo _escape($item['count']); ?>
                    </a>
                </td>
            </tr>   
            <?php } ?>
        </tbody>
    </table>
</div>
