<?php
    $this->backbone();
    $this->css($this->assetModule('script/admin.css'));
?>

<form name="user" method="GET" action="<?php echo $url; ?>" style="margin-top: 10px" class="form-inline">
    <div class="form-group">
        <input type="text" class="form-control" name="user" value="<?php echo $user; ?>" placeholder="<?php echo _a('Type user id or identity'); ?>">
    </div>
    <button type="submit" class="btn"><?php echo _a('Submit'); ?></button>
</form>

<?php echo $this->tab($tabs); ?>

<div id="pi-js-media">
    <?php
        if (!empty($medias)) {
    ?>
    <div class="pi-media-batch-operation">
        <input type="checkbox" class="check-all" style="margin-right: 20px">
    <?php
        if (0 === $active || null === $active) {
    ?>
        <input type="button" name="enable" class="btn disabled" value="<?php echo _a('Enable'); ?>">
    <?php
        }
        if (1 === $active || null === $active) {
    ?>
        <input type="button" name="disable" class="btn disabled" value="<?php echo _a('Disable'); ?>">
    <?php
        }
        if (!$delete) {
    ?>
        <input type="button" name="delete" class="btn disabled" value="<?php echo _a('Delete'); ?>">
    <?php
        }
    ?>
        <input type="button" name="download" class="btn disabled" value="<?php echo _a('Download'); ?>">
    </div>
    
    <div class="pi-media-list">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th style="width: 10px"></th>
                    <th style="width: 10px"><?php echo _a('ID'); ?></th>
                    <th style="width: 20%;"><?php echo _a('Title'); ?></th>
                    <th style="width: 40px;"><?php echo _a('Mimetype'); ?></th>
                    <th style="width: 60px;"><?php echo _a('Application'); ?></th>
                    <th style="width: 20px;"><?php echo _a('Module'); ?></th>
                    <th style="width: 40px;"><?php echo _a('Category'); ?></th>
                    <th style="width: 80px;"><?php echo _a('Time') ?></th>
                </tr>
                <?php 
                    foreach ($medias as $media) { 
                        $media['active'] = (int) $media['active'];
                ?>
                <tr data-id="<?php echo _escape($media['id']); ?>" class="<?php echo 0 === $media['active'] && 0 !== $active ? ' text-muted' : ''; ?>">
                    <td>
                        <input type="checkbox" value="<?php echo _escape($media['id']); ?>" class="check-one">
                    </td>
                    <td><?php echo $this->escape($media['id']); ?></td>
                    <td>
                        <?php echo $this->escape($media['title']); ?>
                        <div class="row-actions one-action">
                            <a href="<?php echo $this->url('', array(
                                'controller'    => 'media',
                                'action'        => 'edit',
                                'id'            => $media['id'],
                            )); ?>" data-value="edit"><?php echo _a('Edit'); ?></a> |
                            <a href="javascript:void(0)" data-value="active" data-status="<?php echo $media['active'] ? 0 : 1 ?>">
                                <?php echo $media['active'] ? _a('Disable') : _a('Enable'); ?>
                            </a> |
                            <a href="javascript:void(0)" data-value="delete">
                                <?php echo _a('Delete'); ?>
                            </a> |
                            <a href="javascript:void(0)" data-value="download">
                                <?php echo _a('Download'); ?>
                            </a>
                        </div>
                    </td>
                    <td><?php echo $this->escape($media['mimetype']); ?></td>
                    <td>
                    <?php 
                        if (isset($apps[$media['appkey']])) {
                            echo _escape($apps[$media['appkey']]);
                        } else {
                    ?>
                        <a href="<?php echo $this->url('', array('controller' => 'application', 'action' => 'add', 'appkey' => $media['appkey'])); ?>" title="<?php _e('Click to change application name'); ?>">
                            <?php echo _escape($media['appkey']); ?>
                        </a>
                    <?php
                        }
                    ?>
                    </td>
                    <td><?php echo $this->escape($media['module']); ?></td>
                    <td><?php echo $this->escape($media['token']); ?></td>
                    <td><?php echo _date($media['time_created']); ?></td>
                </tr>   
                <?php } ?>
            </tbody>
        </table>
    </div>
    <?php
        } else {
    ?>
    <div class="pi-media-none"><?php echo _a('No resource available yet.'); ?></div>
    <?php
        }
    ?>
    
    <?php
        if (!empty($medias) && $paginator) {
            echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml');
        }
    ?>
</div>

<script>
(function($) {
    var page = {
        url : "<?php echo $this->url('', array('controller' => 'list', 'action' => 'index')); ?>".replace(/index\/$/,""),
        el  : $("#pi-js-media"),
        $   : function(selector) {
            return this.el.find(selector);
        },
        init : function() {
            _.bindAll(this);
            this.$(".check-all").click(this.checkAll);
            this.$(".check-one").click(this.clickOne);
            this.$("[name=enable]").click(this.batchOperation);
            this.$("[name=disable]").click(this.batchOperation);
            this.$("[name=delete]").click(this.batchOperation);
            this.$("[name=download]").click(this.batchOperation);
            this.$(".one-action a").click(this.oneAction);
        },
        checkAll : function() {
            var flag = this.$(".check-all").prop("checked");
            this.$(".check-one").prop("checked", flag).each(function() {
                var tr = $(this).parents("tr:first");
                if (flag) {
                    tr.addClass("info");
                } else {
                    tr.removeClass("info");
                }
            });
            this.toggleBulk();
        },
        batchOperation : function(e) {
            var url = "<?php echo $this->url('', array('controller' => 'media', 'action' => 'index')); ?>".replace(/index\/$/,"");
            var el = $(e.target);
            if (el.hasClass('disabled')) {
                return;
            }
            
            var name = el.attr('name');
            var operation, flag;
            var id = [],
                fn = function() {
                    this.$(".check-one:checked").each(function() {
                        id.push($(this).val()); 
                    });
                    if ('enable' == name || 'disable' == name) {
                        operation = 'active';
                        if ('enable' == name) {
                            flag = 1;
                        } else {
                            flag = 0;
                        }
                    } else {
                        operation = name;
                    }
                    if ('active' == operation) {
                        location.href = url + operation + "/id/" + id.join(",") + "/status/"
                                      + flag + "?redirect=" + this.encodeUrl();
                    } else if ('download' == operation) {
                        url = "<?php echo $this->url('default', array('controller' => 'download', 'action' => 'index')) ?>";
                        location.href = url + "?id=" + id + "&redirect=" + this.encodeUrl();
                    } else {
                        location.href = url + operation + "/id/" + id.join(",") + "?redirect="
                                      + this.encodeUrl();
                    }
                };
            if (name) {
                if (name == "delete") {
                    if (confirm("<?php echo _a('Please make sure these media resources are no in use!'); ?>")) {
                        fn.call(this);
                    }
                } else {
                    fn.call(this);
                }
            }
        },
        clickOne : function(e) {
            var el = $(e.target),
                tr = el.parents("tr:first");
            if (el.prop("checked")) {
                tr.addClass("info");
            } else {
                tr.removeClass("info");
            }
            this.toggleBulk();
        },
        toggleBulk : function() {
            var enableObj = this.$("[name=enable]");
            var disableObj = this.$("[name=disable]");
            var deleteObj = this.$("[name=delete]");
            var downloadObj = this.$("[name=download]");
            if (this.$(".check-one:checked").length) {
                deleteObj.removeClass("disabled");
                downloadObj.removeClass("disabled");
                if (enableObj) {
                    enableObj.removeClass("disabled");
                }
                if (disableObj) {
                    disableObj.removeClass("disabled");
                }
            } else {
                deleteObj.addClass("disabled");
                downloadObj.addClass("disabled");
                if (enableObj) {
                    enableObj.addClass("disabled");
                }
                if (disableObj) {
                    disableObj.addClass("disabled");
                }
            }
        },
        oneAction : function(e) {
            var url = "<?php echo $this->url('', array('controller' => 'media', 'action' => 'index')); ?>".replace(/index\/$/,"");
            var el = $(e.target),
                id = el.parents("tr:first").attr("data-id"),
                val = el.attr("data-value"),
                status = el.attr("data-status");
            if (val == "delete") {
                if (confirm("<?php echo _a('Please make sure this media is not in use!'); ?>")) {
                    location.href = url + "delete?id=" + id + "&redirect=" + this.encodeUrl(); 
                }
            } else if ('active' == val) {
                location.href = url + val + "?id=" + id + "&status=" 
                              + status + "&redirect=" + this.encodeUrl();
            } else if ('download' == val) {
                url = "<?php echo $this->url('default', array('controller' => 'download', 'action' => 'index')) ?>";
                location.href = url + "?id=" + id + "&redirect=" + this.encodeUrl();
            } else if ('edit' != val) {
                location.href = url + val + "?id=" + id + "&redirect=" + this.encodeUrl();
            }
        },
        encodeUrl : function() {
            return encodeURIComponent(location.href);
        }
    }
    page.init();
})(jQuery)
</script>
