<style>
    .stats-title {
        width: 100%;
        height: 25px;
        font-weight: bold;
        margin: 5px 0 10px 0;
    }
</style>
<div class="row">
    <div class="col-md-6 pull-left">
        <div class="stats-title"><?php echo _a('Top 10 resources'); ?></div>
        <table class="table table-striped" id="top-media">
            <?php
                $items = $medias;
                $field = 'count';
                include $this->template('admin/stats-page');
            ?>
        </table>
    </div>
    <div class="col-md-6 pull-right">
        <div class="stats-title"><?php echo _a('Top 10 submitters'); ?></div>
        <ul class="nav nav-tabs">
            <li class="active"><a href="javascript:void(0)" data-toggle="tab" data-target="#top-submitter-1">
                <?php echo _a('Today'); ?>
                </a>
            <li><a href="javascript:void(0)" data-toggle="tab" data-target="#top-submitter-2">
                <?php echo _a('In 7 days'); ?>
                </a>
            <li><a href="javascript:void(0)" data-toggle="tab" data-target="#top-submitter-3">
                <?php echo _a('In 30 days'); ?>
                </a>
            <li><a href="javascript:void(0)" data-toggle="tab" data-target="#top-submitter-4">
                <?php echo _a('history'); ?>
                </a>    
        </ul>
        <div class="tab-content">
            <table class="table table-striped tab-pane active" id="top-submitter-1">
                <?php
                    $items = $user['today'];
                    $field = 'total';
                    include 'stats-page.phtml';
                ?>
            </table>
            <table class="table table-striped tab-pane" id="top-submitter-2">
                <?php
                   $items = $user['week'];
                   include 'stats-page.phtml';
               ?>
            </table>
            <table class="table table-striped tab-pane" id="top-submitter-3">
                <?php
                   $items = $user['month'];
                   include 'stats-page.phtml';
                ?>
            </table>
            <table class="table table-striped tab-pane" id="top-submitter-4">
                <?php
                   $items = $user['ever'];
                   include 'stats-page.phtml';
                ?>
            </table>
        </div>
    </div>
</div>
