<style>
.dl-horizontal dt {
  width: 100px;
}
.dl-horizontal dd {
  margin-left: 120px;
}
</style>

<h2 class="page-header"><?php _e('Route list'); ?></h2>


<h3><?php _e('Routes'); ?></h3>
<ul>
    <?php foreach ($routes as $name => $data) { ?>
    <li><a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['label']); ?>"><?php echo _escape($data['label']); ?></a> </li>
    <?php } ?>
</ul>


<h3><?php _e('URL'); ?></h3>
<div><?php echo $uri; ?></div>


<h3 class="legend"><?php _e('Params'); ?></h3>
<dl class="dl-horizontal">
    <?php foreach ($params as $key => $value) { ?>
    <dt><?php echo _escape($key); ?></dt> <dd><?php echo _escape($value); ?></dd>
    <?php } ?>
</dl>