<h2 class="page-header"><?php _e('Demo File List'); ?></h2>

<ul>
<?php foreach ($files as $file) {?>
    <li><?php echo $file['filename']; ?>
        <a href="<?php echo $file['url_download']; ?>" class="btn btn-default"><?php _e('Download'); ?></a>
        <a href="<?php echo $file['url_delete']; ?>" class="btn btn-default"><?php _e('Delete'); ?></a>
    </li>
<?php } ?>
</ul>
<form action="<?php echo $this->url('', array('action' => 'upload')); ?>" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-lg-6">
    <div class="input-group">
        <input name="upload_demo" type="file" class="form-control">
        <span class="input-group-btn">
            <input class="btn btn-default" type="submit" name="submit" value="<?php _e('Upload'); ?>">
        </span>
    </div>
    </div>
</div>
</form>