<?php
/**
 * Pi Engine (http://pialog.org)
 *
 * @link            http://code.pialog.org for the Pi Engine source repository
 * @copyright       Copyright (c) Pi Engine http://pialog.org
 * @license         http://pialog.org/license.txt New BSD License
 */

namespace Module\Demo;

class Block
{
    public static function blocka($options, $module = null)
    {
        $block = array(
            'caption'   => __('Block A'),
            'content'   => sprintf('Called by %s through %s', $module,
                                   __METHOD__),
            'options'   => $options,
        );

        return $block;
    }

    public static function blockb($options, $module = null)
    {
        $block = array(
            'caption'   => __('Block B'),
            'content'   => sprintf('Called by %s through %s', $module,
                                   __METHOD__),
            'options'   => $options,
        );

        return $block;
    }

    public static function random($options, $module = null)
    {
        $block = sprintf('Block generated by %s through %s w/o template',
                         $module, __METHOD__);

        return $block;
    }
}
