<?php
    $this->css(array(
        $this->assetModule('script/block.css'),
        $this->assetModule('script/front.css'),
    ));
    $this->jQuery();
    
    if (isset($seo['title'])) {
        $this->headTitle($seo['title'], 'SET');
    }
    if (isset($seo['keywords'])) {
        $this->headMeta()->setName('keywords', $seo['keywords']);
    }
    if (isset($seo['description'])) {
        $this->headMeta()->setName('description', $seo['description']);
    }
    
    $elements = $config['list_item'];
?>

<div class="row">
<?php 
    if ($config['enable_list_nav'] && !empty($navs)) {
?>
    <div class="col-md-2"><?php echo $this->navigation($navs); ?></div>
<?php
    }
?>
    <div class="<?php echo !empty($navs) ? 'col-md-10' : 'col-md-12'; ?>">
        <div class="pi-article-module">
            <div class="clearfix pi-block-header">
                <span class="pi-block-title pull-left"><?php echo _escape($categories[$categoryId]['title']); ?></span>
                <span class="text-muted col-md-2" style="margin-top: 5px">
                    (<?php echo array_sum($counts) . __(' articles'); ?>)
                </span>
            </div>
            <div class="article-list-content">
                <div style="margin: 10px 0 20px 0">
                <?php $index = 0;
                    foreach ($children as $id) {
                        if (++$index > $config['max_sub_category']) {
                            break;
                        }
                ?>
                    <span style="margin-right: 10px">
                        <a href="<?php echo _escape($categories[$id]['url']); ?>" style="font-size: 15px; font-weight: bold; color: #333333">
                            <?php echo _escape($categories[$id]['title']); ?>
                        </a>
                        <span class="text-muted" style="margin-left: 3px">
                            (<?php echo isset($counts[$id]) ? _escape($counts[$id]) : 0 ?>)
                        </span>
                    </span>
                <?php
                    }
                ?>
                </div>
                <div class="list list14" id="jsList" style="list-style: none">
                    <?php $index = 0 ?>
                    <?php foreach ($articles as $article) { $index++ ?>
                        <div class="text-muted media">
                        <?php
                            if (in_array('feature', $elements)) {
                        ?>
                            <div class="pull-left" style="margin-right: 10px;">
                            <?php if ($article['image']) { ?>
                                <img src="<?php echo Pi::url($article['image']); ?>" style="width: 100px">
                            <?php } ?>
                            </div>
                        <?php
                            }
                        ?>
                            <div class="list-hover media-body">
                                <div class="list-title">
                                <?php
                                    if (in_array('time', $elements)) {
                                ?>
                                    <span class="pull-right article-list-desc">
                                        <?php echo  _date($article['time_publish']); ?>
                                    </span>
                                <?php
                                    }
                                ?>
                                    <a class="article-list-title" target="_blank" href="<?php echo $article['url'] ?>" 
                                    title="<?php echo _escape($article['subject']); ?>" style="color: #333333">
                                        <?php echo _escape($article['subject']); ?>
                                    </a>
                                </div>
                            <?php
                                if (in_array('author', $elements) || in_array('category', $elements)) {
                            ?>
                                <div class="list-desc">
                                <?php
                                    if (in_array('author', $elements)) {
                                ?>
                                    <span style="margin-right: 10px"><?php echo _escape($article['author']['name']); ?></span>
                                <?php
                                    }
                                    if (in_array('category', $elements)) {
                                ?>
                                    <span style="margin-right: 10px"><?php echo _escape($article['category']['title']); ?></span>
                                <?php
                                    }
                                ?>
                                </div>
                            <?php
                                }
                                if (in_array('summary', $elements)) {
                            ?>
                                <div class="list-summary">
                                    <?php echo mb_substr($article['summary'], 0, $config['list_summary_length'], 'UTF8'); ?>
                                </div>
                            <?php
                                }
                            ?>
                            </div>
                        </div>
                    <?php } ?>   
                </div>
                <div style="text-align: center">
                    <?php 
                        echo $this->paginationControl(
                            $paginator,
                            'Sliding',
                            'paginator.phtml'
                        );
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
