<?php
    $this->css(array(
        $this->assetModule('script/block.css'),
        $this->assetModule('script/front.css'),
    ));
    
    if (isset($seo['title'])) {
        $this->headTitle($seo['title'], 'SET');
    }
    if (isset($seo['keywords'])) {
        $this->headMeta()->setName('keywords', $seo['keywords']);
    }
    if (isset($seo['description'])) {
        $this->headMeta()->setName('description', $seo['description']);
    }
    
    $elements = $config['list_item'];
?>

<div class="row">
<?php
    if ($config['enable_list_nav'] && !empty($navs)) {
?>
    <div class="col-md-2"><?php echo $this->navigation($navs); ?></div>
<?php
    }
?>
    <div class="<?php echo !empty($navs) ? 'col-md-10' : 'col-md-12'; ?>">
        <div class="pi-article-module">
            <div class="clearfix pi-block-header">
                <h4 class="pi-block-title"><?php echo isset($categories[$category]) ? $categories[$category]['title'] : __('All Articles'); ?></h4>
            </div>
            <div class="article-list-content">
                <div class="list list14" style="list-style: none">
                    <?php $index = 0; ?>
                    <?php foreach ($articles as $row) { ?>
                        <div class="text-muted media">
                        <?php
                            if (in_array('feature', $elements)) {
                        ?>
                            <div class="pull-left" style="margin-right: 10px;">
                            <?php if ($row['image']) { ?>
                                <img src="<?php echo Pi::url($row['image']); ?>" style="width: 100px">
                            <?php } ?>
                            </div>
                        <?php
                            }
                        ?>
                            <div class="list-hover media-body">
                                <div class="list-title">
                                <?php
                                    if (in_array('time', $elements)) {
                                ?>
                                    <span class="pull-right article-list-desc">
                                        <?php echo _date($row['time_publish']); ?>
                                    </span>
                                <?php
                                    }
                                ?>
                                    <a class="article-list-title" target="_blank" href="<?php echo $this->escape($row['url']); ?>" title="<?php echo $this->escape($row['subject']); ?>">
                                        <?php echo $this->escape($row['subject']); ?>
                                    </a>
                                </div>
                            <?php
                                if (in_array('author', $elements) || in_array('category', $elements)) {
                            ?>
                                <div class="list-desc">
                                <?php
                                    if (in_array('author', $elements)) {
                                ?>
                                    <span style="margin-right: 10px"><?php echo isset($row['author']['name']) ? $row['author']['name'] : ''; ?></span>
                                <?php
                                    }
                                    if (in_array('category', $elements)) {
                                ?>
                                    <span style="margin-right: 10px"><?php echo $row['category']['title']; ?></span>
                                <?php
                                    }
                                ?>
                                </div>
                            <?php
                                }
                                if (in_array('summary', $elements)) {
                            ?>
                                <div class="list-summary">
                                    <?php echo mb_substr($row['summary'], 0, $config['list_summary_length'], 'UTF8'); ?>
                                </div>
                            <?php
                                }
                            ?>
                            </div>
                        </div>   
                    <?php } ?>
                </div>
                <div style="text-align: center">
                    <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(".article-list-content").find(".dashed:last").css("height", "0");
</script>
