<div id="multi-gallery-box" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-header" aria-hidden="true" style="width: 900px; margin-left: -450px">
    <!-- Header -->
    <div class="modal-header">
        <button type="button" class="close media-close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3><?php echo __('Choose Files') ?></h3>
    </div>
    <!-- Body -->
    <div class="modal-body">
        <div class="row-fluid">
            <!-- Displaying searching bar -->
            <div class="span12">
                <div class="pull-left">
                    <span class="btn upload fileinput-button">
                        <?php _e('Upload') ?>
                        <input type="file" multiple="" name="gallery">
                    </span>
                </div>
                <div class="clearfix form-inline pull-right" style="margin-bottom: 20px">
                    <div class="pull-right form-search">
                        <div class="input-append">
                            <input type="text" value="" placeholder="<?php _e('Title') ?>" class="input-medium search-query" name="gallery-title">
                            <button class="btn media-search" data-from="search"><?php _e('Search') ?></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Displaying search results -->
            <div class="span6 pull-left" style="margin-left: 0px">
                <div id="gallery-search-result"></div>
                <div class="media-page hide" style="text-align: center">
                    <div class="btn-toolbar">
                        <div class="btn-group">
                            <a class="btn btn-small disabled prev-page" data-from="prev" data-url="" href="javascript:void(0)">
                                &lt;&lt;&nbsp;<?php _e('Prev') ?>
                            </a>
                            <a class="btn btn-small next-page" data-from="next" data-url="" href="javascript:void(0)">
                                <?php _e('Next') ?>&nbsp;&gt;&gt;
                            </a>
                        </div>
                    </div>
                </div>
                <div id="gallery-upload-list"></div>
            </div>
            <!-- Displaying results want to add -->
            <div class="span6 pull-right">
                <div id="gallery-select-lists">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th><?php _e('Image') ?></th>
                                <th><?php _e('Title') ?></th>
                                <th><?php _e('Remove') ?></th>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <div class="modal-footer">
        <button id="gallery-cancel" class="btn" data-dismiss="modal" aria-hidden="true"><?php echo __('Cancel') ?></button>
        <button id="gallery-process" class="btn btn-primary" data-dismiss="modal" ><?php echo __('Yes') ?></button>
    </div>
</div>