<div id="multi-gallery-box" class="modal fade bs-modal-lg" tabindex="-1" role="dialog" aria-labelledby="modal-header" aria-hidden="true">
    <div class="modal-dialog modal-lg" style="width: 900px">
        <div class="modal-content">
            <!-- Header -->
            <div class="modal-header">
                <button type="button" class="close media-close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="modal-title"><?php echo __('Choose Files'); ?></h3>
            </div>
            <!-- Body -->
            <div class="modal-body">
                <div class="" style="margin: 0 15px">
                    <!-- Displaying searching bar -->
                    <div class="row">
                        <div class="pull-left">
                            <span class="btn btn-primary upload fileinput-button">
                                <?php _e('Upload'); ?>
                                <input type="file" multiple="" name="gallery">
                            </span>
                        </div>
                        <div class="clearfix form-inline pull-right" style="margin-bottom: 20px">
                            <div class="navbar-form navbar-right" style="margin: 0; padding-right: 0">
                                <div class="form-group">
                                    <input type="text" value="" placeholder="<?php _e('Title'); ?>" class="form-control" name="gallery-title">
                                </div>
                                <button class="btn media-search" data-from="search"><?php _e('Search'); ?></button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <!-- Displaying search results -->
                        <div class="col-md-6 pull-left" style="margin-left: 0px; padding: 0">
                            <div id="gallery-search-result"></div>
                            <div class="media-page hide" style="text-align: center">
                                <ul class="pager">
                                    <li>
                                        <a class="btn btn-small disabled prev-page" data-from="prev" data-url="" href="javascript:void(0)">
                                            &lt;&lt;&nbsp;<?php _e('Prev'); ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="btn btn-small next-page" data-from="next" data-url="" href="javascript:void(0)">
                                            <?php _e('Next'); ?>&nbsp;&gt;&gt;
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div id="gallery-upload-list"></div>
                        </div>
                        <!-- Displaying results want to add -->
                        <div class="col-md-6 pull-right" style="padding: 0">
                            <div id="gallery-select-lists">
                                <table class="table table-bordered">
                                    <tbody>
                                        <tr>
                                            <th><?php _e('Image'); ?></th>
                                            <th><?php _e('Title'); ?></th>
                                            <th><?php _e('Remove'); ?></th>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer -->
            <div class="modal-footer">
                <button id="gallery-cancel" class="btn" data-dismiss="modal" aria-hidden="true"><?php echo __('Cancel'); ?></button>
                <button id="gallery-process" class="btn btn-primary" data-dismiss="modal" ><?php echo __('Yes'); ?></button>
            </div>
        </div>
    </div>
</div>