<?php
    $this->css(array(
        $this->assetModule('script/article-front.css'),
        $this->assetModule('script/block.css'),
    ));
    $this->jQuery();
?>
<div class="pi-block">
    <div class="clearfix pi-block-header">
        <h4 class="pi-block-title"><?php echo $this->escape($title) . '"' ?>
            <span class="text-important divider">
                <?php echo $this->escape($tag); ?>
            </span><?php echo '"' ?>
        </h4>
        <span class="muted span2" style="margin: 10px 0 0 10px">
            (<?php echo $this->escape($count) . ' articles' ?>)
        </span>
    </div>
    <div class="article-list-content">
        <ul class="list list14">
            <?php $index = 0 ?>
            <?php foreach ($articles as $article) { $index++ ?>
                <li class="muted">
                    <div class="list-hover">
                        <span class="pull-right article-list-desc">
                            <?php echo date('Y-m-d', $article['time_publish']); ?>
                        </span>
                        <a class="article-list-title" target="_blank" href="<?php echo $article['url']; ?>" title="<?php echo $this->escape($article['subject']); ?>">
                            <?php echo $this->escape($article['subject']); ?>
                        </a>
                    </div>               
                <?php if ($index % 5 == 0) { ?>
                    <li class="dashed">
                <?php } ?>
            <?php } ?>   
        </ul>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml', array('class' => 'pagination-centered')); ?>
    </div>
</div>
<script>
    $(".article-list-content").find(".dashed:last").css("height", "0");
</script>
