<div class="pi-article-module">
    <div class="clearfix pi-block-header">
        <h4 class="pi-block-title"><?php echo $this->escape($title); ?></h4>
    </div>
    <div class="topic-list-content">
        <?php foreach ($topics as $row) {
            $eachCount = isset($count[$row['id']]) ? $count[$row['id']] : 0;
        ?>
            <div class="text-muted" style="margin-bottom: 20px">
                <div class="list-hover">
                    <div class="media">
                        <img class="pull-left" src="<?php echo Pi::url($row['image']); ?>">
                        <div class="media-body">
                            <div class="col-md-10">
                                <a class="topic-list-title" target="_blank" href="<?php echo $this->escape($row['url']); ?>"
                                    title="<?php echo $this->escape($row['title']); ?>" style="color: #333333">
                                        <?php echo $this->escape($row['title']); ?>
                                </a>
                                <div class="text-muted" style="font-size: 12px">
                                    <span><?php echo sprintf(__('Created at %s'), _date($row['time_create'])); ?></span>
                                    <span style="margin-left: 10px">
                                        <?php echo isset($lastAdded[$row['id']])
                                            ? sprintf(__('Last added at %s', _date($lastAdded[$row['id']])))
                                            : ''; ?>
                                    </span>
                                </div>
                                <div style="margin-top: 5px; color: #333333; font-size: 12px">
                                    <p><?php echo $this->escape($row['description']); ?></p>
                                </div>
                            </div>
                            <span class="pull-right col-md-2" style="text-align: right">
                                <a href="<?php echo $this->url($route, array('topic' => $row['slug'] ?: $row['id'], 'list' => 'all')); ?>">
                                    <?php echo $this->escape($eachCount) . __(' articles'); ?>
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<?php 
    echo $this->paginationControl(
        $paginator,
        'Sliding',
        'paginator.phtml',
        array('class' => 'pagination-centered')
    ); 
?>
