<?php
    $this->css(array(
        $this->assetModule('script/article-front.css'),
        $this->assetModule('script/block.css'),
    ));
?>

<div class="">
    <div class="clearfix" style="padding-bottom: 20px; border-bottom: 2px inset #000">
        <div class="span12">
            <h4 class="pi-block-title" style="margin-left: 0"><?php echo $this->escape($title) ?></h4>
            <span class="muted span2" style="margin: 10px 0 0 10px">
                (<?php echo $this->escape($count) . __(' articles') ?>)
            </span>
        </div>
        <div class="muted" style="font-size: 12px">
            <span><?php echo __('Created at ') . date('Y/m/d', $topic['time_create']) ?></span>
            <span style="margin-left: 10px">
                <?php echo $lastAdded ? __('Last added at ') . date('Y/m/d', $lastAdded) : '' ?>
            </span>
        </div>
    </div>
    <div class="topic-article-list" style="padding: 10px 10px 10px; border-bottom: 1px inset #000">
        <ul class="list list14" style="margin-left: 5px;">
            <?php $index = 0 ?>
            <?php foreach ($articles as $row) { ?>
                <li class="muted">
                    <div class="list-hover">
                        <span class="pull-right article-size12">
                            <?php echo date('Y/m/d H:i', $row['time_publish']) ?>
                        </span>
                        <a class="article-list-title" target="_blank" href="<?php echo $this->escape($row['url']) ?>" 
                           title="<?php echo $this->escape($row['subject']) ?>">
                               <?php echo $this->escape($row['subject']) ?>
                        </a>
                    </div>
                </li>
                <?php if (!(++$index % 5)) { ?>
                    <li class="dashed"></li>    
                <?php } ?>    
            <?php } ?>   
        </ul>
        <?php echo $this->paginationControl(
            $paginator,
            'Sliding',
            'paginator.phtml',
            array('class' => 'pagination-centered'))
        ?>
    </div>
</div>
<script>
    $(".topic-article-list").find(".dashed:last").css("height", "0");
</script>
