<ul class="nav nav-tabs message-nav-tabs">
    <li class="">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'index')); ?>" title="<?php _e('Private message'); ?>"><?php _e('Private message');; ?></a>
    </li>

    <li class="active">
        <a href="<?php echo $this->url('', array('controller' => 'index', 'action' => 'archive')); ?>" title="<?php _e('Archive'); ?>"><?php _e('Archive'); ?></a>
    </li>
</ul>
<p>
    <?php _e('Message system has upadtedEarly messages are still in the old system');?>
<p>

<ul class="nav nav-pills">
    <li>
        <a href="http://www.eefocus.com/message/index.php?msgtype=receive">
            <?php _e('Manage EEFOCUS old messages');?>
        </a>
        <a href="http://www.cndzz.com/space/message/index.php?msgtype=receive">
            <?php _e('Manage CNDZZ old messages');?>
        </a>
    </li>
</ul>