<?php $this->css($this->assetModule('script/admin.css')); ?>
<div class="clearfix">
    <?php if (isset($list) && !empty($list)) { ?>
        <h3><?php _e('List of messages'); ?></h3>
        <div class="message-list">
            <?php foreach ($list as $message) { ?>
                <?php $class = '';
                if ($message['is_deleted_to'] == 1 || $message['is_deleted_from'] == 1) {
                    $class = 'bg-danger';
                } elseif ($message['is_read_to'] == 0) {
                    $class = 'bg-warning';
                } ?>
                <div class="message-single clearfix <?php echo $class; ?>">
                    <div class="col-md-1">
                        <?php echo $message['userFrom']['avatar']; ?>
                    </div>
                    <div class="col-md-11">
                        <ul class="list-inline small text-muted">
                            <li><?php _e('From'); ?> : <?php echo $message['userFrom']['name']; ?></li>
                            <li class="message-divider">|</li>
                            <li><?php _e('To'); ?> : <?php echo $message['userTo']['name']; ?></li>
                            <li class="message-divider">|</li>
                            <li><?php _e('Send on'); ?> : <?php echo $message['time_send_view']; ?></li>
                            <li class="message-divider">|</li>
                            <li><?php _e('ID'); ?> : <?php echo $message['id']; ?></li>
                        </ul>
                        <div class="message-content">
                            <?php echo $message['contentShort']; ?>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#messageModal<?php echo $message['id']; ?>">
                                <?php _e('Full details'); ?>
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="messageModal<?php echo $message['id']; ?>" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel<?php echo $message['id']; ?>">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="messageModalLabel<?php echo $message['id']; ?>">
                                                <?php _e('From'); ?> : <?php echo $message['userFrom']['name']; ?>
                                                <?php _e('To'); ?> : <?php echo $message['userTo']['name']; ?>
                                                <?php _e('Send on'); ?> : <?php echo $message['time_send_view']; ?>
                                            </h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="clearfix">
                                                <div class="col-md-6">
                                                    <div class=" well well-xs">                                                    <h5><?php _e('From'); ?> : <?php echo $message['userFrom']['avatar']; ?> <?php echo $message['userFrom']['name']; ?></h5>
                                                        <ul class="list-unstyled">
                                                            <li><?php _e('Name'); ?> : <?php echo $message['userFrom']['name']; ?></li>
                                                            <li><?php _e('Identity'); ?> : <?php echo $message['userFrom']['identity']; ?></li>
                                                            <li><?php _e('Email'); ?> : <?php echo $message['userFrom']['email']; ?></li>
                                                            <li><?php _e('Is read ?'); ?> : <?php $message['is_read_from'] ? $text = __('Yes') : $text = __('No'); ?><?php echo $text; ?></li>
                                                            <li><?php _e('Is deleted ?'); ?> : <?php $message['is_delete_from'] ? $text = __('Yes') : $text = __('No'); ?><?php echo $text; ?></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class=" well well-xs">
                                                        <h5><?php _e('To'); ?> : <?php echo $message['userTo']['avatar']; ?> <?php echo $message['userTo']['name']; ?></h5>
                                                        <ul class="list-unstyled">
                                                            <li><?php _e('Name'); ?> : <?php echo $message['userTo']['name']; ?></li>
                                                            <li><?php _e('Identity'); ?> : <?php echo $message['userTo']['identity']; ?></li>
                                                            <li><?php _e('Email'); ?> : <?php echo $message['userTo']['email']; ?></li>
                                                            <li><?php _e('Is read ?'); ?> : <?php $message['is_read_to'] ? $text = __('Yes') : $text = __('No'); ?><?php echo $text; ?></li>
                                                            <li><?php _e('Is deleted ?'); ?> : <?php $message['is_delete_to'] ? $text = __('Yes') : $text = __('No'); ?><?php echo $text; ?></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="clearfix">
                                                <?php echo $message['content']; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger">
            <?php _e('Message list is empty !'); ?>
        </div>
    <?php } ?>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
</div>