<?php
// Load translation data
$this->i18nTheme('main');

// Load Bootstrap css by Twitter Team
$this->bootstrap(array(
    'css/font-awesome.min.css',
    'css/font-awesome-ie7.min.css'  => array(
        'conditional'   => 'IE 7',
    ),
));
// Load style.css, front.css
$this->css(array(
    $this->assetTheme('css/style.css')
));
$this->jQuery();
$this->js(array(
    $this->assetTheme('js/html5.js') => array(
        'conditional'   => 'lt IE 9',
    )
));
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <?php echo $this->assemble('headTitle', 4); ?>
    <?php echo $this->assemble('headMeta', 4); ?>
    <?php echo $this->assemble('headLink', 4); ?>
    <?php echo $this->assemble('headStyle', 4); ?>
    <?php echo $this->assemble('headScript', 4); ?>
</head>
<body id="pi-<?php echo Pi::service('module')->current(); ?>" class="<?php echo $locale; ?>">
    <!-- Header: logo, user bar -->
    <header class="container pi-header">
        <div class="pi-logo">
            <a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>" class="pi-logo-symbol">&pi;</a>
            <h1 title="<?php echo $this->escape($sitename); ?>" class="pi-logo-headline">
                <a href="<?php echo Pi::url('www'); ?>"><?php echo $this->escape($sitename); ?></a>
            </h1>
            <em class="pi-logo-tagline" title="<?php echo $this->escape($slogan); ?>"><?php echo $this->escape($slogan); ?></em>
        </div>
        <div class="pull-right pi-user-bar">
           <?php echo $this->widget('system-user-bar'); ?>
        </div>
    </header>

    <!-- Navigation: menu, breadcrumbs  -->
    <nav class="container pi-nav-container">
        <?php
            $navigation = $this->nav('front'/*, array('cache_ttl' => null, 'cache_level' => 'role')*/);
            echo $navigation->menu()->setUlClass('unstyled pi-menu');
        ?>
        <!-- Breadcrumbs: check if it exists  -->
        <?php $breadcrumbs = $navigation->breadcrumbs()->setSeparator('<span class="pi-divider">/</span>')->render(); ?>
        <?php if ($breadcrumbs) { ?>
        <div class="breadcrumb">
           <?php echo $breadcrumbs; ?>
        </div>
        <?php } ?>
    </nav>

    <!-- Page main content: blocks and module content -->
    <?php
        $blocks = $this->blocks();
        $blockTemplate = $this->template('block');
    ?>
    <section class="container">
        <!-- Top head zone -->
        <?php if (!empty($blocks['0'])) { ?>
        <div class="pi-zone-0">
            <?php foreach ($blocks['0'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
        <?php } ?>
        <!-- Left zone -->
        <?php if (!empty($blocks['1'])) { ?>
        <aside class="pi-zone-1">
            <?php foreach ($blocks['1'] as $block) {
                include $blockTemplate;
            } ?>
        </aside>
        <?php } ?>
        <!-- Right zone -->
        <?php if (!empty($blocks['8'])) { ?>
        <aside class="pi-zone-8">
            <?php foreach ($blocks['8'] as $block) {
                include $blockTemplate;
            } ?>
        </aside>
        <?php } ?>
        <div class="pi-main<?php
        if (!empty($blocks['1'])) { echo ' pi-main-left'; }
        if (!empty($blocks['8'])) { echo ' pi-main-right'; }
        ?>">
            <!-- Center top zone -->
            <?php if (!empty($blocks['2'])) { ?>
            <div class="pi-zone-2">
                <?php foreach ($blocks['2'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Top left zone -->
            <?php if (!empty($blocks['3'])) { ?>
            <div class="pi-zone-3">
                <?php foreach ($blocks['3'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Top right zone -->
            <?php if (!empty($blocks['4'])) { ?>
            <div class="pi-zone-4">
                <?php foreach ($blocks['4'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Module zone -->
            <div class="row-fluid pi-module-content">
                <?php echo $content; ?>
            </div>
            <!-- Bottom left zone -->
            <?php if (!empty($blocks['5'])) { ?>
            <div class="pi-zone-5">
                <?php foreach ($blocks['5'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Bottom right zone -->
            <?php if (!empty($blocks['6'])) { ?>
            <div class="pi-zone-6">
                <?php foreach ($blocks['6'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Center bottom zone -->
            <?php if (!empty($blocks['7'])) { ?>
            <div class="pi-zone-7">
                <?php foreach ($blocks['7'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
        </div>
        <!-- Bottom foot zone -->
        <?php if (!empty($blocks['99'])) { ?>
        <div class="pi-zone-99">
            <?php foreach ($blocks['99'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
        <?php } ?>
    </section>

    <!-- Footer: sitelink -->
    <footer class="pi-footer">
        <div class="container">
            <div class="pi-footer-line"></div>
            <a href="<?php echo Pi::url('page/terms'); ?>" title="<?php _e('Terms of use'); ?>"><?php _e('Terms of use'); ?></a><span class="pi-divider">|</span>
            <a href="<?php echo Pi::url('page/privacy'); ?>" title="<?php _e('Privacy guidelines'); ?>"><?php _e('Privacy guidelines'); ?></a><span class="pi-divider">|</span>
            <a href="<?php echo Pi::url('page/license'); ?>" title="<?php _e('License'); ?>"><?php _e('License'); ?></a><span class="pi-divider">|</span>
            <a href="<?php echo Pi::url('page/about'); ?>" title="<?php _e('About us'); ?>"><?php _e('About us'); ?></a><span class="pi-divider">|</span>
            <a href="<?php echo Pi::url('page/contact'); ?>" title="<?php _e('Contact us'); ?>"><?php _e('Contact us'); ?></a><span class="pi-divider">|</span>
            <a href="<?php echo Pi::url('page/join'); ?>" title="<?php _e('Join us'); ?>"><?php _e('Join us'); ?></a><span class="pi-divider">|</span>
            <a href="<?php echo Pi::url('page/help'); ?>" title="<?php _e('Help'); ?>"><?php _e('Help'); ?></a><span class="pi-divider">|</span>
            <a href="<?php echo Pi::url('page/sitemap'); ?>" title="<?php _e('Sitemap'); ?>"><?php _e('Sitemap'); ?></a> <br/>
            <a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>">&copy;<?php echo $this->escape($sitename); ?></a><span class="pi-divider">|</span>
            <a href="http://www.pialog.org" title="Pi Engine" target="_blank">Powered by Pi Engine</a><span class="pi-divider">|</span>
            <a href="http://www.pialog.org" title="Pi Engine" target="_blank">Design of Pi Engine</a>
        </div>
        <!-- Show execution time -->
        <?php $time = microtime(true) - Pi::startTime(); ?>
        <span style="font-size: 80%;" title="<?php _e('Execution time'); ?>"><?php echo $time; ?></span>
    </footer>
    <?php echo $this->assemble('footScript', 4); ?>
</body>
</html>
