<?php
// Load translation data
$this->i18nTheme('main');

$this->jQuery();
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'css/font-awesome.min.css'
));
$this->css(array(
    $this->assetTheme('css/style.css'),
    $this->assetTheme('css/admin.css'),
    $this->assetTheme('css/menu.css'),
));

$module = Pi::service('module')->current();
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale ?>">
<head>
    <!-- Charset -->
    <meta charset="<?php echo $charset; ?>">

    <!-- Title -->
    <?php echo $this->headTitle(); ?>
</head>
<body id="pi-<?php echo $module; ?>" class="<?php echo $locale; ?>">
    <!-- Global header logo starts -->
    <div class="header clearfix">
        <div class="container clearfix">
            <a href="<?php echo $this->url(); ?>" title="<?php echo $this->escape($sitename); ?>" class="header-logo"><?php echo $this->escape($sitename); ?></a>

            <span class="pull-right" style="margin: 20px 10px;">
                <a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>" target="_blank"><?php _e('Go to front'); ?> <i class="icon-circle-arrow-right"></i> </a>
            </span>

            <div class="pull-right" style="margin: 20px 5px;">
            <?php echo $this->widget('system-user-bar'); ?>
            </div>
        </div>
    </div>
    <!-- Global header logo ends -->

    <!-- Top menu starts -->
    <div class="container">
        <div class="span3 pull-left">
            <?php echo $this->adminSwitch($module); ?>
        </div>
        <div class="span9 pull-left global-nav">
            <!-- Global navigation starts -->
            <?php $navigation = $this->adminTop($module); ?>
            <?php if ($navigation) { ?>
                <!-- Global menu starts -->
                <div class="menu">
                <?php
                    echo $navigation->menu()->setUlClass('menu-horizontal')->render();
                ?>
                </div>
                <!-- Global menu ends -->
            <?php } ?>
        </div>
    </div>
    <!-- Top menu ends -->


    <div class="wrapper">
        <!-- Side menu starts -->
        <div class="span3 pull-left">
            <!-- Side navigation starts -->
            <?php $navigation = $this->adminSide($module); ?>
            <?php if ($navigation) { ?>
                <!-- Global menu starts -->
                <div class="menu">
                    <?php echo $navigation->menu()->setUlClass('menu-vertical')->render(); ?>
                </div>
                <!-- Side menu ends -->
            <?php } ?>
        </div>
        <!-- Side menu ends -->

        <!-- Main content starts -->
        <div class="container">
            <!-- Module content starts -->
            <?php if (!empty($content)) { ?>
                <div class="pi-zone-module"><?php echo $content; ?></div>
            <?php } ?>
            <!-- Module content ends -->
        </div>
        <!-- Main content ends -->
    </div>

    <!-- Footer starts -->
    <div class="footer">
        <div class="horizontal-rule"></div>
        <div class="container">
            &copy; <a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>"><?php echo $this->escape($sitename); ?></a> | Powered by <a href="http://www.xoopsengine.org" title="Pi Engine" target="_blank">Pi Engine</a> | Design of <a href="http://www.xoopsengine.org" title="Pi Engine" target="_blank">Pi Engine</a>
        </div>

        <!-- Show execution time -->
        <?php $time = microtime(true) - Pi::startTime(); ?>
        <span style="font-size: 80%;" title="<?php _e('Execution time'); ?>"><?php echo $time; ?></span>
        <!-- Show execution time -->

    </div>
    <!-- Footer ends -->

</body>
</html>