<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="sitemap"> 
	<p>
	   <a class="btn btn-primary" title="<?php _e('Add Link'); ?>" href="<?php echo $this->url('', array('action' => 'update')); ?>"><i class="fa fa-file"></i> <?php _e('Add Link'); ?></a>
	</p>
	<?php if (!empty($links)) { ?>
	<h3><?php _e('List of top links'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('URL'); ?></th>
			<th><?php _e('Change frequency'); ?></th>
			<th><?php _e('Time'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($links as $link) { ?>
		<?php
		if($link['status'] == 1) {
			$labelIdClass = 'label-success';	
		} elseif($link['status'] == 2) {
			$labelIdClass = 'label-warning';	
		} elseif($link['status'] == 3) {
			$labelIdClass = 'label-warning';	
		} elseif($link['status'] == 4) {
			$labelIdClass = 'label-warning';	
		} elseif($link['status'] == 5) {
			$labelIdClass = 'label-danger';	
		}	
		?>
        <tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($link['id']); ?></span></td>
            <td><?php echo $this->escape($link['loc']); ?></td>
            <td><?php echo $this->escape($link['changefreq']); ?></td>
            <td><?php echo $this->escape($link['time_create']); ?></td>
            <td>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $link['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				<a class="btn btn-danger" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'deleteLink', 'id' => $link['id'])); ?>"><i class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
            </td>
		</tr>	
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
	<p>
		<span class="label label-success"><?php _e('Published'); ?></span>
		<span class="label label-warning"><?php _e('Pending review'); ?></span>
		<span class="label label-warning"><?php _e('Draft'); ?></span>
		<span class="label label-warning"><?php _e('Private'); ?></span>
		<span class="label label-danger"><?php _e('Trash'); ?></span>
	</p>
	<?php } else { ?>
	<div class="alert alert-danger">
		<h4><?php _e('Empty list'); ?></h4>
		<p><?php _e('Link top table is empty, you can add your important website links on this table manually.'); ?></p>
	</div>
	<?php } ?>
</div>