
<h2 class="page-header"><?php echo $title; ?></h2>


<div class="login-message">
    <?php
    $homeUrl = $this->url('home');
    $homeString = sprintf('<a href="%s" title="%s">%s</a>', $homeUrl, __('homepage'), __('homepage'));
    $loginUrl = $this->url('sysuser', array('controller' => 'login'));
    $loginString = sprintf('<a href="%s" title="%s">%s</a>', $loginUrl, __('re-login'), __('re-login'));
    echo sprintf(__('You have logged out successfully, please go to %s or to %s.'), $homeString, $loginString);
    ?>
</div>

<div class="empty">
    <strong><?php _e('Choose: '); ?></strong>
    <span><a href="<?php echo $this->url('', array('controller' => 'login')); ?>" title="<?php _e('Login'); ?>"><?php _e('Login'); ?></a></span>
    <span><a href="<?php echo $this->url('', array('controller' => 'register')); ?>" title="<?php _e('Register'); ?>"><?php _e('Register'); ?></a></span>
</div>