<div class="page-header">
    <h1><?php echo _escape($title); ?></h1>
</div>
<?php if (!empty($message)) { ?>
    <div class="alert alert-danger">
        <?php echo _escape($message); ?>
    </div>
<?php } ?>
<?php
//include $this->templateComponent('form');
echo $this->form($form);
?>
<div class="row" style="padding: 40px 0;">
    <div class="offset-md-2 col-md-10">
        <a href="<?php echo Pi::service('user')->getUrl('password'); ?>"
           style="margin-right: 10px;">
            <?php _e('Find password'); ?>
        </a>
        <a href="<?php echo Pi::service('user')->getUrl('register'); ?>">
            <?php _e('Register'); ?>
        </a>
    </div>
</div>