<h1 class="page-header"><?php echo _escape($title); ?></h1>
<div class="login-message">
    <?php
    $logoutUrl    = $this->url('sysuser', ['controller' => 'login', 'action' => 'logout']);
    $logoutString = sprintf('<a href="%s" title="%s">%s</a>', $logoutUrl, __('logout'), __('logout'));
    echo sprintf(__('You have been logged on with account <strong>%s</strong>, please %s to re-login.'), $identity, $logoutString);
    ?>
</div>