
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>

<h3><?php _e('Coming soon ...'); ?></h3>

<div class="empty">
    <strong><?php _e('Choose: '); ?></strong>
    <span><a href="<?php echo $this->url('', array('controller' => 'email', 'action' => 'send')); ?>" title="<?php _e('Re-send activation email'); ?>"><?php _e('Re-send activation email'); ?></a></span>
    <span><a href="<?php echo $this->url('', array('controller' => 'login')); ?>" title="<?php _e('Login'); ?>"><?php _e('Login'); ?></a></span>
    <span><a href="<?php echo $this->url('', array('controller' => 'register')); ?>" title="<?php _e('Register'); ?>"><?php _e('Register'); ?></a></span>
</div>