

<div class="span3">
<ul class="nav nav-list bs-docs-sidenav">
    <li><a href="<?php echo $this->url('', array('controller' => 'account')); ?>"><?php _e('View account'); ?></a>
    <li><a href="<?php echo $this->url('', array('controller' => 'account', 'action' => 'edit')); ?>"><?php _e('Edit account'); ?></a>
    <li><a href="<?php echo $this->url('', array('controller' => 'email')); ?>"><?php _e('Change email'); ?></a>
    <li class="active"><a><?php _e('Change password'); ?></a>
    <li><a href="<?php echo $this->url('', array('controller' => 'login', 'action' => 'logout')); ?>" title="<?php _e('Logout'); ?>"><?php _e('Logout'); ?></a>
</ul>
</div>

<div class="span9">
    <h2 class="page-header"><?php echo $this->escape($title); ?></h2>
    <?php include $this->templateComponent('form'); ?>
</div>
