
<h2 class="page-header"><?php echo $this->escape($title); ?></h2>

<?php include $this->templateComponent('form'); ?>


<div class="empty">
    <strong><?php _e('Choose: '); ?></strong>
    <span><a href="<?php echo $this->url('', array('controller' => 'email', 'action' => 'send')); ?>" title="<?php _e('Re-send activation email'); ?>"><?php _e('Re-send activation email'); ?></a></span>
    <span><a href="<?php echo $this->url('', array('controller' => 'password', 'action' => 'find')); ?>" title="<?php _e('Find password'); ?>"><?php _e('Find password'); ?></a></span>
    <span><a href="<?php echo $this->url('', array('controller' => 'login')); ?>" title="<?php _e('Login'); ?>"><?php _e('Login'); ?></a></span>
</div>