
<h2 class="page-header"><?php echo _escape($title); ?></h2>

<?php include $this->templateComponent('form'); ?>


<div class="empty">
    <strong><?php _e('Choose: '); ?></strong>
    <span><a href="<?php echo Pi::service('user')->getUrl('password'); ?>" title="<?php _e('Find password'); ?>"><?php _e('Find password'); ?></a></span>
    <span><a href="<?php echo Pi::service('authentication')->getUrl('login', ''); ?>" title="<?php _e('Login'); ?>"><?php _e('Login'); ?></a></span>
</div>