<h1 class="page-header"><?php echo _escape($title); ?></h1>
<?php echo $this->form($form); ?>
<div class="empty">
    <strong><?php _e('Choose: '); ?></strong>
    <span><a href="<?php echo Pi::service('user')->getUrl('password'); ?>"
             title="<?php _e('Find password'); ?>"><?php _e('Find password'); ?></a></span>
    <span><a href="<?php echo Pi::service('authentication')->getUrl('login', ''); ?>"
             title="<?php _e('Login'); ?>"><?php _e('Login'); ?></a></span>
</div>