<?php

$this->css($this->assetModule('front/front.css'));

if (!empty(Pi::user()->config('login_description'))) {
    $description = Pi::user()->config('login_description');
    $class = 'col-md-6';
} else {
    $description = '';
    $class = 'col-md-12';
}
?>

<div class="modal fade" id="loginRegisterModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><?php echo __('User login') ?></h4>
            </div>
            <div class="modal-body">

                <div class="row clearfix">
                    <?php if (!empty($description)) { ?>
                        <div class="hidden-xs hidden-sm col-md-6">
                            <?php echo $description; ?>
                        </div>
                    <?php } ?>
                    <div class="<?php echo $class; ?>">
                        <?php echo $this->form($block['loginForm'], 'vertical'); ?>
                        <div class="user-action-bar">
                            <div class="col-md-offset-2 col-md-10">
                                <ul class="list-inline">
                                    <li>
                                        <a title="<?php _e('Find password'); ?>" href="<?php echo Pi::service('user')->getUrl('password'); ?>"><?php _e('Find password'); ?></a>
                                    </li>
                                    <li>
                                        <a title="<?php _e('Register'); ?>" href="<?php echo Pi::service('user')->getUrl('register'); ?>"><?php _e('Register'); ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>