<?php

$this->css($this->assetModule('front/front.css', 'user'));

if (!empty(Pi::user()->config('login_description'))) {
    $description = Pi::user()->config('login_description');
    $class = 'col-md-6';
} else {
    $description = '';
    $class = 'col-md-12';
}

/* @var \Module\User\Form\LoginForm $loginForm */
$loginForm = $block['loginForm'];
$registerForm = $block['registerForm'];

if($registerForm->has('redirect') && !$registerForm->get('redirect')->getValue()){
    $redirect = Pi::service('url')->getRequestUri();
    $registerForm->get('redirect')->setValue($redirect);
}

?>

<div class="modal fade" id="loginRegisterModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><?php echo __('Login / register') ?></h4>
            </div>
            <div class="modal-body user-template">
                <div class="row clearfix">
                    <?php if (!empty($description)) { ?>
                        <div class="hidden-xs hidden-sm col-md-6">
                            <?php echo $description; ?>
                        </div>
                    <?php } ?>
                    <div class="<?php echo $class; ?>">

                        <div id="modal-login-wrapper" class="modal-action-wrapper" data-action="login">
                            <?php echo $this->form($loginForm, 'vertical'); ?>

                            <a title="<?php _e('Find password'); ?>" href="<?php echo Pi::service('user')->getUrl('password'); ?>"><?php _e('Find password'); ?></a>

                            <div class="clearfix user-action-bar">
                                <h2><?php _e('Not already registered ?'); ?></h2>
                                <p>
                                    <a class="btn btn-default toggle-modal-action" title="<?php _e('Register'); ?>" href="#">
                                        <?php _e('Register'); ?>
                                    </a>
                                </p>
                            </div>
                        </div>

                        <div id="modal-register-wrapper" class="modal-action-wrapper" data-action="register">
                            <?php echo $this->form($registerForm, 'vertical'); ?>

                            <a title="<?php _e('Find password'); ?>" href="<?php echo Pi::service('user')->getUrl('password'); ?>"><?php _e('Find password'); ?></a>

                            <div class="clearfix user-action-bar">
                                <h2><?php _e('Already registered ?'); ?></h2>
                                <p>
                                    <a class="btn btn-default toggle-modal-action" title="<?php _e('Login'); ?>" href="#">
                                        <?php _e('Login'); ?>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('#loginRegisterModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var action = button.data('action');
        var modal = $(this);
        modal.find('.modal-action-wrapper').hide();
        modal.find('.modal-action-wrapper[data-action="'+action+'"]').show();
    });

    $('.toggle-modal-action').click(function(){
        $('#loginRegisterModal .modal-action-wrapper').toggle();
        return false;
    });
</script>