<?php
    $this->css($this->assetModule('script/article-front-admin.css'));
?>

<div id="jsList">
    <div class="clearfix form-inline">
        <a class="btn" href="<?php echo $this->url('', array('action' => 'add')) ?>"><?php _e('Add') ?></a>
        <form class="pull-right" 
              method="get" 
              action="<?php echo $this->url('', array('action' => 'list')) ?>" style="margin: 0">
            <div class="input-append">
                <input type="text" 
                       value="" 
                       placeholder="<?php _e('Name') ?>" 
                       class="input-medium" 
                       name="name"> 
                <button type="submit" class="btn"><?php _e('Search') ?></button>
            </div>
        </form>
    </div>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width:10%;"><?php _e('Photo') ?></th>
                <th style="width:15%;"><?php _e('Name') ?></th>
                <th><?php _e('Biography') ?></th>
            </tr>
            <?php foreach ($authors as $author) { ?>
            <tr>
                <td>
                    <?php if ($author->photo) { ?>
                        <img src="<?php echo Pi::url($author->photo) ?>" 
                             alt="<?php echo $this->escape($author->name) ?>" 
                             style="height: 40px;">
                    <?php } else { ?>
                        <div class="default-author-img">
                            <i class="icon-user"></i>
                        </div>
                    <?php } ?>    
                </td>
                <td>
                    <?php echo $this->escape($author->name) ?>
                    <div class="row-actions">
                        <a href="<?php echo $this->url('', array(
                            'action' => 'edit',
                            'id'     => $author->id
                        )) ?>"><?php _e('Edit') ?></a> | 
                        <a href="<?php echo $this->url('', array(
                            'action' => 'delete',
                            'id'     => $author->id
                        )) ?>" onclick="return window.confirm('Really delete?');"><?php _e('Delete') ?></a>
                    </div>
                </td>
                <td><?php echo $this->escape($author->description) ?></td>
            </tr>   
            <?php } ?>
        </tbody>
    </table>
    <div class="pull-right">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>
