<?php
    $this->css(
        array(
            $this->assetModule('script/article-front-admin.css'),
            $this->assetModule('script/article-admin.css'),
            $this->assetModule('script/jquery.Jcrop.min.css'),
        )
    );
    $this->jQuery('extension/fileupload-min.js');
    $this->Backbone();
    $this->js(array(
        $this->assetModule('script/ajax-upload-min.js'),
        $this->assetModule('script/jquery.Jcrop.min.js')
    ));
?>

<style>
    .article-preview-photo img {
         max-width: none;
    }
</style>

<h2 class="page-header"><?php echo $this->escape($title); ?></h2>

<?php include 'message-box.phtml' ?>

<div id="jsUpload">
    <?php include $this->templateComponent('form'); ?>

    <script id="template-upload" type="text/template">
        <div>
            <div id="author-image" class="upload-image-bg">
                <?php $src = $form->get('photo')->getValue(); ?>
                <?php if ($src) { ?>
                    <div class="black-bg"><i class="author icon-remove"></i></div>    
                    <img src="<?php echo Pi::url($src) ?>">
                <?php } else { ?>    
                    <i class="icon-user"></i>
                <?php } ?>
            </div>
            <button class="btn upload fileinput-button" data-toggle="modal" href="#upload-box">
                <?php _e('Upload') ?>
            </button>
        </div>
    </script>

    <div id="upload-box" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-header" aria-hidden="true">
        <!-- Header -->
        <div class="modal-header">
            <button id="photo-close" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="modal-header"><?php echo __('Modify Photo') ?></h3>
        </div>
        <!-- Body -->
        <div class="modal-body">
            <div class="article-uploaded-box">
                <div class="article-upload-hit">
                    <input class="btn article-add-photo" type="button" value="<?php _e('Upload') ?>" style="width: 110px;">
                    <div class="muted" style="margin-top: 10px; font-size: 12px;">
                        <?php echo __('Format supported: ') . implode(', ', $imageExtension) ?>
                        (<?php echo $this->escape($maxMediaSize) ?>)
                    </div>
                </div>
                <img class="hide article-upload-image">
            </div>
            <div class="article-preview">
                <div class="preview-desc"><?php _e('Please make sure your photo is clearly.') ?></div>
                <div class="article-preview-photo" style="width: <?php echo $this->escape($authorSize) ?>px; height: <?php echo $this->escape($authorSize) ?>px">
                    <img src="<?php echo $src ? Pi::url($src) : '' ?>" class="<?php echo $src ? '' : 'hide' ?>">
                    <i class="icon-user<?php echo $src ? ' hide' : '' ?>"></i>
                </div>
                <div class="preview-desc-size muted"><?php echo __('Size: ') . $this->escape($authorSize) . '×' . $this->escape($authorSize) . 'px' ?></div>
            </div>
            <input name="photo-url" type="hidden">
        </div>
        <!-- Footer -->
        <div class="modal-footer">
            <button id="photo-cancel" class="btn" disabled><?php _e('Cancel') ?></button>
            <button id="photo-process" class="btn btn-primary" data-dismiss="modal" disabled><?php _e('Yes') ?></button>
        </div>
    </div>
</div>

<script>
    var jcrop_api;
    var page = {
        id      : function() {
            return "<?php echo $form->get('id')->getValue()
                ? 'id/' . $form->get('id')->getValue()
                : 'fake_id/' . $form->get('fake_id')->getValue() ?>";
        },
        resizeFakeId : '<?php echo uniqid() ?>',
        el      : $('#jsUpload'),
        $       : function(selector) {
            return  this.el.find(selector);      
        },
        size    : '<?php echo $this->escape($authorSize) ?>',
        savedPhoto : '',
        format  : function() {
            var format = '<?php echo implode(',', $imageExtension) ?>';
            var data   = new Array();
            data = format.split(',');
            return data;
        },
        template : _.template('<div class="black-bg">'
                        + '<i class="author icon-remove"></i></div>'
                        + '<img src="<%=preview_url %>">'
        ),
        events  : function() {
            $('#photo-process').click(this.savePhoto.bind(this));
            $('#photo-cancel').click(this.cancelUpload.bind(this));
            
        },
        init: function() {
            page.$("[name=placeholder]")
                .parents(".control-group:first")
                .find(".controls")
                .html($("#template-upload").html());
            
            $('.icon-remove').click(this.removePhoto.bind(this));
            this.ajaxUpload();
        },
        ajaxUpload: function() {
            this.uploadImg = page.$('.article-upload-image');
            this.preImg    = page.$('.article-preview-photo img');
            this.iconImg   = page.$('.article-preview-photo i');
            new ajaxUpload($('.article-add-photo'), {
                action  : '<?php echo $this->url('', array(
                    'controller' => 'author',
                    'action'     => 'upload',
                )) ?>fake_id/' + page.resizeFakeId,
                format  : page.format(),
                name    : 'upload',
                json    : true,
                start   : function() {
                    page.$('.article-add-photo').val('<?php _e('In process ...') ?>');
                },
                done: function(res) {
                    if (res.status) {
                        page.$('.article-upload-hit').addClass('hide');
                        $('[target=ajaxUploadIframe]').remove();
                        page.$('#photo-cancel').removeAttr('disabled');
                        page.$('#photo-process').removeAttr('disabled');
                        page.initJcrop(res.data);
                    } else {
                        alert(res.message);
                        page.$('.article-add-photo').val('<?php _e('Upload') ?>');
                    }
                },
                fail: function() {
                    alert('<?php _e('Error occured, please try again!') ?>');
                    page.$('.article-add-photo').val('<?php _e('Upload') ?>');
                }
            });
        },
        initJcrop: function(res) {
            var time = new Date().getTime();
            var url = res['preview_url'] + '?' + time,
                boundx = 0,
                boundy = 0;
            var preImg = this.preImg;
            this.result = res;
            this.uploadImg.removeClass('hide').attr('src', url);
            this.preImg.removeClass('hide').attr('src', url);
            this.iconImg.addClass('hide');
            jcrop_api && jcrop_api.destroy();
            if (res.w > res.h) {
                boundx = 300;
            } else {
                boundy = 300;
            }
            if (boundx) {
                boundy = 300 * res.h / res.w;
                this.uploadImg.css({
                    width: 300,
                    height: boundy
                });
            } else {
                boundx = 300 * res.w / res.h;
                this.uploadImg.css({
                    width: boundx,
                    height: 300
                });
            }
            this.uploadImg.Jcrop({
                aspectRatio: 1,
                bgOpacity: .5,
                onChange: function(c) {
                    var rx = page.size / c.w;
                    var ry = page.size / c.h;

                    var r = Math.round;
                    
                    preImg.css({
                        'width'      : r(rx * boundx),
                        'height'     : r(ry * boundy),
                        'marginLeft' : r(-rx * c.x),
                        'marginTop'  : r(-ry * c.y)
                    });
                }
            }, function() {
                jcrop_api = this;
                var h = this.ui.holder;
                h.css({
                    left: (300 - h.outerWidth()) /2,
                    top: (300 - h.outerHeight()) /2     
                });
                this.setSelect([40,40,200,200]);
            });
        },
        cancelUpload   : function() {
            var url = '<?php echo $this->url('', array(
                'action'       => 'remove-upload',
            )) ?>fake_id/' + page.resizeFakeId;
            var preImg  = this.preImg;
            var iconImg = this.iconImg;
            $.get(url, function(result) {
                result = $.parseJSON(result);
                if (result.status) {
                    var imageUrl = '<?php echo $src ? Pi::url($src) : '' ?>';
                    imageUrl = page.savedPhoto ? page.savedPhoto : imageUrl;
                    if (imageUrl) {
                        preImg.attr('style', '');
                        preImg.attr('src', imageUrl);
                    } else {
                        preImg.attr('style', '');
                        preImg.attr('src', '');
                        preImg.addClass('hide');
                        iconImg.removeClass('hide');
                    }
                    page.$('.article-upload-hit').removeClass('hide');
                    page.$('.article-uploaded-box img').remove();
                    page.$('.article-uploaded-box').append('<img class="hide article-upload-image">');
                    page.$('.article-uploaded-box .jcrop-holder').remove();
                    page.$('.article-add-photo').val('<?php _e('Upload') ?>');
                    page.init();
                } else {
                    alert(result.message);
                }
                page.$('#photo-cancel').attr('disabled', 'disabled');
                page.$('#photo-process').attr('disabled', 'disabled');
            });
        },
        savePhoto: function(e) {
            var self = this;
            e.preventDefault();
            var d = jcrop_api.tellScaled();
            var ret = this.result.w > this.result.h ? this.result.w / 300 : this.result.h / 300;
            for (var i in d) {
                if (d.hasOwnProperty(i)) {
                    d[i] = Math.round(d[i] * ret);
                }
            }
            d['photo']   = this.result.preview_url;
            d['id']      = '<?php echo $form->get('id')->getValue() ?>';
            d['fake_id'] = '<?php echo $form->get('fake_id')->getValue() ?>';
            d['upload_id'] = page.resizeFakeId;
            
            if (this.result.preview_url) {
                $.post('<?php echo $this->url('', array('action' => 'save-image')); ?>', d).done(function(res) {
                    res = $.parseJSON(res);
                    if (res.status) {
                        page.$('.article-upload-hit').removeClass('hide');
                        page.$('.article-uploaded-box img').remove();
                        page.$('.article-uploaded-box').append('<img class="hide article-upload-image">');
                        page.$('.article-uploaded-box .jcrop-holder').remove();
                        page.$('.article-add-photo').val('<?php _e('Upload') ?>');

                        self.render(res.data);
                        page.savedPhoto = res.data.preview_url;
                        page.init();
                    } else {
                        alert(res.message);
                    }
                    page.$('#photo-cancel').attr('disabled', 'disabled');
                    page.$('#photo-process').attr('disabled', 'disabled');
                });
            }
        },
        removePhoto    : function() {
            var self    = this;
            var preImg  = this.preImg;
            var iconImg = this.iconImg;
            $.getJSON('<?php echo $this->url(
                '',
                array(
                    'controller' => 'author',
                    'action'     => 'remove-image'
                )
            ); ?>' + page.id()).done(function() {
                page.$('[name=image]').val('');
                self.$("#author-image").html('<i class="icon-user"></i>');
                preImg.attr('style', '');
                preImg.attr('src', '');
                preImg.addClass('hide');
                iconImg.removeClass('hide');
                page.init();
            });
        },
        render          : function(obj) {
            obj.preview_url = obj.preview_url + '?' + new Date().getTime();
            page.$("#author-image").html(page.template(obj));
        }
    }
    page.events();
    page.init();
</script>
