<?php
    $this->css($this->assetModule('script/admin.css'));
    $this->jQuery();
?>
<div id="pi-js-list">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 50px"><?php echo _a('Image'); ?></th>
                <th style="width: 350px"><?php echo _a('Title'); ?></th>
                <th><?php echo _a('Description'); ?></th>
            </tr>
            <?php foreach ($items as $item) {
                if ('root' == $item['slug']) {
                    continue;
                }
                // Generate url
                $addUrl    = $this->url('', array(
                    'action' => 'add',
                    'parent' => $item['id'],
                ));
                $editUrl   = $this->url('', array(
                    'action' => 'edit',
                    'id'     => $item['id'],
                ));
                $activeUrl = $this->url('', array(
                    'action' => 'active',
                    'id'     => $item['id'],
                    'status' => $item['active'] ? 0 : 1,
                ));
                $deleteUrl = $this->url('', array(
                    'action' => 'delete',
                    'id'     => $item['id'],
                ));
                $mergeUrl  = $this->url('', array(
                    'action' => 'merge',
                    'from'   => $item['id'],
                ));
                $moveUrl   = $this->url('', array(
                    'action' => 'move',
                    'from'   => $item['id'],
                ));
                $sortUrl  = $this->url('', array(
                    'action' => 'sort',
                    'from'   => $item['id'],
                ));
            ?>
            <tr>
                <td><?php 
                    if ($item['image']) {
                        $image = Pi::url($item['image']);
                ?>
                    <div class="list-image">
                        <img src="<?php echo _escape($image); ?>" alt="<?php echo _escape($item['title']); ?>">
                    </div>
                <?php
                    } else {
                ?>
                        <div class="list-image"><span class="fa fa-list"><i></i></span></div>
                <?php
                    }
                ?>
                </td>
                <td><?php echo _escape(str_repeat('-', $item['depth']) . ' ' . $item['title']); ?>
                    <?php if ($item['active'] == 0) { ?> - <strong class="text-warning"><?php echo _a('Inactive'); ?></strong> <?php } ?>
                    <div class="row-actions">
                        <a href="<?php echo _escape($addUrl); ?>"><?php _e('Add'); ?></a> |
                        <a href="<?php echo _escape($editUrl); ?>"><?php _e('Edit'); ?></a> |
                        <a href="<?php echo _escape($activeUrl); ?>"><?php $item['active'] ? _e('Deactivate') : _e('Active'); ?></a> |
                        <a href="<?php echo _escape($deleteUrl); ?>"
                           onclick="return window.confirm('Really delete it?');"><?php _e('Delete'); ?></a> |
                        <a href="<?php echo _escape($mergeUrl); ?>"><?php _e('Merge'); ?></a> |
                        <a href="<?php echo _escape($moveUrl); ?>"><?php _e('Move'); ?></a> |
                        <a href="<?php echo _escape($sortUrl); ?>"><?php _e('Sort'); ?></a>
                    </div>
                </td>
                <td><?php echo _escape($item['description']); ?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
