<?php
    $this->css($this->assetModule('script/admin.css'));
    $this->jQuery();
?>
<div id="pi-js-list">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 50px"><?php echo _a('Image'); ?></th>
                <th style="width: 250px"><?php echo _a('Title'); ?></th>
                <th><?php echo _a('Description'); ?></th>
            </tr>
            <?php foreach ($items as $item) {
                if ('root' == $item['slug']) {
                    continue;
                }
                // Generate url
                $addUrl    = $this->url('', array(
                    'action' => 'add',
                    'parent' => $item['id']
                ));
                $editUrl   = $this->url('', array(
                    'action' => 'edit',
                    'id'     => $item['id']
                ));
                $deleteUrl = $this->url('', array(
                    'action' => 'delete',
                    'id'     => $item['id']
                ));
                $mergeUrl  = $this->url('', array(
                    'action' => 'merge',
                    'from'   => $item['id']
                ));
                $moveUrl   = $this->url('', array(
                    'action' => 'move',
                    'from'   => $item['id']
                ));
                $sortUrl  = $this->url('', array(
                    'action' => 'sort',
                    'from'   => $item['id'],
                ));
            ?>
            <tr>
                <td><?php 
                    if ($item['image']) {
                        $image = Pi::url($item['image']);
                ?>
                    <div class="list-image">
                        <img src="<?php echo $this->escape($image); ?>" alt="<?php echo $this->escape($item['title']); ?>">
                    </div>
                <?php
                    } else {
                ?>
                        <div class="list-image"><span class="fa fa-list"><i></i></span></div>
                <?php
                    }
                ?>
                </td>
                <td><?php echo $this->escape(str_repeat('-', $item['depth']) . ' ' . $item['title']); ?>
                    <div class="row-actions">
                        <a href="<?php echo $this->escape($addUrl); ?>"><?php echo _a('Add'); ?></a> |
                        <a href="<?php echo $this->escape($editUrl); ?>"><?php echo _a('Edit'); ?></a> |
                        <a href="<?php echo $this->escape($deleteUrl); ?>"
                           onclick="return window.confirm('Really delete it?');"><?php echo _a('Delete'); ?></a> |
                        <a href="<?php echo $this->escape($mergeUrl); ?>"><?php echo _a('Merge'); ?></a> |
                        <a href="<?php echo $this->escape($moveUrl); ?>"><?php echo _a('Move'); ?></a> |
                        <a href="<?php echo $this->escape($sortUrl); ?>"><?php echo _a('Sort'); ?></a>
                    </div>
                </td>
                <td><?php echo $this->escape($item['description']); ?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
