<?php
    $this->css($this->assetModule('script/article-front-admin.css'));
    $this->jQuery();
?>
<div id="jsList">
    <div class="form-inline">
        <a class="btn" href="<?php echo $this->url('', array('action' => 'add')) ?>"><?php echo _a('Add') ?></a>
    </div>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 50px"><?php echo _a('Image') ?></th>
                <th style="width: 250px"><?php echo _a('Title') ?></th>
                <th><?php echo _a('Description') ?></th>
            </tr>
            <?php foreach ($categories as $category) {
                if ('root' == $category['slug']) {
                    continue;
                }
                // Generate url
                $addUrl    = $this->url('', array(
                    'action' => 'add',
                    'parent' => $category['id']
                ));
                $editUrl   = $this->url('', array(
                    'action' => 'edit',
                    'id'     => $category['id']
                ));
                $deleteUrl = $this->url('', array(
                    'action' => 'delete',
                    'id'     => $category['id']
                ));
                $mergeUrl  = $this->url('', array(
                    'action' => 'merge',
                    'from'   => $category['id']
                ));
                $moveUrl   = $this->url('', array(
                    'action' => 'move',
                    'from'   => $category['id']
                ));
            ?>
            <tr>
                <td><?php 
                    if ($category['image']) {
                        $image = Pi::url($category['image']);
                ?>
                        <img src="<?php echo $this->escape($image) ?>" alt="<?php echo $this->escape($category['title']) ?>">
                <?php
                    } else {
                ?>
                        <div class="list-image"><i class="icon-th-list"></i></div>
                <?php
                    }
                ?>
                </td>
                <td><?php echo $this->escape(str_repeat('-', $category['depth']) . ' ' . $category['title']) ?>
                    <div class="row-actions">
                        <a href="<?php echo $this->escape($addUrl) ?>"><?php echo _a('Add') ?></a> |
                        <a href="<?php echo $this->escape($editUrl) ?>"><?php echo _a('Edit') ?></a> |
                        <a href="<?php echo $this->escape($deleteUrl) ?>" 
                           onclick="return window.confirm('Really delete?');"><?php echo _a('Delete') ?></a> |
                        <a href="<?php echo $this->escape($mergeUrl) ?>"><?php echo _a('Merge') ?></a> |
                        <a href="<?php echo $this->escape($moveUrl) ?>"><?php echo _a('Move') ?></a>
                    </div>
                </td>
                <td><?php echo $this->escape($category['description']) ?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
