<?php include 'message-box.phtml'; ?>

<?php
    $form->setAttributes(array(
        'action'  => $this->url('', array('action' => $action)),
        'method'  => 'post',
        'class'   => 'form-horizontal',
    ));
    echo $this->form()->openTag($form);
?>
<div class="">
    <div class="col-md-12 alert alert-info">
    <?php 
        echo sprintf(
            _a('%s all articles from source cluster to target cluster'),
            'merge' === $action ? _a('Merge') : _a('Move')
        );
    ?>
    </div>

    <div class="col-md-12">
        <div class="">
            <div class="col-md-5">
                <h3><?php echo _a('Source Cluster'); ?></h3>
                <br/>
                <?php
                    $element = $form->get('from');
                    echo $this->formElement($element);
                ?>
                <p class="help-block">
                </p>
            </div>
            <div class="col-md-2">
                <h3>&nbsp;</h3>
                <br/>
                <p class="help-block">
                    <?php echo sprintf(_a('%s into'), 'merge' === $action ? _a('merge') : _a('move')); ?>
                </p>
            </div>
            <div class="col-md-5">
                <h3><?php echo _a('Target Cluster'); ?></h3>
                <br/>
                <?php
                    $element = $form->get('to');
                    echo $this->formElement($element);
                ?>
                <p class="help-block">
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <?php 
            $elements = $form->elementList();
            foreach ($elements['hidden'] as $element) {
                echo $this->formElement($element);
            }
        ?>
    </div>
</div>
<div class="form-actions" style="margin: 30px">
    <button type="submit" class="btn btn-primary"><?php echo $elements['submit']->getValue(); ?></button>
</div>
<?php echo $this->form()->closeTag(); ?>
