<div id="message-box">
<?php if (isset($message)) { ?>
    <div class="alert alert-<?php echo $error ? 'danger' : 'success'; ?>">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <?php echo $this->escape($message); ?>
    </div>
<?php } ?>
</div>

<script id="template-message" type="text/template">
    <div class="alert alert-<%= status %>">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <%= message %>
    </div>
</script>
