<?php $module = Pi::service('module')->current(); ?>
<div style="height: 250px;">
    <div class="row" style="margin: 150px 0 0 0">
        <div class="col-md-3">
            <img class="pull-right" src="<?php echo $this->assetModule('image/error-operation.png', $module); ?>">
        </div>
        <div class="col-md-7">
            <div><h2 class="page-header"><?php echo _a('You have an error operation: '); ?></h2></div>
            <div><?php echo $this->escape($message); ?></div>
        </div>
    </div>
</div>
