<?php
    $this->css($this->assetModule('script/admin.css'));
    $this->jQuery();
?>
<div id="pi-js-page">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th style="width: 200px"><?php _e('Title'); ?></th>
                <th><?php _e('Dressup'); ?></th>
                <th><?php _e('Category'); ?></th>
                <th><?php _e('Cluster'); ?></th>
                <th><?php _e('Type'); ?></th>
                <th><?php _e('Controller'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($items as $item) {
                if (1 == $item['id']) {
                    continue;
                }
                // Generate url
                $addUrl    = $this->url('', array(
                    'action' => 'add',
                    'parent' => $item['id']
                ));
                $editUrl   = $this->url('', array(
                    'action' => 'edit',
                    'id'     => $item['id']
                ));
                $deleteUrl = $this->url('', array(
                    'action' => 'delete',
                    'id'     => $item['id']
                ));
                $meta = json_decode($item['meta'], true);
            ?>
            <tr>
                <td><?php echo _escape(str_repeat('-', $item['depth']) . ' ' . $item['title']); ?>
                    <div class="row-actions">
                        <a href="<?php echo _escape($addUrl); ?>"><?php echo _a('Add'); ?></a> |
                        <a href="<?php echo _escape($editUrl); ?>"><?php echo _a('Edit'); ?></a> |
                        <a href="<?php echo _escape($deleteUrl); ?>"
                           onclick="return window.confirm('Really delete it?');"><?php echo _a('Delete'); ?></a>
                    </div>
                </td>
                <td><a target="blank" href="<?php echo _escape($item['dressup']); ?>" class="btn btn-primary"><?php _e('Dressup'); ?></a></td>
                <td><?php echo _escape($category[$meta['category']]['title']); ?></td>
                <td><?php echo _escape($cluster[$meta['cluster']]['title']); ?></td>
                <td><?php echo _escape($meta['type']); ?></td>
                <td><?php echo _escape($item['controller']); ?></td>
                <td><?php echo _escape($item['action']); ?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
