<div class="well">
    <ul class="nav nav-list">
        <li class="<?php echo $action == 'list' ? 'active' : '' ?>">
            <a href="<?php echo $this->url('admin', array('action' => 'list')) ?>">
                <?php _e('List User Level') ?>
            </a>
        </li>
        <li class="<?php echo $action == 'list-level' ? 'active' : '' ?>">
            <a href="<?php echo $this->url('admin', array('action' => 'list-level')) ?>">
                <?php _e('List Level') ?>
            </a>
        </li>
    </ul>
</div>
