<?php
    $this->bootstrap();
    $this->css(array(
        $this->assetModule('script/article-ui.css'),
        $this->assetModule('script/article-admin.css'),
    ));
    $this->jQuery();
    $this->Backbone();
?>

<div>
    <div class="span3">
        <?php include 'permission-nav.phtml' ?>
    </div>

    <div id="jsList" class="span12">
        <div class="form-inline">
            <a class="btn" href="<?php echo $this->url('',array('action' => 'add-level')) ?>">
                <?php _e('Add') ?>
            </a>
        </div>
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th><?php _e('Title') ?></th>
                    <th><?php _e('Description') ?></th>
                    <th><?php _e('Created Time') ?></th>
                </tr>
                <?php 
                    foreach ($levels as $level) { 
                        $editUrl   = $this->url('', array('action' => 'edit-level', 'id' => $level['id']));
                        $deleteUrl = $this->url('', array('action' => 'delete-level', 'id' => $level['id']));
                ?>
                <tr>
                    <td><?php echo $this->escape($level['title']) ?>
                    <?php if (!$level['active']) { ?> - <strong class="text-warning"><?php _e('Deactive') ?></strong> <?php } ?>
                        <div class="row-actions">
                            <a href="<?php echo $this->escape($editUrl) ?>"><?php _e('Edit') ?></a> |
                            <a href="<?php echo $this->escape($deleteUrl) ?>" 
                               onclick="return window.confirm('Do you really want to delete it?');">
                                   <?php _e('Delete') ?></a> |
                            <?php if ($level['active']) { ?>
                                <a class="one-action" data-id="<?php echo $this->escape($level['id']) ?>" 
                                   data-value="active" data-status="0" href="javascript:void(0)">
                                       <?php _e('Deactivate') ?>
                                </a>
                            <?php } else { ?>
                                <a class="one-action" data-id="<?php echo $this->escape($level['id']) ?>" 
                                   data-value="active" data-status="1" href="javascript:void(0)">
                                       <?php _e('Active') ?>
                                </a>
                            <?php } ?>
                        </div>
                    </td>
                    <td><?php echo $this->escape($level['description']) ?></td>
                    <td><?php echo date('Y-m-d', $level['time_create']) ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<script>
(function($) {
    var page = {
        url: "<?php echo $this->url('', array('controller' => 'permission', 'action' => '')) ?>".replace(/\/$/,""),
        el : $("#jsList"),
        $  : function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            this.$(".one-action").click(this.oneAction);
        },
        oneAction: function(e) {
            var el     = $(e.target),
                id     = el.attr("data-id"),
                val    = el.attr("data-value"),
                status = el.attr("data-status");
           if (status) {
                location.href = this.url + val + "?id=" + id + "&status=" + status + "&from=" + this.encodeUrl();
           } else {
                location.href = this.url + val + "?id=" + id + "&from=" + this.encodeUrl();
           }
        },
        encodeUrl: function() {
            return encodeURIComponent(location.href);
        }
    }
    page.init();
})(jQuery)
</script>
