<?php
    $this->bootstrap();
    $this->css(array(
        $this->assetModule('script/article-ui.css'),
        $this->assetModule('script/article-admin.css'),
    ));
    $this->jQuery();
    $this->Backbone();
?>

<div>
    <div class="span3">
        <?php include 'permission-nav.phtml' ?>
    </div>

    <div id="jsList" class="span12">
        <div class="form-inline">
            <a class="btn" href="<?php echo $this->url('', array('action' => 'add')) ?>"><?php _e('Add') ?></a>
        </div>
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th><?php _e('User') ?></th>
                    <th><?php _e('Category') ?></th>
                    <th><?php _e('Level') ?></th>
                </tr>
                <?php 
                    foreach ($userLevels as $row) { 
                        $editUrl   = $this->url('', array('action' => 'edit', 'id' => $row['id']));
                        $deleteUrl = $this->url('', array('action' => 'delete', 'id' => $row['id']));
                        ?>
                <tr>
                    <td><?php echo $this->escape($users[$row['uid']]) ?>
                        <div class="row-actions">
                            <a href="<?php echo $this->escape($editUrl) ?>"><?php _e('Edit') ?></a> |
                            <a href="<?php echo $this->escape($deleteUrl) ?>" 
                               onclick="return window.confirm('Do you really want to delete it?');">
                                   <?php _e('Delete') ?>
                            </a>
                        </div>
                    </td>
                    <?php $item = array();
                    foreach ($row['category'] as $category) { 
                        $item[] = $categories[$category];
                    } ?>
                    <td>
                        <?php echo empty($item) ? __('All categories') : $this->escape(implode(',', $item)) ?>
                    </td>
                    <td><?php echo $this->escape($levels[$row['level']]) ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<script>
(function($) {
    var page = {
        url: "<?php echo $this->url('', array('controller' => 'permission', 'action' => '')) ?>".replace(/\/$/,""),
        el : $("#jsList"),
        $  : function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            this.$(".one-action").click(this.oneAction);
        },
        oneAction: function(e) {
            var el     = $(e.target),
                id     = el.attr("data-id"),
                val    = el.attr("data-value"),
                status = el.attr("data-status");
           if (status) {
                location.href = this.url + val + "?id=" + id + "&status=" + status + "&from=" + this.encodeUrl();
           } else {
                location.href = this.url + val + "?id=" + id + "&from=" + this.encodeUrl();
           }
        },
        encodeUrl: function() {
            return encodeURIComponent(location.href);
        }
    }
    page.init();
})(jQuery)
</script>
