<?php
    $this->css(array(
        $this->assetModule('script/article-admin.css'),
    ));
    $this->jQuery();
    $this->Backbone();
?>

<div>
    <div class="span12">
        <?php include 'setup-nav.phtml' ?>
    </div>
    
    <div class="span12">

        <?php include 'message-box.phtml' ?>

        <?php echo $this->form()->openTag($form) ?>
        <div><?php $element = $form->get('mode'); ?>
            <?php
                $options = $element->getValueOptions();
                $value   = $element->getValue();
                foreach ($options as $name => $label) {
            ?>
            <div class="span12">
                <label class="radio span3">
                    <input type="radio" value="<?php echo $this->escape($name) ?>" name="mode"<?php echo ($value == $name) ? ' checked' : '' ?>>
                        <?php echo $this->escape($label) ?>
                </label>
                <a class="article-form-mode" data-mode="<?php echo $this->escape($name) ?>" href="javascript:void(0)">
                    <?php _e('Preview') ?>
                </a>
            </div>
            <?php
                }
            ?>
        </div>

        <div id="article-config-form-elements" 
            <?php 
                if ($custom != $form->get('mode')->getValue()) {
                    echo 'style="display: none"';
                }
            ?>>
            <h5 class="span12 page-header">
                <?php _e('Form Elements') ?>
                <a class="btn btn-small btn-primary custom-form-update" style="margin-left: 10px">
                    <?php _e('Update') ?>
                </a>
            </h5>
            <?php foreach ($items as $name => $item) { ?>
                <?php $element = $form->get($name); ?>
                <div class="span3 control-group<?php if ($this->formElementErrors($element)) echo ' error' ?>">
                    <div><?php echo $this->formElement($element) ?></div>
                </div>
            <?php } ?>
        </div>

        <div class="span12">
        <?php $element = $form->get('submit'); ?>
            <div><?php echo $this->formElement($element) ?></div>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<script>
    var page = {
        init        : function() {
            $('input[name="submit"]').css('margin-top', '20px');
            $('.article-form-mode').click(this.preview.bind(this));
            $('input[name="mode"]').change(this.changeMode.bind(this));
            $('.custom-form-update').click(this.update.bind(this));
        },
        preview     : function(e) {
            var obj  = $(e.target);
            var mode = obj.data('mode');
            var url  = '<?php echo $this->url('', array('action' => 'preview')) ?>';
            url += 'mode/' + mode;
            
            if ('custom' == mode) {
                var form = '';
                $('input[type="checkbox"]:checked').each(function() {
                    if (form.length) {
                        form += ',' + $(this).attr('name');
                    } else {
                        form = $(this).attr('name');
                    }
                });
                url += '/elements/' + form;
            }
            obj.attr('target', '_blank');
            obj.attr("href", url);
        },
        changeMode  : function(e) {
            if ('custom' == $(e.target).val()) {
                $('#article-config-form-elements').css('display', 'block');
            } else {
                $('#article-config-form-elements').css('display', 'none');
            }
        },
        update      : function() {
            var url = '<?php echo $this->url('', array('action' => 'update')) ?>';
            var form = '';
            $('input[type="checkbox"]:checked').each(function() {
                if (form.length) {
                    form += ',' + $(this).attr('name');
                } else {
                    form = $(this).attr('name');
                }
            });
            url += 'elements/' + form;
            
            var self = this;
            $.get(url, function(result) {
                result = $.parseJSON(result);
                self.renderMessage(result.status, result.message);
            });
        },
        renderMessage   : function(status, message) {
            $('#message-box').html(
                _.template($('#template-message').html(), {
                    status      : status ? 'success' : 'error',
                    message     : message
                })
            );
        }
    };
    page.init();
</script>
