<?php
    $this->jQuery('extension/fileupload-min.js');
    $this->Backbone();
?>

<div>
    <div class="">
        <?php include 'message-box.phtml'; ?>
        <div id="article-js-route">
            
            <div class="article-route-content">
                <div class="article-route-header">
                    <span class="pull-left"><?php echo _a('Custom Parameters'); ?></span>&nbsp;
                    <span class="install-status">[<?php echo $installed ? _a('Install') : _a('Un-install'); ?>]</span>
                    <div class="pull-right">
                        <a href="javascript:void(0)" class="route-delete"><?php echo _a('Delete'); ?></a>
                    </div>
                </div>
                <div id="article-route-param">
                    <ol class="muted">
                    <?php
                        foreach ($configs as $key => $value) {
                    ?>
                        <li data-key="<?php echo $this->escape($key); ?>" data-value="<?php echo $this->escape($routeConfigs[$key]); ?>">
                            <span><?php echo ucfirst(preg_replace('/[_-]/', ' ', $key)) . ':'; ?></span>
                            <?php if (empty($value)) { ?>
                            <span class="label label-important route-param"><?php echo _a('None'); ?></span>
                            <?php } else { ?>
                            <span class="label label-info route-param"><?php echo $this->escape($value); ?></span>
                            <?php } ?>
                            <span class="hide route-form"><?php echo $this->formElement($form->get($key)); ?></span>
                        </li>
                    <?php 
                        }
                    ?>
                    </ol>
                </div>
            </div>

            <div class="article-route-content">
                <div class="article-route-header">
                    <span class="pull-left"><?php echo _a('Required File'); ?></span>
                </div>
                <div class="article-route-param">
                    <ol class="muted">
                        <li>
                            <span><?php echo _a('Current route: '); ?></span>
                            <?php
                                $params = '<ul class="current-route-params hide">';
                                foreach ($routeConfigs as $key => $config) {
                                    $key = ucfirst($key);
                                    $params .= <<<EOD
<li><span style="width: 150px">{$key}</span><span class="label label-info">{$config}</span></li>
EOD;
                                }
                                $params .= '</ul>';
                            ?>
                            <span class="label label-success">
                                <?php echo $this->escape($route); ?>
                                <a class="view-route-param" href="#" style="color: #fff; margin-left: 5px" data-status="up">
                                    <i class="icon-chevron-down"></i>
                                </a>
                            </span>
                            <?php echo $params ?>
                        </li>
                        <li>
                            <span><?php echo _a('Route configuration: '); ?></span>
                            <span class="file-config <?php echo empty($filename) ? 'label label-important' : 'label label-success'; ?>">
                                <?php echo empty($filename) ? _a('No file') : $this->escape($filename); ?>
                            </span>
                        </li>
                        <li>
                            <span><?php echo _a('Route class: '); ?></span>
                            <span class="file-class <?php echo empty($class) ? 'label label-important' : 'label label-success'; ?>">
                                <?php echo empty($class) ? _a('No class') : $this->escape($class); ?>
                            </span>
                        </li>
                    </ol>
                </div>
            </div>

            <div>
                <button class="btn btn-primary route-setup"><?php echo _a('Setup'); ?></button>
                <button class="btn route-default"><?php echo _a('Use default'); ?></button>
            </div>
        </div>
    </div>
</div>

<script>
(function($) {
    var RouteView = Backbone.View.extend({
        events   : {
            "click .route-delete"       : "deleteConfig",
            "click .route-setup"        : "setupCustom",
            "click .route-default"      : 'setupDefault',
            "click .route-param"        : "showForm",
            "blur  input"               : "saveData",
            "click .view-route-param"   : "toggleCurrentConfig"
        },
        initialize   : function() {
            this.$el   = $("#article-js-route");
        },
        showForm        : function(e) {
            var el = $(e.target);
            var formObj = el.parent().find('.route-form');
            var key = el.parents('li').data("key");
            if ('section' != key && 'module' != key) {
                formObj.removeClass("hide");
                formObj.find("input").focus();
                el.addClass("hide");
            }
        },
        saveData        : function(e) {
            var params = new Object;
            $("#article-route-param").find('input').each(function() {
                var obj = $(this);
                params[obj.attr("name")] = obj.val();
            });
            
            // Save data
            var self = this;
            var url = '<?php echo $this->url('', array('action' => 'save')); ?>';
            $.post(url, params, function(result) {
                result = $.parseJSON(result);
                if (result.status) {
                    self.hideForm(e);
                    self.updateInfo(result.data);
                    self.updateInstallStatus(e);
                } else {
                    alert(result.message);
                }
            });
        },
        hideForm        : function(e) {
            var el = $(e.target);
            el.parents('span').addClass("hide");
            
            // Show result
            var value  = $(e.target).val();
            var obj = el.parents("li").find(".route-param");
            obj.removeClass("label-important");
            obj.removeClass("label-info");
            
            if (value == '') {
                obj.addClass("label-important");
                obj.html('<?php echo _a('None'); ?>');
            } else {
                obj.addClass("label-info");
                obj.html(value);
            }
            el.parents("li").find(".route-param").removeClass("hide");
        },
        updateInfo      : function(data) {
            var configObj = $(".file-config");
            configObj.removeClass("label-important");
            configObj.removeClass("label-success");
            if (data.config_file) {
                configObj.html(data.config_file);
                configObj.addClass("label-success");
            } else {
                configObj.html('<?php echo _a('None'); ?>');
                configObj.addClass("label-important");
            }
            
            var classObj = $(".file-class");
            classObj.removeClass("label-important");
            classObj.removeClass("label-success");
            if (data.type) {
                classObj.html(data.type);
                classObj.addClass("label-success");
            } else {
                classObj.html('<?php echo _a('None'); ?>');
                classObj.addClass("label-important");
            }
        },
        updateInstallStatus : function(e) {
            var el = $(e.target);
            var routeData = el.parents("li").data('value');
            var content = '';
            if (routeData != el.val()) {
                content = '[<?php echo _a('Un-install'); ?>]';
            } else {
                content = '[<?php echo _a('Install'); ?>]';
            }
            $(".install-status").html(content)
        },
        toggleCurrentConfig : function(e) {
            var el = $(e.target).parent();
            if ('up' == el.data('status')) {
                $(".current-route-params").removeClass("hide");
                el.find('i').removeClass("icon-chevron-down");
                el.find('i').addClass("icon-chevron-up");
                el.data('status', 'down');
            } else {
                $(".current-route-params").addClass("hide");
                el.find('i').addClass("icon-chevron-down");
                el.find('i').removeClass("icon-chevron-up");
                el.data('status', 'up');
            }
        },
        deleteConfig    : function() {
            location.href = '<?php echo $this->url('', array('action' => 'delete-route')); ?>';
        },
        setupCustom     : function() {
            var self = this;
            var url = '<?php echo $this->url('', array('action' => 'setup-route', 'custom' => 1)); ?>';
            $.get(url, function(result) {
                result = $.parseJSON(result);
                self.renderMessage(result.status ? 'success' : 'danger', result.message);
                if (result.status) {
                    window.location.reload();
                }
            });
        },
        setupDefault    : function() {
            var self = this;
            var url = '<?php echo $this->url('', array('action' => 'setup-route')); ?>';
            $.get(url, function(result) {
                result = $.parseJSON(result);
                self.renderMessage(result.status ? 'success' : 'danger', result.message);
                if (result.status) {
                    window.location.reload();
                }
            });
        },
        renderMessage   : function(status, message) {
            $('#message-box').html(
                _.template($('#template-message').html(), {
                    status      : status,
                    message     : message
                })
            );
        }
    });
    new RouteView;   
})(jQuery)
</script>
