<ul class="nav nav-pills">
    <li class="<?php if ('list-topic' == $action) echo 'active' ?>">
        <a href="<?php echo $this->url('', array('action' => 'list-topic')) ?>">
            <?php  _e('All Topics') ?>
        </a>
    </li>
    <li class="<?php if ('add' == $action) echo 'active' ?>">
        <a href="<?php echo $this->url('', array('action' => 'add')) ?>">
            <?php  _e('Add Topic') ?>
        </a>
    </li>
</ul>
