<?php
    $this->css(array(
        $this->assetModule('script/admin.css'),
    ));
    $this->jQuery('extension/fileupload-min.js');
    $this->Backbone();
?>

<?php include 'message-box.phtml'; ?>

<div id="pi-js-upload">
    <?php include $this->templateComponent('form'); ?>
</div>

<script id="template-template" type="text/template">
    <div id="topic-template">
        <?php 
            $template = $form->get('template')->getValue();
        ?>
        <div class="topic-template-title"><?php echo ucfirst($template)  ?></div>
        <div class="topic-template-desc"><?php echo _a('This is screenshot'); ?></div>
        <a class="topic-template-change" href="javascript:void(0)" value="0" style="color: #0082bf">
            <?php echo _a('Change'); ?>
        </a>
        <div class="topic-template-bar"></div>
        <img class="topic-template-screenshot" src="<?php echo $this->escape($url); ?>">
    </div>
    <div id="topic-templates" class="hide" style="width: auto; overflow: hidden"></div>
</script>

<script id="template-item" type="text/template">
    <div class="template" id="<%= name %>">
        <img class="template-screenshot" src="<%= url %>" style="width: 100%">
        <div class="template-bar"></div>
        <a class="template-apply" href="javascript:void(0)" style="color: #fff"><?php echo _a('Apply'); ?></a>
        <div style="height: 20px; margin-top: 5px">
            <span class="template-title"><%= title %></span>
            <a class="template-fullsize pull-right" target="_blank" href="<%= fullsize %>"><?php echo _a('Fullsize'); ?></a>
        </div>
    </div>
</script>

<script id="template-chevron-left" type="text/template">
    <div class="view-previous" style="text-align: right" data-page="<%= p %>">
        <a href="javascript:void(0)"><span class="fa fa-chevron-left"></span></a>
    </div>
</script>

<script id="template-chevron-right" type="text/template">
    <div class="view-next" data-page="<%= p %>">
        <a href="javascript:void(0)"><span class="fa fa-chevron-right"></span></a>
    </div>
</script>

<script>
(function($) {
var page = {
    form    : $("form.form-horizontal"),
    $       : function(selector) {
       return this.form.find(selector);
    }
};

var UploadView = Backbone.View.extend({
    events          : {
        // Change template
        "click .topic-template-change"  : "displayTemplates",
        "click .view-previous a"        : "fetchPrevious",
        "click .view-next a"            : "fetchNext",
        "click .template-apply"         : "apply"
    },
    initialize      : function() {
        page.$("[name=template-placeholder]")
            .parents(".form-group:first")
            .find(".js-form-element")
            .html($("#template-template").html());
        this.$el   = $("#pi-js-upload");
    },
    renderMessage : function(status, message) {
        $('#message-box').html(
            _.template($('#template-message').html(), {
                status      : status,
                message     : message
            })
        );
    },
    
    // PROCESS TEMPLATE
    disableScreenshot   : function(e) {
        e.find('.template-apply').addClass('hide');
        e.find('.template-bar').addClass('hide');
        e.find('.template-screenshot').addClass('diable-image');
    },
    renderTemplates     : function(page) {
        var self = this;
        var templateObj = $('#topic-templates');
        var url = '<?php echo $this->url('', array('action' => 'get-template')); ?>';
        if (page > 0) {
            url += 'page/' + page;
        }
        $.ajax({
            cache       : false,
            async       : false,
            dataType    : 'json',
            type        : 'get',
            url         : url,
            success     : function(result) {
                if (!result.status) {
                    alert(result.message);
                }
                templateObj.html('');
                templateObj.append(_.template($('#template-chevron-left').html(), {'p' : result.previous}));
                if ($('.view-previous').data('page') == 0) {
                    $('.view-previous').find('span').addClass('hide');
                }
                for (var i in result.data) {
                    var item = result.data[i];
                    templateObj.append(_.template($('#template-item').html(), {
                        'url'       : item.url,
                        'name'      : item.name,
                        'title'     : item.title,
                        'fullsize'  : item.fullsize
                    }));
                    if ($('input[name="template"]').val() == item.name) {
                        self.disableScreenshot($("#" + item.name));
                    }
                }

                templateObj.append(_.template($('#template-chevron-right').html(), {'p' : result.next}));
                if ($('.view-next').data('page') == 0) {
                    $('.view-next').find('span').addClass('hide');
                }
                var prevWidth = $("#topic-templates").find(".view-previous").css("width");
                var nextWidth = $("#topic-templates").find(".view-next").css("width");
                var imageWidth = $("#topic-templates").find(".template").css("width");
                prevWidth = parseInt(prevWidth.replace('px', ''));
                nextWidth = parseInt(nextWidth.replace('px', ''));
                imageWidth = parseInt(imageWidth.replace('px', ''));
                var width = result.count * imageWidth + prevWidth + nextWidth + 4;
                $("#topic-templates").css("width", width);
            },
            error       : function() {
                alert('<?php echo _a('Error occured when required url!'); ?>');
            }
        });
    },
    displayTemplates  : function(e) {
        // Check whether templates are hide 
        var el = $(e.target);
        var status = el.attr('value') == 1 ? true : false;
        var haveTemplate = '' == $('#topic-templates').html() ? false : true;
        
        if (!status && !haveTemplate) {
            this.renderTemplates(1);
        }
        
        if (status) {
            this.$('#topic-templates').addClass('hide');
        } else {
            this.$('#topic-templates').removeClass('hide');
        }
        el.attr('value', status ? '0' : '1');
    },
    fetchPrevious   : function() {
        var page = $('.view-previous').data('page');
        this.renderTemplates(page);
    },
    fetchNext       : function() {
        var page = $('.view-next').data('page');
        this.renderTemplates(page);
    },
    apply           : function(e) {
        var el    = $(e.target).parent();
        var name  = el.attr("id");
        var title = el.find('.template-title').html();
        var url   = el.find('.template-screenshot').attr('src');
        
        // Hide the apply link
        $('.template-apply').removeClass('hide');
        $('.template-bar').removeClass('hide');
        $('.template-screenshot').removeClass('diable-image');
        this.disableScreenshot(el);
        
        // Change the topic template screenshot
        $('#topic-template').find('.topic-template-title').html(title);
        $('#topic-template').find('.topic-template-screenshot').attr('src', url);
        
        $('input[name="template"]').val(name);
        
    }
});
new UploadView;
})(jQuery);
</script>
