<table class="table table-striped" style="margin-top: 20px">
    <tr>
        <th><?php echo _a('Title'); ?></th>
        <th><?php echo _a('Action'); ?></th>
    </tr>
    <?php foreach ($modules as $name => $data) { ?>
    <tr>
        <td><?php echo _escape($name); ?></td>
        <td>
            <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>">
                <?php echo _a('View comments'); ?>
            </a>
        </td>
    </tr>
        <?php foreach ($data['types'] as $type) { ?>
    <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $type['title']; ?></td>
        <td>
            <a href="<?php echo $type['url']; ?>" title="<?php echo _escape($type['title']); ?>">
                <?php echo _a('View comments'); ?>
            </a>
        </td>
    </tr>
        <?php } ?>
    <?php } ?>
</table>
