<?php $this->css($this->assetModule('css/admin.css', 'comment')); ?>

<div class="row-fluid">
    <div class="span5 pull-left">
        <div class="pi-comment-portal">
            <div class="portal-header"><?php _e('Comment stats'); ?></div>
            <table class="table table-striped">
                <tr>
                    <th><?php _e('Title'); ?></th>
                    <th><?php _e('Amounts') ?></th>
                </tr>
                <?php foreach ($counts as $name => $data) { ?>
                <tr>
                    <td><?php echo _escape($data['title']); ?></td>
                    <td>
                        <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>" target="_blank">
                            <?php echo $data['count']; ?>
                        </a>
                    </td>
                </tr>
                <?php } ?>
            </table>
        </div>
        <div class="pi-comment-portal">
            <div class="portal-header"><?php _e('Top posters'); ?></div>
            <table class="table table-striped">
                <tr>
                    <th></th>
                    <th><?php _e('Submitters'); ?></th>
                    <th><?php _e('Comments') ?></th>
                </tr>
                <?php 
                    $index = 0;
                    foreach ($users as $uid => $data) { 
                ?>
                <tr>
                    <td><?php echo _escape(++$index); ?></td>
                    <td><?php echo _escape($data['name']); ?></td>
                    <td>
                        <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['name']); ?>" target="_blank">
                            <?php echo $data['count']; ?>
                        </a>
                    </td>
                </tr>
                <?php } ?>
            </table>
        </div>
        <div class="pi-comment-portal">
            <div class="portal-header"><?php _e('Active comment posts by module'); ?></div>
            <table class="table table-striped">
                <tr>
                    <th><?php _e('Title'); ?></th>
                    <th><?php _e('Amounts') ?></th>
                </tr>
                <?php foreach ($modules as $name => $data) { ?>
                <tr>
                    <td><?php echo _escape($data['title']); ?></td>
                    <td><a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>" target="_blank">
                        <?php echo $data['count']; ?>
                    </a></td>
                </tr>
                    <?php foreach ($data['categories'] as $category => $cData) { ?>
                <tr>
                    <td>&nbsp;&nbsp;<?php echo _escape($cData['title']); ?></td>
                    <td><a href="<?php echo $cData['url']; ?>" title="<?php echo _escape($cData['title']); ?>" target="_blank">
                        <?php echo $cData['count']; ?></a>
                    </td>
                </tr>
                    <?php } ?>
                <?php } ?>
            </table>
        </div>
    </div>
    <div class="span5">
        <div class="pi-comment-portal">
            <div class="portal-header"><?php _e('Links'); ?></div>
            <div style="border: 1px solid #dddddd">
                <ul>
                    <?php foreach ($links as $name => $data) { ?>
                        <li><a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>" target="_blank">
                                <?php echo _escape($data['title']); ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div class="pi-comment-portal">
            <div class="portal-header"><?php _e('Most commented'); ?></div>
            <table class="table table-striped">
                <tr>
                    <th></th>
                    <th><?php _e('Article title'); ?></th>
                    <th><?php _e('Comments') ?></th>
                </tr>
                <?php 
                    $index = 0;
                    foreach ($targets as $name => $data) { 
                ?>
                <tr>
                    <td><?php echo _escape(++$index); ?></td>
                    <td><?php echo _escape($data['title']); ?></td>
                    <td>
                        <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>" target="_blank">
                            <?php echo $data['count']; ?>
                        </a>
                    </td>
                </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>
