<table class="table table-striped" style="margin-top: 20px">
    <tr>
        <th><?php _e('Title') ?></th>
        <th><?php _e('Action') ?></th>
    </tr>
    <?php foreach ($modules as $name => $data) { ?>
    <tr>
        <td><?php echo $this->escape($name) ?></td>
        <td>
            <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>">
                <?php _e('View comments') ?>
            </a>
        </td>
    </tr>
        <?php foreach ($data['categories'] as $category) { ?>
    <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $category['title'] ?></td>
        <td>
            <a href="<?php echo $category['url']; ?>" title="<?php echo _escape($category['title']); ?>">
                <?php _e('View comments') ?>
            </a>
        </td>
    </tr>
        <?php } ?>
    <?php } ?>
</table>
